### ISSUE TITLE
Expanding triangle icon is not vertically centered while scaled in list view mode on Fedora

### ISSUE THREAD

**Issue by marlock9** [elementary/files#1005]
See screenshots. Files 4.1.8 on Fedora, same with latest git version. Didn't saw this on eOS Juno.
![Screenshot from 2019-08-02 09 16 14](https://user-images.githubusercontent.com/9781492/62348747-5448d000-b506-11e9-91d6-d69e8e6b863e.png)
![Screenshot from 2019-08-02 09 16 44](https://user-images.githubusercontent.com/9781492/62348749-5579fd00-b506-11e9-880f-547648d677ca.png)

**Comment by jeremypw** [comment]
I cannot conform this on Juno (I do not have a Fedora install).

**Comment by marlock9** [comment]
I think it isn't reproducible on Juno due to some ubuntu-specific patches of underlying components (GTK, Granite etc.).
I'm also having this bug on Archlinux.

**Comment by jeremypw** [comment]
Do you know if it is a problem with other GTK3 file managers e.g. Nemo on Fedora?

**Comment by jeremypw** [comment]
Files does not really touch the expander in Gtk.ListView - it is not rendered by Files.  When you say "scaled" do you mean "zoomed" or changing the window scaling factor?  It looks like the row height is changing but the expander stays in the same place instead of vertical alignment being CENTER.

**Comment by marlock9** [comment]
> It looks like the row height is changing but the expander stays in the same place instead of vertical alignment being CENTER.

Exactly what I tried to describe.
I don't know about such bug in Nemo, but I can try it.

**Comment by marlock9** [comment]
Tested Nautilus - the same bug. What should I do now?

**Comment by jeremypw** [comment]
You could try different themes to see whether it affects them all, but I think you need to raise the issue against Gtk (after checking for duplicates) - https://gitlab.gnome.org/GNOME/gtk/issues.

I'll close this report as it does not only affect Files.
