### ISSUE TITLE
Open in terminal like in Windows

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/files#1009]
In order to make it more convenient for Windows users to switch to elementary, it should be possible to make it behave a bit more like Windows.

When in a folder, one can already right click -> Open In -> Terminal.
In Microsoft Windows (at least in Versions 7 and 10 AFAIK), one hold the shift key, right click and "Open Terminal" / "Open in Powershell" is not on a submenu but directly accessible.

I'd like to be able to choose whether elementary file browser shows that option directly or on the submenu. Maybe being able to change that via gsettings is sufficient?

**Comment by cassidyjames** [comment]
We use the "Open In" menu to show all apps that can open directories, based on what they report to the OS they can open. I'm really not interested in special-casing Terminal and hiding the special-casing behind modifier keys just because Windows happens to do so.

**Comment by CodingSpiderFox** [comment]
In order to reach a broader range of people with elementary OS I think the better way to think would be what most users would like. I think it's a good approach to be as similar as possible to the things possible adopters may know already.

**Comment by jeremypw** [comment]
It may be possible to add "Open in Terminal" to the bookmark context menu as this is very short and consists mostly of "Open (in) ..." entries?

**Comment by cassidyjames** [comment]
@jeremypw I think I'd rather just add the normal "Open with" item there if we're going for consistency. Again, no need to special-case Terminal as opening in another app might be equally handy, and I'd rather keep the apps together in the same submenu.

**Comment by jeremypw** [comment]
@cassidyjames How about a keyboard shortcut then?  I use Open in Terminal a lot, and it is a little irritating to have to navigate to a submenu.
