### ISSUE TITLE
[Feature Request] "Dialogue box while deleting the files".

### ISSUE THREAD

**Issue by wankhedepawan1996** [elementary/files#1017]
While deleting the files dialogue box is required for avoiding accidental file deletion.
For shift + delete it is a must required feature as data could be deleted by accident permanently.

**Comment by danrabbit** [comment]
I can't confirm this issue in Files master. It looks like we already throw a warning dialog when using Shift + Delete:

![Screenshot from 2019-08-08 11 24 11@2x](https://user-images.githubusercontent.com/7277719/62727793-11d43700-b9cf-11e9-9934-00a201566bda.png)

**Comment by wankhedepawan1996** [comment]
Apologies, due to the  use of themes provided by third party i.e. tweak tools they didn’t provided the dialogue box as a feature with the theme. But when I switched the theme off, it worked perfectly with the dialogue box as you mentioned above.

But please look at the below scenario that I just observed -
File (select) -> delete -> trash -> delete   : No dialogue box 

Following the above scenario 

File (select) -> shift + delete   : No dialogue box.

For this to happen the files must be from the same folder. 
I am a new user to this os please let me know if it is a feature that I am unaware of.

**Comment by jeremypw** [comment]
Please open the above as a new issue.  I can confirm it does occur under certain circumstance.  Please put the exact procedure in the issue report (e.g. Trash in separate tab, whether you empty the trash from a view or with the sidebar etc).

**Comment by wankhedepawan1996** [comment]
I have opened the above as a new issue with id as #1022.
