### ISSUE TITLE
Single click on folders, double-click on files (miller columns)

### ISSUE THREAD

**Issue by jnnkB** [elementary/files#1021]
If you have enabled double-click mode and use the miller columns, you would have to press a folder only once to open it, while keeping a double-click required to open files.
I really think this could improve the time you need to navigate if you use miller-columns. 

This would fit to #690.

**Comment by jeremypw** [comment]
It could be argued that this could be applied to all the views.  It is fairly rare to want to multiselect folders.  Needs design team input.

**Comment by matfantinel** [comment]
This could also be the solution to the everlasting "Single-click vs Double-click" discussion, at it seems to me a pretty fair middle ground between them in all views.

This:

- Brings the agility of the single-click behaviour;
- Avoids the accidental clicks when opening files. Misclicks might still happen on folders, but they're much less of a hassle considering no other application will be opened, whereas misclicking a large PDF or Video might be frustrating to the user considering the time it would take to load.

**Comment by jeremypw** [comment]
@matfantinel  @jnnkB This idea is being considered by the UX team and has received some interest.

**Comment by BAProductions** [comment]
I agree Thats why im trying to add but with little to no luck at all & also select a file with mouse or arrow key on the keyboard invoke a preview on the right with the contents of the file or info about the file if its a ZIP, DEB, APK, SH.  Plus select selecting a folder with arrow key on the keyboard should open the folder as well.

**Comment by BAProductions** [comment]
I Agree
