### ISSUE TITLE
[Feature Confirmation] 'Shift + delete' behaviour under below conditions.

### ISSUE THREAD

**Issue by wankhedepawan1996** [elementary/files#1022]
Please look at the below scenario that I just observed -

Conditions::
The files to be deleted needs to be from same folder.

Scenario 1::
File (select) -> (Right click) delete -> trash(open via clicking the trash icon) -> (Right Click)delete the file just deleted in trash which is from the folder in previous step ::    Here dialogue box is not present as a warning.

After executing the above scenario. 
Come to the folder from which files were deleted  in Scenario 1. 
Now perform Scenario 2.

Scenario 2::
File (select) -> shift + delete(any file) : No dialogue box appears as a warning.

**Comment by jeremypw** [comment]
I can only confirm this if the Trash is opened in a separate tab or window, so that the original location view is not reloaded when you return to it.

**Comment by wankhedepawan1996** [comment]
Okay,  if the above conditions are met, there is possibility of accidental permanent deletion without warning.

**Comment by jeremypw** [comment]
PR #1024 fixed this.
