### ISSUE TITLE
Check dependency

### ISSUE THREAD

**Issue by Dirli** [elementary/files#1025]
Please check dependency:
files-4.1.9 => zeitgeist-1.0.2
files-4.1.8 => zeitgeist-1.0.1 (1.0.2? did not try to build from 1.0.2)

**Comment by tintou** [comment]
I don't understand the issue, don't you have Zeitgeist 1.0.2 on your system?

**Comment by Dirli** [comment]
zeitgeist_dep = dependency('zeitgeist-2.0') implies that the version is not important. for example, debian has version 1.0.1

**Comment by tintou** [comment]
Yes, the version is not important here

**Comment by Dirli** [comment]
Please build files-4.1.9 with the zeitgeist-1.0.1. However, this is not important, only a piece of perfectionist

**Comment by tintou** [comment]
It's more difficult than it looks, here the Zeitgeist dependency also depends on the Vala version as 1.0.2 is a bug fix to allow newer Vala to build projects using it properly :wink:

**Comment by tintou** [comment]
So technically it builds with Zeitgeist 1.0.1 with previous Vala version

**Comment by Dirli** [comment]
has accepted)))
