### ISSUE TITLE
restrict dependency on libcloudproviders to >=0.3.0

### ISSUE THREAD

**Issue by decathorpe** [elementary/files#1031]
libcloudproviders only provides VAPI since version 0.3.0.

Older versions crash the build, since it can't find VAPI for CloudProviders.

It would be nice if a version restriction of `>=0.3.0` was put into meson to make this explicit and an actionable error.

**Comment by tintou** [comment]
Fixed in master

**Comment by decathorpe** [comment]
Thanks :)
