### ISSUE TITLE
'Compress' dialog window design fix

### ISSUE THREAD

**Issue by a-tokarev** [elementary/files#1033]
![arch](https://user-images.githubusercontent.com/32895328/63570380-a15c1700-c585-11e9-9d5a-343172c9d7d0.png)

1. 'Split into volumes of' input field is too narrow (now allows only 4 digits).
 Suggestion: widen this field to allow input of 6 digits or more (say, 100 000).

2. Volume units are allowed only in MB. 
Suggestion: create a drop-down list for units: MB/GB, which will allow to quickly and conveniently input volume size in GB.

**Comment by jeremypw** [comment]
Thanks for the report but this dialog is not part of the Files codebase.  The compress menu entry is supplied by a contractor - in this case `file-roller`.

You could file an issue here: https://github.com/GNOME/file-roller

**Comment by a-tokarev** [comment]
Got it, thanks. Based on what I see on its GitHub page, the project is more dead than alive. There's even no 'issues' tab there. Still, I mailed the author, let's see if he will reply.

**Comment by jeremypw** [comment]
Closing as out of scope.
