### ISSUE TITLE
Files app not showing PDF thumbnails

### ISSUE THREAD

**Issue by queeup** [elementary/files#1034]
Files stopped showing PDF thumbnails. If I remove apparmor profile or adding new rule, it works as expected.

```console
# bash -c "owner /tmp/tumbler-* w, >> /etc/apparmor.d/local/usr.bin.evince"
# apparmor_parser -r /etc/apparmor.d/usr.bin.evince
```

OR

```console
# apparmor_parser -R /etc/apparmor.d/usr.bin.evince
```

Details of the packages:
```console
apparmor    2.12-4ubuntu5.1
evince  3.28.4-0ubuntu1.2+elementary2~ubuntu5.0.1
pantheon-files  4.1.9+r3433+pkg82~ubuntu5.0.1
```

**Comment by rizaumami** [comment]
Have this problem on elementary OS 5.1.3 Hera.

| Package | Version |
|-----|-----|
| apparmor | 2.12-4ubuntu5.1 |
| evince | 3.28.4-0ubuntu1.2+elementary2\~ubuntu5.0.1 |
| pantheon-files | 4.4.2+r3786+pkg92~ubuntu5.1.2.1 |

Solution is as stated by OP.
```
# apparmor_parser -R /etc/apparmor.d/usr.bin.evince
```

**Comment by jeremypw** [comment]
Not sure that this is a Files issue - I am getting thumbnails for pdf files OK on Hera daily.

**Comment by joe733** [comment]
Same here: elementary OS 5.1.6 Hera

```zsh
joe733 in ~ at xpsl502x 
➜ sudo apparmor_parser --version
AppArmor parser version 2.12
Copyright (C) 1999-2008 Novell Inc.
Copyright 2009-2012 Canonical Ltd.

joe733 in ~ at xpsl502x 
➜ evince --version
GNOME Document Viewer 3.28.4

joe733 in ~ at xpsl502x 
➜ io.elementary.files --version
io.elementary.files 4.4.4
```

Solution same as mentioned by OP.
> apparmor_parser -R /etc/apparmor.d/usr.bin.evince

**Comment by joe733** [comment]
Not sure if this is a good idea but I've put that command as a cron job at every reboot: `$ sudo crontab -e`, add the line:

```bash
@reboot sudo apparmor_parser -R /etc/apparmor.d/usr.bin.evince
```

**Comment by queeup** [comment]
Still an issue on the elementary OS 6 Early Access.

**Comment by queeup** [comment]
This is fixed on Odin stable. Thank you.
