### ISSUE TITLE
Ditch LibUnity and Quicklists

### ISSUE THREAD

**Issue by danrabbit** [elementary/files#1038]
In favor of Granite's new functions

**Comment by jeremypw** [comment]
There does not seem to be any functions in Granite to manipulate the Unity.LauncherEntry.quicklist, which is used by Files.   Or have I missed something?

**Comment by tintou** [comment]
We have decided that Quicklists weren't really relevant as they are only present when the application is running so we are alright with losing that feature

**Comment by jeremypw** [comment]
OK, I have modified issue description accordingly.

**Comment by decathorpe** [comment]
Is this issue still on your radar? It would be nice if we could drop libunity.

Files is one of the last three packages in all of fedora (!) that still non-optionally requires it, and I'd like to get rid of it :)

**Comment by jeremypw** [comment]
Looks like the code will already compile and run without unity (although I havent tried it) so presumably just need to amend the packaging?

**Comment by jeremypw** [comment]
I think the source should compile without libunity and libplank - have you tried it?

**Comment by jeremypw** [comment]
AH, you need to change meson option "with-unity" to `false`.

**Comment by jeremypw** [comment]
See #1313. The source should compile with and without libunity and libzeitgeist with this PR. The deb-packaging branch still has unity and zeitgeist as build dependencies though, but presumably Files is repackaged for Fedora?

**Comment by decathorpe** [comment]
Oh, sorry, I did not see the old issue, and GitHub didn't warn me about the duplicate. I'll try your PR, thanks!
