### ISSUE TITLE
fails with newer glib

### ISSUE THREAD

**Issue by mpkh** [elementary/files#104]
glib 2.53.4

(pantheon-files:26760): Gtk-WARNING **: Theme parsing error: <data>:7:43: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version
[FATAL 18:18:58.661498] [GLib] g_strsplit: assertion 'string != NULL' failed

**Comment by jeremypw** [comment]
Please could you run with gdb and post a back-trace?  Also please describe at what point it fails.

**Comment by mpkh** [comment]
@jeremypw at startup

**Comment by jeremypw** [comment]
Thanks.  Any chance of a backtrace from someone running glib 2.53.4 and has the debugging symbols installed?  This will indicate the exact line that is is problematic .

**Comment by mpkh** [comment]
@jeremypw sorry no, will not have time for that

**Comment by jeremypw** [comment]
OK, np.  I have now found a source for Loki+1 which will have a later glib.  Hopefully this will help.

**Comment by jeremypw** [comment]
FIles master currently compliles and runs on Loki+1, which uses glib 2.54.1.
