### ISSUE TITLE
Bulk rename

### ISSUE THREAD

**Issue by kp2401075** [elementary/files#1040]
Hello there,
I was wondering if there was any work in progress for implementing bulk rename functionality.

It would be nice to have it.

Kind regards, and Keep up the good work

**Comment by jeremypw** [comment]
I believe this has been discussed in the past but elementary philosophy would argue against adding features that are already provided by other apps - i.e. we do not want to spend time and effort re-inventing the wheel.  The correct approach would be to provide a contractor file that invokes a specialist app. See similar discussion on issue #1030

**Comment by cassidyjames** [comment]
Eh, bulk rename is pretty common in file managers, it's just a natural extension of the rename functionality, but still working when you have multiple files selected. I.e. highlight a bunch of images, hit F2 or right-click → Rename, then type "foo" and they get named "foo-1.ext", "foo-2.ext", etc.

**Comment by jeremypw** [comment]
I don't dispute bulk rename ought to be doable from the file manager, just whether we need to write and maintain new code to do it.

**Comment by jeremypw** [comment]
That said, were someone to submit a suitable PR I would not oppose.  The question is - should Files provide "best of class" renaming facilities or something more basic?

**Comment by jeremypw** [comment]
I notice that there is already a 3rd party bulk renamer for Files: https://github.com/VartanBelavejian/ElementaryBulkRenamer

It is not in the AppCenter though. I haven't tried it yet.

**Comment by jeremypw** [comment]
The only renamer in the AppCenter is a KDE app (Krename) which is not ideal :-(  There are over 100 renamer apps on GitHub though.

**Comment by jeremypw** [comment]
Vartan Belavejian's renamer seems a decent basic renamer although the codebase needs updating to current elementaryos code standards. It works well as a contractor although I suppose the code could be imported into Files.

**Comment by jeremypw** [comment]
The advantage of installing as a contractor is that bulk rename becomes available in other elementary apps - not just Files - e.g. Photos.

**Comment by jeremypw** [comment]
I have created a bulk renamer contractor here https://github.com/jeremypw/bulk-renamer and submitted it for possible inclusion in the AppCenter.  It is the initial release so may not have all functionality desired.

**Comment by dar5hak** [comment]
I am interested in contributing to this feature. Now that we no longer do Contractor, does it make sense to do this in a portal, so that it can support apps other than Files as Jeremy mentioned?

**Comment by jeremypw** [comment]
I have already put forward a PR that allows sequential (arbitrary) renaming of multiple selected files just by modifying the existing rename code.  Once you get into systematic automatic renaming of files, then that is a lot more code and you have to get the design past the UX team.  Very simple automatic renaming - as described by @cassidyjames above and provided by e.g. Nautilus - could probably be provided by the main code, but whether that too limited to be worth doing is questionable.

I might put forward my old plugin PR so you have something to start with if you do want to work on this.  It could probably be converted to a portal.  Not sure how many other apps would use it though.

**Comment by jeremypw** [comment]
![Screenshot from 2022-01-07 18 05 32](https://user-images.githubusercontent.com/10513844/148587337-c1c72c32-1a9a-4d64-b9e1-cf9406676f92.png)

**Comment by danirabbit** [comment]
Recently fixed in #1999
