### ISSUE TITLE
Ability to create individual encrypted folders

### ISSUE THREAD

**Issue by ghost** [elementary/files#1046]
Would love the ability to simplify encryption for only important things you want to encrypt. (I do understand there is full disk encryption though but still think this would be neat.) Being able to right click on Files and create a "New Encrypted Folder", Then be prompted with a small password creation box. Any files added to that folder would be automatically encrypted. Opening said folder would open a small password box which would then open up like a regular folder in Files.
You could have it set up to have different passwords for different individual folders or use the same passwords for all encrypted folders. I would believe having different passwords for each encrypted folder increases security of your files too?

I would love to design an example of what I mean but I'm far from being a designer. And I'm sure implementing something like this would be a difficult task but just thought I'd share the idea since I've always looked for something like this in a OS.

**Comment by jeremypw** [comment]
See alos #862

**Comment by jeremypw** [comment]
This is already possible (but not obvious).  

* Right-click on folder
* Choose "Compress"
* Chooser ".7z" format
* In other options chooser enter a password and check tickboxes as required.

Something more integrated with system security would be nice.

**Comment by jeremypw** [comment]
Unfortunately file-roller does not seem to have any command-line options for specifiying archive-type, and other options, which would have made it possible to automate the process with a contractor.

**Comment by GhostyPi** [comment]
Just tried out what you mentioned. It does seem to work somewhat similar to what I had mention so makes a good alternative for now, Thanks for mentioning it! I think it would be much cooler being more of an uncompressed form though and not having to deal with extraction either. Something that seems more seamless I suppose? As you said more integrated. But I'm not sure how possible it would be has I have no coding experience as of yet.

**Comment by jeremypw** [comment]
I agree the current facility is less than satisfactory. There needs to be one step to switch between an unencrypted folder and an encrypted one.

**Comment by 4jNsY6fCVqZv** [comment]
Which way to integrate this functionality makes the most sense for Files and elementary OS?
see #1030 (comment) for reference.

**Comment by jeremypw** [comment]
Writing new encryption code is not realistic, in my opinion, so we could
* find a suitable encryption app with a command-line interface that we could ship as a contractor
* patch or fork file-roller to give it a command-line interface
* port encryption code from an existing command line tool (unlikely) 

Any suggestions for open source encryption apps or tools other than file-roller?

**Comment by 4jNsY6fCVqZv** [comment]
Yeah, writing your own encryption code isn't that easy. An integration of existing tools would be wonderful!

> find a suitable encryption app with a command-line interface that we could ship as a contractor

Wasn't there already the idea to integrate https://gitlab.gnome.org/GNOME/seahorse-nautilus via Contractor? But I don't know if the tool will be maintained at all.

**Comment by jeremypw** [comment]
The problem with seahorse is that it does not have a suitable command-line interface and seems to be mainly aimed at key and password management. Despite what it says on its home page I cannot see a way of directly encrypting/decrypting files through the seahorse gui or commandline (unless I've missed something).  The seahorse-nautilus extension is a plugin of some kind. However, it also provides seahorse-tool which looks like it has a suitable interface.  This tool does not seem to be available separately unfortunately.

**Comment by 4jNsY6fCVqZv** [comment]
You prefer a standalone solution, don't you?
I will do some more research and ask myself, how and if Tails already offers a solution for this problem.

**Comment by 4jNsY6fCVqZv** [comment]
Does it make sense to adjust the issue title? Proposal: "Provide a graphical interface to create encrypted files and folders".

**Comment by jeremypw** [comment]
Yes, it is possible that a basic solution might be possible by providing contractors which just call gpg with appropriate parameters to encrypt/decrypt files with the default key. To allow choice of parameters would need a UI but that might not be too hard if all it does is to call gpg in the end.

**Comment by jeremypw** [comment]
In fact, I have just discovered someone has already done it!  See https://github.com/phocean/contracts-gpg

**Comment by jeremypw** [comment]
The problem with using gpg directly as a contractor is that it needs to receive an explicit ID on the commandline in order to find the key - there is no option to use the ID of the current user (which seahorse-tool has).

**Comment by jeremypw** [comment]
Actually, reading the original issue description, I think we (or I) have strayed somewhat.  Maybe we should create a new issue addressing what we recently discussed that is encrypting/decrypting one or more files with gpg.  This issue is about *folders* that automatically encrypt their contents - which is a much harder problem and possibly outside the scope of Files.  To encrypt folders as a whole using a contractor we would have to use a patched version of file-roller that accepts commandline options (or another more suitable tool if one can be found).

**Comment by jeremypw** [comment]
I have started to play around with a wrapper/contractor for gpg here : https://github.com/jeremypw/gpg_wrapper

**Comment by jeremypw** [comment]
I now have a basic working contractor for encrypting (with default key of current user) and decrypting (with user passphrase entry) of one or more regular files.

**Comment by jeremypw** [comment]
The creation of transparently encrypted disks, partitions and folders is outside the scope of Files. This is best done at system level I think. Files would be best used for creating an encrypted version of a file or set of files suitable for e.g. sending by email; and for reversing such a process.

I am closing this now as out of scope.  Please raise a similar issue at elementary/os, thanks.
