### ISSUE TITLE
Fails to build from source with vala 0.46.2

### ISSUE THREAD

**Issue by worldofpeace** [elementary/files#1081]
## Describe the bug
As title states, with vala 0.46.2 files fails to build with an error.
```
../src/ClipboardManager.vala:176.48-176.65: error: Argument 6: Cannot convert from `void GLib.Callback? ()' to `void Marlin.CopyCallback? ()'
                                               new_files_callback);
                                               ^^^^^^^^^^^^^^^^^^
```

There's also many other warnings
* [link to build log](https://gist.github.com/worldofpeace/d8f54a37ec5bfe302870e0ad2f019dcb)

## Platform Information
 - OS: NixOS
 - OS Version: 20.03

Reported downstream in https://github.com/NixOS/nixpkgs/issues/71725

- [x] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

^ I've tested with both.

## Additional context
I believe this broke directly during the move from `vala: 0.46.1 -> 0.46.2`.
I've yet to test with latest [0.46.3](https://gitlab.gnome.org/GNOME/vala/blob/0.46.3/NEWS)
Less than 0.46.2 doesn't have this problem.

**Comment by tintou** [comment]
It has been fixed with this commit https://github.com/elementary/files/commit/76b5cc95466733c2c100a99127ecd4fbd4d2a5ec
