### ISSUE TITLE
Could not open files or URIs with this app

### ISSUE THREAD

**Issue by EwonRael** [elementary/files#1089]
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Describe the bug
When I try to open certain file types in certain programs using files I get this error message, "Could not open files or URIs with this app". 

So far I have this issue trying to open .ufo files with [trufont](https://github.com/trufont/trufont), and more recently .mscz files with [musescore](https://github.com/musescore/MuseScore).

### To Reproduce
1. Install musescore.
2. Set musescore to be the default program when opening .mscz files
3. try and open a .mscz file.
4.
![Screenshot from 2019-10-27 15 41 15@2x](https://user-images.githubusercontent.com/16858124/67636376-479f0280-f8d0-11e9-834e-286fb14aea89.png)

### Expected behaviour
I'm expecting musecore to open and to load the file. This happens in every other file application I've tried.

## Platform Information
![Screenshot from 2019-10-27 15 43 36@2x](https://user-images.githubusercontent.com/16858124/67636418-9351ac00-f8d0-11e9-82a3-a685d43178f9.png)

Please check what applies:
- [ ] I'm using the latest released stable version

## Additional context
Both of these programs are ones that I didn't/couldn't install using the AppCenter or a ppa. Perhaps more importantly, I made the .desktop file for them myself. I think what's most likely happening is that something about how I'm configuring my .desktop files is causing this to happen, but I don't know what that is or how to properly configure my files. 

Love you guys!

**Comment by davidmhewitt** [comment]
Yes, this is likely an issue with the desktop files. Can you post the content of one as an example?

**Comment by EwonRael** [comment]
```
[Desktop Entry]
Type=Application
Name[en_US]=TruFont
X-GNOME-FullName[en_US]=TruFont
Comment[en_US]=
Icon=/home/owen/.icons/urutau-icons-master/apps/trufont.svg
NoDisplay=false
Exec=/home/owen/.trufont/bin/trufont
Terminal=false
X-GNOME-UsesNotifications=true
Categories=Graphics;
```

**Comment by davidmhewitt** [comment]
I'd imagine you want to put `%f` on the end of the `Exec` line, so something like:

`Exec=/home/owen/.trufont/bin/trufont %f`

The %f gets substituted with the name of the file you're trying to open. You can also use `%F` if the application supports opening multiple files. Or `%u` and `%U` if the application opens URIs instead of file paths.

**Comment by EwonRael** [comment]
This worked thank you so much for your help!
