### ISSUE TITLE
Using drag & drop to export images from shotwell to "files" does not work

### ISSUE THREAD

**Issue by tuxiano** [elementary/files#1096]
## Prerequisites
- [x ] I have searched open and closed issues for duplicates.

## Describe the bug
According to [Exporting photos](http://yorba.org/shotwell/help/share-export.html) shotwell allows to export photos via drag and drop. 

But unfortunately that does not work as expected, because the image does not appear in the folder where I "dropped" it.

### To Reproduce
1. Go to shotwell 0.30.7
2. Click and hold an image
3. Drop it into a folder in "files"
4. Nothing happens.

### Expected behavior
Image should be copied into the desired folder where it was dropped. 

 - OS: eos
 - OS Version juno

- [ ] I'm using the latest version from git that I've manually compiled
- [x ] I'm using the latest released stable version

**Comment by jeremypw** [comment]
This should be fixed by PR #1087

**Comment by tuxiano** [comment]
Cool, thank you.
