### ISSUE TITLE
Check for equivalent existing tab when locating downloaded files

### ISSUE THREAD

**Issue by joe247** [elementary/files#1104]
This issue seems very similar to this: [#265](https://github.com/elementary/terminal/pull/265).

### Steps to reproduce:
1. Open Firefox.
2. Download anything.
3. Click on 'Open containing folder'
4. Opens a new download tab and highlights the file.

### Expected Behaviour:
1. Locates the file in the same tab if it is already open.
2. Auto-scrolls the window to bring it into view. (usually take manual scrolling to locate the highlighted file)

**Comment by jeremypw** [comment]
This will be fixed by the latest version of PR #1032.

**Comment by joe247** [comment]
>Auto-scrolls the window to bring it into view. (usually take manual scrolling to locate the highlighted file)

**Can this be expected any time soon (Auto-scroll)?<br><br>**

_PS: I don't know Vala (in which most of the repositories is written), but I can do Python, how can I technically contribute to this project?_

**Comment by jeremypw** [comment]
Autoscrolling is working in #1032

**Comment by joe247** [comment]
Is there something like nightly builds or rolling release, how can I test them?

**Comment by jeremypw** [comment]
There are no binaries available for unmerged branches I am afraid.  You need to install the appropriate development tools, clone the Files the repository and then build and install that branch for yourself locally. If you do not already know how to do this,  the README.md document includes instructions for building and this page https://elementary.io/docs/code/getting-started#getting-started contains information on the tools required.

If you install the `elementary-sdk` package (`sudo apt install elementary-sdk`) and also `sudo apt build-dep pantheon-files`  you should have everything you need (and more).

**Comment by jeremypw** [comment]
Otherwise, if you add the repository http://ppa.launchpad.net/elementary-os/daily/ubuntu/ bionic main you will get the master version of Files but will need to wait for the PR to be approved and merged.

**Comment by joe247** [comment]
Thanks!
