### ISSUE TITLE
Can't unmount (eject) device if terminal is working inside mounted device directory

### ISSUE THREAD

**Issue by queeup** [elementary/files#1108]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
If terminal is working inside mounted device directory, files app refuse to unmount (eject) device.

### To Reproduce
1. Mount device (usb disk) in files app
2. Go to directory inside mounted device
2. Open terminal inside that directory from right click menu
4. Try to unmount device from files app

### Expected behavior
Unmount device directly or warning about some other app using it etc.

## Platform Information
 - OS: elementary OS
 - OS Version: Juno

- [X] I'm using the latest released stable version

## Additional context
```console
pantheon-files:     4.2.0+r3478+pkg84~ubuntu5.0.1
pantheon-terminal:  5.3.6+r1326+pkg68~ubuntu5.0.1
```

**Comment by jeremypw** [comment]
I seem to remember there used to be a system dialog saying the device was busy if unmounting failed, under some circumstances.

**Comment by jeremypw** [comment]
Trying this out, it looks like the device starts to unmount and then is immediately remounted. It could be that Files is just reflecting actions taken at system level.

**Comment by jeremypw** [comment]
Just tried with another Gtk based file manager - in this case a "Volume busy" dialog is displayed with an "Unmount anyway" option.  I guess Files should do the same - or at least show some message.

**Comment by queeup** [comment]
I test it with text and image file opened by _Code_ & _Photos_ app on mounted device then try to unmount while files are open:

_Code_: Unmounted successfully, while trying to close _Code_ app ask me to save the file. 
_Photos_:  Unmounted successfully, while trying to close _Photos_ app ask me to save the file.
_VLC_: Can't unmount device while playing media. I guess this s normal behaviour. But no warning about busy device.

**Comment by jeremypw** [comment]
OK, it seems that Files was using Glib.MountOperation instead of Gtk.MountOperation when unmounting so the the system messages were not being displayed.  I am not sure if this was changed for a specific reason but changing it back at least allows the "Volume busy" dialog to show.  The alternative would be to use the "FORCE" flag to force unmounting even if the mount is being used.
