### ISSUE TITLE
Right click on jar file should have "Extract here" menu item

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/files#1135]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
Sometimes you need to check the contents of your java binary. As .jar/.ear/.war files are only a certain form of ZIP files, the elementary file manager could speed up extraction of the contents by treating their right click context menu the same way as zip files.

**Describe the solution you'd like**
When right clicking on a *.jar, *.war, *.ear file, the context menu should have the item "Extract here"

**Comment by jeremypw** [comment]
Which version of Elementary/Files are you using?  I just tried this and there an "Extract here" item in the context menu (at least for .jar - I havent tried the others).  Note this depends on "Archive Manager" (`file-roller`) and the related `.contractor` file being installed which should be the case by default in in Elementary.  Files does not extract files itself but relies on there being a suitable contractor app installed.

**Comment by CodingSpiderFox** [comment]
pantheon-files/bionic,now 4.2.0+r3478+pkg84~ubuntu5.0.1 amd64 [installed,automatic]

**Comment by jeremypw** [comment]
Which version of ElementaryOS are you running (latest is v5.1 - Hera)?  If you are running an unmodified install of ElementaryOS it is puzzling you are having this problem.  Try going into AppCenter and reinstalling both Files and FIle Roller.

**Comment by CodingSpiderFox** [comment]
After reinstalling, it works, thanks
