### ISSUE TITLE
Esc key to close switching between windows/apps during Alt+Tab 

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/files#1139]
When switching windows using Alt+Tab, it would be nice to use the Esc key to **not** switch between windows. Basically, since we use Alt+Tab to switch between windows, Alt+Esc in that process to get out of the task view and back to the original window. I know this is supported in Windows 7/8/10 but it would be nice to have here.

### Platform information
elementaryOS 5.1 Hera
Dell XPS 13 9380
Dual booted system

**Comment by jeremypw** [comment]
In Files you use Ctrl+Tab to cycle between the notebook tabs.   Alt+Tab is used by the window manager to cycle between windows. Could you explain your issue further please?

**Comment by vikasnataraja** [comment]
Basically, when switching between different windows/apps like from Files to Terminal, I usually use Alt+Tab to cycle through the windows/apps and eventually land on Terminal. It would be nice to use Alt+Esc to return to the original window, in this case, Files.

**Comment by jeremypw** [comment]
I do not think this is a Files issue - it should be filed agains gala, the window manager.
