### ISSUE TITLE
Files process does not end and plank progress bar remains after some file operations.

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#1153]
I have searched open and closed issues for duplicates. Maybe related to #1050.

## Describe the bug
After carrying out some file operations, I noticed that the dock icon still had a progressbar emblem.  Upon closing all Files windows the Files process did not end (as seen in system-monitor). Suggests application has been inhibited but not released.

This does not always happen so maybe a race condition of some kind.

### Expected behavior
After completion or cancellation of file operations the application should be released and the plank icon progressbar removed.

## Platform Information
Hera 5.1 daily
 I'm using the latest version from git that I've manually compiled

## Additional context
I suspect this maybe a regression due to this fix: #727

**Comment by jeremypw** [comment]
This seems to be associated with cancelled operations.  If the operation was cancelled before the plank progressbar appears (e.g. through the "replace?" dialog) then there is nothing obvious to indicate the app process is still running after closing the window.

**Comment by minutesinch** [comment]
+1

**Comment by Fatih20** [comment]
+1
