### ISSUE TITLE
File copy time calculation wrong

### ISSUE THREAD

**Issue by marbetschar** [elementary/files#1155]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

Copied a large file from a SMB share today and experienced the following situation:

![Screenshot from 2020-01-14 13-17-33](https://user-images.githubusercontent.com/392542/72344020-8de64f80-36d0-11ea-8e01-21c591eec06d.png)

Of course the copy process did take longer than the displayed 4 seconds - and that's Ok. But what I'm puzzled about is, how did the 4 seconds get calculated in the first place? The displayed size left to be copied is roughly `2.4 GB` and the transfer speed is displayed as `8.0 MB/sec` ... and this leads to a remaining transfer time of `4 seconds`?

In my opinion the remaining transfer time should be calculated as `2.4 * 1024 / 8 = 307.2 seconds = roughly 5mins`.

**Comment by marbetschar** [comment]
Just seen: This is probably related to https://github.com/elementary/files/pull/1152

**Comment by jeremypw** [comment]
I think this is being fixed by #1152.   The time remaining should have been 4 minutes.  The number calculation is (approx) correct but the units string is wrong.
