### ISSUE TITLE
Opening folder mounted with sshfs that contains a git repo causes long load times

### ISSUE THREAD

**Issue by GammaGames** [elementary/files#1156]
I have a folder I mount with `sshfs` so I can edit the files on my local machine. Trying to open the folder causes files to hang. It eventually loads, but I really only want git status on files that are physically located on my local hard drive.

### To Reproduce
1. Mount a folder containing a git repo with `sshfs`
2. Open folder in files
3. Wait for files to scan
4. Keep waiting
5. Give up and just use the terminal

### Expected behavior
This is expected with the current implementation, but I think the option to disable the git status in a directory would be nice.

## Platform Information
![image](https://user-images.githubusercontent.com/7832163/72363511-3802af00-36b2-11ea-832e-1db5e48fe430.png)

- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
Yes, sounds like we will probably have to disable git status for remote filesystems, at least by default.

**Comment by GammaGames** [comment]
I see it's merged and there's been a release since then, is there any ETA on this fix being released?

**Comment by jeremypw** [comment]
@GammaGames If you have Files  version 4.4.0 or greater then it should include this fix. As you say, there have been more than one release since this was merged.  However, it looks like the release info did not include a reference to this fix - which is an oversight.

**Comment by GammaGames** [comment]
I have 4.4.2 and am still having the issue, or at least it looks like the same issue

**Comment by jeremypw** [comment]
Hmm, the git plugin should no longer be scanning non-local folders.  If you run Files with `G_MESSAGES_DEBUG=all io.elementary.files` you should see amongst the output a debug message "Git plugin ignoring non-local folder" when you enter a non-local folder.  What is the url of the folder you are having problems with?  If it has a protocol part other than "trash", "recent" or "file" it should be treated by Files as non-local.

**Comment by GammaGames** [comment]
Here's the output for `io.elementary.files 4.4.2`. I opened my remote dir then tried to move into the git repo, then I killed it when the popup came up after a minute or two.
```log-file
** (io.elementary.files:5723): DEBUG: 13:58:49.009: gof-directory-async.vala:1151: Dir file:///home/jlieberg/Documents/remote-dir not in cache
** (io.elementary.files:5723): DEBUG: 13:58:49.009: gof-directory-async.vala:1151: Dir file:///home/jlieberg/Documents not in cache
** (io.elementary.files:5723): DEBUG: 13:58:49.012: gof-directory-async.vala:205: Preparing directory for loading
** (io.elementary.files:5723): DEBUG: 13:58:49.012: gof-directory-async.vala:240: get_file_info
** (io.elementary.files:5723): DEBUG: 13:58:49.012: gof-directory-async.vala:271: try_query_info
** (io.elementary.files:5723): DEBUG: 13:58:49.013: gof-directory-async.vala:535: Async is last toggle_ref_notify file:///home/jlieberg/Downloads
** (io.elementary.files:5723): DEBUG: 13:58:49.013: gof-directory-async.vala:155: Async destruct file:///home/jlieberg/Downloads
** (io.elementary.files:5723): DEBUG: 13:58:49.015: gof-directory-async.vala:296: got file info - updating
** (io.elementary.files:5723): DEBUG: 13:58:49.015: gof-directory-async.vala:298: success true; enclosing mount groot
** (io.elementary.files:5723): DEBUG: 13:58:49.015: gof-directory-async.vala:232: success true; enclosing mount groot
** (io.elementary.files:5723): DEBUG: 13:58:49.015: gof-directory-async.vala:431: make ready
** (io.elementary.files:5723): DEBUG: 13:58:49.015: gof-directory-async.vala:465: Directory has mount point
** (io.elementary.files:5723): DEBUG: 13:58:49.117: gof-directory-async.vala:617: list directory async
** (io.elementary.files:5723): DEBUG: 13:58:49.141: gof-directory-async.vala:647: Obtained file enumerator for location file:///home/jlieberg/Documents/remote-dir
** (io.elementary.files:5723): DEBUG: 13:58:49.282: gof-directory-async.vala:731: after loading state is GOF_DIRECTORY_ASYNC_STATE_LOADED
** (io.elementary.files:5723): DEBUG: 13:58:49.366: plugin.vala:126: Error opening git repository at file:///home/jlieberg/Documents/remote-dir - could not find repository from '/home/jlieberg/Documents/remote-dir'
** (io.elementary.files:5723): DEBUG: 13:58:49.390: sql-schema.vala:204: schema_version is 10
** (io.elementary.files:5723): DEBUG: 13:58:49.391: sql-schema.vala:204: schema_version is 10
** (io.elementary.files:5723): DEBUG: 13:58:50.331: gof-directory-async.vala:1151: Dir file:///home/jlieberg/Documents/remote-dir/git-repo not in cache
** (io.elementary.files:5723): DEBUG: 13:58:50.331: gof-directory-async.vala:1138: found cached dir file:///home/jlieberg/Documents/remote-dir
** (io.elementary.files:5723): DEBUG: 13:58:50.349: gof-directory-async.vala:205: Preparing directory for loading
** (io.elementary.files:5723): DEBUG: 13:58:50.349: gof-directory-async.vala:240: get_file_info
** (io.elementary.files:5723): DEBUG: 13:58:50.349: gof-directory-async.vala:271: try_query_info
** (io.elementary.files:5723): DEBUG: 13:58:50.401: gof-directory-async.vala:296: got file info - updating
** (io.elementary.files:5723): DEBUG: 13:58:50.401: gof-directory-async.vala:298: success true; enclosing mount groot
** (io.elementary.files:5723): DEBUG: 13:58:50.402: gof-directory-async.vala:232: success true; enclosing mount groot
** (io.elementary.files:5723): DEBUG: 13:58:50.402: gof-directory-async.vala:431: make ready
** (io.elementary.files:5723): DEBUG: 13:58:50.402: gof-directory-async.vala:465: Directory has mount point
** (io.elementary.files:5723): DEBUG: 13:58:50.501: gof-directory-async.vala:617: list directory async
** (io.elementary.files:5723): DEBUG: 13:58:50.502: gof-directory-async.vala:647: Obtained file enumerator for location file:///home/jlieberg/Documents/remote-dir/git-repo
** (io.elementary.files:5723): DEBUG: 13:58:50.780: gof-directory-async.vala:731: after loading state is GOF_DIRECTORY_ASYNC_STATE_LOADED
Killed
```

**Comment by jeremypw** [comment]
OK, so it looks like your remote directory is at URL `file:///home/jlieberg/Documents/remote-dir/git-repo` so looks to Files like a local folder.  I notice now you used sshfs not ssh so the simple method Files uses to identify remote folders does not work in this case.   I am not sure how to identify folders mounted with sshfs (anyone who does please advise!).  A quick fix would be to add a timeout and exclude locations that exceed it and/or, if possible, stop the scanning from blocking the FIles interface.   A workaround now would be, if possible, connect to that folder using the Files Connect to Server dialog and bookmark it, rather than using sshfs.

**Comment by jeremypw** [comment]
Reopening as the fix does not work for folders mounted with sshfs and, presumably, other FUSE file systems.

**Comment by jeremypw** [comment]
Another partial solution might be to exclude all subfolders of `/mnt` in the git plugin.  It would mean you mounting the folder there rather than in your home directory.

**Comment by jeremypw** [comment]
Working on a solution using the FileAttribute.FILESYSTEM_TYPE.

**Comment by GammaGames** [comment]
> It would mean you mounting the folder there rather than in your home directory.

That’s what I should have done and will do today, I was more of a Linux novice when I originally set all my aliases for sshfs and umount

**Comment by jeremypw** [comment]
@GammaGames Please could you confirm whether the problem remote directory had a git repo in it or was the plugin just spending a lot of time looking repos that were not there?

**Comment by jeremypw** [comment]
@GammaGames Do you get a similar issue if you open the problem folder in the sidebar of Code, which also scans for git repo info?

**Comment by GammaGames** [comment]
Browsing non-git remote directories works fine, it's only when the folder is part of a git repo it has a problem. Code has the same issue and I either have to wait for it to popup with the kill prompt or unmount the remote filesystem. If I clone the repo so it is on my local drive I have no issues with either files or code.

**Comment by jeremypw** [comment]
@GammaGames Thanks!  Would you mind filing another issue at https://github.com/elementary/code/issues ? Unless it is a very large repo on a very slow connection, It may be a limitation of `libgit2-glib-1.0` causing the scan to block indefinitely.  I'll try and set up a git repo on a sshfs mount and find out exactly where the block is.

**Comment by GammaGames** [comment]
Shouldn't be a slow connection, it takes ~30s to transfer a 2gb file from the same remote server to my local machine. It is a kinda large repo though, about 500MB cloned. I'll open an issue on the other repo too. Thank you!

**Comment by GammaGames** [comment]
Thank you for fixing this! I can finally use the file browser for work again :)
