### ISSUE TITLE
Invert logic of Show/Hide Thumbnails

### ISSUE THREAD

**Issue by danirabbit** [elementary/files#1163]
@cassidyjames mentioned that check items should have positive labels. So this item should be "Show Thumbnails", not "Hide Thumbnails".

This involves inverting the gsettings defaults, Action defaults, renaming the properties in AbstractDirectoryView, and changing the menuitem label

**Comment by cassidyjames** [comment]
@danrabbit I guess in the most ideal/perfect world all of those things would be inverted, but this is a case where I think it would be fine for the underlying GSetting to remain, and we just invert the binding and user-facing copy.

**Comment by danrabbit** [comment]
That might be kind of a pain and give us code with some double negatives since we also have to deal with GLib.Action storing that boolean

**Comment by jeremypw** [comment]
`G_SETTINGS_BIND_INVERT_BOOLEAN` might help with that.  Changing the meaning of settings between versions is not ideal.

**Comment by danirabbit** [comment]
Fixed in #2132
