### ISSUE TITLE
Too large icons in List-view

### ISSUE THREAD

**Issue by ayvind** [elementary/files#1164]
Icons are to too big by default. As such I feel that the 'list-view' becomes less effective.  Using dconf-editor I changed all zoom-levels to 'smallest'. Much better!

**Comment by jeremypw** [comment]
The default setting is never going to be optimal for everyone.  If you zoom out the ListView (`<Ctrl>-` or `<Ctrl>ScrollUp`) then the setting persists, so its not a significant problem.

**Comment by DisguisedBear** [comment]
> The default setting is never going to be optimal for everyone. If you zoom out the ListView (`<Ctrl>-` or `<Ctrl>ScrollUp`) then the setting persists, so its not a significant problem.

The minimum size of the list items is still way too large, it's very hard to navigate long lists even when downsizing to the smallest possible setting.

**Comment by jeremypw** [comment]
>The minimum size of the list items is still way too large, it's very hard to navigate long lists even when downsizing to the smallest possible setting.

Do you mean the default minimum size? You can reduce the minimum size in List View by editing the setting "io.elementary.files.list-view.minimum-zoom-level" and changing it to "smallest". This changes the icon from 24px to 16px. Much smaller and legibility would suffer.  You can jump down the list by typing the first few letters of a filename.  It might be nice to add some kind of filtering feature but thats another issue.

**Comment by jeremypw** [comment]
Note that Column View has a minimum icon size of 16px by default.

**Comment by jeremypw** [comment]
Maybe could reduce the whitespace between lines a little for smaller icon sizes.

**Comment by jeremypw** [comment]
On review there is little scope for reducing whitespace as we need to leave space for the helper and other emblems (at least while they are positioned to protrude above and below the icon).  I suppose the icon renderer could be tweaked to reposition the emblems to the side when the icon size is less than "smaller".

**Comment by jeremypw** [comment]
I don't think there is a lot of benefit to preventing the user selecting the smallest icon size in List View so I have pushed a PR that removes that restriction.

**Comment by DisguisedBear** [comment]
> Maybe could reduce the whitespace between lines a little for smaller icon sizes.

That, plus 16px icon size would be preferable. I'm comparing the sizes right now to my macOS machine and its exactly 16px for the smallest setting in Finder. 

For the 16px icon setting I think the whitespace between lines can be made about 3px above and below the icon so it makes the total line height of 22px. Larger icon sizes could use a bit smaller whitespaces as well.

Just for comparison sake, here's how it looks in Finder with the smallest setting. The line height is a bit too thin with just 1 or 2px between lines, so 3px whitespace would probably look optimal for 16px icon size.

![Screen Shot 2020-07-14 at 18 25 25](https://user-images.githubusercontent.com/68272253/87446706-4d757900-c602-11ea-92f1-9733a1970e43.png)

**Comment by jeremypw** [comment]
As mentioned above, we would have to redesign where the emblems appear in order to reduce the whitespace. We cannot reduce the size of the helper emblem as it needs to be a click target. The more changes that are made, the harder it is to get through the review process.

**Comment by DisguisedBear** [comment]
You're talking about the selection checkmark circle? I'm not sure I understand what's the "helper emblem", you'll have to excuse my unfmiliarty with the terminology, I'm kinda new here.

If it's the selection checkmark, would it be possible to simply move it to the middle of the line so it would appear from the left of the icon but to the right of the arrow. Or does it require some extra work? maybe add it to a design wishlist for now?

**Comment by jeremypw** [comment]
Yes, helper-emblem = selection check-mark.  Its referred to as the "helper" in the code.  Yes, putting it between the expander arrow and the icon was what I was suggesting when I said "repositioning to the side".  It would add some additional complexity to the icon renderer as it would have to depend on the situation. Also requires approval of design team. I'll try and look into it when I have time.

**Comment by jeremypw** [comment]
![Screenshot from 2020-07-15 14 48 48](https://user-images.githubusercontent.com/10513844/87553042-69345a00-c6aa-11ea-8139-43e150a616d0.png)

I have found a way of reducing the row spacing for small icon sizes - see PR #1392 and above screenshot.
