### ISSUE TITLE
Clicking breadcrumbs in file picker takes me home

### ISSUE THREAD

**Issue by janxkoci** [elementary/files#1165]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
File picker / chooser usually shows last used folder when I want to save / open file, e.g. when saving email attachment. Sometimes I want to go one folder up in hierarchy from this last-used folder, but clicking in breadcrumbs resets it to home directory.

### To Reproduce
1. Try to e.g. save some file from email.
2. file picker should show last used folder
3. click in breadcrumbs to change to folder up in hierarchy
4. You end up in your home folder instead

### Expected behavior

Breadcrumbs should work as in normal Files, clicking breadcrumb should take you to selected directory.

## Platform Information

 - OS: elementary OS
 - OS Version: Juno

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
The code indicates that clicking on the pathbar is intended to work properly, but it for some reason it is not working.  As a temproary work around you can use the `<Alt>Up` shortcut to navigate to the parent folder.

**Comment by wout** [comment]
I can confirm this is fixed, and it's a relief. Thanks guys!
