### ISSUE TITLE
Tabs are deleted when "history" is disabled

### ISSUE THREAD

**Issue by cmburg** [elementary/files#1166]
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Describe the bug
I do not want to collect a history so I disabled it in system settings->privacy.
Then, when I close files, all opened tabs are deleted and I start fresh from Home. I see one might see this as a correct behaviour since tabs might be considered as history too but I see "history" as "last opened files like..."

### To Reproduce
1. Go to 'system settings'->'privacy'->disable history
2. open some tabs by pressing ctrl+t
3. close and reopen files
4. you should see one tab pointing to your home directory

### Expected behavior
The previously opened tabs are restored.

## Platform Information
![Screenshot von 2020-01-16 20 27 48](https://user-images.githubusercontent.com/18635557/72667949-97015480-3a21-11ea-8771-8af625804818.png)

Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
Yes, I am not too sure about this but the current behaviour matches that of Code and Terminal.  Have to see what UX team think.

**Comment by jeremypw** [comment]
As this design pattern is consistent with other elementary apps I am going to close now.
