### ISSUE TITLE
Only Office: "Could not open files or URIs with this app"

### ISSUE THREAD

**Issue by marbetschar** [elementary/files#1172]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

Whenever I try to open a Microsoft Office document in Files by clicking on it, I can see the following error message and the file does not open:

![Screenshot from 2020-01-20 18 29 07](https://user-images.githubusercontent.com/392542/72746686-065a7e00-3bb3-11ea-979b-27c537cfa312.png)

### To Reproduce

1. Open AppCenter and install "ONLYOFFICE"
2. Navigate to a Microsoft Office file in Files
3. Right click on the Microsoft Office file and select "Open in ONLYOFFICE Desktop Editors"
4. The error is thrown

### Expected behavior

The document opens successfully in ONLYOFFICE.

**Comment by marbetschar** [comment]
**UPDATE:** My bad. I assume that's because I've installed ONLY OFFICE via FlatHub and I  (wasn't aware of this fact, because I can't see that in the AppCenter)

**Comment by jeremypw** [comment]
I cannot see ONLYOFFICE in the AppCenter?  Have you installed a 3rd party ppa or something?  Is there a `.desktop` file for ONLYOFFICE in `/usr/share/applications`?  Can you show its contents?  It looks like the AppInfo being returned for this app does not have either the `supports_files` or `supports_uris` set to `true`.

Note, if you which to edit `docx` files locally you can use LibreOffice.

**Comment by jeremypw** [comment]
Just seen you last comment (written while I was writing mine).  I am not certain about FlatHub apps but I imagine they should work with Files so long as a suitable `.desktop` file is installed.

**Comment by jeremypw** [comment]
Have you tried launching the app from the command-line?

**Comment by jeremypw** [comment]
This may help: https://www.linuxbabe.com/office-suite/install-onlyoffice-desktop-editors-debian-ubuntu-mint-fedora-arch

**Comment by marbetschar** [comment]
@jeremypw wow, that was quick! :) I solved the issue by installing ONLYOFFICE via plain old apt, as described on their website: https://helpcenter.onlyoffice.com/desktop/documents/linux/installation-ubuntu.aspx

I assume it was shown in AppCenter because I already installed some FlatHub Apps before - and it seems AppCenter then also shows other apps from FlatHub.

**Comment by jeremypw** [comment]
Glad you solved the problem!  I just happened to be checking for new issues - not usually quite that fast ;-)
