### ISSUE TITLE
Opening a document via Files does not add it to Recent

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#1183]
I have searched open and closed issues for duplicates.
May be related to #851 but not a duplicate.

## Describe the bug
Opening a document in Code using the context menu of Files does not add it to the Recent View, even if it is edited.

### To Reproduce
1. Go to a folder containing a writable text file not already open in Code and not already in Recent View
2. Secondary click to show context menu and choose "Open in Code".
3. Edit the file in Code and the close it.
4. Navigate to Recent View in Files.  The used document does not appear.
5. Open the same file using Code and the close it.
6. The file appears in Recent View

### Expected behavior
Documents should appear consistently in Recent View regardless of the method used to access them.

## Platform Information
Elementary 5.1 Hera, daily
I'm using the latest version from git that I've manually compiled

## Additional context
The same issue applies to Music files.  However, opening a video with Videos *does* result in its appearance in Recent View.  It is uncertain whether this is an issue with Files, the individual apps, or with Zeitgeist.

**Comment by munepuun** [comment]
In Horus even opening with code does not add it to Recent in Files. 
Even though history is enabled using: System Settings - Security & Privacy - History -all items checked and enabled in the right corner.

I' ve checked it with: 
video files (.webm) opening using the default video app Videos.
And Photos ( .jpg) opening the default Photo app Photo's.

Are others having the same issue?

**Comment by jeremypw** [comment]
On reflection I do think this is an issue with Files but with the applications Files uses to open the various documents.  It is their responsibility to update Zeitgeist (or Tracker). I think.

**Comment by jeremypw** [comment]
A new issue was opened here: https://github.com/elementary/code/issues/1281

**Comment by jeremypw** [comment]
I can confirm that editing a photo with Photos (Viewer) does result in a new Recent entry.

**Comment by jeremypw** [comment]
I can confirm that opening a video with Videos does result in a new Recent entry.

**Comment by jeremypw** [comment]
I can confirm that operations carried out in the main Photos app do not result in a new Recent entry.
