### ISSUE TITLE
Following hotlinked file reference makes the view jump to the wrong place

### ISSUE THREAD

**Issue by Vortex-TH** [elementary/files#1187]
When I click on a link that refers to a file somewhere in the system, like this: `file:///home/username/Downloads/filename.txt` (which is used when clicking on downloaded files in the browser for example), the elementary files app is opened and it takes me straight to the file. The file viewer automatically scrolls to the corresponding file which is then auto-selected.

This works as it should as long as the default sorting order is active (sort by name). When this is changed to, let's say, "sort by date modified", the file viewer still scrolls to the location where the file would be if all files were sorted by name and not where it actually is according to the new sorting order.

os: elementaryos 5.1

**Comment by jeremypw** [comment]
The same issue also affects scrolling while entering a search term.

**Comment by 4jNsY6fCVqZv** [comment]
@jeremypw how could a solution look like?

**Comment by 4jNsY6fCVqZv** [comment]
@jeremypw how could a solution look like?

**Comment by jeremypw** [comment]
I'll try and find time to look into this, but there are a lot of PRs awaiting review.

**Comment by jeremypw** [comment]
The incorrect scrolling only affects IconView. The List and Column views do not scroll to the selected file at all - not sure why.

**Comment by jeremypw** [comment]
OK, so the cause is that the file gets selected (and the scroll position set) __before__ the sort order is applied when Files is launched with a target file so need to fix this race.
