### ISSUE TITLE
Closing the Home folder while being in a tab located at Home makes a small black square appear

### ISSUE THREAD

**Issue by ghost** [elementary/files#1192]
# Prerequisites
- [x] I have searched open and closed issues for duplicates.

# Describe the error

Closing the Home folder while being in a tab located at Home makes a small black square appear.

## To reproduce

1. Open Files.
2. Right click the current tab to close it, or press the Ctrl + W keyboard shortcut to close it.
3. A small, black square in the lower right corner appears.

## Expected behaviour

No black square appears.

Beyond that, I am unsure; it seems from a slightly related, _not identical_, and seemingly stalled issue #327 that the application should remain open; so, based on that, perhaps pressing Ctrl + W on the only remaining tab should do nothing, and the Close Tab option in the context menu when right clicking the only remaining tab should likewise be disabled.

## Screenshots or screen recordings

[Screen recording](https://github.com/elementary/files/files/4135719/Closing.the.Home.folder.while.being.in.a.tab.located.at.Home.makes.a.small.black.square.appear.zip)

# Platform information

![System information](https://user-images.githubusercontent.com/51057001/73479659-a88b1a80-4398-11ea-9437-49c0a22c62bb.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

Language: French
Keyboard: English (US) - English (Dvorak intl., with dead keys)
Location: Paris

The testing system is installed on a small partition on a ThinkPad T470 laptop on which UEFI Secure Boot is disabled. Aside from specifying the language, keyboard, location, initial user, and the specific partition in which to install elementary OS, all of the default settings were used during the installation. No Internet connection was used during the installation. The only system-wide changes which have been made after the installation are that the system connects to the Internet by wi-fi via a Linksys WRT54GL Wireless Router and that [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder/) has been installed via AppCentre.

# Additional context

Before this test was performed, the following steps were followed:

1. All system-wide changes from previous tests were reverted.
2. All system components were updated via the blue “Update All” button in AppCentre.
3. A new administrator user named “Essai” or “Essai 2” was created with the password “komalleana”.
4. The current user was logged out and the new user was logged in.
5. The old user was deleted, the screen resolution was set to 800x600 at 60 Hz, tap clicking was disabled, and the touchpad pointer speed was set to the maximal value.
6. The computer was rebooted.
6. The test user was logged in.

**Comment by jeremypw** [comment]
The small black square appears to be an empty overlaybar - this should only appear when hovering a file item but for some reason in this case is momentarily visible when the tab is initialised.  This only happens when the home tab is the only tab.  Ctrl-W then closes it and immediatey reopens it. There is some argument whether this is the correct behaviour anyway. - see #327.

**Comment by jeremypw** [comment]
Closing as no longer occurs in latest version.
