### ISSUE TITLE
Selection is updated when creating a new file or folder in a separate process

### ISSUE THREAD

**Issue by ghost** [elementary/files#1196]
# Prerequisites
- [x] I have searched open and closed issues for duplicates.

# Describe the error

The selection in Files is updated when creating a new file or folder in a separate process.

## To reproduce

1. Open two windows of Files.
2. In the first window, select a folder which is not the first folder in the view.
3. In the second window, create a new file or folder.
4. In the first window, the newly created file or folder is selected.
5. Open a Terminal.
6. Run the command: `echo Essai > Essai.txt`
7. In both Files windows, the newly created file is selected.

## Expected behaviour

Newly created files or folders are not automatically selected. Only that which the user has manually selected remains selected.

## Screenshots or screen recordings

[Screen recording](https://github.com/elementary/files/files/4135767/Selection.is.updated.when.creating.a.new.file.or.folder.in.a.separate.process.zip)

# Platform information

![System information](https://user-images.githubusercontent.com/51057001/73480099-9362bb80-4399-11ea-9f45-648adf5b6389.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

Language: French
Keyboard: English (US) - English (Dvorak intl., with dead keys)
Location: Paris

The testing system is installed on a small partition on a ThinkPad T470 laptop on which UEFI Secure Boot is disabled. Aside from specifying the language, keyboard, location, initial user, and the specific partition in which to install elementary OS, all of the default settings were used during the installation. No Internet connection was used during the installation. The only system-wide changes which have been made after the installation are that the system connects to the Internet by wi-fi via a Linksys WRT54GL Wireless Router and that [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder/) has been installed via AppCentre.

# Additional context

Before this test was performed, the following steps were followed:

1. All system-wide changes from previous tests were reverted.
2. All system components were updated via the blue “Update All” button in AppCentre.
3. A new administrator user named “Essai” or “Essai 2” was created with the password “komalleana”.
4. The current user was logged out and the new user was logged in.
5. The old user was deleted, the screen resolution was set to 800x600 at 60 Hz, tap clicking was disabled, and the touchpad pointer speed was set to the maximal value.
6. The computer was rebooted.
6. The test user was logged in.

**Comment by mcclurgm** [comment]
Superseded by #2022
