### ISSUE TITLE
cannot open/interact with lower level files in tree-view

### ISSUE THREAD

**Issue by eddieimada** [elementary/files#120]
When using files in column mode (tree-view) if you try to interact with any file located in a lower level than the last open folder it will not work.

Example:

dir1: dir2, file1, file2
dir2: file 3, file4

Open files in column mode, open dir1, then dir2. Try to open file1 or file2 by clicking and it will not work. However if right click and then select open it will work.

**Comment by jeremypw** [comment]
Is the cursor a pointer or a hand when you left click?  Are both a directory and a file selected?

**Comment by eddieimada** [comment]
Now that you mentioned I noticed that if I click when it is a hand (right over the file name) it does nothing and both are highlighted. However if I click on the empty space beside the file name (arrow cursor) it works.

**Comment by eddieimada** [comment]
This was fixed with a fresh reinstall. Closing this issue.
