### ISSUE TITLE
Copying a file from another folder and then switching view mode causes the application to close

### ISSUE THREAD

**Issue by KomalleanaByzantis** [elementary/files#1213]
# Prerequisites
- [x] I have searched open and closed issues for duplicates.

# Describe the error

Copying a file from another folder and then switching view mode causes the Files application to close.

## To reproduce

1. Open Files.
2. Open a folder in a new tab.
3. Create an empty file and copy it.
4. Go to the Home folder and paste the file there.
5. Change the view mode to List or Column.
6. The application closes.

- If you are unable to reproduce the error during subsequent attempts, then name the empty file something else and try again.
- The general pattern I found was that as soon as this error happened to a specific file, a file with that exact name would not reproduce the error.

## Expected behaviour

The application does not suddenly close.

## Screenshots or screen recordings

[Screen recording](https://github.com/elementary/files/files/4144371/Copying.a.file.from.another.folder.and.then.switching.view.mode.causes.the.application.to.close.zip)

# Platform information

![System information](https://user-images.githubusercontent.com/51057001/73610153-baf19800-45d4-11ea-8eea-98b9af911f84.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

Language: French
Keyboard: English (US) - English (Dvorak intl., with dead keys)
Location: Paris

The testing system is installed on a small partition on a ThinkPad T470 laptop on which UEFI Secure Boot is disabled. Aside from specifying the language, keyboard, location, initial user, and the specific partition in which to install elementary OS, all of the default settings were used during the installation. No Internet connection was used during the installation. The only system-wide changes which have been made after the installation are that the system connects to the Internet by wi-fi via a Linksys WRT54GL Wireless Router and that [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder/) has been installed via AppCentre.

# Additional context

Before this test was performed, the following steps were followed:

1. All system-wide changes from previous tests were reverted.
2. All system components were updated via the blue “Update All” button in AppCentre.
3. A new administrator user named “Essai” or “Essai 2” was created with the password “komalleana”.
4. The current user was logged out and the new user was logged in.
5. The old user was deleted, the screen resolution was set to 800x600 at 60 Hz, tap clicking was disabled, and the touchpad pointer speed was set to the maximal value.
6. The computer was rebooted.
6. The test user was logged in.

**Comment by jeremypw** [comment]
Did not happen with a folder, but happened with a file (??)

**Comment by jeremypw** [comment]
Only happens with specific sequence:  File must be right-clicked *immediately* after creation to cut or copy.   Possibly related to the PR #1200

**Comment by jeremypw** [comment]
Confirmed PR#1200 fixes this as well.

**Comment by aljelly** [comment]
I don't know if it's the same bug, but if I create a folder in Grid view and then switch to List view, Files crashes (segfault).

gdb output:

```
Thread 1 "io.elementary.f" received signal SIGSEGV, Segmentation fault.
0x00007ffff76611d8 in g_list_copy_deep () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) backtrace
#0  0x00007ffff76611d8 in g_list_copy_deep () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00005555555ccaab in  ()
#2  0x00007ffff7665d03 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7665285 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7665650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff76656dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff70c8e3d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x000055555557b5c7 in _vala_main ()
#8  0x00007ffff499fb97 in __libc_start_main (main=0x55555557b440 <main>, argc=1, argv=0x7fffffffe078, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffe068)
    at ../csu/libc-start.c:310
#9  0x000055555557b47a in _start ()
```

(the backtrace itself seems to not be very useful if it's all just from glib, probably lack of debug symbols/compilation doesn't help, but knowing it's from calling `g_list_copy_deep ()` might help locate the bug)

The folder was in `~/Misc/bugtest` and contained only one empty file. It seemed to happen much more inconsistently when I started Files with gdb, I had to do it several times in order to get the segfault. Either there's some other factor involved, or maybe it's a race condition of some sort?

**Comment by jeremypw** [comment]
Its probably the same bug - creating a folder starts a rename.  Did you switch views without exiting the rename or after finishing/cancelling the rename?

**Comment by aljelly** [comment]
I think I switched view after finishing the rename to get the crash, but I just tried switching the view without finishing the rename and it also crashes.

**Comment by jeremypw** [comment]
@aljelly : I can confirm the new folder problem. #1200 seems to fix this if you complete/cancel the rename but not if you switch view mode in the middle of a rename. Should probably either prohibit mode changes while renaming or force renaming to end before changing mode.

**Comment by jeremypw** [comment]
@aljelly Your crash is occurring in the OverlayBar so is unrelated to #1200 fix unfortunately.
