### ISSUE TITLE
Scrolling horizontally with a touchpad causes the pointer to retain the scrolling cursor

### ISSUE THREAD

**Issue by KomalleanaByzantis** [elementary/files#1214]
# Prerequisites
- [x] I have searched open and closed issues for duplicates.

# Describe the error

Scrolling horizontally with a touchpad causes the pointer to retain the scrolling cursor.

## To reproduce

- To reproduce this, you must use a laptop.

1. Open Files.
2. Switch to Column View.
3. Open a folder.
4. Scroll horizontally to the left and right using the touchpad.
5. The pointer retains the scrolling cursor.

## Expected behaviour

The pointer returns to using the normal cursor instead of retaining the scrolling cursor.

## Screenshots or screen recordings

[Screen recording](https://github.com/elementary/files/files/4144443/Scrolling.horizontally.causes.the.pointer.to.retain.the.scrolling.cursor.zip)

# Platform information

![System information](https://user-images.githubusercontent.com/51057001/73610457-b7abdb80-45d7-11ea-976e-9c4ff64b408d.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

Language: French
Keyboard: English (US) - English (Dvorak intl., with dead keys)
Location: Paris

The testing system is installed on a small partition on a ThinkPad T470 laptop on which UEFI Secure Boot is disabled. Aside from specifying the language, keyboard, location, initial user, and the specific partition in which to install elementary OS, all of the default settings were used during the installation. No Internet connection was used during the installation. The only system-wide changes which have been made after the installation are that the system connects to the Internet by wi-fi via a Linksys WRT54GL Wireless Router and that [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder/) has been installed via AppCentre.

# Additional context

Before this test was performed, the following steps were followed:

1. All system-wide changes from previous tests were reverted.
2. All system components were updated via the blue “Update All” button in AppCentre.
3. A new administrator user named “Essai” or “Essai 2” was created with the password “komalleana”.
4. The current user was logged out and the new user was logged in.
5. The old user was deleted, the screen resolution was set to 800x600 at 60 Hz, tap clicking was disabled, and the touchpad pointer speed was set to the maximal value.
6. The computer was rebooted.
6. The test user was logged in.

**Comment by jeremypw** [comment]
I do not get any cursor change when scrolling horizontally with touchpad with my usual settings. Could you post a screenshot of your touchpad settings? Thanks.

**Comment by KomalleanaByzantis** [comment]
@jeremypw The touchpad settings in the testing system are exactly as the default settings, except that tap clicking is disabled and the pointer speed is set to the maximal value, as I describe in the _Additional context_ section of my report. If you still want an image, then here is what the settings look like:
![Capture d’écran de 2020-02-03 17-24-57](https://user-images.githubusercontent.com/51057001/73670876-4ab54600-46aa-11ea-8a70-8df2684ebbaa.png)

**Comment by jeremypw** [comment]
Thanks - saves me trying to remember what the default settings are ;-)

**Comment by jeremypw** [comment]
Still cannot reproduce on my unstable install, but just tried out an unmodified stable install and can confirm that it does happen there.  I cannot recall ever seeing that "scroll cursor" so I guess I must have changed something.  My touchpad settings are the same as yours.
