### ISSUE TITLE
Opening folders and then switching to a different view mode causes the folder icons to always look open

### ISSUE THREAD

**Issue by KomalleanaByzantis** [elementary/files#1215]
# Prerequisites
- [x] I have searched open and closed issues for duplicates.

# Describe the error

Opening folders, switching to a different view mode, and then returning to the parent folder containing the aforementioned folders causes their icons to always look as though the folders are open.

## To reproduce

1. Open Files.
2. Switch to Column View.
3. Open a folder.
4. Switch to Grid or List View.
5. Return to the Home folder.
6. The folder which you previously opened has an icon which makes the folder look as though it is currently open.

## Expected behaviour

The folders visually look closed when they are closed, and look open when they are open; obviously, this only makes sense in List and Column View. In Grid View, a folder would always look closed.

## Screenshots or screen recordings

[Screen recording](https://github.com/elementary/files/files/4144463/Opening.folders.and.then.switching.to.a.different.view.mode.causes.the.folders.to.always.look.open.zip)

# Platform information

![System information](https://user-images.githubusercontent.com/51057001/73610520-8089fa00-45d8-11ea-8459-a1aaa3bc39f3.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

Language: French
Keyboard: English (US) - English (Dvorak intl., with dead keys)
Location: Paris

The testing system is installed on a small partition on a ThinkPad T470 laptop on which UEFI Secure Boot is disabled. Aside from specifying the language, keyboard, location, initial user, and the specific partition in which to install elementary OS, all of the default settings were used during the installation. No Internet connection was used during the installation. The only system-wide changes which have been made after the installation are that the system connects to the Internet by wi-fi via a Linksys WRT54GL Wireless Router and that [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder/) has been installed via AppCentre.

# Additional context

Before this test was performed, the following steps were followed:

1. All system-wide changes from previous tests were reverted.
2. All system components were updated via the blue “Update All” button in AppCentre.
3. A new administrator user named “Essai” or “Essai 2” was created with the password “komalleana”.
4. The current user was logged out and the new user was logged in.
5. The old user was deleted, the screen resolution was set to 800x600 at 60 Hz, tap clicking was disabled, and the touchpad pointer speed was set to the maximal value.
6. The computer was rebooted.
6. The test user was logged in.

**Comment by jeremypw** [comment]
Also occurs if open a subfolder in List View then change to Grid View.

**Comment by jeremypw** [comment]
May be related to PR #506
