### ISSUE TITLE
Right-clicking in a blank area in the folder when files/folders are selected shows options for those files/folders rather than the folder

### ISSUE THREAD

**Issue by aljelly** [elementary/files#1221]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Selecting any amount of files or folders and then right-clicking on a blank space in the folder shows the context menu for those files rather than the parent folder.

I don't actually know if this is a bug or intended behaviour. The problem is that when you have a grid of lots of files/folders in Grid view, you have to find a blank part of the folder that you can right-click. With the current right-click behaviour you often find you have to first deselect the items by left clicking on blank space (usually you have to find it again as the pointer has probably moved onto the context menu to some extent by then) and then right clicking there again.

### To Reproduce
Steps to reproduce the behaviour:
1. Open Files
2. Go to a folder with at least one file in it
3. Select any amount of files
4. Right click on a blank area within the folder

### Expected behaviour
The context menu for the parent folder shows.

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/10395308/73829263-96770500-47fa-11ea-9eb9-45ea98875193.png)

## Platform Information
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

It's elementary OS 5.1.

## Additional context
I think if this is fixed, it may be a good idea to retain the selection of files/folders so that your selection isn't lost if you right clicked in the wrong place (e.g. if it's a very specific, complex selection of files and folders).

**Comment by jeremypw** [comment]
I'd need to check the code but I think Files does assume that if a context menu is requested when a selection exists then the user wants to carry out an action on that selection.  Nautilus and Dolphin handle this by deselecting all the items if you secondary-click on the background which, as you say, is not ideal if the selection is complex.  PCManFM however, does implement the behaviour you suggest which does seem to be better.
