### ISSUE TITLE
Switching tabs and back without cancelling rename is possible using tab switching shortcuts

### ISSUE THREAD

**Issue by aljelly** [elementary/files#1225]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
You can switch to and from tabs without cancelling the rename action if you use keyboard shortcuts for switching tabs. This includes <kbd>Ctrl</kbd> <kbd>Tab</kbd>, <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>Tab</kbd>, <kbd>Ctrl</kbd> <kbd>1</kbd>-<kbd>9</kbd>, and possibly any other shortcuts for tab switching if there are any others.

### To Reproduce

1. Make sure you have at least 2 tabs open.
2. Go to a folder with at least one file or folder in it.
3. Start renaming the file/folder
4. Press Ctrl + Tab to switch to the next tab
5. Press Ctrl + Shift + Tab to switch back

### Expected behavior
It should cancel the rename action upon switching tab, like when using the mouse.

## Platform Information
elementary 5.1
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by aljelly** [comment]
Update: you can also do this by scrolling on tabs with mouse while renaming

**Comment by jeremypw** [comment]
The rename is intended to cancel if another view becomes active - not sure why it fails to do so in these cases.

**Comment by jeremypw** [comment]
In the latest release, renaming does not cancel when switching tab using the mouse (click or scroll) or the keyboard shortcuts so it is now consistent.  There does not seem to be any problem with this so I will close this for now.  Please feel free to reopen if a particular issue arises from this behaviour.
