### ISSUE TITLE
In-app file picker address bar does not always direct user to the correct page when choosing it via the 'breadcrumb' view

### ISSUE THREAD

**Issue by yerbestpal** [elementary/files#1226]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
First of all, I have to apologise for the title and explain it a little. I tried my best but hey-ho:
* by file picker, I mean the picker that is displayed when opening an external file with any given program; think opening a text file with Code
* by 'breadcrumb view', I mean the form the address bar takes when not accepting text entry
* this report is probably in the wrong repository, but I couldn't find where is should go, and I thought there might be a chance that it is somehow tied to Files

Now that the housekeeping is dealt with, on with the bug report.

### To Reproduce
Steps to reproduce the behaviour:
1. Open any file with any application.
2. Try to navigate backwards to a previous directory.
3. Observe whether or not you were taken to the correct directory.

### Expected behaviour
When selected a previous directly via the breadcrumb view, I should be taken to it.

### Screenshots or screen recordings
![full](https://user-images.githubusercontent.com/15250241/73999808-d1457e00-495d-11ea-9204-ff142e623018.png)
File picker.

![breadcrumb](https://user-images.githubusercontent.com/15250241/73999821-d73b5f00-495d-11ea-943b-d928f6a1bd66.png)
'Breadcrumb' address bar mode.

## Platform Information
![Screenshot from 2020-02-07 03-59-42](https://user-images.githubusercontent.com/15250241/73999953-4913a880-495e-11ea-8043-5ae55eb90558.png)

Please check what applies:
- [X] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context
It seems to be that I am always returned to the home directory, though I can't say for certain that that is definitely always the case.

**Comment by jeremypw** [comment]
This seems to be fixed in the master branch since the last release possibly due to 529e13833ec3d86827faf920e333e70e5d86975d

Maybe time for another release ...

**Comment by jeremypw** [comment]
Closing as fixed in last release.
