### ISSUE TITLE
Selecting any back/forward history menu option only goes back/forward one level

### ISSUE THREAD

**Issue by aljelly** [elementary/files#1227]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Trying to go back or forward in history more than one level always navigates back or forward only once (the most recently accessed path).

### To Reproduce
1. Open Files
2. Navigate into at least 3 folders (maybe go into 4-5 to make it more obvious)
3. Right click the back navigation arrow
4. Select the last item in the list (in other words, we're attempting to go back to the initial folder you started in)

### Expected behavior
Files should go to the path you selected.

## Platform Information
elementary 5.1
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
Also the file:// prefix is visible. (#1146)

**Comment by jeremypw** [comment]
I never use the menu so never noticed this!
