### ISSUE TITLE
File chooser failed to load (flatpak)

### ISSUE THREAD

**Issue by janxkoci** [elementary/files#1240]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Today I updated Epiphany Technology preview (aka Nightly, version 3.35.2) and it fails to open. Icon briefly appears in dock and then disappears again. When running `flatpak run org.gnome.Epiphany.Devel` in terminal, this is the output (and reason I report it here):

```bash
Gtk-Message: 15:30:41.521: Failed to load module "pantheon-filechooser-module"
libsecret-Message: 15:30:41.593: secret portal is not available: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Žádné rozhraní „org.freedesktop.portal.Secret“ neexistuje
Gtk-Message: 15:30:41.908: Failed to load module "pantheon-filechooser-module"
Gtk-Message: 15:30:41.942: Failed to load module "pantheon-filechooser-module"
```

### To Reproduce
1. Install Epiphany Tech preview via flatpak
2. Launch it
3. Boom!

### Expected behavior
Launch Epiphany Tech Preview, as before.

### Logs
See above.

## Platform Information

![Snímek z 2020-02-23 15-44-34](https://user-images.githubusercontent.com/19331850/75114097-75fcd680-5653-11ea-9477-d8c39101ff1a.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
Probably need to implement the FileChooser portal - which is on the roadmap.

**Comment by janxkoci** [comment]
Actually I got a few updates to Ephy (it's "Nightly" after all) and the one today aparently fixed something and now I'm able to launch the browser again :)

Still, portal will be great :)
