### ISSUE TITLE
No icon next to mounted drives

### ISSUE THREAD

**Issue by Teraskull** [elementary/files#1243]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When the drive is not mounted, the icon next to it is visible. It disappears when you mount the drive.

### To Reproduce
1. Go to Files
2. Mount any drive that is not mounted yet.
3. Icon disappears.

### Expected behavior

Have the same icon that was before mounting.

### Screenshots or screen recordings

![Devices](https://user-images.githubusercontent.com/24798198/75415423-dcbc1180-592b-11ea-8123-dc7d35a343c0.png)

## Platform Information

 - OS: elementary OS
 - OS Version: 5.1.2 Hera

- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
I am not seeing this with my harddisk or solid-state drives.  Could you give more info about your "My Passport" device? i.e. type of hardware, file system, whether encrypted etc

**Comment by Teraskull** [comment]
> I am not seeing this with my harddisk or solid-state drives. Could you give more info about your "My Passport" device? i.e. type of hardware, file system, whether encrypted etc

"My passport" is the Western Digital external SSD

![image](https://user-images.githubusercontent.com/24798198/75425644-69be9500-5943-11ea-9de0-e759232afd6b.png)

The icons are default elementary, so is the theme. I reinstalled the OS, and the issue still persists. 

As I am dualbooting, the issue also happens to the drive that has Windows installed, and the file drive, all of them are SSDs, and are formatted to NTFS.

**Comment by jeremypw** [comment]
OK, thanks for the extra info. I'll have a look at the code to see if I can see any reason for this. I wasnt aware that the icon could change depending on mount status.

**Comment by jeremypw** [comment]
OK, so when mounted the icon is returned by the Gtk function `mount.get_icon ()` whereas unmounted volumes the icon is returned by `volume.get_icon ()`.  For me these have always been the same but for that device it looks like either no icon is returned or the icon is not recognized by the theme.  I guess we should provide a fallback (e,g, the unmounted icon) under these circumstances.

**Comment by Teraskull** [comment]
> For me these have always been the same but for that device it looks like either no icon is returned or the icon is not recognized by the theme

I experimented, and installed another system on a new partition, so in the Files, I can see:

1. Windows 10 partition
2. Separate SSD for files
3. External SSD
4. Partition "/" from previous system
5. Partition "/home" from previous system

Only partitions 4 and 5 show icons when mounted, others don't.
Hope you find this info useful.

**Comment by jeremypw** [comment]
I tried creating NTFS partitions on both SSD and HD (internal) using gparted.  I could mount both of these with FIles without losing the icon. As mentioned above the best we can do is to provide a fallback should the usual way of getting an icon fails for whatever reason.

**Comment by Teraskull** [comment]
> As mentioned above the best we can do is to provide a fallback should the usual way of getting an icon fails for whatever reason.

Any drive icon would be better than no icon, I guess. Would be great.

**Comment by jeremypw** [comment]
@Teraskull  I have proposed a fix for this (#1250) but cannot properly test it as I do not experience the issue on my system.  If you are able to build this branch and see whether it fixes your problem then that would be helpful.  The PR is currently blocked for merging until the imminent release of v4.4.1 so no hurry.

**Comment by Teraskull** [comment]
> If you are able to build this branch and see whether it fixes your problem then that would be helpful.

Built the branch, everything seems fine, all of my drive icons are visible when mounted. Thanks a lot!

![Screenshot from 2020-03-01 21 32 05](https://user-images.githubusercontent.com/24798198/75633362-6279de80-5c04-11ea-818b-51894e17a29e.png)

**Comment by jeremypw** [comment]
@Teraskull  Thanks! Could you leave a comment on the PR as well?

**Comment by Teraskull** [comment]
@jeremypw sure, should I close this issue now?

**Comment by jeremypw** [comment]
@Teraskull No, it will close automatically when the PR is merged :-)
