### ISSUE TITLE
After creating a new file/folder without some characters in the input field you cannot delete it, context menu does not work either

### ISSUE THREAD

**Issue by J0Ar** [elementary/files#1252]
## Prerequisites
- [x] I have searched open and closed issues for duplicates…and did not find a similiar one.

## Describe the bug

In Files 4.4.1 you can not delete a new folder, when you just create it without some characters in the input field. Context menu also does not work as long as you not restart io.elementary.files.

### To Reproduce
1. Create a new file/folder with context menu or keyboard shortcut and make sure it does not have a name (delete all characters in the input field) and press enter...now the name is 'New file' or 'New folder'
2. Now you cannot delete this new file or folder, only a restart of files helps.

### Expected behavior
Deleting the new file/folders works as expected with [DEL] or with the context menu.

Please share a screenshot of the System Settings > About screen.
![Bildschirmfoto von 2020-03-04 18-27-11](https://user-images.githubusercontent.com/23266409/75905807-d2c37280-5e45-11ea-9018-32cdceae43dc.png)

Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
Confirmed - but you can unfreeze Files by changing the view mode. Possibly a regression after 164df0075894373d7d611e57e1f3c52d279ab1b7.

**Comment by J0Ar** [comment]
You are right, changing the view-mode also unfreeze Files.
