### ISSUE TITLE
Draging a linked directory to create new bookmark don't work

### ISSUE THREAD

**Issue by megatux** [elementary/files#1254]
## Prerequisites
- [x ] I have searched open and closed issues for duplicates.

## Describe the bug
Draging a linked directory (sym. link) to create new bookmark don't work. Probably permissions issues but I can enter and work there from a terminal, so I expect the same from Files.

**ls -l** info: 
    lrwxrwxrwx  1 tuxmega tuxmega   19 mar  1 19:17 code -> /home/megatux/code//

### To Reproduce
Drag & drop the directory to left panel to create bookmark.
No bookmark is created. No error is displayed.

Adding a small screencast video attached to show it.

## Platform Information
elementary OS 5.1.2 Hera

Please check what applies:
- [x] I'm using the latest released stable version

[Screen record.zip](https://github.com/elementary/files/files/4293370/Screen.record.zip)

**Comment by jeremypw** [comment]
The only way I was able to reproduce this was to rename the folder to which the link points.  The sidebar will not accept links that point to a non-existent file.  Even if you remove all permissions from the target, you can still create a bookmark from a link pointing to it.  I haven't tried changing permissions on the actual link file (using the Files UI, changing permissions on a link just changes them on the target).

I notice from your `ls -l` output that the path pointed to appears malformed. On my system, there are no trailing '/'.  Again, if the path is malformed for any reason it will not point to a valid file and the sidebar will not bookmark it.

I suggest you recreate the link using the Files UI and try again.  Also why not just drag the target folder onto the sidebar?

**Comment by jeremypw** [comment]
Weird - there should be no difference at all.  If there is a problem with drag and drop in general then that would explain the sidebar issue. 

After searching old issues I remembered this: https://github.com/elementary/files/issues/890#issuecomment-544262130

Could this be related to your issue? I did produce a fix but it didn't attract reviewers attention so I was going to try and find a simpler solution. I'll try and find time to look at it again.

**Comment by megatux** [comment]
Forget about the "other" Files app working, it's not the ElementaryOS _Files_ app :man_facepalming: :grin: 
So, I'm assuming Files app does not support this "drag to left-panel to create a shotcut" functionality. If that's true, then I will close this ticket.

**Comment by jeremypw** [comment]
Yeah, it can be confusing with other file-managers having the same icon and name!
