### ISSUE TITLE
Use a local .desktop for persistent dynamic quicklists

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#127]
@danrabbit and I were talking about how to improve dynamic quicklists in Files (so they persist even when the app isn't running). We could do something like copy the .desktop into `~/.local/share/applications` and add the bookmarks dynamically.

If we find this is useful, we could wrap it up somehow in Granite to be more easily usable by other apps as well.

**Comment by cassidyjames** [comment]
This also gets us away from using LibUnity dynamic quicklists, which are effectively dead now that Unity is going away. :P

**Comment by jeremypw** [comment]
I had a branch on Launchpad that implemented persistent quicklists by having them handled by the daemon; however that use the existing unity framework and was part of a more far-reaching change.

see https://code.launchpad.net/~jeremywootten/pantheon-files/transfer-popover-with-pie-progress

**Comment by cassidyjames** [comment]
@jeremypw ah yeah if the app has a daemon anyway then that could work. But I'd rather not encourage apps to have an always-running daemon just for quicklists, and I feel like either Plank/Slingshot should cache/persist those items (like what modern Android does), or we should lean on the existing .desktop spec for this.

**Comment by jeremypw** [comment]
Closing this as it is unclear whether this is in line with current design and the new dock etc.
