### ISSUE TITLE
[DAILY] Can't drag anything (folder or file) to other locations

### ISSUE THREAD

**Issue by lainsce** [elementary/files#1270]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
After opening two windows of Files today (or a single window with two tabs of different locations), and attempting to move files or folders to other locations, it doesn't do anything.

### To Reproduce
1. Open 2 Files windows (or even a new tab).
2. Select a file/folder.
3. Attempt to drag this selected file/folder to the other window location.
4. See how it doesn't do anything.

### Expected behavior
It should be able to move the file/folder to the other location as before.

## Platform Information
elementary OS Hera [Daily]

- [x] I'm using the latest version from git (from daily)
- [ ] I'm using the latest released stable version

**Comment by jeremypw** [comment]
Regression due to 491a9e04be21e7816c12655e5b584f55bd8c4d88. Willl fix immediately.
