### ISSUE TITLE
Suggestion for a better UI when sending through bluetooth

### ISSUE THREAD

**Issue by Fatih20** [elementary/files#1271]
The current UI of sending stuff through bluetooth isn't really aesthetically pleasing and really feels like programmer design.
![Original](https://user-images.githubusercontent.com/51940383/77720990-1dd33e80-701c-11ea-8a7e-ef16bd33bad4.png)

I'm suggesting for the use of images in it to make it less boring. Like this :
![Mockups](https://user-images.githubusercontent.com/51940383/77721035-3f342a80-701c-11ea-86cf-47334d7aa019.png)
Or this (if I'm using a laptop)
![Mockups L](https://user-images.githubusercontent.com/51940383/77721044-478c6580-701c-11ea-9f91-fb07414e3d5f.png)
 This is just mockups so it's not my final suggestion of how it'd look. If possible, an animated instead of static image like the file transfer window in Windows XP would be nice. I could make the corresponding animation if needed.

**Comment by jeremypw** [comment]
I agree about the design but this UI is not supplied by Files (nor, as far as I can see, the wingpanel or switchboard bluetooth plugins.  It may be coming from Gnome (bluetooth-sendto?).
