### ISSUE TITLE
Creation/modification timestamp missing from file properties

### ISSUE THREAD

**Issue by derkomai** [elementary/files#1279]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When I right click a file -> Properties, the file menu does not show the creation/ last modification timestamps.

If applicable, add screenshots or screen recordings to help explain your problem.

### To Reproduce
1. Go to any file
2. Right click on it
3. Select properties
4. No created / last modified tag is visible

### Expected behavior
Until a few days ago, file modification information showed in the properties menu.

## Platform Information
 - elementary OS
 - Juno
 - 5.1.3

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
Thanks for noticing this regression, which seems to have been present for a while.  A fix is in progress.
