### ISSUE TITLE
Copy progress

### ISSUE THREAD

**Issue by Djaler** [elementary/files#128]
When I tried to copy some files to flash drive, I see something strange. Look at attached video
https://youtu.be/QpcpjrHcbQo

**Comment by jeremypw** [comment]
I presume you are referring to the fact that progress rapidly approaches 100% then seems to stall?

I suspect this is due to the write being cached rapidly but the actual transfer happening more slowly. Does the progress window eventually close?

**Comment by Djaler** [comment]
I did not wait for 10 minutes

**Comment by jeremypw** [comment]
Hmm, its unlikely to take that long unless there was an enormous amount of data being transferred over a slow link.

**Comment by Djaler** [comment]
I reproduce it with different USB drives, also

**Comment by Djaler** [comment]
It ended in 15 minutes. But without any changes in progress bar it looks like freeze, you know

**Comment by jeremypw** [comment]
OK, do transfers of smaller files work OK?  I agree we should try to find a way of detecting whether cached data is still being transferred so the user does not prematurely unplug the drive (although if you press the unmount button it should tell you it is busy)

**Comment by Djaler** [comment]
I managed to localize the problem a bit. When I format flash drive to NTFS instead of FAT32, progress bar works good. And it ended in less than a minute

**Comment by jeremypw** [comment]
OK, sounds like something to do with the gvfs backends for those filesystems working differently.  Files leaves all those details to Gio and Gvfs - it does not know what filesystems are actually in use.

**Comment by Djaler** [comment]
Also, cancel button do nothing for me

**Comment by jeremypw** [comment]
I am just transferring a 1.9GB iso to a FAT32 thumbdrive and the progress bar is showing about 13Mb/Sec transfer rate - falling now to about 10 Mb/sec.  The progress appears to be realistic except that it remained in view for about 10 - 15 seconds after the "time remaining" fell to 0 seconds.  Maybe I have write caching turned off (I vaguely remember tweaking something ...)

**Comment by jeremypw** [comment]
When I press "Cancel" while the progress bar is moving, the progress halts immediately but it takes 10 - 15 seconds for the window to close.  It seems like there is a certain amount of data "committed" to the transfer which cannot be cancelled and the window waits for this to complete?  I presume you pressed "Cancel" when the bar was already showing most of the 2Gb as transferred?

**Comment by Djaler** [comment]
Yes, because it showing 1.9GB after 1 second by start. Also, I tried many small files (mp3). Progress bar works good, but cancel button do nothing in this case too.

**Comment by jeremypw** [comment]
I tried Thunar and it behaves similarly, except that when cancel is pressed the message in the progress window changes to "cancelling ... ", which is something we should perhaps copy.  I'll see whether I can turn write caching on and test again.

**Comment by jeremypw** [comment]
When transferring many small files, I would expect cancel, if pressed while the progress is less than 90+% to stop the transfer of any more files but not stop any data already cached. Depending on the amount cached it could take some time for the window to close.

**Comment by jeremypw** [comment]
The progress window reacts to cancel (apart from requesting the current operation to cancel) between individual file transfers, so it may react faster when the operation comprising many small files rather than one large one.

**Comment by jeremypw** [comment]
Closing as a specific issue unrelated to the underlying system caching etc was not never clearly identified.  Please raise a specific actionable issue for Horus if required.
