### ISSUE TITLE
Quick Connect to Remote Location

### ISSUE THREAD

**Issue by marbetschar** [elementary/files#1281]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature

I'd love to "favourise" remote, network shares to be able to quickly connect/reconnect to them. My use case is: I need to access a network share which is available in my companies LAN. Obviously this network share is only available if I'm in the office or connected through VPN.

**Describe the solution you'd like**

A way to "store" remote location information without actually being connected. The connection should only be established, if this piece of information gets "activated".

**Existing work**

Connection wise everything is in place. But as it is right now, I need to create a new "Server Connection" every time I want to use the network share:

![Screenshot from 2020-04-09 09-34-34](https://user-images.githubusercontent.com/392542/78870283-2711d180-7a46-11ea-91db-162ab6a895f9.png)

**Comment by jeremypw** [comment]
You can bookmark a location on a remote share. Is this not sufficient?

**Comment by marbetschar** [comment]
@jeremypw awesome, a bookmark solves that beautifully! I just wasn't aware of this feature, because I started to look for a way to create a bookmark for the mounted drive exploring its context menu (see screenshot below). Any chance we can add a bookmark option there?

![Bookmark](https://user-images.githubusercontent.com/392542/78973632-994ee880-7b10-11ea-8cc4-6d7e4eb2e779.png)

**Comment by jeremypw** [comment]
@marbetschar I guess that is a possibility for temporary network locations.  Even better if the bookmarked network location appears in the Network category.

**Comment by marbetschar** [comment]
Yeah, would love displaying it in the network section. 👍🏼
