### ISSUE TITLE
Copy images instead of their path

### ISSUE THREAD

**Issue by rajkumaar23** [elementary/files#1282]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
I’m always frustrated when I copy an image and try to paste it on, say Telegram, the path of the image gets pasted rather than the image itself.

**Describe the solution you'd like**
When an image is copied, I would like to be able to paste it as image in any other place rather than pasting the path. 

**Existing work**
Yes, it works on Nemo of Linux Mint

**Comment by rajkumaar23** [comment]
@cassidyjames @danrabbit Your thoughts?

**Comment by jeremypw** [comment]
At the moment the Files ClipboardManager only provides "x-special/gnome-copied-files" (for pasting files) and "UTF8_STRING" (for pasting text) targets.  I guess it would be possible to provide an image target as well where the file represents an image.  What is the simplest app that suffers from this problem, do you know? I would need something to test a solution.

**Comment by rajkumaar23** [comment]
@jeremypw As I mentioned, it would be useful to send pictures in Telegram by copy-paste.

**Comment by jeremypw** [comment]
OK, but I did not want to install Telegram particularly if there was a simpler app.

**Comment by rajkumaar23** [comment]
![image](https://user-images.githubusercontent.com/37476886/79694638-3affd380-828f-11ea-8356-f36c2dbb2e88.png)
This is the simplest I could think of :)

**Comment by jeremypw** [comment]
Ah, OK - good point. I usually drag and drop the image - which triggers uploading.  (Does DND work with Telegram?)

**Comment by rajkumaar23** [comment]
@jeremypw I didn’t understand the context of your question on DND.

**Comment by jeremypw** [comment]
I mean can you drag an image file out of Files and drop it into Telegram in order to transfer the image?  This works with GitHub.

By the way I just tried Nautilus copy-paste to try and put an image in this message but it just transferred the path like Files.   I found that there is a "copyimage" extension available for Nautilus (https://www.maketecheasier.com/copy-paste-images-clipboard-nautilus/) - is that what you are using?

**Comment by rajkumaar23** [comment]
Yes, DND works with Telegram. But since I’m more of a maximised window user, I don’t find that much useful :(

Also, sorry for the Nautilus thing. I was using Nemo on Linux Mint and it was working.

**Comment by jeremypw** [comment]
OK, I'll try Nemo and if it works I'll have a look at the source code.

**Comment by jeremypw** [comment]
I have a branch that works with GitHub (pasting png images into comments).  Does Telegram take png images as well?

**Comment by rajkumaar23** [comment]
Yes, Telegram does.

**Comment by jeremypw** [comment]
Actually, the branch seems to work for other image formats as well (tried svg and jpg) - they just get converted to png.

**Comment by rajkumaar23** [comment]
Well, in Telegram when you DND an image, you have two options - send compressed image (or) send original file. Will your branch satisfy the latter as well ?

![image](https://user-images.githubusercontent.com/37476886/79732519-6cb97e80-8311-11ea-9b2a-6395a4f10bb3.png)

**Comment by jeremypw** [comment]
No, I am afraid not, it is intended for UI-less operation using only keyboard shortcuts for Copy/Paste. Image files get converted to pixbufs when requested from the clipboard.

**Comment by rajkumaar23** [comment]
I think it would be helpful for you to know that both the options are shown when I take a screenshot using `Ctrl + PrtScr` and paste it on Telegram.

**Comment by jeremypw** [comment]
I think this functionality is probably provided by Telegram then, in which case you will hopefully get the same options when pasting an image from Files.

**Comment by rajkumaar23** [comment]
@jeremypw Hope to see it :) Thanks for the quick response 😁️

**Comment by AmitJoki** [comment]
+1  This is a serious issue. I am Web Developer and I want to build a feature where people can paste files to upload like how Whatsapp Web and Slack lets you do.

But I only get paths here and no paste event works in Browser. Earlier I could paste images in Whatsapp Web. Some build must have broken that feature.
