### ISSUE TITLE
File info popover does not show if files are in List View

### ISSUE THREAD

**Issue by drom98** [elementary/files#1285]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When using files with list view, if I hover over a file it does not show the file information on the bottom right of the window like what happens with the other views. 

![imagem](https://user-images.githubusercontent.com/19615827/79617992-bd0dc200-8100-11ea-941a-9246e7d6e6ae.png)

### To Reproduce
1. With list view active, go to any file
2. Hover over the file
### Expected behavior

Should appear the file information on the bottom right of the window.
## Platform Information
![imagem](https://user-images.githubusercontent.com/19615827/79618109-17a71e00-8101-11ea-998a-88a0c0ee841d.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
Could be usefull to show some more information about the file under "Properties".
![imagem](https://user-images.githubusercontent.com/19615827/79618208-53da7e80-8101-11ea-9c4f-cea334dae86f.png)
This is the properties window from an image file. Why not show the width and height for example?

**Comment by jeremypw** [comment]
It has long been the case, by design, that the List View does not show the popover, presumably because similar info was already visible. I think the popover shows more info than it used to so I am not sure the original reasoning is still valid.  It would be very simple to show the popover in list view.  I'll flag this for UX team input.

**Comment by jeremypw** [comment]
Please raise a separate issue about the content of the Properties window (if not duplicated)

**Comment by drom98** [comment]
> It has long been the case, by design, that the List View does not show the overlay, presumably because similar info was already visible. I think the overlay shows more info than it used to so I am not sure the original reasoning is still valid. It would be very simple to show the overlay in list view. I'll flag this for UX team input.

I see. But if I'm using files with list view active how am I supposed to view those details?

**Comment by jeremypw** [comment]
Good question.  You can only bring up the Properties Window or switch to either Icon or Column view mode at the moment.
