### ISSUE TITLE
Switching selection in search results with "Tab" key

### ISSUE THREAD

**Issue by workstation-i** [elementary/files#1286]
## Feature
I think it's very helpful if I can switch the selection in search results with "Tab" key.

**Comment by in-character** [comment]
Meanwhile, I hope the problem in [https://github.com/elementary/os/issues/329] won't happen in pantheon-file.

**Comment by in-character** [comment]
**Another feature**: go to upper level directory with "Backsapce" key.

**Comment by jeremypw** [comment]
You can switch the selection with the "Up" and "Down" keys and activate the selection with the "Enter" key.  Please explain further the advantage of using the "Tab" key.

**Comment by jeremypw** [comment]
You can go to the parent directory with `<Alt>Up`.

**Comment by in-character** [comment]
1. there exists so many cases using Tab to swtich selection
urlbar in chrome  firefox 
File Manager in Ubuntu and mint
launcher in Ubuntu / elementary / 
...
So why not in pantheon-file
2. brain memory
Oh, my poor English. I can't explain it precisely.
But you can image that through the title.
3. it's more convenient to select and active
First, "Tab" key is bigger in keyboard. And you don't need to move your wrist to press it after inputing sth.
Second, image that `combination 1: Tab + Enter`  and `combination 2: Down + Enter`.
Combination 1 is obviously more convenient and effective. **Coordination with both your hands, man.**
---
"Backspace" is set `go back` in File Manager of Ubuntu and Mint. And it's really effective in some situation.

**Comment by jeremypw** [comment]
OK, thanks for the additional justifications.  I'll flag for UX team input.

The backspace issue has already been addressed by the UX team (see https://github.com/elementary/files/issues/291)

**Comment by in-character** [comment]
Thank you for consider it.
