### ISSUE TITLE
Resizing Filename column causes weird behaviour

### ISSUE THREAD

**Issue by jtrees** [elementary/files#1292]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
This one is a bit hard to describe, so I've added a screen recording. Basically, if you resize the Filename column, it triggers various anomalies and puts the window into a state that you can only recover from by closing and re-opening the app.

Here is a summary of each issue:

1. Resizing the column can cause the sidebar width to shrink.
2. Resizing the column can cause the window width to grow.
3. If (1) occurred, then the sidebar is no longer resizable.
4. If (2) occurred, then usually (interestingly, not always) the window is no longer snappable at the edge of the screen.
5. If (2) occurred, then the window width can no longer be reduced.

### To Reproduce
1. Open Files
2. Increase the size of the Filename column

### Expected behavior
- The sidebar should always retain its size when resizing a column.
- The window should always retain its size when resizing a column.
- If the Filename column has reached it's maximum possible size, it should simply stop growing, regardless of mouse movements.
- The window should always be resizable.

### Screenshots or screen recordings
![2020-04-22-files_bug](https://user-images.githubusercontent.com/5802758/79978283-f72fe880-849f-11ea-8887-8ac99e2e291d.gif)

## Platform Information

![Screenshot from 2020-04-22 13-52-26](https://user-images.githubusercontent.com/5802758/79978842-db791200-84a0-11ea-9329-5ca6dde0ab04.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
This seems to be down to the choices that were made for the "shrink" and "resize" parameters used when adding the sidebar and notebook to the HPaned.  These can be adjusted to make the behaviour the same as Nautilus ( that is, instead of the window width increasing, some of the view content disappears beyond the right-hand side).  Perhaps this would be more acceptable?
