### ISSUE TITLE
Tags are disappearing

### ISSUE THREAD

**Issue by mathessaricci** [elementary/files#1297]
When I select a colour for a file or folder it disappears after I close the window and I have to tag it again. For example: I tag "Text.odt" with yellow...All ok! But if I close the window when I reopen it the "Text.odt" is uncoloured again!

**Comment by jeremypw** [comment]
This is not happening for me - the color tag plugin is working as expected.  Please provide full details regarding the versions of Elementary and Files you are using and any changes to the default settings you have made.

**Comment by jeremypw** [comment]
For info, the color tag info is stored at `/home/jeremy/.config/marlin/marlin.db`

**Comment by jeremypw** [comment]
Try running Files from the commandline with debug messages enabled `G_MESSAGE_DEBUG io.elementary.files` to see whether there are any messages from the color tag plugin when you add a color tag.

**Comment by mathessaricci** [comment]
I'm running the latest version of elementary OS Hera 5.1.3. The only change I made was force the X11 resolution using this script that I run every session:

#!/bin/bash

echo "Criando nova resolução..."
xrandr --newmode "1600x900_60.00"  118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync
sleep 1
echo "Adicionando nova resolução..."
xrandr --addmode eDP-1 1600x900_60.00
sleep 1
echo "Configurando..."
xrandr --output eDP-1 --mode 1600x900_60.00
echo "PRONTO!"
exit

This script is at /bin/

**Comment by mathessaricci** [comment]
None bug report when I run the command 

> G_MESSAGE_DEBUG=all io.elementary.files

**Comment by jeremypw** [comment]
Hmm, not sure what is causing this for you.  Will wait to see whether others report same problem.

**Comment by mathessaricci** [comment]
Thank you very much!

**Comment by mathessaricci** [comment]
Tags are disappearing no more, so I'll close the issue
