### ISSUE TITLE
Add files pop-up preview

### ISSUE THREAD

**Issue by mathessaricci** [elementary/files#1299]
It'd be very cool if files had a feature like gnome-sushi on nautilus, for example, this way we could access the content of our documents, photos and videos without need to open them.

**Comment by jeremypw** [comment]
This is a duplicate of several others. It has already been determined that Elementary will not support a previewer natively but some work is ongoing to provide a 3rd party plugin to link to Sushi.
See #438 and #1289

**Comment by mathessaricci** [comment]
Sorry for my mistake. Thank you very much for explaining!
