### ISSUE TITLE
Failed to install a new font

### ISSUE THREAD

**Issue by andirsun** [elementary/files#1301]
## Prerequisites
- [x ] I have searched open and closed issues for duplicates.

## Describe the bug
When i hit in the install buttton for a .ttf font, any action happend, if i hit the button again says "failed instalation". 

If applicable, add screenshots or screen recordings to help explain your problem.

### To Reproduce
1. Go to ' some font.ttf file'
2. Click on 'the font to install '
4. See error "it not show that the font is installed if i click again says install failed"

### Expected behavior

I expect when i click in the install button, the button needs to put disabled until the font will be installed, maybe could you add a spiner or something 

### Screenshots or screen recordings

https://streamable.com/4a84vf
## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x ] I'm using the latest released stable version

**Comment by jeremypw** [comment]
This is not a Files issue - Files is just responsible for opening the Fonts app.

**Comment by micahilbery** [comment]
The fonts app shipped by default is GNOME Fonts app.

To report an issue with GNOME Fonts, please see their Gitlab page here: https://gitlab.gnome.org/GNOME/gnome-font-viewer
