### ISSUE TITLE
Stop icon on file progress dialog looks odd.

### ISSUE THREAD

**Issue by gkr09** [elementary/files#1308]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The cancel icon on file copy dialog in the files app appears on a sharp grey square which doesn't go well with rest of the theme.

### To Reproduce
1. Copy a file to another disk
2. The cancel/stop icon on the dialog looks odd, on a grey square

### Expected behavior
Maybe a circular button or a button with .destructive action??!

### Screenshots or screen recordings
![Screenshot from 2020-04-30 11-50-17](https://user-images.githubusercontent.com/33555597/80679000-a8a2cf80-8ad9-11ea-86d0-17f7f37dc24c.png)

## Platform Information
 - OS: elementary OS
 - OS Version : 5.1.3 Hera

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
Maybe because .flat styleclass is added to the icon?
(files/src/View/Widgets/ProgressInfoWidget.vala:69)

**Comment by danrabbit** [comment]
This is the default focus style for flat buttons. This is part of the design of the system stylesheet. Closing this issue as "Out of Scope" for Files
