### ISSUE TITLE
make zeitgeist integration optional

### ISSUE THREAD

**Issue by decathorpe** [elementary/files#1312]
On fedora, there are only a few packages left that require zeitgeist, including Code (where it's optional), Files (not optional), Music (not optional), Slingthot (optional), and two other non-elementary packages. 

Would it be possible to make the zeitgeist integration in Files optional? It looks like zeitgeist is a pretty dead project, with only ~15 git commits in the three years since 2017's 1.0 release, and most of those are "only" compilation fixes by tintou and ricotz.

**Comment by jeremypw** [comment]
See #1313.  The deb-packaging branch still has unity and zeitgeist as build dependencies though, but presumably it Files is repackaged for Fedora?

**Comment by decathorpe** [comment]
This is implemented now. Closing the ticket. Thanks!
