### ISSUE TITLE
The placeholder text line on the search entry is misaligned, it should be more central

### ISSUE THREAD

**Issue by IDOHAVENOT** [elementary/files#1316]
![Screenshot from 2020-05-04 01-51-12](https://user-images.githubusercontent.com/64141145/80931509-d32aac00-8da9-11ea-95a4-f22ee758fcbc.png)

**Comment by jeremypw** [comment]
On my system (elementary Hera 5.1  with the default elementary theme) the text is slightly too low:
![Screenshot from 2020-05-04 08 45 16](https://user-images.githubusercontent.com/10513844/80945478-d04cad00-8de3-11ea-9f50-9a4f55574242.png)
![Screenshot from 2020-05-04 08 48 27](https://user-images.githubusercontent.com/10513844/80945631-1f92dd80-8de4-11ea-8b24-58f832f257cf.png)

But with Adwaita theme:
![Screenshot from 2020-05-04 08 50 51](https://user-images.githubusercontent.com/10513844/80945782-7d272a00-8de4-11ea-94f4-856b16f61068.png).

While Files is only intended to behave properly on elementary with the elementary theme, the position of the text should not really change this much with another theme.

**Comment by jeremypw** [comment]
Strangely, this only affects the placeholder text.  The path text and any entered search term is centered.

**Comment by 4jNsY6fCVqZv** [comment]
This is how it looks to me with the last stable elementary OS 5.1.4 Hera and without any modifications.

![Screenshot](https://user-images.githubusercontent.com/46536067/80969476-30a21580-8e09-11ea-90a3-a40ad48c49e3.png)

**Comment by 4jNsY6fCVqZv** [comment]
@jeremypw How do you explain that it looks different in my default installation than in your screenshots? https://github.com/elementary/files/issues/1316#issuecomment-623313711

**Comment by jeremypw** [comment]
@4jNsY6fCVqZv No idea - I might have changed the default font. Anyway a fix has been merged now so hopefully everyone will see centered placeholder text now.
