### ISSUE TITLE
Image width and height properties are not shown anymore in property information

### ISSUE THREAD

**Issue by bastinc** [elementary/files#1326]
## Prerequisites
- [x ] I have searched open and closed issues for duplicates.

## Describe the bug
When you look at the property of an image, width and height are not shown anymore

pantheon-files version:  4.4.2+r3786+pkg92~ubuntu5.1.2.1
elementaryos version : elementary OS 5.1.4 Hera

For a PNG file:
![Capture d’écran de 2020-05-17 18-48-29](https://user-images.githubusercontent.com/5850561/82183576-889b4a80-98e6-11ea-8365-0bb02db7472a.png)

For a JPG file:
![Capture d’écran de 2020-05-18 09-07-27](https://user-images.githubusercontent.com/5850561/82183987-33ac0400-98e7-11ea-86d1-8df7c57b7921.png)

**Comment by jeremypw** [comment]
Could you give more information about what version of Files you are running what system and maybe give a screenshot of the the incorrect display?   Both the Properties Window and the Overlay Bar are giving dimension info for e.g. jpg files for me.

**Comment by jeremypw** [comment]
I just noticed that .png files are not giving dimensions in Properties Window but they are in Overlaybar which is weird.

**Comment by bastinc** [comment]
@jeremypw I have updated the bug description. Seems to occur for PNG and JPG.

**Comment by bastinc** [comment]
Seems to be fixed in elementary OS 5.1.6 and pantheon-files 4.4.4
