### ISSUE TITLE
Files in Elementary Os is not tiling in sides

### ISSUE THREAD

**Issue by tmak99** [elementary/files#1337]
Hi Team,
I am new to linux and recently installed Elementary OS and have few issues to report

1. Files App window is not tiling in sides when I move it to the sides. It is getting maximized when I move it to top. But other apps window are getting tiled to sides properly. Facing issue only with Files app. I saw few vidoes on eOS review and see that the files window is tiling properly on sides.

2. The system is going to suspend even when music app is playing after the specified time in Power settings. I dont want to change the setting to Never.

3. The OS felt bit faster when I had it dual boot with Windows, but after uninstalling Win and keeping eOS alone feeling like it became slower. initial booting and opening other apps like music are taking time(I have just installed firefox apart from pre installed apps) Previously I wont even notice the login and password page when starting the system. Now the login page is there for few seconds and then going in. Also becoming very slow when I copy or move files between system and external hard disk.

Thanks

**Comment by jeremypw** [comment]
Hello, thanks for the interest in elementary!  There are three different issues here which should raised in the appropriate repositories - only one issue per report please!  Also please give details about your system e.g. by attaching a screenshot of the "About" plug in System Settings.

1. Files is tiling to the side OK for me using a single laptop screen.  There is no obvious reason why it should behave differently to other apps - tiling is handled by the window manager (issues should reported at https://github.com/elementary/gala/issues).  Note that tiling will not work on the shared edge of two monitors.

2. This could be an issue with Music not issuing the correct Gtk.ApplicationInhibit  flags when playing  or the system not honouring them.  Music issues should be raised here https://github.com/elementary/gala/issues;  I am not sure which is the best repo for power issues but this couldbe related: https://github.com/elementary/switchboard-plug-power/issues/139

3. The presence or absence of other OSes in other partitions should not affect the performance of elementary as far as I know (assuming you kept the available memory, swap space and so on the same) so it may just be a coincidence that the performance deteriorated after uninstalling Windows.  But perhaps someone else will suggest a possible reason.  If you have not set up much then you could consider doing a clean reinstall of elementary without Windows (after backing up any data).

**Comment by jeremypw** [comment]
I am going to mark as "Out of Scope" as I do not think any of these issues is likely to due to Files code.

**Comment by tmak99** [comment]
Thanks jeremypw. I have raised issues in the other page you have given.
