### ISSUE TITLE
When Single Tab, DnD will create a new window (Design)

### ISSUE THREAD

**Issue by alex285** [elementary/files#1339]
## Description
When there is a single tab open, if we Drag and Drop it, it will create a new instance. Which actually is a very convenient way to create new windows, but at the same time breaks the logic of "moving tabs", plus it breaks consistent behavior with everything else, including Terminal 

## Reproduce
1. Open Files
2. Have a single Tab open
3. Drag and Drop the tab

**Result:** A new Files window will be created
**Expected:** The window should be moved

## Artifacts
That's a demo that shows Terminal Vs Files tabs behavior: https://youtu.be/FUEuBQbAM6o

However, this bug report is mostly a question whats the proper design here; Because again, I do like we can create new windows from a single tab!!

**Comment by jeremypw** [comment]
I think Files behaviour is more expected; also, it is the same in Code.  So I think Terminal is the odd one out.  But I'll flag for elementary design comment.
