### ISSUE TITLE
Regression: context menu in breadcrumbs does not work

### ISSUE THREAD

**Issue by PlatonB** [elementary/files#1355]
### Software Info
- elementary OS 5.1.5 Hera
- files 4.4.3

### Description
Previously, it was possible to go into any subfolder and easily open one of the parent folders in another tab using the breadcrumb's context menu. After update, this feature disappeared.

### To reproduce
1. Open file manager
2. Go to any subfolder
3. Try right-clicking on the breadcrumb of the parent folder.

**Comment by jeremypw** [comment]
Confirmed.  Probably due to d7b7ff0670146b7d1067bbb35570dccd70d05519 :-(
