### ISSUE TITLE
Navigating directories via the path works sporadically

### ISSUE THREAD

**Issue by BWPanda** [elementary/files#1358]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When in a directory that has at least one parent, navigating to parent directories by clicking them in the path bar only works sporadically. Sometimes the click takes you to the parent directory, but sometimes it just activates the typing mode. See screencast below for an example. I can't see a reason why certain clicks navigate and certain clicks activate typing instead...

### To Reproduce
1. Open a nested directory in Files
2. Click on a parent directory
3. Repeat as necessary

### Expected behavior
Clicking a parent directory takes you there, all the time. Another method should be used for enabling typing mode.

### Screenshots or screen recordings
![Peek 2020-06-07 11-05](https://user-images.githubusercontent.com/2385329/83958048-b30e7100-a8b0-11ea-8937-5ee42d4be209.gif)

## Platform Information
![Screenshot from 2020-06-07 11-21-17](https://user-images.githubusercontent.com/2385329/83958077-10a2bd80-a8b1-11ea-8f63-2ce2c3cd6558.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
This is a known regression and a fix has been approved.  Unfortunately it missed the latest release. Will try and get a minor release out soon.
