### ISSUE TITLE
Mouse cursor changes to text when hovering over addressbar

### ISSUE THREAD

**Issue by eliocamp** [elementary/files#1365]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

The mouse cursor changes to text selection mode when hovering over the addressbar. Clicking still works as excpected.

### To Reproduce
1. Open files
2. Hover over the address bar

### Expected behavior
Mouse pointer should be an arrow.

### Screenshots or screen recordings

![Peek 2020-06-11 11-20](https://user-images.githubusercontent.com/8617595/84398247-190f3700-abd6-11ea-8c7f-4496653cc7aa.gif)

## Platform Information

 - OS: elementary Os 
 - OS Version: 5.1.1 Hera

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
This issue has been fixed by #1358 but that was merged after the last release so, if you are on the stable version, it will be in the next release.
