### ISSUE TITLE
Issue with the `New Menu` on `Files`

### ISSUE THREAD

**Issue by hasansuryaman** [elementary/files#1366]
## Prerequisites
- [ ] I have a issue with the `New Menu` on `Files`

## Describe the bug
On the New menu, display all files (even hidden files) contained in `home`

### Screenshots

![error](https://i.stack.imgur.com/JvcTD.png)

## Platform Information

- [x] I'm using the latest version update of `io.elementary.files`
- [x] I'm using the latest released stable version

**Comment by davidmhewitt** [comment]
See here for someone with the same issue and a potential solution:
https://elementaryos.stackexchange.com/questions/24833/right-click-new-menu-is-overflowing-with-unnecessary-options
