### ISSUE TITLE
Open folders with middle mouse button in address bar

### ISSUE THREAD

**Issue by Vortex-TH** [elementary/files#1371]
## Prerequisites
- [x]  I have searched open and closed issues for duplicates.

## Feature
I think it used to be possible to open folders in new tabs with a middle mouse click on superordinate folders (or the current folder) in the address bar. I would like to have this feature restored.

![screenshot](https://user-images.githubusercontent.com/3118243/84785204-81518480-afeb-11ea-9ab1-85b04e9122fd.png)

**Comment by jeremypw** [comment]
This has been fixed in master by 77126812d6fea329363129b4f5d5c0d9c9ccf757 so will be available in the next stable release.
