### ISSUE TITLE
💡: Drop back to renaming field if any error occurs

### ISSUE THREAD

**Issue by joe733** [elementary/files#1372]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
While renaming say and error occurs like this:
![photo_2020-06-17_19-17-08](https://user-images.githubusercontent.com/38415384/84906140-2a24e000-b0cf-11ea-946f-54c6793bfb40.jpg)
the focus on renaming field is lost.

**Describe the solution you'd like**
The cursors is dropped back to renaming field, instead of taking the focus to file / folder selection.

---

**Additional Context**
Probably related #1194, #1018.

**Comment by jeremypw** [comment]
Can't really "drop back" as the renaming has already ended by the time the error occurs.  Maybe can initiate another rename, which I guess for the user is the same thing.

**Comment by joe733** [comment]
> Can't really "drop back" as the renaming has already ended by the time the error occurs. Maybe can initiate another rename, which I guess for the user is the same thing.

Oh okay, but is it possible to put in concurrency in `renaming` & the `process` that invokes error messages? Like putting renaming process to `sleep` instead of closing it & then restating it when error occurs. Will it complicate the code-base?

**Comment by joe733** [comment]
Closing, waiting for eOS 6 :)
