### ISSUE TITLE
Rewrite Sidebar as ListBox

### ISSUE THREAD

**Issue by danrabbit** [elementary/files#1375]
ListBox seems better suited here for a few reasons:
* We never use any kind of nesting or headers or columns, so I don't think we use any treeview-specific-features
* We could pack sidebar sections into a revealer for animations
* We could animate expander image rotation
* It would probably be easier to layout and style complex widgets like drives with levelbars

**Comment by cassidyjames** [comment]
Something raised on a call today is that this would probably allow us much better drag-and-drop into ~Bookmarks~ _Favorites_ (#1406) in the sidebar.

**Comment by jeremypw** [comment]
As a first step towards this I am looking at using an Interface for the Sidebar in libcore rather than an abstract class

**Comment by jeremypw** [comment]
@cassidyjames In what ways could drag/drop into Favorites be improved?  Visually or functionally?

**Comment by danrabbit** [comment]
We could probably look at Akira which has some very nice drop indicators:

https://twitter.com/akiraux/status/1276949837561257985?s=21

Planner also has some interesting drop indicators and the row expands to make room which is nice:

https://twitter.com/alainm23/status/1183581251367768064?s=21

Another one where dragging makes room in the sidebar:

https://twitter.com/alainm23/status/1170353415718879233?s=21

**Comment by jeremypw** [comment]
Interesting - if these are using ListBox.

**Comment by jeremypw** [comment]
@danrabbit I have pushed a commit that implements the bookmarks (appearing to) move apart when dropping between them.  Still needs some debugging, but is this on the right lines?
