### ISSUE TITLE
Folder size to be displayed in list view

### ISSUE THREAD

**Issue by askanish** [elementary/files#1387]
## Prerequisites
- [YES] I have searched open and closed issues for duplicates.

## Feature
Need support for listing the folder sizes when displaying in list view. The sizes are left blank for folders and it will immensly help to display the size of folder in the "Size" column. 

![Screenshot from 2020-07-11 10-48-09](https://user-images.githubusercontent.com/115666/87217151-108c5680-c364-11ea-9dd1-8c0faa681dbf.png)

**Comment by jeremypw** [comment]
FIle managers like Nautilus and Nemo show the number of items contained in the folder (non-recursive), which can be obtained very quickly.  This could be implemented. However, I am not sure it is practical to obtain the size of the folder and all its contents in bytes at a fast enough speed on the fly.

**Comment by jeremypw** [comment]
I would point out that now even in List View, if you hover the pointer over any folder the disk usage will be calculated and displayed in the overlay.

**Comment by jeremypw** [comment]
Just pushed a PR to provide the item count for folders in List View.

**Comment by askanish** [comment]
I agree that its costly to find the size of folder in the fly. But as you mentioned the overlay already does this and its fairly fast. Hence I felt it shld be doable to get the size.

**Comment by jeremypw** [comment]
The overlay does it on one folder at a time.  The view would have to do it on a (potentially) large number of files simultaneously which is likely to affect performance.

**Comment by askanish** [comment]
Agreed. 
If its not too much to ask, in that case would it be better to have a static status bar or something at the bottom that shows the size data instead of the overlay? Because everytime the mouse moves the overlow vanishes and a static info somewhere would be helpful.

I am not sure if the status bar defeats the design language of the browser, so if thats not possible may be the overlay can be made static if the folder is selected in the list?

**Comment by jeremypw** [comment]
It is certainly an idea to make the overlay persist if there is a selection.  I suggest you raise a separate issue for that and see what support it gets.  Elementary design is generally against static status bars though.

**Comment by cassidyjames** [comment]
I like the idea of showing the overlay bar for a folder when it's selected. It also makes it more touch friendly as it does not require a mouse cursor to display that data. I've opened a new issue: #1389

**Comment by askanish** [comment]
Thanks guys. I will be closing this issue as there is seperate issues to track this.
