### ISSUE TITLE
Display overlay bar on selection

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1389]
As raised in #1387. Opening for thoughts. I think it makes sense, as it makes that data more accessible, especially since it no longer requires a mouse to display it. Thoughts @danrabbit?

**Comment by DisguisedBear** [comment]
In my personal opinion I don't think displaying anything "on the fly" is a good idea from a UX/UI standpoint.
Things that pop in and out of view and are not visually linked to anything directly are extremely distracting and irritating... I personally found that overlay bar to be very annoying when doing any sort of work within Files.

I honestly think a better solution would be to just display an improved version of "file info" by selecting a file/folder and hitting the `i` key and making the window non persistent, meaning that when the user moves the mouse or selects something else the "file info" window would either go away or switch to the new selected file.
When translating this kind of design to touch UI, the same functionality would be achieved by long pressing on a file and the "file info" window would appear next to the file, something like "force touch" on iPhone.

The "file info" window design looks like an overlay in it self, I think you should leverage this design more often. Displaying yet another quick "file info" like overlay bar is basically redundant functionality, especially if the user doesn't wants or needs to see this information constantly.

**Comment by jeremypw** [comment]
I tend to agree with @DisguisedBear tbh. I think the overlay bar was inherited from the origin Marlin app but I rarely, if ever, make use of it so it is kind of a waste of cpu cycles.  If I want info on a file I open the Properties window.  Note the Properties window already has a short cut (`<Alt><Enter>`).  Hitting `i` will start a search so if you want to use that letter a modifier would have to be added.

Making the window non-modal is interesting.  You *can* currently change the selection while the window is open but the Properties Window does not reflect the change.

**Comment by DisguisedBear** [comment]
> Hitting `i` will start a search so if you want to use that letter a modifier would have to be added.

It doesn't have to be `i`, it be `⌘`+`p`, and work similar to how "preview" works on macOS with `spacebar`.
In fact this is exactly how you get the file/folder properties on macOS with`⌘`+`i`, but its obviously a persistent window you constantly need to close, its basically mixing the idea of "preview" and "Properties window" into a single thing. I usually just want to glance at a date or file size and not have to deal with the window it self, or deal with pop up overlays that constantly catch my eye.

I may also add that in macOS when you select multiple files and hit `⌘`+`i` the information being shown is a concatiantion of them all, which is very useful.

**Comment by jeremypw** [comment]
The discussion is getting a little off-topic as this issue is specifically about the overlay showing only when there is a selection.  It would be better to raise a separate wishlist issue to discuss an enhanced properties window which maybe replaces the overlay.
Maybe an incremental approach would be to implement overlay-with-selection first as that should be fairly easy and then replace it with an enhanced properties window later?

**Comment by DisguisedBear** [comment]
> Maybe an incremental approach would be to implement overlay-with-selection first as that should be fairly easy and then replace it with an enhanced properties window later?

Oh absolutely, I don't intend to overload you guys... I just want eOS to be best it can. Overlay-with-selection would be nice for now, its definitely better than having it appear out of no where for no obvious reason, at least when an item is selected this behavior will be expected.

Should I open a feature request for the other method for future implementation?

**Comment by jeremypw** [comment]
Yes, please feel free to raise a separate issue about your ideal solution
