### ISSUE TITLE
Can't copy file/folder name if my user don't have write permission

### ISSUE THREAD

**Issue by rafaelcorsi** [elementary/files#1397]
There is no way to copy a file/folder name if my user don`t have write permission on the item. 

If I want to copy an item name on files I usually use the rename action and copy that name, but when I don`t have write permission on the item I cant rename and copy the name. 

File/Folder `properties` don`t have the file name, this would solve the problem.

## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature

- copy a file/folder name when user don`t have ownership 

**Describe alternatives you've considered**

Add the file name on item properties (info)

![image](https://user-images.githubusercontent.com/1039615/88233949-c00fd580-cc4e-11ea-9654-f00674afc67a.png)

**Comment by jeremypw** [comment]
Yes, I do not see why the user should be prevented from copying the name in circumstances where they are unable to rename the file.  Using the Properties window seems sensible.

**Comment by rafaelcorsi** [comment]
> Yes, I do not see why the user should be prevented from copying the name in circumstances where they are unable to rename the file. Using the Properties window seems sensible.

A worked on this and I think got a better solution.

The Properties already show de file name for One Item and Writeble (the filed lets the user to rename the file), why not the same for the file that is no Writeble, but if a label? 

Sending a PR that implement this.

![image](https://user-images.githubusercontent.com/1039615/88286384-0a349d80-ccc7-11ea-8cba-e485e7d48f96.png)

**Comment by jeremypw** [comment]
@rafaelcorsi That sounds similar to the PR I have already pushed - did you see that?

**Comment by rafaelcorsi** [comment]
@jeremypw  I did the same but I was suffering  to let the Label to be "selectable", know I see how to do. I`m new to gtk...

thanks!

**Comment by jeremypw** [comment]
@rafaelcorsi  Thanks for having a go anyway.  Any contributions are welcome.
