### ISSUE TITLE
Better tooltip format for devices in the sidebar

### ISSUE THREAD

**Issue by danrabbit** [elementary/files#1410]
We should make better use of formatting and multiples lines here. I feel like it would be a big improvement just to put the usage on a second line and use small, dim text (echoing the style of accel tooltip markup)

**/path/to/volume — ext3/ext4**
218 GB Free of 250 GB

**Comment by lainsce** [comment]
Something of note is that the path doesn't hide the "file://" prefix thing so that should be tackled when fixing this issue.
