### ISSUE TITLE
Files crashes on attempt of copy/cut and paste

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#1424]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Copying/pasting a file and trying to paste it to somewhere causes a segmentation fault.

### To Reproduce
1. Run Files
2. Copy/cut some file
3. Move to other folders
4. Paste the copied file
4. The app crashes

### Expected behavior
The paste action should be completed and the app should stay running.

### Screenshots or screen recordings
![2020-08-12 20 23 06 の画面録画](https://user-images.githubusercontent.com/26003928/90009805-b7547180-dcd9-11ea-88eb-75ce8611cfa6.gif)

### Logs
Here is a gdb log:

```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff6c73e95 in __vfprintf_internal
    (s=s@entry=0x7fffbd7f97a0, format=format@entry=0x7ffff7f6abb7 "%s of %s \342\200\224 %s left (%s/sec)", ap=ap@entry=0x7fffbd7f9920, mode_flags=mode_flags@entry=2) at vfprintf-internal.c:1688
#2  0x00007ffff6c86d4a in __vasprintf_internal
    (result_ptr=0x7fffbd7f9900, format=0x7ffff7f6abb7 "%s of %s \342\200\224 %s left (%s/sec)", args=0x7fffbd7f9920, mode_flags=2) at vasprintf.c:57
#3  0x00007ffff7e6de63 in g_vasprintf () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7e45141 in g_strdup_vprintf () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7e451fd in g_strdup_printf () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7f522ab in  () at /lib/x86_64-linux-gnu/libpantheon-files-core.so.4
#7  0x00007ffff7f58e0d in  () at /lib/x86_64-linux-gnu/libpantheon-files-core.so.4
#8  0x00007ffff7c13ffe in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x00007ffff7c47c62 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007ffff7e4f1d4 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff7e4e931 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff69ef609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#13 0x00007ffff6d1a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

## Platform Information
I'm on Odin Daily.

- [x] I'm using the latest version from daily
- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

## Additional context
N/A

**Comment by jeremypw** [comment]
Hmm, its happening for me as well (on Focal).  Maybe linked to https://github.com/elementary/files/commit/1da8f2e546cb3d102423549307f1caef3e7bc8d6 although it seemed to work OK when merged.
