### ISSUE TITLE
When restoring tabs, ignore folders that no longer exist

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1431]
E.g. if you're browsing an external drive and close Files, then open it back up later, it's really not useful to always get a “This Folder Does Not Exist” welcome screen.

**Comment by jeremypw** [comment]
It was previously the case that Files checked for the existence of a folder before restoring it, but this was found to cause the interface to hang in the case that the location was on the network server that could not be connected to.

I guess we could add a flag to the "add tab" process that indicates whether we are restoring or just navigating.

**Comment by cassidyjames** [comment]
Oops, I think this is a duplicate of #1216, right?
