### ISSUE TITLE
The FileChooser "Open" button does not work after selecting several files

### ISSUE THREAD

**Issue by Fabioulloaev** [elementary/files#1450]
The "open" button does not work when I select several files to attach in an email or in onedrive or google drive.
It forces me to upload one by one even though the platform (onedrive, google drive, etc) supports uploading several files at the same time

**Comment by jeremypw** [comment]
Do the files not share a common content type (mime-type)?  The "Open" option will not appear in the context menu if that is the case.  You could try dragging and dropping the files - that works for e.g. Google Mail attachments.

**Comment by jeremypw** [comment]
Sorry - did you mean the "Open" button on the filechooser or on the context menu?

**Comment by Fabioulloaev** [comment]
In the file chooser.

**Comment by jeremypw** [comment]
Ah OK, in that case ignoew my previous comment. I have edited the issue description accordingly.

**Comment by jeremypw** [comment]
I just tried it with Google Drive and had no problem uploading several files of different types.  Please could you confirm that you are getting the Pantheon FileChooser (that is the one with the Files style of breadcrumbs) and could you describe in detail exactly what is happening?  Thanks.

**Comment by Fabioulloaev** [comment]
I already found out what happened, when I opened the file selector a folder was selected immediately, that's why it wouldn't let me load the files
