### ISSUE TITLE
Where to get libhandy-1-dev >= 0.83.0 and latest valac from?

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/files#1469]
The dev dependencies seem to have changed quite a bit.

I cannot find libhandy-1-dev in the default elementary package repositories.
Also, for compiling, the minimum Vala version is 0.48.something. How do I install that valac version on a vanilla elementaryOS installation?

Currently, it contains only valac 0.40.23

**Comment by danrabbit** [comment]
These newer libraries are only available starting in elementary OS 6. It is unlikely you will be able to get them on elementary OS 5.x

**Comment by CodingSpiderFox** [comment]
When will elementaryOS 6 be released? Is there a beta version already?

**Comment by danrabbit** [comment]
@CodingSpiderFox We'll be able to release once all of the actions on this project board are completed: https://github.com/orgs/elementary/projects/55

You can sign up for early access at https://builds.elementary.io

**Comment by CodingSpiderFox** [comment]
Great, thanks :)

**Comment by CodingSpiderFox** [comment]
Is there a branch that is still maintained which still works for elementary 5?

**Comment by CodingSpiderFox** [comment]
*Ping

**Comment by jeremypw** [comment]
You can get latest (stable) Vala from https://launchpad.net/~vala-team/+archive/ubuntu/next.  Note that `sudo add-apt-repository` does not work on elementary so you will have to update your sources.list manually or using e.g. Synaptic.

**Comment by jeremypw** [comment]
I found this for libhandy-1-dev - `https://packages.debian.org/sid/amd64/libhandy-1-dev/download` 

The last stable release for FIles for Hera has happened and it is now incompatible with that version - we are not maintaining a backports branch.

**Comment by cassidyjames** [comment]
@CodingSpiderFox if you're talking about Files, then no, development has been retargeted to elementary OS 6—we've been mentioning this is starting to happen on the blog since the [June updates](https://blog.elementary.io/updates-for-june-2020/).

**Comment by CodingSpiderFox** [comment]
> 
> 
> I found this for libhandy-1-dev - `https://packages.debian.org/sid/amd64/libhandy-1-dev/download`
> 
> The last stable release for FIles for Hera has happened and it is now incompatible with that version - we are not maintaining a backports branch.

Which was the lastest version for Hera?

**Comment by BAProductions** [comment]
Libyandy-1 works for me on Juno but file giving me build error

**Comment by BAProductions** [comment]
> > I found this for libhandy-1-dev - `https://packages.debian.org/sid/amd64/libhandy-1-dev/download`
> > The last stable release for FIles for Hera has happened and it is now incompatible with that version - we are not maintaining a backports branch.
> 
> Which was the lastest version for Hera?

Libyandy-1 works for me on elementary OS 5.1.7 Hera, But file giving me build error
 ../libcore/FileUtils.vala:930.24-930.37: error: The name `pathconf' does not exist in the context of `Posix'
        var max_path = Posix.pathconf (dir, Posix.PathConfName.PATH_MAX);
                       ^^^^^^^^^^^^^^
../libcore/FileUtils.vala:931.24-931.37: error: The name `pathconf' does not exist in the context of `Posix'
        var max_name = Posix.pathconf (dir, Posix.PathConfName.NAME_MAX);
                       ^^^^^^^^^^^^^^
../libcore/PluginManager.vala:132.49-132.65: error: The name `LOCAL' does not exist in the context of `GLib.ModuleFlags'
        Module module = Module.open (file_path, ModuleFlags.LOCAL);

**Comment by cassidyjames** [comment]
4.5.0 is the latest release, and is available as a tagged release and in the [`juno`](https://github.com/elementary/files/tree/juno) branch.

**Comment by CodingSpiderFox** [comment]
Thanks a lot :)
