### ISSUE TITLE
Sidebar (left panel) shrinks on selecting 'Rubbish Bin' with small window

### ISSUE THREAD

**Issue by ultraviolet-1986** [elementary/files#147]
Hi, I just noticed this small issue when I accidentally left-clicked on the Rubbish Bin in the left column instead of my Workspace folder shortcut (I usually right click and delete from there).

This only happens when there is something in the bin to delete, and it appears to be caused by the text prompt at the top of the main window pane which says 'These items may be restored or deleted' pushing the left column to fit the text instead of wrapping the text to fit the current window size. When there is nothing inside of the bin to delete, it behaves normally. Sorry about the long-winded explanation - it would have been easier with screenshots.

Hope this helps, and thank you for your time.

**Comment by jeremypw** [comment]
The columns in the column browser adjust their size depending on the length of the longest filename in the directory they are showing.  So if you you navigate from a directory with long filenames (or one with the column width manually increased) to the a rubbish bin containing only short filenames, then the column will shrink.   Is this is what you are describing?

**Comment by ultraviolet-1986** [comment]
Hi, sorry for taking a while.

I've added a couple of screenshots which show this below. The left column shrinks to accommodate the white information bar with the 'Restore' and 'Delete' buttons. The left column can't be resized while on the Rubbish Bin page and this only happens when there is something to delete in the Rubbish Bin.

Sorry I don't know the correct name for the left browser column - except to say that. Like I said, a screenshot shows this better but I'm fairly new at this. Thanks for bearing with me and for your time.

![01](https://user-images.githubusercontent.com/13064323/31082612-60892998-a787-11e7-9883-41310c1fc5bf.png)

![02](https://user-images.githubusercontent.com/13064323/31082613-60e75cd4-a787-11e7-8c4b-bce7379bd86e.png)

**Comment by jeremypw** [comment]
Ah, sorry I thought you were referring to the "Column View" (as opposed to Icon View or List View) when you said "Column Browser".  You are referring to the sidebar.  I am not sure what the best solution is, but in any case the sidebar should return to its original size when you navigate away from the rubbish bin (which it currently does not).

**Comment by ultraviolet-1986** [comment]
Thanks, yeah, I'm not that great at describing things I'm afraid but I try ^_^b

I think the easiest solution would be in allowing the information text  'These items may be restored or deleted' to wrap - but I have to admit, I wouldn't know where to start.

Cheers!
