### ISSUE TITLE
Search result header colors are cached on open

### ISSUE THREAD

**Issue by danrabbit** [elementary/files#1471]
![Screenshot from 2020-09-11 14 10 27@2x](https://user-images.githubusercontent.com/7277719/92973270-a9108700-f438-11ea-9558-a7de607ac328.png)

This is probably a hardcoded style instead of using `Granite.STYLE_CLASS_H4_LABEL`

**Comment by cassidyjames** [comment]
I can't reproduce here…

**Comment by cassidyjames** [comment]
Ah, it looks similar to the issue we had with breadcrumb icons. It caches the style on open, so if you change the light/dark style while Files is open, you get stuck with low contrast.
