### ISSUE TITLE
Option to  choose color on right click on any file is not coming

### ISSUE THREAD

**Issue by malikrajat** [elementary/files#1488]
Hello Every one,

I am using ubuntu 20.04. I have installed pantheon-files. Everything is working well, except for the color option that, I was getting in Ubuntu 18.

I have all the other options
I am attaching an image, How, I am expecting it.
![aDDLD9X](https://user-images.githubusercontent.com/11173135/94413996-6faa7c00-0199-11eb-9d41-396a671216ab.png)

Thanks in advance for any kind of suggestion and help as well.

**Comment by jeremypw** [comment]
This plugin requires the correct Gtk+ theme to be installed.  Install the `elementary-theme` package.  After experimenting with `GTK_DEBUG=interactive io.elementary.files` it seems the old 'elementary' Gtk theme does not work for this plugin but if you choose one of the `io.elementary.stylesheet.XXXX` themes then it does work. 

The easiest way to change the theme globally is by installing the `gnome-tweaks-tool` package.

The `io.elementary.stylesheet` themes are under active development for elementary 6.0 at the moment so there may be some glitches.

**Comment by jeremypw** [comment]
Marking "Out of Scope" as Files is not intended to work "out of the box" on other desktops.
