### ISSUE TITLE
Mint and Bubblegum color tags are missing in Odin

### ISSUE THREAD

**Issue by fabiozaramella** [elementary/files#1496]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
As the title says, new Mint and Bubblegum colors from the palette are missing from Files color tags section.

![Schermata del 2020-10-08 15 21 05](https://user-images.githubusercontent.com/5459945/95479187-03d6c900-097a-11eb-9d04-ae6fac2d3a1f.png)

**Existing work**
Similar to this: https://github.com/elementary/calendar/pull/606

**Additional context**
On Odin daily.

**Comment by jeremypw** [comment]
Fixed by #1497
