### ISSUE TITLE
Simplify duplicate name management

### ISSUE THREAD

**Issue by tintou** [elementary/files#1504]
(From https://github.com/elementary/files/pull/1437)
We want to end the overly complicated handling of duplicates to a simple one.
For links:
- FileName (link)
- FileName (link 2)
- etc.

For copies
- FileName (copy)
- FileName (copy 2)

**Comment by jeremypw** [comment]
https://github.com/elementary/files/pull/1437 is waiting to be amended along these lines - but I rather forgot about it.

**Comment by jeremypw** [comment]
One question - if you copy `Filename (link)` should you get `Filename (link)(copy)` or ` Filename (link 2)`?  Unlikely to be an issue in practice I imagine.

**Comment by tintou** [comment]
I imagine that you get `Filename (link 2)` as it is more a second link than a copy :man_shrugging:

**Comment by jeremypw** [comment]
Regarding copies of filenames with extensions, I imagine you want `BaseName (copy).Extension` as at present.

**Comment by jeremypw** [comment]
There are some complications with copying or linking file copies or links which are already named in the old format but I will not address that in the first PRs.

**Comment by jeremypw** [comment]
#1437 is now merged so closing.  Please re-open or create a new report if issues with duplicates still exist.
