### ISSUE TITLE
Filechooser Portal can't select files or folders

### ISSUE THREAD

**Issue by Marukesu** [elementary/files#1518]
## What Happened

When trying to open a file in epiphany or flatpak-ed code, i can't select any file or enter any folder on the portal. Also, if i cancel or close the portal, the application freeze.

## Expected Behavior

That i can open a file in the portal.

## Steps to Reproduce

1. Open flatpak-ed code
2. Try to open a file from the portal.
3. Can't select any file.

## Platform Information

OS: elementary OS next 6.0
Flatpak Version: 1.6.5
xdg-desktop-portal Version: 1.6.0

**Comment by jeremypw** [comment]
Confirmed with the Flathub Epiphany flatpak using import bookmarks dialog.

**Comment by cassidyjames** [comment]
Also confirmed with Firefox Flatpak

**Comment by Marukesu** [comment]
Closing since #1519 fixed it.
