### ISSUE TITLE
Hangs when "Keep newest" chosen in file conflict dialog when administrator.

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#1530]
## What Happened
When Files is open as administrator and a file conflict occurs during a copy operation, if the "Apply to all" option is chosed and the "Keep Newest" button pressed in the resulting conflict dialog then Files hangs and becomes unresponsive.  The same operation can be carried out successfully as an ordinary user.

## Expected Behavior
The file conflict dialog operations should work properly when running as administrator (or not be offered if they are inappropriate).

## Steps to Reproduce
1. Open Files as administrator
2. Copy a test text file into a folder
3. Edit the original file so that it is newer than the one that was moved.
3. Copy the same file into the same folder - the file conflict dialog shows
4. Select "Apply to all"
5. Press "Keep newest"

It is possible that other options also cause a crash - not fully investigated yet.

## Platform Information
Up to date Elementary 6.0 running in VirtualBox VM.

This may be due to replacing a file requires it be deleted or trashed.  Deleting a file as administrator is permanent and normally shows a warning dialog whereas deleting a file as a normal user just moves it to trash without a dialog.

**Comment by tintou** [comment]
Does running `pkexec io.elementary.files` gives you some warnings when following the steps?

**Comment by jeremypw** [comment]
No - there was no output when running `io.elementary.files-pkexec`.

**Comment by jeremypw** [comment]
Actually just realized I was running Files in Ubuntu Focal not the VM - haven't been able to reproduce it on elementary 6.0 yet :disappointed:   I'll close this if I can't.

**Comment by jeremypw** [comment]
Closing as I have not reproduced in elementary 6.0
