### ISSUE TITLE
Copy suffix is off

### ISSUE THREAD

**Issue by tintou** [elementary/files#1531]
## What Happened

The copy suffix is cutting a word in two.

## Expected Behavior

The copy suffix should be appended.

## Steps to Reproduce

1. Create a folder named "toto"
2. Copy and paste it into the same folder
3. The result (in fr_FR) is "tot (copie)o"

**Comment by jeremypw** [comment]
Affects English local as well - only file names without an extension.

**Comment by jeremypw** [comment]
Not sure why this was not picked up - there was a unit test supposed to check copying files with no extension.

**Comment by jeremypw** [comment]
Seems to only affect short filenames.  The name used for the unit test had 8 characters.
