### ISSUE TITLE
File has no icon

### ISSUE THREAD

**Issue by marcinjahn** [elementary/files#1535]
For some reason, the file is displayed without any icon. I am not using any icon pack, I stick with the default icons.

I believe every file should have some icon displayed. If the file's type is not recognized, there should be some default icon.

![image](https://user-images.githubusercontent.com/10273406/102020450-a300ae00-3d79-11eb-9510-a9754721659d.png)

**Comment by jeremypw** [comment]
Yes, the intended behaviour is to show an image-missing icon so this looks like a regression.  What is the mime-type of the affected file?

**Comment by jeremypw** [comment]
Is the icon missing at all sizes?

**Comment by Loreno10** [comment]
@jeremypw 
Here's the output of `file pack-a7278e3efc81cab421f1644d574c6202dd87a62e.idx `:

```
pack-a7278e3efc81cab421f1644d574c6202dd87a62e.idx: Git pack index, version 2
```

Here's the output of `file --mime-type pack-a7278e3efc81cab421f1644d574c6202dd87a62e.idx`:

```
pack-a7278e3efc81cab421f1644d574c6202dd87a62e.idx: application/octet-stream
```

It's a file that resides in Git repository in `./.git/objects/pack/`.

I tried resizing the icon with CTRL+scroll, and the icon never appeared.

Btw, I'm using eOS 5.1.7 Hera

**Comment by jeremypw** [comment]
@Loreno10  OK, thanks.  Looks like there is no icon define for that mime-type by default - but as you say, Files should fallback to a suitable icon.  I'll try and fix this soon.

**Comment by jeremypw** [comment]
Hmm, I seem to get an icon (at least, using elementary 6) 

![Screenshot from 2020-12-15 00 36 46](https://user-images.githubusercontent.com/10513844/102077264-e94d2000-3e00-11eb-8ac4-4d0ef8e3b621.png)
![Screenshot from 2020-12-15 00 41 16](https://user-images.githubusercontent.com/10513844/102077563-6c6e7600-3e01-11eb-856a-b65155702ee8.png)

**Comment by Loreno10** [comment]
Hmm, so it seems to be 5.x bug only. Or something is messed up with my system, although I didn't do any modifications in this area.
If some more info is needed, I'll be happy to provide it.

**Comment by jeremypw** [comment]
Yes, I can now confirm this issue does affect elementary 5.1.7 but not elementary 6.0.

Unfortunately, there are not expected to be any more stable releases of Files for elementary 5.1.7 as the code is now incompatible with the Hera libraries.

**Comment by Loreno10** [comment]
Ok, then I’m looking forward even more for 6.0 to be released ;)

**Comment by jeremypw** [comment]
This should now be fixed.  Please reopen if not.
