### ISSUE TITLE
File chooser dialog showing behind its parent

### ISSUE THREAD

**Issue by danrabbit** [elementary/files#1542]
## What Happened

When opening a file chooser dialog, focus stealing prevention is putting the window behind its parent. I'm not sure if this is actually a Gala issue, but I figured I'd start here. My guess is that maybe the parent actually isn't being set correctly since the portal gets a dock icon and is not centered on its parent

## Expected Behavior

File chooser dialogs should always be on top of their parent window, it shouldn't have its own dock icon, and they should be centered on their parent as well

## Steps to Reproduce

1. Open Code
2. Select "Open a file" in the headerbar
3.The filechooser is placed behind Code

Notice the difference between the behavior here and the behavior when selecting "Open Project Folder" in the sidebar

**Comment by cassidyjames** [comment]
I’ve also been noticing this in Flatpaked apps like Firefox and Epiphany that I presume are using portals. It makes it super annoying with maximized windows, as it's not obvious anything even opened.
