### ISSUE TITLE
filechooser-portal: Support parenting window under Wayland

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/files#1545]
We merged support for parenting the filechooser window to it's requester in X11 here: https://github.com/elementary/files/pull/1544

We need to implement a new class on the `ExternalWindow` interface for this to work under Wayland. It seems we have some missing Vala bindings that mean we don't have a GTK 3 equivalent of https://valadoc.org/gtk4/Gdk.Wayland.Toplevel.set_transient_for_exported.html , but I didn't spend long looking for it, so I could be wrong.

Just opening this to track a minor issue with our already incomplete Wayland support.

**Comment by Marukesu** [comment]
There's a gdk-wayland-3.0 pkgconfig, and looking at the installed headers `gdk_wayland_window_set_transient_for_exported ()` is defined, but they don't export a vapi or gir file.
