### ISSUE TITLE
File tagging should use elementary colours.

### ISSUE THREAD

**Issue by TraumaD** [elementary/files#155]
The file tagging colours should be from the elementary colour palette and not tango's.
![file-highlights](https://user-images.githubusercontent.com/10608836/31393201-d03b73f8-ada0-11e7-9e68-ab47443cae02.png)

**Comment by jeremypw** [comment]
To avoid confusion with highlighting during e.g. drag and drop and for consistency with the relevant plugin, the term "tagging" is used.

**Comment by jeremypw** [comment]
Tag colors are currently hard coded in gof-preferences.vala:
```public const string TAGS_COLORS[10] = { null, "#fce94f", "#fcaf3e", "#997666", "#8ae234", "#729fcf", "#ad7fa8", "#ef2929", "#d3d7cf", "#888a85" };```

**Comment by TraumaD** [comment]
If it's as simple as changing those hex values I could probably handle that. Or is this something where we should change how it works?

**Comment by TraumaD** [comment]
I went ahead and took a stab at it and got it working I'm just not entirely sure which "weight" of the colours we should go with. I chose 100 for most of them with the exception of silver and this is what it looks like:
![screenshot from 2017-10-10 16 44 37](https://user-images.githubusercontent.com/10608836/31413007-fe036da4-addc-11e7-85ac-a48b09ab48a9.png)
![screenshot from 2017-10-10 16 39 31](https://user-images.githubusercontent.com/10608836/31413009-011a5282-addd-11e7-8451-0f1e6aa60c9d.png)

**Comment by cassidyjames** [comment]
@TraumaD that looks legit to me
