### ISSUE TITLE
Latest build doesn't actually delete files

### ISSUE THREAD

**Issue by hanaral** [elementary/files#1553]
## What Happened
Trying to delete a file or directory results in the view makes it look as if it has until you refresh or re-enter the directory, meaning that nothing happened to it. It _will_ sometimes delete the desired item, but when it does the app hangs.

## Expected Behavior

Files and dirs delete correctly

## Steps to Reproduce

1. Open files and create a test folder/file
2. Delete it by dragging to the bin, context menu or by the delete key
3. Refresh the folder you deleted it from

### Logs

```
Gtk-Message: 09:15:21.771: Failed to load module "pantheon-filechooser-module"
** Message: 09:15:21.803: Application.vala:75: Report any issues/bugs you might find to https://github.com/elementary/files/issues
強制終了
han@elementary-os:~/遊び物/coinkillerwin$ io.elementary.files
Gtk-Message: 09:15:45.334: Failed to load module "pantheon-filechooser-module"
** Message: 09:15:45.363: Application.vala:75: Report any issues/bugs you might find to https://github.com/elementary/files/issues
```
nothing useful

## Platform Information

elementary OS 6 Daily

**Comment by jeremypw** [comment]
Thanks for the report.

I could not reproduce this using native files (with ASCII names) with Files compiled from the latest source on elementary 6.0  (in encrypted VM). Please try and identify, if possible, specific circumstances where this issue occurs e.g. remote folders with certain protocol; certain characters in the filename;  trashing/permanently deleting.

The fact there are no error messages indicates Files "thinks" the file is deleted successfully so the issue could be at a system level (?).

If the app hangs then you may be able to get a backtrace using gdb (see https://wiki.debian.org/HowToGetABacktrace).  If so, please post here.

**Comment by hanaral** [comment]
> Thanks for the report.
> 
> I could not reproduce this using native files (with ASCII names) with Files compiled from the latest source on elementary 6.0 (in encrypted VM). Please try and identify, if possible, specific circumstances where this issue occurs e.g. remote folders with certain protocol; certain characters in the filename; trashing/permanently deleting.
> 
> The fact there are no error messages indicates Files "thinks" the file is deleted successfully so the issue could be at a system level (?).
> 
> If the app hangs then you may be able to get a backtrace using gdb (see https://wiki.debian.org/HowToGetABacktrace). If so, please post here.

Apologies, maybe it was something in the release version? Anyway I just rebuilt from latest and it doesn't have the issue at all.

**Comment by jeremypw** [comment]
Weirdly my install started doing this after working on an old PR - even after recompiling and installing master and rebooting.  Only affects folders - not regular files. Will investigate further.

**Comment by jeremypw** [comment]
It seems that this is caused by `g_file_trash ()` returning `TRUE` with no error set but the file is not actually being trashed by the underlying system.  Not sure what the ultimate problem is, but it does not seem to be a Files issue.   As I said above, Files "thinks" the file has been trashed and only finds it has not when the view refreshes.

**Comment by jeremypw** [comment]
Maybe https://gitlab.gnome.org/GNOME/glib/-/issues/2249 is related?

**Comment by jeremypw** [comment]
I think I may have run a system update after my original testing of this issue so the problem may be in a system library or configuration file. Purging and reinstalling the daily pantheon-files package has not fixed it.

**Comment by jeremypw** [comment]
Deleting folders with Code has also stopped working on my install so it does appear to be a system problem.

**Comment by jeremypw** [comment]
OK, so it is related to `GTK_USE_PORTAL` environment variable as suggested by the Gnome issue mentioned above.  Running `env GTK_USE_PORTAL=0 io.elementary.files` fixes the problem temporarily.

**Comment by jeremypw** [comment]
GTK_USE_PORTAL=1 is being set in `/etc/profile.d/gtk-filechooser-native.sh` so editing this and rebooting fixes the problem (although unknown whether there are any regressions).

**Comment by hanaral** [comment]
So what I gather there is an issue with the portal? Wasn't the portal only recently implemented?

**Comment by jeremypw** [comment]
Yes, I think so but I am not sure whether it is an issue with the default-settings repo or this one.  I have messaged the dev who wrote the Files portal for his input.

**Comment by danrabbit** [comment]
Reopening since multiple people have confirmed experiencing this issue

**Comment by cassidyjames** [comment]
I can confirm here on an updated daily build that trashing files seems to work fine, but trashing folders is not working for me—both in Code and Files itself.

**Comment by davidmhewitt** [comment]
@jeremypw I've just linked a PR to this issue as we're looking at reverting that environment variable as it looks like it's causing problems with notifications too.
