### ISSUE TITLE
Weird highlight when clicking on the first item in the path

### ISSUE THREAD

**Issue by Loreno10** [elementary/files#1558]
When you're in any folder, click on the first element of the path at the top. You'll see this:
![image](https://user-images.githubusercontent.com/10273406/104643938-6e9c4c80-56ad-11eb-893b-244a33cf3ba1.png)

The blue bars go out of the "button", to the left.

It's on eOS 5.1.7.

**Comment by jeremypw** [comment]
This should be fixed in elementary 6.0 by #1514
