### ISSUE TITLE
Certain folders in sidebar have no tooltip

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/files#1566]
## What Happened

As title implies. Home, Recent and Trash have a tooltip but not the others.

## Expected Behavior

All items under Bookmark should have a tooltip, except for folders added by Users (i.e. Just Home, Recent, Documents, Music, Pictures, Videos, Downloads, Trash).

## Proposal

Documents: "View your saved documents"
Music: "Listen to saved songs"
Pictures: "Store some pictures"
Videos: "Watch your saved videos"
Downloads: "View downloaded files"

## Steps to Reproduce

1. Open Files.
2. Hover over one of the bookmarked items.

## Platform Information
Files master

**Comment by jeremypw** [comment]
PR #1453 provides tooltips for all bookmarks.  At the moment, when no custom tooltip is provided, this fallsback to the path that will be navigated to on clicking.  I guess custom tooltips could also be provided for e.g. Documents, Music etc - suggestions?

**Comment by danrabbit** [comment]
I'm not sure these proposed tooltips are significantly differentiating or helpful enough. We typically only provide tooltips for labeled widgets when the tooltip exposes more advanced information or an explanation. It doesn't seem like the directory names are unclear enough that it would require a longer explanation

**Comment by jeremypw** [comment]
Also, these other folders have shortcut to expose.  I agree the above suggestions do not add any information that is not self evident from the bookmark name.

**Comment by pongloongyeat** [comment]
Well if that's the case then I'll close this issue.
