### ISSUE TITLE
Use tabular numbers in file transfer dialog

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1567]
## Problem

When a file is being transferred, the string showing the progress jitters all over the place due to the differing widths of the numbers.

https://user-images.githubusercontent.com/611168/106035168-04ae7a80-6091-11eb-8eeb-114c455d0554.mp4

## Proposal

We use tabular numbers in the file transfer dialog (or really, anywhere we're showing filesizes, probably). (Idea from [@alatiera@mastodon.social](https://mastodon.social/@alatiera/105624731925706525).)

## Prior Art

GNOME Web seems to use tabular numbers in the download popover to prevent the string from jumping around.

**Comment by alatiera** [comment]
If any newcomer is interested, what you'd need to do is apply the a `tnum=1` font-feature attribute to the `GtkLabel` through  `gtk_label_set_attributes`

The equivalent gtkbuilder xml is this.

```xml
      <object class="GtkLabel" id="current_time">
        <property name="label">0:00</property>
        <attributes>
          <attribute name="font-features" value="tnum=1"/>
        </attributes>
      </object>
 ```

**Comment by cassidyjames** [comment]
Since we don't use GtkBuilder XML… here's an equivalent PR to the date/time indicator: https://github.com/elementary/wingpanel-indicator-datetime/pull/246/files

Basically, wrap the relevant string in `<span font_features='tnum'>%s</span>`.
