### ISSUE TITLE
Ability to choose a different icon for Folder

### ISSUE THREAD

**Issue by Vyshnav2255** [elementary/files#1570]
## Problem
Currently, we can change the folder icon only by changing the system-wide icon pack.

## Proposal
An easy way to change the folder icon by including a change icon option in properties.

**Comment by danrabbit** [comment]
Can you elaborate a bit more on the problem you are facing? Changing an icon is a proposed solution, but what are you hoping to achieve by doing this?

**Comment by Vyshnav2255** [comment]
I want to change the icon of a folder to a custom png file.
Like, I have a Dropbox folder in the home directory. I want to change the folder icon to Dropbox icon so that when I bookmark the folder, I will be able to see it in the sidebar.

**Comment by hanaral** [comment]
Wouldn’t a better solution to this just to be smarter about cloud folder icons and to add colour tag support to the sidebar?

**Comment by jeremypw** [comment]
See #1189

**Comment by danrabbit** [comment]
@Vyshnav2255 if your concern is about Dropbox then there is already a cross platform API for Dropbox to add a branded bookmark to the sidebar, they just have to use it
