### ISSUE TITLE
Scanner plugin

### ISSUE THREAD

**Issue by Ordissimo** [elementary/files#1577]
## Problem
Scanning under Linux requires the addition of a software, simple-scan or xsane.
It is necessary to systematically search for the scanner you want to use.

## Proposal
From the file manager we offer the search for scanners.
The registration of the chosen scanner. 
It is possible to search for a new scanner and save it to replace the previous one.
The interface is built according to the properties of the scanner.
Only the source, mode and resolution are used.
We can scan, save and attach to an email the scan obtained.

Source code : https://gitlab.gnome.org/Ordissimo/pantheon-files-scanners
Licence : GPL V3

## Prior Art
List of scanners found.
![2-A](https://user-images.githubusercontent.com/10682892/107395469-22ea9080-6afd-11eb-9371-b9d11c3cdb9e.png)

Available options of the chosen scanner 
![1-A](https://user-images.githubusercontent.com/10682892/107395494-29790800-6afd-11eb-809c-03070a7eb9b1.png)

**Comment by danrabbit** [comment]
Scanning is definitely far outside the scope of Files. If you need to scan documents, you should install one of the 3rd party tools you mentioned like Simple Scan

Closing as "out of scope"

**Comment by Ordissimo** [comment]
I do not share your opinion!
The scanner generates files and finds all its place in Files, it brings simplicity.
I'm sorry I didn't find an echo in your project which I appreciate very much.
