### ISSUE TITLE
Better column view spacing

### ISSUE THREAD

**Issue by hanaral** [elementary/files#1578]
## Problem

Columns take up far too much space and folder and file names and icons are poorly padded, which is a self reproducing problem.

The smallest icon view gives list icons a very generous amount of padding on the left and an absurd amount of padding on the right:
![Screenshot from 2021-02-11 12-01-33](https://user-images.githubusercontent.com/58219504/107634097-ee8fe500-6c60-11eb-9ab6-37490c4b7e0e.png)
I understand that the  padding on the left is for the selection badge, but I personally don't think the badge should overlap the icons when they are so small anyway.

The columns themselves are also far too large, and I can only fit about 2.4 columns in a relatively normal sized window:
![Screenshot from 2021-02-11 12-05-22](https://user-images.githubusercontent.com/58219504/107634457-6fe77780-6c61-11eb-8aad-6485f5c3362d.png)

## Proposal

Item text and icons should have better padding so that columns can be tighter and easier to fit on screen. Possibly the selection badge should be moved to the far end of the list box

## Prior Art

![image](https://user-images.githubusercontent.com/58219504/107635030-61e62680-6c62-11eb-8fe4-ec123789c41d.png)

**Comment by jeremypw** [comment]
Note that the default column width can be changed by editing the settings key `io.elementary.files.column-view.preferred-column-width`.  So it would be simple to change the default value subject to design team approval.  

Also, the column width can be changed by dragging the dividing line.

Maybe we could change the padding in proportion to the icon size - it the moment it appears to be fixed.

Flagging for design-team attention.

**Comment by jeremypw** [comment]
Unlike e.g. sidebar width, any user changes to the column width made by dragging is not remembered - so that is another thing to consider.

**Comment by hanaral** [comment]
> Unlike e.g. sidebar width, any user changes to the column width made by dragging is not remembered - so that is another thing to consider.

tbh I would rather see a fixed column view and then just address the issue of cut off titles with [this](https://github.com/elementary/granite/issues/449). I cannot see the resize feature as actually solving anything unless I have overlooked something.

**Comment by cassidyjames** [comment]
@hanaral if you were dealing in a folder with a bunch of long filenames, truncating or scrolling them all would be VERY annoying when you could just temporarily resize that one column; so I think there is definitely value in keeping them resizable. I do wonder if it would be sensible or over-the-top to remember column widths per-folder, like we remember sort order. A smaller default might make sense. 

An alternative approach could be to dynamically size the columns to fit their contents (perhaps with lower and upper bounds). A folder full of short filenames would get a skinnier column, while a folder with long filenames would get a wider column. I have no idea how much work that would be, though.

**Comment by hanaral** [comment]
> @hanaral if you were dealing in a folder with a bunch of long filenames, truncating or scrolling them all would be VERY annoying when you could just temporarily resize that one column; so I think there is definitely value in keeping them resizable. 

@cassidyjames 
I should probably file another feature request under granite for this, but macOS shows the entire line of text when you hover over something with a name that's too long:
![Screenshot from 2021-02-11 19-30-46](https://user-images.githubusercontent.com/58219504/107688647-ca072d80-6c9f-11eb-9d4c-6969432e439e.png)
![Screenshot from 2021-02-11 19-30-58](https://user-images.githubusercontent.com/58219504/107688656-cb385a80-6c9f-11eb-87bc-8aac9071b1f9.png)

**Comment by jeremypw** [comment]
> An alternative approach could be to dynamically size the columns to fit their contents 

This could have an impact on performance for folders with a large number of items.  Also the longest item might never actually be displayed.  I have a vague memory that Files used to do this but it was discontinued.

**Comment by cassidyjames** [comment]
@hanaral no need to file that against Granite, it could be filed here against Files.

**Comment by hanaral** [comment]
@cassidyjames I've been running Files with the default column width set to 120 via dconf, it feels far better this way and lets me see more.
Would elementary/UX consider changing the default to this via the default-settings repo?

**Comment by hanaral** [comment]
The hpadding seems a little better now, but is anyone working on files willing to try toning down the left gutter? (the space between the icon and the left side, although keep enough space for the badge)
@jeremypw If you could add this to #1669 I'd be more than happy to test it!

**Comment by jeremypw** [comment]
The reason why I kept a more than minimum gap in ListView was to provide a reasonable separation between the helper emblem and the expander. I can try shaving off a few pixels and see what UX team think.

There is less scope in ColumnView as the edge of the helper emblem is already only a few pixels away from the edge of the view.

**Comment by hanaral** [comment]
I was mainly worried about column view, which at the smalles size shows the selection badge so close to the edge that if it was moved down inline witht the icon it would essentially be a listview tickbox (mainly helped by how file/folder icon has almost it's entire width worth of left padding)

**Comment by jeremypw** [comment]
Any better?:
![Screenshot from 2021-04-23 09 33 24](https://user-images.githubusercontent.com/10513844/115843951-485a1b80-a417-11eb-84c2-524184383430.png)
![Screenshot from 2021-04-23 09 35 09](https://user-images.githubusercontent.com/10513844/115844144-76d7f680-a417-11eb-9591-b01637cb56c5.png)

**Comment by jeremypw** [comment]
I suppose putting the expander on the right of the filename column would be possible but not simple - need UX team direction for that.

**Comment by hanaral** [comment]
The second screenshot looks quite good imo, the first one could use some vpadding on the entries themselves though (I can't remember if that was an intentional change)

**Comment by jeremypw** [comment]
By the way - do not raise issues against the "merge-fixes" branch. From your screenshot it looks like you are using that branch?  There may be regressions and issues caused by the merge process.  You should comment on the relevant specific PRs in those PRs themselves. Only raise issues against the master branch here.

**Comment by jeremypw** [comment]
My screenshot of the ColumnView was at minimum icon size which is designed for maximum compactness.

**Comment by hanaral** [comment]
> By the way - do not raise issues against the "merge-fixes" branch. From your screenshot it looks like you are using that branch? There may be regressions and issues caused by the merge process. You should comment on the relevant specific PRs in those PRs themselves. Only raise issues against the master branch here.

You're quite right. I've rebuilt from master and it is marginally better, but still looks like a misaligned seperate widget. The example in both your screenshots stil look far better

**Comment by hanaral** [comment]
@danrabbit Could you re-open this issue? It was mainly about the width of the columns themselves, not the left gutter size...

**Comment by jeremypw** [comment]
@hanaral It would be better to open a new feature request issue with a single specific issue - "Change the default column view column with to X"
