### ISSUE TITLE
Files crashes or locks up when deleting files and dirs

### ISSUE THREAD

**Issue by hanaral** [elementary/files#1581]
## What Happened

Deleting files causes the app to crash seemingly every other time

## Expected Behavior

Files is able to delete files without crashing

## Steps to Reproduce

Try repeatedly deleting and restoring the same file OR try deleting a bunch of files one-by-one

### Logs

seemingly none

## Platform Information

elementary OS 6 Daily, files up to date

**Comment by jeremypw** [comment]
I could not reproduce this deleting and restoring small files below my Home folder after compiling from source.  When was the last time you did NOT get this issue?  There was a couple of file operations merges in the the last two or three days (one of which was intended to stop crashes caused under some circumstances when a dialog was triggered) and a big sidebar related merge today (although that should not touch file operation code materially).

**Comment by hanaral** [comment]
I haven’t gotten it since I rebuilt from master. I’ll close this by tomorrow unless I get it again.

**Comment by hanaral** [comment]
Cannot reproduce, closing as resolved
