### ISSUE TITLE
Cannot mouse-3 click on sidebar locations to open in new tab

### ISSUE THREAD

**Issue by hanaral** [elementary/files#1582]
## What Happened

Trying to mouse-3 on a sidebire directory will result in nothing happening

## Expected Behavior

mouse 3 or 3 finger clicking on a location should open in new tab

## Platform Information

latest git elementary OS 6 Daily

**Comment by jeremypw** [comment]
Confirmed, I forgot to implement this when rewriting the Sidebar using Gtk.ListBox
