### ISSUE TITLE
Files Always Crashing

### ISSUE THREAD

**Issue by kedehboy** [elementary/files#1587]
Hello there, i've been using ele,elementary Os for some times now, I love it but as i go deep into using it for my day to day activities, each time i try to access the  Files application, it either crashes or it take way too much time to load unlike when you just freshly install the operating system. And Please,i'll like if you add fractional scalling to the  next release of your updates, and also your wingpanel icons are too big and buggy i'll like if there be a place for customization. Thanks

**Comment by jeremypw** [comment]
Hi.  Please give more information about which version of elementary you are using and the circumstances under which Files crashes.

Loading time will depend on which tabs are being restored (how many files they contain), or whether they are on a slow remote connection.  Its best to close views of large views or remote folders before closing Files or to turn off restoring tabs.  

You can find information about getting backtrace for a crash here: https://wiki.debian.org/HowToGetABacktrace.  Posting this will help us diagnose the problem.

Please raise the other issues you raised in the relevent projects as they are not Files issues.

**Comment by heiscostly** [comment]
The version of elementary am using is elementary OS 5.1.7 Hera
How do i turn off restoring tabs?
And please can you include fractional scalling, i really don't like my wingpanel icons, there too big

**Comment by jeremypw** [comment]
@heiscostly 
>How do i turn off restoring tabs?

You can turn off restoring tabs by typing the command `gsettings set io.elementary.files.preferences restore-tabs false` into a terminal.

On elementary 6.0 (not yet released)  Files will also honor the privacy settings so tabs will not restore if you disable "History" in "System Settings/Security  & Privacy" using the Switchboard app.  This will affect the behaviour of other apps though. Also, not sure if this works in Hera.

>And please can you include fractional scalling, i really don't like my wingpanel icons, there too big
Do you mean "wingpanel" (the panel along the top of the screen - this only has very small icons already) or "dock" (the panel at the bottom of the screem).  The size of icons in the dock can be adjusted with Switchboard.  Navigate to "System Settings/Desktop/Dock".  You can also change the icon size (and many other properties of the dock) by right-clicking on the right-hand edge of the base of the dock and using the "Preferences" menu (Note the target is very small - it easy to click on an icon instead).

**Comment by heiscostly** [comment]
![Screenshot from 2021-02-23 10-07-46](https://user-images.githubusercontent.com/39498038/108822320-339c0b80-75bf-11eb-9757-be976721c42a.png)

Take a look at my wingpanel icons, there too big for my liking

**Comment by heiscostly** [comment]
How about fractional scalling like ubuntu has fractional scaling, to reduce your screen scalling factor

**Comment by jeremypw** [comment]
OK, it looks like the non-elementary icons are out of proportion.  I suggest you raise an issue here: https://github.com/elementary/wingpanel/issues.

**Comment by jeremypw** [comment]
Closing as there was no specific issue.
