### ISSUE TITLE
There is no eject (unmount) button on the sidebar for connected ssh servers.

### ISSUE THREAD

**Issue by queeup** [elementary/files#1592]
## What Happened
There is no way to eject (unmount) ssh server connection on the files app. There is no eject (unmount) button on the sidebar.

## Steps to Reproduce
1. Connect ssh server with files app
2. Try to eject (unmount) ssh server connection from sidebar

## Platform Information
```bash
~ $ head -2 /etc/os-release
NAME="elementary OS"
VERSION="6 Early Access"
~ $ dpkg-query --showformat='${Package}:\t${Version}\n' --show pantheon-files
pantheon-files:	4.5.0+r4286+pkg100~daily~ubuntu6.1
```

**Comment by jeremypw** [comment]
Confirmed. This is a regression after the recent Sidebar rewrite. Will fix.
