### ISSUE TITLE
Hide default folders from the home directory that are bookmarked in the sidebar

### ISSUE THREAD

**Issue by hanaral** [elementary/files#1602]
## Problem

The Files app has seemingly so many ways to access folders that should just be seperate isolated locations in the sidebar.
You can access the home folder;
1. From the sidebar
2. From the navbar at the top
3. By opening a new tab

The user can access the default locations (Documents, Videos etc.);
1. From the sidebar
2. From the default new tab view in the home folder

And this is on top of just navigating to /home/X/X after clicking 'filesystem' from the sidebar.

## Proposal

Files should hide the default locations when the user navigates to the home folder unless they are removed from the sidebar, and possibly remove the bookmark for the home directory by default (only to be visible with ctrl-h).

Optimally the home directory is not supposed to be seen by users and only contains xdg-documents, xdg-pictures, xdg-local(rather than .local) xdg-appdata(rather than .var) etc. and the sidebar becomes the primary way of navigating to 'base' directories of different categories, but that's a bit much for this issue

**Comment by cassidyjames** [comment]
I think trying to be clever would just end up being confusing. One of the most infuriating things about using Windows and macOS for me is how confusing the default file manager is, because it makes it difficult to actually get to where you want to go. Folders disappearing from the view because they happen to be bookmarked seems like the same sort of spooky magic.

**Comment by danrabbit** [comment]
Yeah this definitely seems like trying to be clever at the expense of being obvious. The home folder is a real file system location, so I think we need to represent its contents accurately

I think there may be another issue report about creating a home view that isn't a representation of the home folder that may be more in the direction of deduplicating things

The opposite direction could also be considered: removing some default bookmarks from the sidebar, especially ones that are typically managed by apps like music and photos

**Comment by hanaral** [comment]
> The opposite direction could also be considered: removing some default bookmarks from the sidebar, especially ones that are typically managed by apps like music and photos

That would also work, but then you have to look at it from the perspective that a lot of the things in the user's homefolder (with the addition of a Flatpak based app system) now becomes fatal for normal app operation...
And thats on top of the fact that if the user somehow manages to mess with the .Xauthority file they become permentently locked out of their computer without dropping to a terminal. 
Although in the future if elementary OS opts for an approach like macOS where all factors that effect normal system operation are system-side this wouldn't be an issue.

**Comment by jeremypw** [comment]
I am :-1: on this - it seems like a potentially confusing solution to a non-existent (or very minor) problem.

**Comment by hanaral** [comment]
Closing in favour of removing #1611
