### ISSUE TITLE
A better sidebar UX

### ISSUE THREAD

**Issue by hanaral** [elementary/files#1611]
## Problem

1. There are too many ways to access the same home dir. folders by default. The way users access directories such as Documents or Pictures is duplicated between actual navigation and that provided by bookmarks. 

2. Home, Recent and Trash behave as if they were static buttons, so why are they in the bookmarks list? 

3. I don't expect web browsers to have any bookmarks by default, let alone unremovable ones.

## Proposal

The sidebar should have the home directory, recents and trash as static buttons at the top of the list _(since 2 of them aren't even visible folders)_ and _possibly_ not have any bookmarks by default(?)
(I don't think using the user's tools for them is a good idea, it's just confusing since a bookmark is something you add yourself)

This way you have 3 static buttons to access the 3 base locations:

1. **The home directory**; where user _always_ starts on first launch or new tab. All the default folders are immediately accessible from here anyway
2. **The recents view**;  a collection of recently _used_ items and isn't even a folder
3.  **The trash folder**; a collection of recently _deleted_ items and is only a folder in the literal sense

Another thing that can now be considered is carrying over a bookmarked item/folder's colour tag to the bookmarks

## Prior Art

![Screenshot from 2021-03-03 00-29-16](https://user-images.githubusercontent.com/58219504/109734276-a78a7500-7bb8-11eb-824b-f07ac0295caa.png)

**Comment by pongloongyeat** [comment]
Having them ungrouped just makes it look weird to me and makes the ungrouped list seem redundant (from your pic, there are only 3 buttons).

Fundamentally, I believe you're right (since bookmarks _are_ supposed to be added by the user) but I am in favour of leaving it as it is and besides, most of the default bookmarks can be removed with the exception of home and trash. Perhaps renaming "Bookmarks" would be more appropriate here. Something like "Favourites" or "Places".

**Comment by hanaral** [comment]
I don't think it's appropriate to add bookmarks in this case. The user will always right click files and see that they can do it anyway

**Comment by jeremypw** [comment]
There does seem to be a trend to put user bookmarks in a separate group in other filemanagers, which does seem more logical.  Unfortunately the user bookmark group usually gets put at the bottom of the sidebar which I am :-1: on as it makes them less accessible often requiring scrolling to access. They should be at or near the top. The current layout is probably for historical reasons but people are used to it now - whether there are sufficient downsides to warrant a change is questionable but it would be easy enough to do if the UX team agreed.

**Comment by hanaral** [comment]
What I don't get then is why Files relies on a fundementally different navigation system that is more similar to web browsers - why is it that it is fine to reimagine that, but not something you just said is more logical? I see no problem with reimagining illogical design choices that are there because they were there before.

Anyway, moving 3 buttons that were already there above the category that they aren't in isn't a huge change - argue that there should or should not be bookmarks by default, but it does not change that home, recents and trash are not at all bookmarks.

**Comment by jeremypw** [comment]
I don't disagree.  As the sidebar is currently being rewritten now would be a good time to reconsider past design decisions (which may pre-date elementaryos), but ultimately it is up to the UX team.
