### ISSUE TITLE
Rename and/or split the "Devices" section

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#1615]
## Problem
The items listed under "Devices" are not necessarily physical devices (currently includes bind mounts and other mountable locations).  Moreover not all devices attached to the system will appear here (only Drives, Volumes or Mounts).

## Proposal
Rename the section to better reflect its contents. e.g. "Storage"

Alternatively, limit the contents of this section to actual physical devices (i.e Drives) and show other mounts elsewhere or in their own section.

## Prior Art
At least one other filemanager shows the root partition ("File System") under built-in bookmarks

**Comment by cassidyjames** [comment]
I think I'm on board with "Storage". Devices could mean anything from webcams to flash drives, so I agree it's not really precise, and especially when you consider it's showing other locations, too. 

For more prior art, it looks like the Google Files app on Android says "Storage Devices" and has "Internal storage" as one item, then any attached storage devices like flash drives, then "Other storage" as an item that takes you to cloud storage locations. The Solid Explorer app (a pretty nice alternative file manager on Android) has "Storages" (lol) with an "Internal Memory" item and then any network mounts.
