### ISSUE TITLE
Network expander in sidebar is not visible

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1620]
For some reason the grid in the Network expander title widget is not set to visible

![Screenshot from 2021-03-05 12-46-02](https://user-images.githubusercontent.com/611168/110165876-cd7a6a00-7db0-11eb-9f53-59b505a2ca4d.png)

**Comment by danrabbit** [comment]
This was fixed in #1619 :)

**Comment by cassidyjames** [comment]
d'oh!
