### ISSUE TITLE
MTP devices don't open from sidebar

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1625]
## What Happened

I connected my Pixel 5 Android phone to my computer, enabled data transfer on the phone side, and then clicked the item in the sidebar.

## Expected Behavior

The Pixel 5's internal storage should open via `mtp://`

## Steps to Reproduce

1. Connect an Android phone (or other mtp device) and enable file transfer on the device
2. Open files and click on the device in the sidebar

As a note, right-clicking and opening properties works, and the `mtp://` URI in the properties dialog _does_ actually work and open the folder.

## Platform Information

elementary OS 6 Odin daily build

**Comment by jeremypw** [comment]
I am usually getting bookmarks under "Storage" when the phone is plugged in and these are non-functional.  Sometimes however I get a bookmark under "Network" and this works for both "mtp" and "gphoto2" ("ptp") modes.  It also depends on whether the phone was plugged in before or after starting files.  

Also, changing the mode on the phone produces a new bookmark but does not remove the old one.  So there is some work to do here....
