### ISSUE TITLE
Unable to restore trashed files if folder was deleted

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/files#1632]
## What Happened

Cannot restore trashed file if folder no longer exists.

## Expected Behavior

It should at least show a more friendly error. Currently, it shows

```
Error when getting information for file “/home/loongyeat/Projects/calculator/data”: No such file or directory
```

Rather, this should perhaps show "Folder "/home/loongyeat/Projects/calculator" no longer exists. Would you like to re-create the folder?". Something like what's shown below.

![Screenshot from 2021-03-20 03-45-14](https://user-images.githubusercontent.com/31680656/111834589-c74ac880-892e-11eb-8c4e-dbc540633573.png)

Showing an alternative button with "Choose another folder" might be good too.

## Steps to Reproduce

1. Trash a file.
2. Delete the folder where the trashed file was in.
3. Go to trash and restore file.

### Logs

```
Error when getting information for file “/home/loongyeat/Projects/calculator/data”: No such file or directory
```

## Platform Information
Files daily

**Comment by jeremypw** [comment]
Not even sure you need the dialog - the user probably would expect the parent folder(s) to be recreated and to do so would not be destructive or irreversible.

**Comment by pongloongyeat** [comment]
@jeremypw I was thinking more of if the user restores the file, how would we show the user where the file is being restored to. Often times, when you delete a file, you don't really remember where it was stored (or maybe it's just me) so, having a dialog show where the path it will be restored in helps that slightly, though I'd be more keen on opening a new tab at the path it was restored in (but this has issues when you're restoring a few files at once).

**Comment by jeremypw** [comment]
Showing to where the file is restored is a separate issue, I think.  It also applies when the original parent folder still exists.  As you say, things get complicated if the user restores multiple files to multiple locations.  The original location of the file is available under "Properties".  I suppose if a List View were used then it could be made one of the columns or maybe shown in the overlay, but needs to be discussed separately.
