### ISSUE TITLE
update dependencies list in README.md

### ISSUE THREAD

**Issue by newsgrep** [elementary/files#1633]
## What Happened
I guess your dependencies list in README.md is out of date. 
* cmake seems to be missing
* libgranite-dev seemes to be >= 6.0.0

## Steps to Reproduce
I cloned 9780174
and run `meson build --prefix=/usr`

got an error:
Dependency granite found: NO found 5.3.0 but need: '>=6.0.0'

Did not find CMake 'cmake'

Found CMake: NO

Run-time dependency granite found: NO

## Platform Information
The Meson build system Version: 0.53.2
Project name: io.elementary.files
Project version: 4.5.0
C compiler: gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0"

### Logs
Called `/usr/bin/pkg-config --cflags granite` -> 0
-pthread -I/usr/include/granite -I/usr/include/gee-0.8 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
PKG_CONFIG_PATH:                                                                                                
Called `/usr/bin/pkg-config granite --libs` -> 0                                                                
-L/usr/lib/x86_64-linux-gnu -lgranite -lgee-0.8 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0                                   
PKG_CONFIG_PATH:                                                                                                
Called `/usr/bin/pkg-config granite --libs` -> 0                                                                
-lgranite -lgee-0.8 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0                                                               
Dependency granite found: NO found 5.3.0 but need: '>=6.0.0'                                                    
Invalid version of dependency, need 'granite' ['>=6.0.0'] found '5.3.0'.                                        
CMake binary for MachineChoice.HOST is not cached                                                               
CMake binary missing from cross or native file, or env var undefined.                                           
Trying a default CMake fallback at cmake                                                                        
Trying CMake binary cmake for machine MachineChoice.HOST at [None]                                              
Did not find CMake 'cmake'                                                                                      
Found CMake: NO                                                                                                 
No CMake binary for machine MachineChoice.HOST not found. Giving up.                                            
Run-time dependency granite found: NO                                                                           
                                                                                                                
meson.build:50:0: ERROR: Invalid version of dependency, need 'granite' ['>=6.0.0'] found '5.3.0'.

**Comment by jeremypw** [comment]
Files does not depend on cmake (it built it OK after uninstalling cmake).  The master version does however need to be built with Granite >=6.0.0 so the README.md does need updating in that respect.

**Comment by jeremypw** [comment]
I can confirm that the "CMake" message is an artifact of the the granite dependency failure. As mentioned, Files has no dependency on on `cmake`.
