### ISSUE TITLE
Hidden folders clutter 'New' / file templates menu

### ISSUE THREAD

**Issue by ninpnin** [elementary/files#1635]
## What Happened

I'd like to version control my templates. When initializing a git repository, I noticed that the .git folder was included in the 'New' menu when right clicking, along with its subfolders hook and info.

## Expected Behavior

Hidden folders clutter the 'New' menu. I assume this is not intended functionality – the most natural way would be to only include visible files and folders. 

## Steps to Reproduce

1. Create a hidden folder in the Templates folder
2. Add a file inside it 
3. Right click and select 'New' to view templates

## Platform Information

* eOS 5.1.7
* Files 4.5.0

**Comment by jeremypw** [comment]
> I assume this is not intended functionality 

Yes, this is not intended, this use case was not envisaged it seems.  It should be simple enough to ignore hidden files.
