### ISSUE TITLE
Slower to start up with new sidebar

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1642]
Ever since the new sidebar was merged, I've been noticing Files takes a few seconds to start up across my machines, even on my fast SSDs and relatively high-specced laptops. Interestingly, it seems that subsequent startups are faster, like something has to be initially cached after a cold boot.

Before the new sidebar, Files would open nearly instantaneously.

**Comment by jeremypw** [comment]
I can confirm this and have tracked it to adding the "Entire Network" bookmark to the Network listbox. Investigating ...

**Comment by jeremypw** [comment]
The delay is occuring at the `Object ()` statement in `AbstractMountableRow.vala` but weirdly only for the NetworkRow and only on the first use in the session. The same class is used to construct DeviceRows beforehand without delay :shrug:  Something is being cached or initialised but I cannot see what.

**Comment by davidmhewitt** [comment]
@jeremypw My testing seems to point to the following being called on the "Entire network" (`network://`) bookmark:

https://github.com/elementary/files/blob/48a66191ae8c4ccb4459f1a53d6cb739a9e85512/src/View/Sidebar/BookmarkRow.vala#L106

I'm not familiar enough with the codebase to be able to propose a sensible fix.

**Comment by jeremypw** [comment]
@davidmhewitt Thanks for spotting that - that would explain why there is only a problem with the "network:://" target - I'll see whether I can fix it.

**Comment by phabiotemplates** [comment]
Files is very slow at first startup, unlike version 5.1. From there it opens normally. I'm using the beta on May 2, 2021.

**Comment by jeremypw** [comment]
If anyone can test the linked PR with a variety of network servers to make sure there are no regressions it would help.  That is why it is still in draft.
