### ISSUE TITLE
Cannot mount Android phone using Files

### ISSUE THREAD

**Issue by ryanrms** [elementary/files#1644]
## What Happened

I tried to move files to my phone, a Poco X3 NFC, and after connecting the USB cable and enabling file transfer on the phone, the phone showed up in files but clicking the icon/label brought up a blank screen.

## Expected Behavior

It should bring up both the SD Card and the Internal Storage for browsing and file transfer.

## Steps to Reproduce

1. Plug in an Android device, with a recent Linux kernel they should just work
2. Enable file transfer on the phone
3. Attempt to browse the phone's files with Files.

## Platform Information

elementary OS 6 Development Preview, installed several days ago but up to date.

Can anyone confirm this issue?  Perhaps it is just an issue with my particular device, I don't have others to test.

**Comment by ryanrms** [comment]
I was able to browse the files, by clicking on "Properties" of the Poco X3 NFC in the sidebar of Files, and then clicking on the mtp address listed.  This brought me to a screen showing both the SD Card (listed as "disk") and the internal storage (listed as "internal shared storage").  Perhaps Files simply isn't going to the correct address when the phone's item is clicked in the sidebar?

**Comment by jeremypw** [comment]
I think this is is a duplicate of #1625, which has just been fixed by #1634.

**Comment by leonardo-lemos** [comment]
@ryanrms A new daily build of Files is now published, can you update your Files' package and see if the issue is resolved, please?

**Comment by leonardo-lemos** [comment]
@ryanrms A new daily build of Files is now published. Can you please update your Files' packages and see if the issue is resolved?

**Comment by ryanrms** [comment]
@leonardo-lemos I can confirm that the issue is resolved.  Within 24 hours~!  Wow, quick turnaround. ;)
