### ISSUE TITLE
Opening a folder and closing the current tab shows the folder icon as opened

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#1646]
## What Happened

Opening a folder and closing the current tab shows the folder icon as opened

## Expected Behavior

Opening a folder and closing the current tab should back the folder icon to the original one

## Steps to Reproduce

![2021-04-02 20 49 05 の画面録画](https://user-images.githubusercontent.com/26003928/113413287-42af7e00-93f5-11eb-89f0-36da7d79a534.gif)

1. Open Files and move to Home folder
2. Open some folder in Home folder
3. Close the current tab
4. See the icon of the opened folder in the step 2. is displayed as opened, although it's no longer opened in any tab

### Logs

N/A

## Platform Information

- elementary OS Odin Daily with fully updated
- Files `4.5.0+r4402+pkg100~daily~ubuntu6.1`

**Comment by jeremypw** [comment]
This does not happen if you navigate back to the home folder - it seems to be related with closing the tab. Presumably something is not being closed down properly.
