### ISSUE TITLE
Place emblems in line with labels in list views

### ISSUE THREAD

**Issue by danrabbit** [elementary/files#1647]
![bitmap](https://user-images.githubusercontent.com/7277719/113443193-52ec3c80-93a6-11eb-9b18-e6e6517b0d55.png)

## Problem

In list views, especially if we go down smaller than the default size, things get really cluttered as we add emblems over the icons

## Proposal

Instead of overlaying emblems on the file icon, it seems like we should make use of the horizontal space in the list view to render emblems after item labels

**Comment by jeremypw** [comment]
Should the emblems be right justified in the column or next to the filename?

**Comment by danrabbit** [comment]
@jeremypw My gut instinct is that right justification would make it easier to scan in case you were specifically looking for a symlink or something with different permissions
