### ISSUE TITLE
Icons have too much hpadding in smaller list views

### ISSUE THREAD

**Issue by hanaral** [elementary/files#1650]
## What Happened

I initially thought it was a bug, but it seems that it is caused by the 'more-compact-listview' that was merged.
The listview items should not have so much horizontal padding on their icons, at the smallest mode the padding is wider than even the icon itself:
![Screenshot from 2021-04-05 15-15-01](https://user-images.githubusercontent.com/58219504/113590083-b930c380-9621-11eb-8f94-c60d087ef397.png)

## Expected Behavior

If the icon does not have enough space to have badges without obscuring it then it should use the same style as in other places like settings:
![Screenshot from 2021-04-05 15-12-55](https://user-images.githubusercontent.com/58219504/113589879-71aa3780-9621-11eb-89b1-7be53b3210c7.png)

## Platform Information

elementary OS 6 Daily

**Comment by jeremypw** [comment]
Yes, there is another issue open about rethinking how to show badges in list view that works well at the most compact.

**Comment by hanaral** [comment]
I mentioned something about this in #1578 and made some mockups of how it could look (although it might be better to use coloured icons for badges still)
