### ISSUE TITLE
Back button keeps being highlighted after dragging window

### ISSUE THREAD

**Issue by kdwk** [elementary/files#1652]
## What Happened

https://user-images.githubusercontent.com/39268094/114176381-a3970300-996d-11eb-9647-c213e1653b36.mp4
While the window is being dragged and the cursor is on the 'back' button, the button is highlighted. However, the button is still highlighted after the dragging action and cannot be un-highlighted without closing and reopening the window.

## Expected Behavior

The 'back' button is un-highlighted after the drag action

## Steps to Reproduce

1. Open Files
2. Hover the cursor on the 'back' button
3. Drag the window
4. Release the window
5. Observe the 'back' button
6. Reopen the window
7. Observe the 'back' button

## Platform Information

![Screenshot from 2021-04-08 13-53-56](https://user-images.githubusercontent.com/39268094/114176719-215b0e80-996e-11eb-889d-5176b9f881ee.png)

**Comment by jeremypw** [comment]
I am not seeing this on elementary 6 (Odin) - these buttons are no longer highlighted when hovered with the new stylesheet.

**Comment by kdwk** [comment]
Good. I'll overlook that and instead look forward to Odin then
