### ISSUE TITLE
There is no way to connect ssh server just with key (without password)

### ISSUE THREAD

**Issue by queeup** [elementary/files#1666]
## What Happened
All keys are exist for connecting to my ssh server but when I try to connect through files app, it's not allowing me to connect. Connect button is greyed out. Oblige to entering password.

## Expected Behavior
Allow me to connect ssh servers without password.

## Steps to Reproduce

1. Try to connect ssh server from files app (don't enter password)

## Platform Information
```bash
~ $ head -2 /etc/os-release
NAME="elementary OS"
VERSION="6 Early Access"
~ $ dpkg-query --showformat='${Package}:\t${Version}\n' --show pantheon-files
pantheon-files:	4.5.0+r4445+pkg100~daily~ubuntu6.1
```

**Comment by marmeladapk** [comment]
I can add that in previous elementary version this was not the case and I could connect without specifying password.

**Comment by jeremypw** [comment]
Possible due to this commit https://github.com/elementary/files/commit/81cb0b9f82df8438bb3433181d3be1952f324b69.

I guess the Granite.ValidatedEntry widget in password mode does not accept blanks (which previously were accepted).

Can you connect using a dummy password?

**Comment by queeup** [comment]
I can not connect with dummy password.

**Comment by marmeladapk** [comment]
That's weird. I can connect with a dummy password.

**Comment by queeup** [comment]
Sorry, my mistake. Dummy password allows me to connect.
