### ISSUE TITLE
Connected ssh servers are appearing both under Storage and Network sidebar

### ISSUE THREAD

**Issue by queeup** [elementary/files#1667]
I am not sure if this is intentional or a bug. I just want to report it. 

![Ekran görüntüsü 2021-04-17 18-00-48](https://user-images.githubusercontent.com/87835/115117540-bfbb2580-9fa7-11eb-9b0d-96dcdfad5179.png)

## What Happened
Connected ssh servers are appearing both under Storage and Network sidebar

## Expected Behavior
I think it's better to show just under Network

## Steps to Reproduce
1. Connect to ssh server

## Platform Information
```bash
~ $ head -2 /etc/os-release
NAME="elementary OS"
VERSION="6 Early Access"
~ $ dpkg-query --showformat='${Package}:\t${Version}\n' --show pantheon-files
pantheon-files:	4.5.0+r4445+pkg100~daily~ubuntu6.1
```

**Comment by jeremypw** [comment]
The above linked PR does not suffer from this defect but it is uncertain whether the change in UI will be accepted so a separate fix may be required.
