### ISSUE TITLE
error en el menu contextual

### ISSUE THREAD

**Issue by jh3rn4n** [elementary/files#1680]
# error en el menu contextual (quiero decir al dar clic derecho en el explorador)
Realizé una instalación personalizada de elementary os 5.1.7 lo único que preserve fue /home/<user>
como tenia una distro diferente me asegure de elimenar todas las carpetas de configuracion local del usuario
/home/<user>/.local
/home/<user>/.config
etc.
![Captura realizada el 2021-04-27 18 13 06](https://user-images.githubusercontent.com/26331827/116319356-62338f80-a784-11eb-84d1-a2247e299b1a.png)
PS:
Gracias por adelantado.

**Comment by cassidyjames** [comment]
Rough translation (aided by Google Translate):

># Context menu error (I mean right clicking in Files)
>
>I did a custom install of elementary OS 5.1.7; the only thing it preserved was `/home`
as I had a different distro installed. I made sure to delete all the user's local configuration folders, e.g. `/home/.local`, `/home/.config`, etc. 
>
>_screenshot_
>
>Thanks in advance.

**Comment by cassidyjames** [comment]
So it looks like the issue being reported is that the contents of the home folder are showing as templates? This looks like a duplicate of #1635.

**Comment by jh3rn4n** [comment]
so what can i do? in order to cleen this up

**Comment by jh3rn4n** [comment]
@jeremypw publicó unos cambios en que deben solucionar el problema pero no estoy claro en eso. ¿Qué es lo que tengo que hacer?

**Comment by cassidyjames** [comment]
@jh3rn4n it means this issue will be resolved with the next release of Files.

**Comment by jh3rn4n** [comment]
@cassidyjames very thanks
