### ISSUE TITLE
Files application drops custom shortcuts at every reboot

### ISSUE THREAD

**Issue by dagolinuxoid** [elementary/files#1681]
All Settings -> Keyboard -> Shortcuts -> Custom

assign `io.elementary.files` to `Super_L + o`  
it works fine, however upon next reboot pressing these buttons doesn't launch the Files application. In order to fix it I have to manually got to the settings again and reassign the keys on every reboot. Other applications (like terminal or music) behave as expected and persist the custom shortcut settings. I'm using elementary os 5.1.7 Hera kernel 5.4.0-72
[![bug.png](https://i.postimg.cc/T1j41Z3z/bug.png)](https://postimg.cc/gLJDBtRs)

**Comment by jeremypw** [comment]
On Odin (elementary 6 daily), I could not get `<Super>O` to work as a custom shortcut at all but `<Alt>O` worked as expected and survived logging out.

**Comment by dagolinuxoid** [comment]
@jeremypw it looks like some combinations of chars with *Super* doesn't work well. I've switched  to `Alt` and satisfied with the result - it behaves as expected now.
