### ISSUE TITLE
Can no longer sort in both directions

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1682]
## What Happened

I keep my Downloads and Screenshots folders in the icon view sorted by date, reversed so the newest files show up at the top. With a recent update to Files, I am no longer able to sort this way; files appear to always be sorted in non-reversed order.

I'm seeing similar results in the list view, where you can sort files by clicking on the column headers, but clicking again to sort it in reverse does nothing.

## Expected Behavior

Sorting would work in both directions, as it did before.

## Steps to Reproduce

1. Open a folder with several items
2. Sort by date (context menu → Sort by → Date) and observe the sort order
3. Reverse the sort direction (context menu → Sort by → Reversed) and observe the sort order

## Platform Information

elementary OS 6 daily build, Files from master

**Comment by jeremypw** [comment]
Possible due to recent port of ListModel to Vala.

**Comment by jeremypw** [comment]
I am seeing something slightly different (in ListView) - the headers seem to have 3 sort states - Ascending, Descending and None - clicking on them toggles between Up, Down and No arrows.  When in Ascending or Descending state the context menu works as expected but when in the None state, the context menu has no effect.
