### ISSUE TITLE
Make sorting by date default to reversed order

### ISSUE THREAD

**Issue by bleedforever** [elementary/files#1683]
## Problem
Sorting by date in Files defaults to showing oldest files at the top. Most of the time when I personally sort by date, I want to see the newest files and folders first -- like in my screenshots folder, or the folder I store my artwork in.

The concept of sorting by date either being reversed or like, normal..? non-reversed..? has also always been a little confusing to me in file managers... it's vague enough that I often have to look at my files and rely on context to figure out if it's oldest first or not.

## Proposal
It would be rad if clicking "sort by date" would put the newest stuff at the top.

Additionally I would really appreciate if the checkbox under "Sort by" that normally says "Reversed Order" was instead contextual ("A-Z"/"Z-A" for sorting by name, "Newest First"/"Oldest First" for sorting by date, etc.) but I am not sure what would be the most appropriate way to do this. Radio buttons???

## Prior Art
Social media orders things chronologically with the newest items displayed at the top. Photos on iOS puts the newest items on the bottom, but it auto-scrolls to the bottom so if you flip your phone upside down it sort of still applies.

Outside the digital world, a loose-leaf folder full of like homework or whatever will have the newest stuff at the top, because the newest stuff is usually the most relevant.

**Comment by jeremypw** [comment]
Nautilus also seems to default to most recent first.  Work is needed on sorting since the ListModel port anyway (see #1682
