### ISSUE TITLE
Context menu in Files to create a symbolic link [$5]

### ISSUE THREAD

**Issue by codygarver** [elementary/files#169]
Feature to create a symbolic link of a file or folder from the context menu.

Bounty: https://www.bountysource.com/issues/8716448-context-menu-in-files-to-create-a-symbolic-link

**Comment by bil-elmoussaoui** [comment]
Can this be done using a contractor? Or should it be included in Files itself?

**Comment by jeremypw** [comment]
This would probably fit in the Cut/Copy/Paste section.  Perhaps an extra option "Copy Link"?  subsequent Paste would then paste the link at the selected site.
