### ISSUE TITLE
Segmentation fault in miller view

### ISSUE THREAD

**Issue by KeurKeur** [elementary/files#1699]
## What Happened
When changing folder in miller view in same column, the application crashed with a segmentation fault. 

## Expected Behavior

Not crashing.

## Steps to Reproduce

1. Click on miller view.
2. Change folder multiple times on same column.

### Logs

Here is the backtrace : 
```
Thread 1 "io.elementary.f" received signal SIGSEGV, Segmentation fault.
0x00007ffff7eea03c in files_abstract_slot_get_current_slot (self=0x555555d9f9c0) at ../libcore/AbstractSlot.vala:98
98	        public abstract unowned AbstractSlot? get_current_slot ();
(gdb) bt
#0  0x00007ffff7eea03c in files_abstract_slot_get_current_slot (self=0x555555d9f9c0) at ../libcore/AbstractSlot.vala:98
#1  0x00007ffff7eeaa0d in files_abstract_slot_get_directory (self=0x555555d9f9c0) at ../libcore/AbstractSlot.vala:26
#2  0x00007ffff7eeace6 in files_abstract_slot_get_uri (self=0x555555d9f9c0) at ../libcore/AbstractSlot.vala:45
#3  0x00005555555e67e4 in files_abstract_directory_view_finalize (obj=0x555555f37c30) at ../src/View/AbstractDirectoryView.vala:334
#4  0x00005555555bd2b8 in files_abstract_tree_view_finalize (obj=0x555555f37c30) at ../src/View/AbstractTreeView.vala:21
#5  0x00005555555ba498 in files_column_view_finalize (obj=0x555555f37c30) at ../src/View/ColumnView.vala:20
#6  0x00007ffff7d42d0e in g_object_unref () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7dd7413 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff7dd7d39 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff7ddb0d8 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff7ddb400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff7ddb4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff7c2afe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x0000555555582f5a in _vala_main (args=0x7fffffffddf8, args_length1=1) at ../src/main.vala:26
#14 0x0000555555582fa1 in main (argc=1, argv=0x7fffffffddf8) at ../src/main.vala:16
(gdb) 

```

## Platform Information

Elementary OS 6 Beta on gnome-boxes. Tested with pantheon-files from the release and the master.

Thanks !

**Comment by jeremypw** [comment]
Looks closely related to #1695.  I could only trigger the crash when one of the folders was empty and I had to rapidly switch between folders several times as fast as possible before getting a crash.  Hopefully the fix for #1695, which I am working on will also fix this.

**Comment by KeurKeur** [comment]
Understood, thank you very much.

**Comment by jeremypw** [comment]
I have pushed another PR aimed at protecting MillerView from rapid path changes.  I havent been able to get a crash with this fix in place.  The only drawback is that if you click on the second folder too quickly, the click is ignored and the path does not change. a more sophisticated would be to queue the requests or to throttle them and only act on the last one.

**Comment by KeurKeur** [comment]
Hi,

I merged your two PR, but unfortunately it still happens.... 

I don't know if this might help but I have this new errors about signal after crashing : 
```
(io.elementary.files:2135): GLib-GObject-WARNING **: 18:34:26.437: invalid (NULL) pointer instance

(io.elementary.files:2135): GLib-GObject-CRITICAL **: 18:34:26.437: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

Thanks again

**Comment by jeremypw** [comment]
OK, that's a pity - thanks for trying.  Could you confirm whether you are clicking rapidly between folders and whether it happens if you allow say, 1 second between changing folders? If you can get another backtrace of the crash that would help.

**Comment by jeremypw** [comment]
@KeurKeur Thanks for the extra info - I made some more changes in the light of your last backtrace, which have been merged.  Please feel free to re-open this issue if you find it does not fix things in your case. It seems various processes happen at different speeds on you system than on mine resulting in different outcomes of races that occur when directories are created and destroyed at high speed.  It would require a major rewrite to avoid races altogether unfortunately :disappointed:

**Comment by KeurKeur** [comment]
Hmm indeed maybe it's because I use a virtual machine.

I can confirm so far it works (and I clicked like a crazy man)

Thanks again !
