### ISSUE TITLE
ListView: Not all folders has the expander icon

### ISSUE THREAD

**Issue by KeurKeur** [elementary/files#1706]
## What Happened

When expanding a directory, some subdirectory doesn't have the expander icon, while it is not even empty.

## Expected Behavior

Showing expander icon.

## Steps to Reproduce

1. Expand a folder with subdirectories.

### Logs

No logs.

## Platform Information

Elementary OS 6 Beta on gnome-boxes. Tested with pantheon-files from the master.

Thanks !

**Comment by jeremypw** [comment]
Seems to only affect the deepest level folder in an expansion chain.
