### ISSUE TITLE
Opening folder from terminal opens parent if parent already displayed

### ISSUE THREAD

**Issue by dagolinuxoid** [elementary/files#1708]
launch elementary file manager
executing of the command in a terminal
```
io.elementary.files ~/Music
```
## Actual Behavior
focuses file manager which has a path ~/

## Expected Behavior
focuses file manager which has a path ~/Music/

## Steps to Reproduce
see above

NOTE
However if file manager is not currently running or invoked directly from terminal with `-n` flag
the behavior is as expected 

## Platform Information

elementary OS 5.1.7 Hera
Linux 5.4.0-73-generic

**Comment by dagolinuxoid** [comment]
Personally I'm using `io.elementary.terminal`  to do stuff, but occasionally I like to see on content of a current directory in a file manager (it nice to have media previews / thumbnails etc). Not going *inside* the specified folder but rather just highlighting it in a directory above defeats the whole point.

**Comment by jeremypw** [comment]
Just tried this with elementary 6 and it behaves as you would expect (as far as I am aware it always has - it is certainly meant to).

**Comment by dagolinuxoid** [comment]
Glad to hear it. I'm waiting for the stable 6th release meanwhile.

**Comment by dagolinuxoid** [comment]
@jeremypw I've updated the initial text of the issue, there are some nuances can you double check the outcome if the file manager is already running and after that you execute `io.elementary.files ~/Music`  from terminal, thx.

**Comment by jeremypw** [comment]
You are quite right, the issue does occur if Files is already running.  The same issue also arises when giving a regular file as a parameter in the terminal in which Files should open the parent and highlights the file (which it does if Files is not already running).

**Comment by jeremypw** [comment]
The issue only happens if the parent folder is already shown in the running instance of Files.  In this case, if Files is not showing `~/` then `~/Music` opens in a new tab as expected. Files tries not to open duplicate tabs if a folder is opened from the terminal that is already open but it seems it gets it wrong in these circumstances.
