### ISSUE TITLE
Folders' color should be neutral (sort of gray) or changeable (eOS 6).

### ISSUE THREAD

**Issue by lilvadim** [elementary/files#1712]
## Problem
Folders are yellow and accent color is applied.
![Screenshot from 2021-05-15 17-24-55](https://user-images.githubusercontent.com/32203382/118357099-97244c80-b5a2-11eb-9529-bcb9d6f3b631.png)

## Proposal
Don't you think that it would be good idea to make them gray or another neutral color? There is already gray folder in the Files App icon.
AFAIK in macOS if you choose some accent color, Finder leaves its colors being blue, they aren't being changed. But I think it's better when file explorer colors (highlights at least) are changeable.

**Comment by jeremypw** [comment]
This is essentially the same as https://github.com/elementary/stylesheet/issues/1034 which was closed as a design conflict so closing this as well.  Thanks for taking the trouble to file an issue though.
