### ISSUE TITLE
List view mode, multiple files selection - buggy appearance (eOS 6 Public Beta).

### ISSUE THREAD

**Issue by lilvadim** [elementary/files#1713]
I've selected multiple files by pressing on their checkboxes and only last selected file is colored as it should with my accent color, other files are grayish.
![Screenshot from 2021-05-15 17-33-11](https://user-images.githubusercontent.com/32203382/118357304-af489b80-b5a3-11eb-9879-359508ac78bc.png)

**Comment by jeremypw** [comment]
This is essentially the same as https://github.com/elementary/files/issues/1704 which was closed as a design conflict, so closing. Thanks for the issue report though.
