### ISSUE TITLE
Use new Cloud Providers stuff [$360]

### ISSUE THREAD

**Issue by codygarver** [elementary/files#172]
link: https://csorianognome.wordpress.com/2015/07/07/cloud-providers/

It's a DBus API. FTA:

 – GetIcon: which retrieves the cloud provider brand icon.

 – GetPath: which retrieves the folder where the cloud provider stores its files.

 – GetName: which retrieves the name of the cloud provider

 – GetStatus: which retrieves the status (idle, syncing, error) of the cloud provider

 And finally, it can expose a full GMenuModel through DBus for its use for any action.

The expected implementation in Files should probably be the same as described in the article: Showing cloud drives as mounts in the sidebar. In our case however, they should be sorted under the "Network" category

**Comment by benwaffle** [comment]
https://gitlab.gnome.org/External/libcloudproviders

**Comment by diego-d5000** [comment]
what exactly is expected ? The implementation of the workflow in [this article](https://wiki.gnome.org/Design/Whiteboards/CloudProviders) ("Use cases and workflow" section) using this GTK DBus API ?

**Comment by gideondsouza** [comment]
yea it's not too clear to me either. 
This DBus api is cool but what do you expect to be done specifically.

**Comment by oreach** [comment]
So, no traction? I'll take on the task then. I expect to have the Files plugin done by Monday, then I'll spend a week making a cloud provider or two.

**Comment by cassidyjames** [comment]
@oreach any update?

**Comment by cassidyjames** [comment]
@Philip-Scott this is the issue we were talking about at LAS.

**Comment by peteruithoven** [comment]
This might be an interesting example, result of GSoC, what the integration of the Nextcloud client looks like in Nautilus:
https://www.youtube.com/watch?v=Px3TpCWLmbI
Mre info: https://blog.juliushaertl.de/index.php/2017/08/28/gsoc-final-report/

**Comment by naaando** [comment]
I'm working on this, not sure how much time I'll take because I want to add unit tests(I never done unit testing in vala before) and make sure it's working roundly.

**Comment by skewty** [comment]
Is it possible for Files to show "badges" to reflect a synced / unsynched state over top of the icon / folder itself?

**Comment by naaando** [comment]
Hi people, [libcloudproviders](https://gitlab.gnome.org/World/libcloudproviders) seems to be broken, the test client and library aren't working, I'm not good in C language to fix these issues.
I've made the bindings to Vala already and I'm waiting for a response to my merge requests.
My best bet is to implement a client in Vala that connects directly to the server, that solution would be ok?

**Comment by tristanrobert** [comment]
I wonder if a different solution would be better, a solution based on [gnome-online-accounts](https://gitlab.gnome.org/GNOME/gnome-online-accounts) integrated in switchboard-plug-onlineaccounts and [gvfs](https://gitlab.gnome.org/GNOME/gvfs) integrated in pantheon-files like [nautilus is](https://wiki.gnome.org/Projects/GnomeOnlineAccounts/Debugging#Integration_with_GtkFileChooser_and_Nautilus). This solution with gvfs seems to me more mature. It does not depend on gnome desktop packages, although it is two GNOME projects. What do you think about it @danrabbit ?

**Comment by tintou** [comment]
Files is already using GVFS as it uses the Gio library (as well as the whole OS). We made the choice to not use GNOME-Online-Accounts because of their lack of modularity.

**Comment by naaando** [comment]
@skewty If Files already has the badge feature would be possible for the folder but not files inside because the API of the library doesn't cover syncing status for each file. Maybe a hacky way to determine it is listening to file descriptors, so it could be used to notify users about files being written even off of cloud folders.

**Comment by naaando** [comment]
I'd split major changes into PRs.
Related PRs: #648 #649 #650 and have more commits to cherry-pick to another branch before pushing.

Current status
- The Open* actions still don't work
- The first time the plugin context menu opens it is inverted
- I still don't know if the menu is supposed to be inactive or is a problem
- Should 'syncing' be represented by a spinner?

![captura de tela de 2018-10-10 01 53 572](https://user-images.githubusercontent.com/12532760/46713963-96c7b600-cc2f-11e8-8fa7-08e920274f0d.png)

**Comment by naaando** [comment]
@peteruithoven I'm almost done, couldn't make the tests yet, and am not sure how it should be done too. The CI is failing because the plugin requires the library [libcloudproviders](https://gitlab.gnome.org/World/libcloudproviders).

This dependency should be included on deb-packaging's control file and installed by CI script, but the available package won't work for compiling 'cause it doesn't ship the bindings patches. So the lib must be compiled from the master branch or wait for a new release.

**Comment by cassidyjames** [comment]
@naaando according to @tintou, we should be able to bundle the `.vapi` file as we do for other libraries without `.vapi` files. He can help with that if you need, or someone else may be able to. I'll ask around.

**Comment by peteruithoven** [comment]
Looks like the `libcloudproviders-dev` dependency has been successfully added. 
Was there any progress on including those `.vapi` files?

**Comment by naaando** [comment]
Hi @peteruithoven, unfortunately adding the .vapi was not enough due to other changes that are required to binding work, so I think I am blocked until a new release of the library.
The libraries generally have a main header including all the source files, but it didn't so I had to create one and it didn't get upstream yet.

**Comment by danrabbit** [comment]
Sent a DM to @csoriano1618 on Twitter to see if we can get his attention. Let you know when I hear anything back :)

**Comment by codygarver** [comment]
@naaando I built the libcloudproviders package, it's in the OS Patches PPA available on elementary OS Juno now.

**Comment by peteruithoven** [comment]
@naaando could you maybe clarify some things. 
The [pantheon-files-cloud plugin](https://github.com/elementary/files/pull/656) you've made is a cloud provider client?

But this also requires a cloud provider server? 
Currently the libcloudproviders gitlab page lists the Nextcloud client as a server: 
https://gitlab.gnome.org/World/libcloudproviders#server
Which means you still need to install the Nextcloud desktop client and run it in the background?
([ppa](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client) ([linux packaging status](https://help.nextcloud.com/t/linux-packages-status/10216)) / [appimage](https://nextcloud.com/install/#install-clients) / [flatpak](https://flathub.org/apps/details/org.nextcloud.Nextcloud) / [snap](https://snapcraft.io/nextcloud-client))

Do we know if people are working on other servers, for example to support Google Drive or Dropbox?
(I understand we need to start somewhere. Hopefully more cloud provider clients like your Files plugin will stimulate more progress)

**Comment by csoriano1618** [comment]
Hey @peteruithoven, I'm the creator of libcloudproviders.

I plan to work on the Dropbox plugin sooner rather than later, given that their Nautilus plugin (only supported file manager they have) is open source, located [here](https://github.com/dropbox/nautilus-dropbox).

If someone wants to help with this one out I will be more than glad to give reviews and advice any time!

**Comment by peteruithoven** [comment]
@csoriano1618 whow pretty cool that you're keeping your eyes on things here.

The term "plugin" is a bit confusing in this case. 
Do you mean a plugin for Files? Shouldn't implementing the libcloudprovider plugin make that unnecessary?

**Comment by csoriano1618** [comment]
> Do you mean a plugin for Files?

Yeah

> Shouldn't implementing the libcloudprovider plugin make that unnecessary?

Exactly. The Dropbox repo contains how to connect to Dropbox protocol and all as part of the Nautilus plugin, so it "just" needs to wire that to libcloudproviders instead.

**Comment by karim-inabi** [comment]
they have only supported file managers

**Comment by naaando** [comment]
libcloudproviders provide a protocol like MPRIS for media players, that said;

> The [pantheon-files-cloud plugin](https://github.com/elementary/files/pull/656) you've made is a cloud provider client?

From libcloudproviders README
> libcloudproviders is a DBus API that allows cloud storage sync clients to expose
their services. Clients such as file managers and desktop environments can then
provide integrated access to cloud providers services.

Shortly yes, but libcloudproviders already ships a client so what I did was wiring this client to the UI components

> But this also requires a cloud provider server?

No, in libcloudproviders terminology a server refers to a program that expose an API whose clients connects to query updates, the client(the file manager and the desktop environment in this case) can list servers and query information on the server(cloud provider client which is exposing the API) like the path the is syncing your files.

> Currently the libcloudproviders gitlab page lists the Nextcloud client as a server:
> https://gitlab.gnome.org/World/libcloudproviders#server
> Which means you still need to install the Nextcloud desktop client and run it in the background?

Yes.

> ([ppa](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client) ([linux packaging status](https://help.nextcloud.com/t/linux-packages-status/10216)) / [appimage](https://nextcloud.com/install/#install-clients) / [flatpak](https://flathub.org/apps/details/org.nextcloud.Nextcloud) / [snap](https://snapcraft.io/nextcloud-client))
> 
> Do we know if people are working on other servers, for example to support Google Drive or Dropbox?

I don't know for sure.

> (I understand we need to start somewhere. Hopefully more cloud provider clients like your Files plugin will stimulate more progress)

> @csoriano1618 whow pretty cool that you're keeping your eyes on things here.
> 
> The term "plugin" is a bit confusing in this case.

I made it as a plugin to not hard depend on that, integrating it as a plugin looks cleaner.

> Do you mean a plugin for Files? Shouldn't implementing the libcloudprovider plugin make that unnecessary?

I think he means a server to expose Dropbox client to DBus so it can be listed on Files, and yes this plugin makes unnecessary to build specific plugins for each cloud service provider if they are using libcloudproviders DBus API.

**Comment by csoriano1618** [comment]
If there are things I can clarify on the README or documentation, feel free to point them to me, I will be glad to clarify them.

**Comment by naaando** [comment]
Is https://github.com/elementary/files/pull/656 enough to finish this?
