### ISSUE TITLE
Can`t move files to another folders

### ISSUE THREAD

**Issue by PPS9** [elementary/files#1723]
Hi,
after last updates I can not move file to another folders (i.e. from Downloads to Documents/Pictures/Video).

**Comment by meisenzahl** [comment]
Thank you for creating the issue. Could you please describe the issue in some detail and specify with which version of elementary OS (5 or Early Access) the issue occurs.

**Comment by cassidyjames** [comment]
And please specify how you're trying to move files; via drag-and-drop? Keyboard shortcuts to cut and paste? Context menu items?

**Comment by PPS9** [comment]
version 5.1.7
Yes, drag-and-drop.
Ordinary files, such as docs, jpgs
