### ISSUE TITLE
Rename is broken

### ISSUE THREAD

**Issue by KeurKeur** [elementary/files#1730]
## What Happened

Select a file, rename it and you will see that the file with the previous name is still here. 

## Expected Behavior

The file with the previous name is deleted.

## Steps to Reproduce

1. Select a file.
2. Rename it.

### Logs

No logs.

## Platform Information

Elementary OS 6 Beta on gnome-boxes. Tested with pantheon-files from the master.

Thanks !

**Comment by jeremypw** [comment]
Looks like regression due to recent listmodel port to Vala. The old file is not getting removed from the model (pressing refresh (F5) shows it has in fact been renamed)
