### ISSUE TITLE
Files app crashes sometimes

### ISSUE THREAD

**Issue by xenon86k** [elementary/files#1745]
## What Happened
After booting the computer, when I try to open the files app for first time it takes longer time (about 3/4 seconds) to open. In that (3/4) second period if I click the files app again (single or more times) then files app stops working. The app window doesn't appear. The only way to open it is closing the app by clicking close on plank dock icon and then opening it again. If I open it again sometimes files app freezes and stops working and when this happens, there is no way to fix it rather than rebooting the computer. If I try to close the app, it closes but when I open it again, it remains freeze. It only fixes after a reboot.

If I don't click the files app multiple time while opening the files app first time after a boot, the app doesn't crashes or gives any problem. The files app also opens faster after opening it for first time.

## Steps to Reproduce
1. Turn on the computer.
2. Click on the files app icon, while it is opening(for me it takes more than 2 seconds to open after a boot) click on the files app again (single or multiple time).
3. Then it should freeze, try closing it from the window controls (it shouldn't work)

## Platform Information
Elementary OS 6.0 Odin Beta 2
AMD Ryzen 3 3200G Processor
A320M Motherboard

I will try to upload a video or screenshot soon.

**Comment by jeremypw** [comment]
The issue about slower startup the first time was reported here #1642 and there is a draft solution at #1645. However the issue of a crash has not been reported afaik.  Not sure whether that PR also fixes this problem. I'll check when I have time.

**Comment by jeremypw** [comment]
@xenon86k I am having difficulty reproducing this on my computer even with the master branch.  If I click on the dock icon again before the Files window opens then Files starts up but is minimized as expected. Clicking again on the icon opens the Files window immediately. I only get a significant startup delay when one of the tabs restored is `network://`. Can you say what directories you are restoring when Files opens?  Does stopping directory restoration by turning History off in System Settings/Security & Privacy stop this issue occuring?

**Comment by xenon86k** [comment]
I experienced this problem maybe twice, and I'm also trying to reproduce it while recording. But I can't. Maybe I forgot the proper steps. Anyway, thank you very much for your response. I'm closing the issue now. If you can please tell me how can I fix the long startup time of files app while opening it for the first time after booting the pc.

**Comment by jeremypw** [comment]
@xenon86k The issue of long initial start up time should be fixed if PR #1645 is approved and merged.
