### ISSUE TITLE
Option to increase Folder/Thumbnail size in Files

### ISSUE THREAD

**Issue by 4turtlez** [elementary/files#1746]
It would be great if there was an option to increase the size of the folders/thumbnails in files. It would make them way easier to see for many people. They are pretty small.

**Comment by jeremypw** [comment]
You can change the icon/.thumbnail size in the views by holding down the `<Control>` key and scrolling up and down. Or by using the shortcuts `<Control>Minus` and <Control>Equal`  (`<Control>Plus` also works to increase the size).  Is this what you mean?

This does not work in the sidebar though.

**Comment by jeremypw** [comment]
Further info on shortcuts can be found here: https://github.com/elementary/files/wiki/shortcuts

**Comment by 4turtlez** [comment]
OK Thanks. Didn't realize you could use Control and scroll up and down to change size. This is great!!

Although the Control +/- doesn't work (this is what i had been trying)

**Comment by jeremypw** [comment]
The keyboard shortcuts work for me - what locale/keyboard layout are you using?  Make sure the view has the keyboard focus before using them.
