### ISSUE TITLE
Show keyboard shortcut for toggling hidden files

### ISSUE THREAD

**Issue by waldyrious** [elementary/files#1751]
## Problem
It is possible to toggling the display of hidden files with <kbd>Ctrl</kbd>+<kbd>H</kbd>, but this shortcut is not shown in the context menu when right-clicking a folder, whereas the other actions do have a visible hint:

![Screenshot from 2021-07-10 17 33 23 png](https://user-images.githubusercontent.com/478237/125171023-e2756880-e1a9-11eb-9576-19f9686aca94.png)

## Proposal
The "Show hidden files" menu item should have the keyboard shortcut made visible.

## Prior Art
I can see that the Bookmark and the Properties entries in the menu (which do have their shortcuts shown in the menu) are implemented via [`Gtk.MenuItem`](https://valadoc.org/gtk+-3.0/Gtk.MenuItem.html) + [`Granite.AccelLabel`](https://valadoc.org/granite/Granite.AccelLabel.html):

https://github.com/elementary/files/blob/554e85d3fb797e309fce48f651a4bf58396d771a/src/View/AbstractDirectoryView.vala#L1958-L1970

...whereas the "Show Hidden Files" and "Hide Thumbnails" ones are implemented differently, via  [`Gtk.CheckMenuItem.with_label`](https://valadoc.org/gtk+-3.0/Gtk.CheckMenuItem.CheckMenuItem.with_label.html):

https://github.com/elementary/files/blob/554e85d3fb797e309fce48f651a4bf58396d771a/src/View/AbstractDirectoryView.vala#L2087-L2094

Is this a technical limitation for such toggle menu items? Otherwise, I'd be happy to contribute a PR with a fix if offered some pointers.

**Comment by jeremypw** [comment]
@waldyrious Thanks for noticing this and looking into it. I do not see why you should not be able to add a Granite AccelLabel to the CheckMenuItem in the same way as a MenuItem.

**Comment by waldyrious** [comment]
Thanks for the confirmation, @jeremypw. Just to be sure, is the following code OK or am I missing something?

```vala
var show_hidden_menuitem = new Gtk.CheckMenuItem (); 
show_hidden_menuitem.add (new Granite.AccelLabel ( 
    _("Show Hidden Files"), 
    "<Ctrl>h" 
));
show_hidden_menuitem.action_name = "background.show-hidden"; 
```

Also, would I need to remove this line?

https://github.com/elementary/files/blob/2dbb5e9e5a3b6b4ac0045e0760eba9c402e9f98a/src/View/Window.vala#L1195

**Comment by waldyrious** [comment]
(I suppose there's no common shortcut for toggling thumbnails; if there is, I'd be happy to add them as well, so please let me know if you're aware of any.)

**Comment by jeremypw** [comment]
What you propose looks OK but the best thing to do is create a new branch and try it!  However, do *not* remove the `set_accels_for_action` line. 

You are right that there are no keyboard shortcuts set for toggling remote or local thumbnails.  Not sure if there are any commonly established shortcuts for these functions.  That is probably best addressed as a separate issue if you would like to propose suitable shortcuts.

**Comment by waldyrious** [comment]
> the best thing to do is create a new branch and try it!

I've actually never set up a development environment for elementary before, but I'll give it a try when I find the time (just changed jobs so I will not have a lot of spare time for a few weeks).

**Comment by jeremypw** [comment]
OK, no problem.  I can easily test it.

**Comment by jeremypw** [comment]
Using `new Gtk.CheckMenuItem()` and adding a `Granite.AccelLabel` as proposed above:
![ShowHiddenMenuAccel](https://user-images.githubusercontent.com/10513844/125791175-8bfea560-449d-4578-af29-9a8ae9006147.png)

**Comment by waldyrious** [comment]
Thanks so much for testing it! I'll submit the code, then :)
