### ISSUE TITLE
Drag and drop to sidebar is needing to be easier and better visual explanations.

### ISSUE THREAD

**Issue by queeup** [elementary/files#1769]
## Problem

Drag and drop to sidebar is very difficult to do and to understand what is going to happen. You have to be really precise to move to trash or bookmark on the sidebar. Also there is no hover around sidebar items while moving files on top of them.

https://user-images.githubusercontent.com/87835/126909867-a8d2cd4d-1afb-40ae-955f-0de9075ab3b5.mp4

## Proposal

 - Make hover on the sidebar directories while drag and drop
 - Bigger action icons
 - Little bit less sensitive between move to and bookmarked

**Comment by jeremypw** [comment]
If its any help, when the rows move apart, then the drop will make a new bookmark.  Otherwise the file will be moved/copied to the bookmark you are over.  The emblem on the dragged icon also changes accordingly.  However, the exact point at which it switches between modes could do with fine-tuning.

**Comment by queeup** [comment]
@jeremypw sorry for reply. I didn't realize my video was corrupted. I made a new video.

https://user-images.githubusercontent.com/87835/129491231-e5f53c1d-903f-4666-8d24-eade729074dd.mp4

**Comment by jeremypw** [comment]
Thanks for the new video.  I think the target for dropping into a bookmark is too small compared with the target for dropping between them.  I'll see what can be done to improve it.
