### ISSUE TITLE
Connecting to a file server via SMB is not working

### ISSUE THREAD

**Issue by dcharles525** [elementary/files#1785]
## What Happened
When trying to connect to my local file server via SMB I get the message in the screen shot below. Note that this is working fine in OS 5 on my other computer on the same WiFi. 

![Screenshot from 2021-08-14 14 35 37](https://user-images.githubusercontent.com/4961680/129449830-bcb5bcf7-1600-4bdd-beb4-b7cacb95d209.png)

## Expected Behavior
It should display the files on my server. 

## Steps to Reproduce
Try and connect to an SMB on your local network via SMB://192.168.1.1/<yourserver>

## Platform Information
OS 6

**Comment by jeremypw** [comment]
Did you connect by using the "Connect Server" dialog, or by browsing from "Entire Network" bookmark or by entering the address into the pathbar?  The error message "Software caused connection abort" is just being reported back by Files from gvfs - could be a software version mismatch between client and server? 

You could try adding "client max protocol = NT1" to the [Global] section of `/etc/samba/smb.conf` if your local server is running an older version of samba (although this will prevent connection to other servers running up to date software so it would be better to update the server.)

I have a local Samba server set up and can connect OK with Odin via `network://` by clicking on the corresponding server icon.

**Comment by stan-janssen** [comment]
I'm unable to reproduce this problem, even when connecting like dcharles525 by entering an SMB url:

https://user-images.githubusercontent.com/12174852/129478807-5548eaba-8d18-4ef9-86a4-ebe3795da50b.mov

**Comment by dcharles525** [comment]
Thanks @jeremypw and @stan-janssen for testing it out. I still haven't been able to get it to work but my 'smb' server is really a feature built into my router, so its probably out of date on that end. I will close for now but if I find a solution I will post back here.

**Comment by stan-janssen** [comment]
If you happen to be using a Fritz!Box router by AVM; I **had** the same result as you with that, same error message in Files. I also could not access it from a Windows 10 machine, however. Windows 10 told me the FritzNAS only supports SMB1 (as jeremypw correctly assumed in his suggestion above), which Windows 10 also no longer supports.

**However**: there is an update available for the Fritz!Box router (current version 07.27, previous version was 07.12) that fixes the problem on both ElementaryOS and Windows. I can now connect to it using Files.

I
