### ISSUE TITLE
When I hide miniatures the tags disappear

### ISSUE THREAD

**Issue by mathessaricci** [elementary/files#1787]
![image](https://user-images.githubusercontent.com/63082523/129571731-f6cf48ba-15cf-4978-849a-2aaf6ed8bb84.png)
![image](https://user-images.githubusercontent.com/63082523/129571774-75839454-64c5-43b1-bef0-acafa79d9658.png)

**Comment by mathessaricci** [comment]
I already reported a similar bug on Juno. #1306

**Comment by jeremypw** [comment]
I am unable to reproduce this on my install of Odin/Files. When i toggled hidden files with `<Ctrl>H` the color tags of the visible files remained.  The Hera bug is reported as having been fixed and there does not appear to be a regression.  I notice in your images that the icons appear different - that did not happen to me either.

**Comment by jeremypw** [comment]
I also notice that the color tag of the folder remained which is curious.

**Comment by jeremypw** [comment]
Having read your issue properly :stuck_out_tongue_closed_eyes: I can confirm this happens for regular files but not folders. Toggling thumbnail display *does* stop non-folder color tags displaying.
