### ISSUE TITLE
 Network mounted folders appear twice in Devices section 

### ISSUE THREAD

**Issue by Extravert-ir** [elementary/files#180]
(re-raising bug [#1693030](https://bugs.launchpad.net/pantheon-files/+bug/1693030) from Launchpad)

NFS mount that configured in /etc/fstab appear twice in Devices section (see screenshot)

![](https://bugs.launchpad.net/pantheon-files/+bug/1693030/+attachment/4882147/+files/Screenshot%20from%202017-05-23%2023-35-07.png)

fstab:

```
homeserv.local:/export/downloads /media/downloads nfs auto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14 0 0
homeserv.local:/export/vault /media/vault nfs auto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14 0 0
```

```
$ dpkg -l | grep pantheon-files
ii pantheon-files 3.4-0~r2551+pkg63~ubuntu0.4.1
```

**Comment by jeremypw** [comment]
This should now be fixed in elementary 6.0 after rewriting the Sidebar. Please re-open if it recurs.

**Comment by dolpa** [comment]
Having this issue on elementary 6.0

**Comment by jeremypw** [comment]
PR #1752 is intended to ensure only one item appears for each mount.  If you can test this and comment it would help.

**Comment by jeremypw** [comment]
Closing as no further reports after PR#1752 was merged
