### ISSUE TITLE
Certain storage devices may randomly have a duplicate entry in the side panel

### ISSUE THREAD

**Issue by abodedis** [elementary/files#1801]
## What Happened

Certain storage devices may randomly have a duplicate entry in the side pane.
![Screenshot from 2021-08-19 07-13-56@2x](https://user-images.githubusercontent.com/89145148/130063444-fe3240d7-ff3c-4d40-8a20-d9aef7384119.png)
Note that there is only **one** CD-ROM in the system, however, the side panel lists two CD-ROMs.

## Expected Behavior

The devices in the Storage list should always be correct.

## Steps to Reproduce

This is an intermittent issue and the exact steps to reproduce is unknown.  However, it does appear when Files is first opened.  It is also unknown exactly when or how it appears during the course of using Files.  

For a heavy user performing file management operations, this issue may appear, seemingly randomly, about once per hour.  Also see issue #1796 which seems related because it pertains to Storage devices display and navigation.

One workaround is hitting refresh (F5) which will refresh all devices and the duplicate device will be deleted.  

This did not seem to be an issue in 5.1.7 Hera.

## Platform Information

OS: elementary OS 6 Odin x86_64 
Kernel: 5.11.0-27-generic 
Packages: 1699 (dpkg), 20 (flatpak) 
Shell: bash 5.0.17 
Resolution: 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Theme: io.elementary.stylesheet.blueberry [GTK3] 
Icons: elementary [GTK3] 
Terminal: io.elementary.t 
CPU: Intel Xeon W3680 (12) @ 3.326GHz 
GPU: NVIDIA GeForce GT 1030 
Memory: 1370MiB / 24047MiB

**Comment by abodedis** [comment]
After mounting a CDROM, the above described problems tend to occur more frequently.

**Comment by jeremypw** [comment]
PR #1752 is intended to stop such duplicates. If you are able to test that PR it would be helpful :smile:

**Comment by jeremypw** [comment]
#1752 is now merged so closing as this issue should not affect the latest release.  Please re-open if that is not the case.
