### ISSUE TITLE
Can't trash items on NTFS partitions

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/files#1803]
## What Happened
When trying to move an item that's on an NTFS partition to the rubbish bin/trash I get the `Unable to find or create Rubbish Bin directory for /mnt/hdd/whatever.file` 

https://user-images.githubusercontent.com/13716824/130082379-839d6927-4928-483d-9e81-31312da90b09.mp4

## Expected Behavior
I can create directories on the drive so I feel that files should make the correct directory.

## Steps to Reproduce

1. Create an NTFS partition
2. Create a file on it
3. Attempt to delete it/move to rubbish bin

## Platform Information
Odin

**Comment by jeremypw** [comment]
That message is not from Files, it from the underlying system.  I agree it is not immediately obvious why then appropriate directory cannot be created.  Probably because there is no pre-existing trash directory and also no user home directory to create it in (?)

**Comment by jeremypw** [comment]
You could try creating a directory `/home/<username>/.local/share`  (if NTFS supports directories starting with ".").  Otherwise it may be a limitation of the backend with respect to which filesystems it will create trash directories on.

**Comment by ChildishGiant** [comment]
My boot drive is ext4 and I have no issues trashing from it or other ext4 drives. The `~/.local/share/Trash` folder exists already

**Comment by jeremypw** [comment]
Does `~/local/share/Trash` exist on the NTFS partition though?  The backend aggregates separate trash directories on separate drives/partitions.  So if you plug in a USN drive formatted in ext4 you should have no problem trashing files on it but they will be stored in a trash directory *on the drive* not in your home directory although the `trash://` view will aggregate all trashed files.

**Comment by ChildishGiant** [comment]
How can `~/local/share/` exist both on NTFS and ext4, since it's only one path? I could try creating a trash folder on the NTFS drive but I don't know what path to use, other than moving my home dir over there.

**Comment by jeremypw** [comment]
It is perfectly possible to have the same (relative) path on different partitions.  For example I have Ubuntu installed on a different partition and that obviously has its own home directory.  When mounted it is mapped to `/media/<elementary-username>/<partition-name>/home/<ubuntu-username>`.  The highest available directory on the partition is its root (`/`).

I'll try creating a NTFS partition and see if I can fix this.

**Comment by ChildishGiant** [comment]
Thanks! I don't know that much about all the technicalities :sweat_smile:. I'll happily help test but it'd probably be easier for you to skip the middle man haha

**Comment by jeremypw** [comment]
I just tried trashing a file on an NTFS partition and it worked perfectly.  A folder `.Trash-1000` was automatically created.  I could also restore the file from the `trash://` view.

So it may be a permissions issue on your NTFS partition.  Maybe it is related to this issue: #1804?  Are you dual-booting with Windows and is Quick Start enabled on Windows?

**Comment by ChildishGiant** [comment]
The drive was originally from a windows install but that's long gone and I had quick start disabled.

**Comment by jeremypw** [comment]
OK, thanks. Could you report on the permissions of your NTFS root directory?  You can find these by right clicking on the background of the view and choosing "Properties" and then the "Permissions tab of the resulting dialog.

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/132532865-5c052443-36d9-44f3-a6b7-746924e638c9.png) All seems okay to my knowledge. Sorry for the delayed response

**Comment by jeremypw** [comment]
This is what I get:
![NTFSPermissions](https://user-images.githubusercontent.com/10513844/132545814-850cc32a-77e2-4d64-8baa-d048a4776e85.png)

Looks like your NTFS mount needs root privileges? Probably because it was created by Windows whereas mine was created by me on Linux.  I did some Googling and this is a fairly common problem; the solution generally seems to be to add the partition to `\etc\fstab` with the particular options so that you get the right permissions - I have not found a "non-technical" solution unfortunately :disappointed:  Here is one example of a solution: https://askubuntu.com/questions/1253464/cannot-move-to-trash-in-ntfs-partition

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/132551665-d1e903b8-dae6-4803-9bf2-7c23ee207435.png)

It's mounted on boot and doesn't seems to need root to mount although when trying to unmount with files I do get a popup asking for root perms.

**Comment by jeremypw** [comment]
Which software gives the above info?  Will it allow you to change the mount options?  Can you post the contents of your `/etc/fstab` file? I assume that is where the app is getting its info.

You could try adding `uid=1000,gid=1000` to the option list (currently `nosuid,nodev,nofail` as suggested  by the link given above. This should give you  ownership.

**Comment by ChildishGiant** [comment]
That's Gnome Disks. I tried adding my id stuff to the options but then need to use sudo just to write a file. This does seem like it's an issue with my setup, not files. However I can make files on the drive without my id at the end

**Comment by jeremypw** [comment]
Yes, it should be a question of getting the right mount options.  I assume switching to "User Defaults" does not fix things? Note you will have to log out or restart for any changes to take effect.

**Comment by ChildishGiant** [comment]
I've rebooted and tried again and `uid=1000,gid=1000` fixed it. I guess this could have a popup to inform the user about the issue with permissions and an easy fix but for now I think this can be closed
