### ISSUE TITLE
SMB/CIFS file transfers are significantly slower than using Windows

### ISSUE THREAD

**Issue by abodedis** [elementary/files#1805]
## What Happened

SMB/CIFS file transfers are significantly slower in Files than using Windows. SMB transfers can average about ~80MB/s max sustained rate (this of course varies depending on the type, size, and number of files transferred, but never exceeds the ~80MB/s sustained).
<img width="422" alt="Screenshot from 2021-08-19 10-33-31@2x" src="https://user-images.githubusercontent.com/89145148/130100119-a47944a6-3bd5-40f4-86e3-e56af05be3ee.png">

On a much faster computer (Ryzen 7 3700X/3900X) transfer rates using Files are marginally faster, about ~90MB/s.

However, in Windows, even on the slower computer (see specs below) the same transfer always achieves ~110+ MB/s in Windows, which is the desired behavior because it is near the theoretical max for the network (Gigabit).
<img width="336" alt="windows cifs speed" src="https://user-images.githubusercontent.com/89145148/130100644-d37101d5-891c-49db-93d7-c22353b06134.png">

The difference between 80MB/s and 110 MB/s is significant.
 
## Expected Behavior

SMB/CIFS transfers should not be significantly slower than Windows.

## Steps to Reproduce

1.  Using Files, copy a file using SMB/CIFS (such as from or to a NAS). Observe the sustained data transfer rate.  
2.  Do the same thing in Windows.  Perform the exact same operation. Observe the sustained data transfer rate.

## Platform Information

OS: elementary OS 6 Odin x86_64 
Kernel: 5.11.0-27-generic 
Packages: 1699 (dpkg), 20 (flatpak) 
Shell: bash 5.0.17 
Resolution: 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Theme: io.elementary.stylesheet.blueberry [GTK3] 
Icons: elementary [GTK3] 
Terminal: io.elementary.t 
CPU: Intel Xeon W3680 (12) @ 3.326GHz 
GPU: NVIDIA GeForce GT 1030 
Memory: 1370MiB / 24047MiB

**Comment by jeremypw** [comment]
Not sure this is a FIles issue - the nitty gritty of file transfers is handled by the operating system backend (in this case gvfs-smb), not the app.  Files just reports back the information it receives from the backend.  So maybe this should be raised with the Gnome project?

**Comment by jeremypw** [comment]
However, it is possible that the "undo" system of Files is adding an additional overhead.  Not sure if Windows has the same feature.

**Comment by jeremypw** [comment]
I think it is generally accepted that Windows 10 out-performs most Linux distros in terms of performance and battery-life. I guess people use Linux for other reasons.  Hopefully we will catch up eventually ...

**Comment by abodedis** [comment]
One of these days I may do a more "scientific" test to compare file transfer speeds using Files vs. the Terminal to see if there is any meaningful room for improvement.  Overall, I'm satisfied with the speed of Files as it is now, even if it is not as fast as Windows.  Files is so responsive and well laid out (when it behaves, and will forgive the recent new release growing pains) and if people give it a chance it can be used for serious work (file management of hundreds of thousands or millions of files).  I know because I have done this using Hera and see the potential.

**Comment by jeremypw** [comment]
As it is I would use something like `grsync` to backup huge numbers of files.  FIles is known to slow down with > 10^4's files especially in grid view.

**Comment by abodedis** [comment]
Yeah, I use fsync when it's just a bunch of files to back up.  Assuming it is similar to grsync.

I'm talking about content creation, when there are 5000 unorganized files per day on USB disks from 3-4 cameras that need to be sorted carefully by image contents or other metadata into folders on any drive in the network, the naming scheme that a client is very particular about.  That's not a terminal job, that's Files.

**Comment by abodedis** [comment]
Yeah, I already use rsync when it's just a bunch of files to back up.  Assuming it is similar to grsync.

I'm talking about content creation, when there are 5000 unorganized files per day on USB disks from 3-4 cameras that need to be sorted carefully by image contents or other metadata into folders on any drive in the network, the naming scheme that a client is very particular about.  That's not a terminal job, that's Files.

**Comment by jeremypw** [comment]
Photos can tag photos and filter them by tag and date and then export the result to an arbitrary folder but whether that covers what you need I don't know. You know best what works for you. Definitely not a terminal job.  I guess this touches on the discussion at #1729 as to what extent a general purpose file manager should be needed for real-world work (as opposed to system administration).  Ideally an image management app should be better able to meet your needs but if there isn't a suitable one then using the file manager makes sense.

**Comment by jeremypw** [comment]
Closing as no further evidence that this is specifically due to Files (and unrelated to extra overhead of providing Undo) was given.
