### ISSUE TITLE
Can you guys provide a snap build for elementary/files, I don't use ubuntu but I really miller-columns/cascading lists finderish look

### ISSUE THREAD

**Issue by mahfuzullah** [elementary/files#1808]
I don't use ubuntu or any of ubuntu based distros but I really miller-columns/cascading lists finderish look of elementary/files, if there were a snap build of this app it would be really nice for me,

also i would donate $10 to the elementary team

**Comment by cassidyjames** [comment]
I don't think we have interest in building and maintaining a snap, but will likely provide a Flatpak eventually; see #1508.
