### ISSUE TITLE
[Odin] Files localisation missing a Spanish translation

### ISSUE THREAD

**Issue by dennismayr** [elementary/files#1811]
## What Happened
Minor missing element translation
"Permanently Delete Trash" visible in Spanish-localised desktop

![](https://imgur.com/77C0uqU.png)

## Expected Behavior
"Permanently Delete Trash" should be "Vaciar Papelera Permanentemente".
However, I could not find the expression in [Weblate](https://l10n.elementary.io/translate/files/files/es/?offset=1&q=permanently+delete&sort_by=-priority%2Cposition&checksum=), so I could add it myself for future fix versions (happy to help translating elements).
I had previously accessed _System Configuration > Language & Region_ to complete the download of missing language packages, as in previous Elementary releases.

## Steps to Reproduce
1. In System Configuration > Language & Region > set system-wide language to Spanish
2. Log out & log back in 
3. Create a file and drag it to the Trash Bin
4. Left-click to empty trash, check dialog

## Platform Information
Elementary OS 6, Odin - kernel 5.11.0-27-generic
Machine: ThinkPad-T410s
Processor: Intel® Core™ i5 CPU 540M @ 2.53GHz
Video hardware: Intel® Ironlake Mobile + NVIDIA Corporation GT218M [NVS 3100M] (Optimus)
Memory: 7,6 GiB

**Comment by ryonakano** [comment]
I guess [this](https://l10n.elementary.io/translate/files/files/es/?checksum=34aaaa551ded19e1&sort_by=-priority,position) is the counterpart string on weblate and it's marked as "fuzzy"—which means it hasn't updated to work with the latest source change.

**Comment by dennismayr** [comment]
> I guess [this](https://l10n.elementary.io/translate/files/files/es/?checksum=34aaaa551ded19e1&sort_by=-priority,position) is the counterpart string on weblate and it's marked as "fuzzy"—which means it hasn't updated to work with the latest source change.
> 

Thanks for the quick reply! I'm new to Weblate, but now I see how it works. I'll log in later to review that element and suggest a translation.

Therefore, I'm closing this issue, to solve the cause on Weblate.
