### ISSUE TITLE
Can't create a new folder from file browser when downloading/saving files

### ISSUE THREAD

**Issue by jonolumb** [elementary/files#1823]
## What happened

When I want to download a file, or right click on an image and choose "Save as" in any browser, I cannot create a new folder to save the file to from the popup file browser.

## Expected behavior 
In the past, there was a new folder button in the upper-right corner of the file browser. You could first create a folder, then choose to save the file to that new location. However, as you can see in the screenshot, there is no longer any such option visible.

This means that to save a file to a new location, I must first open Files, create that folder, and then browse to that location to save the file there. This creates an extra and unnecessary step.
![Screenshot from 2021-09-02 11 29 33](https://user-images.githubusercontent.com/198493/131778384-cb499506-7b8d-4544-97de-9df5f0c03bac.png)

## Platform information
Latest version of elementary OS 6

**Comment by jeremypw** [comment]
This sounds like a duplicate of #1814.  Are you using a flatpak app? In that case, what you can do with the filechooser will depend on what permissions have been granted to the app.

**Comment by jonolumb** [comment]
> This sounds like a duplicate of #1814. Are you using a flatpak app? In that case, what you can do with the filechooser will depend on what permissions have been granted to the app.

This applies to Brave Browser, but I installed the browser using a .deb file, so it shouldn't be subject to flatpak permissions.

**Comment by jeremypw** [comment]
I can confirm this issue with Brave Browser (and also Gnome Web - which is a Flatpak) but FireFox does not suffer from it.  FireFox shows the unmodified Gtk FileChooser whereas Brave and Gnome Web show the modified chooser used by the portal suggesting they are using Gtk.FileChooserNative rather than using Gtk.FileChooser directly?

**Comment by jeremypw** [comment]
For downloads, it would be normal for these to automatically downloaded to "Downloads".  You can then use Files to move it wherever you want.  However, I am not sure whether folder creation needs to be inhibited when using the FIleChooserNative interface.

**Comment by jonolumb** [comment]
> For downloads, it would be normal for these to automatically downloaded to "Downloads". You can then use Files to move it wherever you want. However, I am not sure whether folder creation needs to be inhibited when using the FIleChooserNative interface.

I agree that automatically downloading to "Downloads" is good **default** behaviour for a browser. However, we all have different file workflows - in my work as a translator, I use the file chooser to create a new folder with the project deadline and client name as a prefix, and then download the translation package straight into that folder. Why do that in two apps when it can be (and previously always was) done in one.

Would be greatly appreciated if folder creation could somehow be re-enabled again. Thanks for your help on this.

**Comment by jonolumb** [comment]
It appears that this issue is now fixed. I can once again create new folders from FileChooser when downloading a file in Brave Browser. Thanks!
