### ISSUE TITLE
Ctrl+Click on a folder in sidebar doesn't open it in a new tab (worked like that in OS 5.1)

### ISSUE THREAD

**Issue by zappan** [elementary/files#1830]
## What Happened
Ctrl+click on a folder in the sidebar opens that folder in the same tab

## Expected Behavior
I expect Ctrl+click on a folder in the sidebar to open that folder in a new tab - it worked like that in elementary 5.x, It doesn't in 6.0

## Steps to Reproduce

1. open files
2. navigate to some folder
3. ctrl+click on any other folder in the sidebar - it opens in the same tab; I expect it to open in a new tab

## Platform Information
* elementary OS 6.0
* "Latest release"
* no special hardware, clean installation on a TigerLake Thinkpad laptop

**Comment by jeremypw** [comment]
Sounds like something that unintentionally got lost in the sidebar rewrite.
