### ISSUE TITLE
"Middle click paste" option doesn't work with text from files path bar

### ISSUE THREAD

**Issue by jsgadas** [elementary/files#1837]
## What Happened
Middle click paste doesn't work when the selected text is from the path bar of the file.

## Expected Behavior
The selected text from the path bar of files should be pasted if middle-click mouse is pressed.

## Steps to Reproduce
1. Go to system settings -> Mouse & Touchpad -> Clicking behaviour and activate the "Middle click paste" option
2. Go to files and select any text from the path bar
3. Use the middle click to paste the selected text, it fails

## Additional information
This feature works with any other app I had tested, including chrome, firefox, Inkscape, etc...

## Platform Information
![image](https://user-images.githubusercontent.com/38897885/133554181-935364d7-c7c7-4776-a3f3-8bf8f50505dd.png)

**Comment by jeremypw** [comment]
Middle-click does not seem to be a drop-in replacement for `<Ctrl>V`.  E.g. it works in Terminal but not in a Code document.  However the Files pathbar in edit mode should behave like an Entry and respond to middle-click (although it is a custom widget) . It does respond to `<Ctrl>V`.

**Comment by jsgadas** [comment]
hum, I see. I hadn't noticed that this small issue also affects Code and other apps, thanks the clarification. It's a little bit weird though. I can't use the middle click to paste text from Code to itself, but I am able to select the text from Code and paste with middle click on Firefox, for example. The same behavior happens with Geany. Interestingly, I'm not able to use the middle click to paste the text from the Files pathbar anywhere 😅.
