### ISSUE TITLE
CIFS share with noauto option in /etc/fstab appear twice

### ISSUE THREAD

**Issue by gnoumph** [elementary/files#1841]
## What Happened

I want to mount a CIFS share using `fstab` with `noauto` option, to prevent it to be mounted at startup.  
While not mounted, it appear once, but it appear twice when I mount it.  
With `auto` option, it appear once every time.

_/etc/fstab:_
```
//192.168.1.1/Partage                           /media/noauto   cifs    _netdev,users,noauto,users,credentials=/home/gaby/.smbcred      0       0
//192.168.1.1/Seedbox                           /media/auto     cifs    _netdev,users,auto,users,credentials=/home/gaby/.smbcred        0       0
```

_State at startup (OK):_
![image](https://user-images.githubusercontent.com/49097358/134479042-59af6215-f1ac-4c7e-8026-aee0d69a16ae.png)

_`noauto` is mounted:_
![image](https://user-images.githubusercontent.com/49097358/134479158-5cafda03-8a7d-4d50-b17e-7f294ac68661.png)

_`auto` and `noauto` are unmounted:_
![image](https://user-images.githubusercontent.com/49097358/134479231-4a1e3f5e-17e2-43f3-8618-31d7d54ca5b1.png)

_`auto` and `noauto` are remounted:_
![image](https://user-images.githubusercontent.com/49097358/134479311-a799eae7-8349-4503-8a6d-3b15a302cc86.png)

Of course, I mount and unmount from file manager.  
Note that I can't mount or unmount from the second `noauto`, nothing happens if I click on it.  
I have to install `cifs-utils` to be able to use samba share (installed with `apt install cifs-utils`).

## Expected Behavior

Mounted share with `noauto` option appear once every time.

## Steps to Reproduce

0. Install `cifs-utils`.
```
sudo apt install cifs-utils
```

1. Add samba share in your `/etc/fstab` with `noauto` option.
```
//192.168.1.1/Partage /media/noauto cifs _netdev,users,noauto,users,credentials=/home/gaby/.smbcred 0 0
```

2. Restart computer.
3. Open file manager.
4. Click on your share.
5. Share appear now twice.

## Platform Information

ElementaryOS 6 Odin with 5.11.0-36-generic kernel.
Files 6.0.2

**Comment by jeremypw** [comment]
Handling of mounts is being reworked in #1752.  Hopefully this will avoid duplicate entries.  If you are able to build and test that branch that would be helpful.

**Comment by gnoumph** [comment]
> Handling of mounts is being reworked in #1752. Hopefully this will avoid duplicate entries. If you are able to build and test that branch that would be helpful.

Just tried this branch, everything is fine! I'll just wait next update.  
Thanks!

Issue is close.

**Comment by jeremypw** [comment]
@gnoumph Thanks for testing!
