### ISSUE TITLE
Audio file icons disappear when scrolling or changing view.

### ISSUE THREAD

**Issue by marco4mp** [elementary/files#1842]
## What Happened

Hi! I found this bug. Audio file icons disappear when scrolling or changing view (I tried with mp3, ogg, and wav).
Documents, videos and images icons work ok.

## Expected Behavior

Icons should not disappear.

## Steps to Reproduce

https://user-images.githubusercontent.com/52709674/134596433-d0b3b9e5-b63b-44c8-a8fa-d1f3e9f509f5.mp4

### Logs

--

## Platform Information

elementary OS 6

**Comment by jeremypw** [comment]
Strange! Files does not take into account file type when loading thumbnails afaict so it is not clear why it should only affect audio files.  I notice that pressing the reload button causes the thumbnails to appear.

**Comment by marco4mp** [comment]
Hi! @jeremypw. I read Dan's comment on #1843 . So I searched my external drive for more audio files. And yep, I have some music albums where the audio files have the cover thumbnail embedded (those icons work fine). 

https://user-images.githubusercontent.com/52709674/134780603-2c354672-5744-407b-8e2f-96dabd76a101.mp4

**Comment by jeremypw** [comment]
@marco4mp Thanks for the info! I am not sure I have audio files with album art on my dev laptop atm - I'll have to get some and then improve the PR.
