### ISSUE TITLE
Files can't turn off external hard disk

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#185]
https://bugs.launchpad.net/pantheon-files/+bug/1611022

**Comment by phocean** [comment]
I was going to report this.

Ejecting / unmounting a disk should spin it down, as it is the case with gnome-files, gnome-disk and other DE/utilities.

Unplugging a disk that is still spinning it not healthy for its lifespan.

**Comment by jeremypw** [comment]
I am looking at the unmount/eject code at the moment in relation to another issue so I'll try to revive the fix that started a long time ago and never got merged.
