### ISSUE TITLE
Separation line practically invisible in dark mode

### ISSUE THREAD

**Issue by kdwk** [elementary/files#1856]
### What Happened?

![Screenshot from 2021-10-06 18 33 18](https://user-images.githubusercontent.com/39268094/136187334-e6439c70-3954-4c63-9424-6a7e0c654874.png)

When dragging and dropping files/ folder onto the sidebar as a bookmark, with dark mode on, it is extremely difficult to make out the separation line, as it is a dark line on dark background.

### Steps to Reproduce

1. Drag a folder and hover cursor over sidebar
2. Wait until a space is created at the point of insertion
3. Try to discern a black separation line from a reasonable viewing distance

### Expected Behavior

The separation line should be made a light colour, like @SILVER_100 (#fafafa)

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I am going to close this as elementary/stylesheet#1093 addresses this issue.
