### ISSUE TITLE
Tests failing against Ubuntu "Jammy" on Launchpad 

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/files#1862]
### What Happened?

When trying to build Files against Ubuntu 22.04 (the currently unreleased next LTS) in launchpad, the `/MarlinIconInfo/goffile_icon_update` test fails with:

```
ERROR:libcore/tests/MarlinIconInfoTests/MarlinIconInfoTests.p/MarlinIconInfoTests.c:126:goffile_icon_update_test: assertion failed: (file.pix != null)
```

The full buildlog can be found here: https://launchpadlibrarian.net/564001870/buildlog_ubuntu-jammy-amd64.pantheon-files_6.0.3+r4958+pkg104~daily~ubuntu21.10.1_BUILDING.txt.gz

I am yet to try and run these tests locally to see if this is a Launchpad specific issue, but these tests pass for focal, so this could be indicative of an actual issue with the newer library versions.

### Steps to Reproduce

Build files against `jammy` in launchpad

### Expected Behavior

Tests pass and resulting build gets uploaded to the daily PPA like it does for `focal`

### OS Version

Other Linux

### Software Version

Compiled from git

**Comment by davidmhewitt** [comment]
This does not happen when cloning from git and building and testing with meson on a `jammy` system.

**Comment by danrabbit** [comment]
Looks like the Jammy recipe succeeded :) https://code.launchpad.net/~elementary-os/+recipe/files-daily
