### ISSUE TITLE
Some text is overwriting "open with"

### ISSUE THREAD

**Issue by alchehabii** [elementary/files#188]
mp3 document properties shows some text positioned above "open with" text.

![screenshot from 2017-10-27 21 34 29](https://user-images.githubusercontent.com/10380737/32122499-d159b02e-bb60-11e7-8797-3129ad41b7a0.png)

**Comment by danrabbit** [comment]
It looks like the device usage header and the open with label are being packed into the same grid quadrant 😬

**Comment by jeremypw** [comment]
Thanks for the report, but this is a duplicate of #141.

**Comment by jeremypw** [comment]
FIxed by #189
