### ISSUE TITLE
Add XDG dirs as .desktop actions

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1888]
### Problem

I find myself hitting Super+Space and starting to type "Downloads" to open the downloads folder, which obviously doesn't do anything today.

### Proposal

We could add the standard XDG directories to the .desktop actions to have these in a quicklist and in search in the Applications Menu.

A potential disconnect I see is that these would _not_ mirror the user's added bookmarks in the sidebar, as it would be static. However, I think making it quicker to open the standard XDG dirs would still be a net benefit.

### Prior Art (Optional)

I believe we used to add bookmarks to the dynamic quicklist (e.g. using the Unity API), but that only worked when the app was open.

**Comment by jhaygood86** [comment]
I wonder if building a bookmarks provider plugin to synapse would be worth it?

The bookmark file format is really simple, just a list of File URIs, and it's not in a Files specific config directory.

**Comment by cassidyjames** [comment]
@jhaygood86 that could be possible, but adding to the .desktop actions also gets us a quicklist in the dock which seems handy (and more closely matches what we used to have with the Unity API).

**Comment by jhaygood86** [comment]
They likely aren't mutually exclusive either. The bookmark search would just have to be aware of the desktop actions.

**Comment by cassidyjames** [comment]
@jhaygood86 that's fair. :smile: It might be a little weird to not get your added bookmarks in the dock quicklist while getting them in the Applications Menu, but it's no worse than what we have today.

We'll also want to keep in mind if/how we want to handle quicklists like .desktop actions when we rewrite the dock, as that's something we'll have to do for Wayland. I do want to continue leaning on the desktop actions spec since it's an open XDG standard, and I also think a dynamic shortcut API (like exists on Android and I believe iOS) is something other desktops will want---but that's probably longer-term thinking.

**Comment by jhaygood86** [comment]
@cassidyjames Look at https://github.com/elementary/applications-menu/pull/514 for the bookmarks in applications menu

**Comment by jeremypw** [comment]
The advantages of @jhaygood86 's approach is that it should work with other filemanagers and does not unnecessarily clutter the dock menu.

**Comment by cassidyjames** [comment]
@jeremypw I don't think having quick access to common folders is unnecessary clutter; I have been using this all the time since prototyping it. 😅 If @jhaygood86’s branch works in tandem with #1889 I am not opposed, though.

**Comment by jeremypw** [comment]
@cassidyjames My argument is that it is the same number of clicks (and both of them primary) to just open files and then click on the sidebar.

**Comment by jeremypw** [comment]
Pretty much the only reason I have to secondary-click on the dock icon is to open a window as Administrator and this PR moves that option further from the mouse.

**Comment by danrabbit** [comment]
Commented on the PR but wanted to comment here too. I think the applications menu plugin is the way to go and Jeremy makes a good point about it not actually being any faster than opening files and clicking the sidebar.

I think I agree that this kind of clutters up the menu where there are actual unique actions and it seems to me that unless we do some kind of workaround in apps menu to hide these actions, it would create duplicate entries there with a bookmarks plugin

So overall I'm kinda more and more -1 and feel like this is probably out of scope

**Comment by danirabbit** [comment]
Gonna close this since there hasn't been any more conversation in about a year and it seems like the bookmarks plugin solved this case for the applications menu
