### ISSUE TITLE
Open file with arbitrary binary

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/files#1891]
### Problem

I want to open a PNG with an editor I use but it is not listed in the recommended or other applications.

![image](https://user-images.githubusercontent.com/13716824/141526466-33b5ce10-172c-4bef-9051-7ff759842479.png)

### Proposal

At the bottom after all "Other applications" give an option to open with "Something else". This would then open a dialogue to chose that binary. I'm aware that there's an app chooser portal (at least in progress) so maybe this should be added to that instead?

### Prior Art (Optional)

Windows offers a "Choose other app" option that then has an option to browse for any binary.
![image](https://user-images.githubusercontent.com/13716824/141526705-b2b80c09-d7c1-498f-b8c2-5a5e5f1bce1e.png)
![image](https://user-images.githubusercontent.com/13716824/141526674-fcd75012-b8ad-4136-9650-b4cf8ef5734b.png)

On Windows once something has been manually selected once I think it gets added to this list.

**Comment by danrabbit** [comment]
If it's not listed under "other applications", it likely doesn't have a desktop file which means it doesn't exist as an app as far as the system is concerned. This seems like an app issue and not an issue with the app chooser

**Comment by ChildishGiant** [comment]
I know that's one way to solve it but I'm suggesting is that files could be opened by binaries without desktop files.

**Comment by jeremypw** [comment]
Might be worth mentioning the "Pin It" app in the Appcenter.  Looks like this app makes it very easy to create an adhoc desktop file for an arbitrary executable.  

Fixing this in Files would be be fairly involved - especially adding the arbitrary executable to the list of available apps so is unlikely to be addressed anytime soon.

**Comment by ChildishGiant** [comment]
Pin it along with Turtle and Desktopius provide a good solution for a vast majority of users so I'll close the issue :smile:
