### ISSUE TITLE
If the arrow button is pressed and the window is dragged, the button will remain shaded.

### ISSUE THREAD

**Issue by marco4mp** [elementary/files#1898]
### What Happened?

Hi! I found this little bug. 
If I press the arrow button and at the same time drag the window, the button will remain shaded until it is pressed again.

### Steps to Reproduce

https://user-images.githubusercontent.com/52709674/142517993-42d2d394-b853-4559-b81e-c527b480bd24.mp4

### Expected Behavior

The button should not remain shaded after being pressed.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Probably because it does not receive the button release event under these circumstances.  Perhaps we should activate on release not on press so that it does not get activated during a drag.
