### ISSUE TITLE
Selecting multiple files continuously by pressing Ctrl no longer works

### ISSUE THREAD

**Issue by marco4mp** [elementary/files#1906]
### What Happened?

Selecting multiple files continuously by pressing Ctrl no longer works.

### Steps to Reproduce

1. Select a group of files, 
2. Then press ctrl while selecting another group of files.

I perform the same action on both, Dolphin and Files.

https://user-images.githubusercontent.com/52709674/143474496-bab1470b-e858-4889-a122-db1983f405c9.mp4

### Expected Behavior

Being able to select all files while pressing Ctrl.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Only affects selection by rubberbanding.
