### ISSUE TITLE
Change default shortcut to switch tabs

### ISSUE THREAD

**Issue by giacomocerquone** [elementary/files#191]
Hi everyone, I'm writing here in the issues of the project's repo not to find a way to change shortcut in the way I prefer, but to ask you to change the default one to switch tabs, because I find ctrl+pageup/pagedown an inconsistency in the ecosystem.

I think the choices are two:
- Define them like the ones used in the terminal: `ctrl+shift+arrow left/arrow-right` to move between tabs
- Define them like the ones of a lot of other apps (Chrome, firefox etc.): `ctrl+tab, ctrl+shift+tab`

**Comment by jeremypw** [comment]
The shortcuts used in elementaryos are currently under review with an a view to improving consistency issues like this.

**Comment by jeremypw** [comment]
It would nice to have consistency between all apps using notebooks but there are some issues.

```ctrl+shift+arrow left/arrow-right``` should work in Files (but not in Code where it is used by the text editor for word level selection).

```ctrl+tab, ctrl+shift+tab``` is used for shifting focus between widgets in general so has accessibility implications.

**Comment by giacomocerquone** [comment]
Yeah but actually I use everywhere `ctrl+tab, ctrl+shift+tab` with no problems (chrome, firefox, atom, robo3t and plenty of other apps as I've already said)

**Comment by cassidyjames** [comment]
`Ctrl`+`Tab` and `Shift`+`Ctrl`+`Tab` is the widely held convention, though the GNOME convention appears to be `Ctrl`+`PageUp`/`PageDn` which is… kind of awful. :stuck_out_tongue: 

Does it make sense for Terminal to be different to avoid other key conflicts or something? I don't think it's the best example of an app to copy keyboard-shortcut-wise.

Also, is this something where the defaults could be handled by Granite, or does each app have to define its shortcuts?

**Comment by jeremypw** [comment]
Granite.DynamicNotebook provides some default shortcuts, including  ``` Ctrl+PageUp/PageDn ``` for next/previous tab.

**Comment by giacomocerquone** [comment]
Honestly I've to be a stuntman to press `ctrl+pageup/pagedn` on my laptop

**Comment by jeremypw** [comment]
As far as I can tell, using `Ctrl+Tab` and `Shift+Ctrl+Tab` would not interfere with normal operation for Files, Code and Terminal provided it is accepted that this would no longer be able to used to move between focusable widgets, which might affect some users who are only able (or prefer) to use only the keyboard.

**Comment by giacomocerquone** [comment]
Actually I'm not quite understanding the issue...
Shouldn't the focus be moved with `tab` key only? I think I'm not getting what "move between focusable widgets" means.

**Comment by jeremypw** [comment]
Maybe I am wrong, but `tab` will not work for all widgets (e.g. text entries) but then again `Ctrl+Tab` may not either.  If there are no accessibility issues or other serious conflicts then it may be the best choice for tab switching.

**Comment by giacomocerquone** [comment]
What's missing here in order to let this go forward in production? Just asking, thank you very much for your great work!

**Comment by jeremypw** [comment]
This branch is awaiting final approval from the UX team.
