### ISSUE TITLE
Possible to launch multiple filechooser dialogs

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#1921]
### What Happened?

It is possible to launch multiple simultaneous filechooser dialogs e.g. by pressing the "Save As" button in Code several times.

### Steps to Reproduce

Open Code
Open a document
Press the "Save As" button
While the filechooser dialog is open, press the "Save As" button again.

### Expected Behavior

It should not be possible to launch another filechooser dialog with the same app while an existing one is in progress.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by Marukesu** [comment]
I believe that the frontend (xdg-desktop-portal) should be the one doing this check, not the backend, however, we can do that here, but, instead of one dialog per app, this should be one dialog per parent_handler, so we can still show two dialogs to two windows of the same app.
