### ISSUE TITLE
FileChooserNative: Full access possible regardless of Flatpak permission

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#1923]
### What Happened?

Using FileChooserNative in the app code allows the app to access entire of the disk even if the app is not allowed in Flatpak permission (that can be set in System Settings).

### Steps to Reproduce

To make things clarify, I created [a test Flatpak app](https://github.com/ryonakano/junk/tree/file-chooser-test) that only has two buttons to open Gtk.FileChooserDialog and Gtk.FileChooserNative:

![Screenshot](https://user-images.githubusercontent.com/26003928/144144057-3943b6cc-4953-429d-9ae9-1b07d2be597f.png)

1. Clone https://github.com/ryonakano/junk.git and checkout to `file-chooser-test` branch
2. Build the app using `flatpak-builder build-dir --user --install --force-clean com.github.ryonakano.file-chooser-test.yml`
3. Run the app using `flatpak run com.github.ryonakano.file-chooser-test`
4. Click "Open Gtk.FileChooserDialog". You can see the file chooser only shows Documents folder which only permitted in the YAML file:
![Screenshot from 2021-12-01 08-30-02](https://user-images.githubusercontent.com/26003928/144144581-0564f671-76cd-4784-93d3-8d9cc56cb77a.png)

5. Close the Gtk.FileChooserDialog and then click "Open Gtk.FileChooserNative". You'll see the file chooser shows and can access all places in your disk:
![Screenshot from 2021-12-01 08-29-17](https://user-images.githubusercontent.com/26003928/144144529-c5ff9727-6b31-45be-b02b-cc9845f497fe.png)

### Expected Behavior

Like Gtk.FileChooserDialog, Gtk.FileChooserNative should also follow access permission defined in the YAML file or in the Application Plug of System Settings.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

- Quad-Core Intel® Core™ i5-8250U CPU @ 1.60GHz
- Intel® UHD Graphics 620 (Kabylake GT2)
- 3.7 GiB memory
- 121.2 GB storage (NVMe SSD)

**Comment by danrabbit** [comment]
Unless I'm misunderstanding, this is the intended function of the filechooser portal. The portal runs as a privileged process which has full file system access and it grants access to the sandbox only to the selection made in it

**Comment by davidmhewitt** [comment]
Uh... this is exactly how things are supposed to work unless I misunderstand your report.

The non-native filechooser isn't using a portal, so it can only see things that the sandboxed application has access to.

The native filechooser goes via the portal which is running as a separate process (so the app cannot see these files, the portal process is showing this dialog). When a file is selected, the sandboxed application is then given access to that file (and only that file), because the user has approved it by choosing it.

**Comment by ryonakano** [comment]
Thank you for your both information, I didn't know about this is a expected behavior. I actually found this "issue" when I tried to replace Gtk.FileChooserDialog with Gtk.FileChooserNative in my app, and worried about why the native one can see all files. Glad to know how these things works, thank you again! Closing as Invalid.

**Comment by jeremypw** [comment]
I find it confusing too!  Saving a file is a different matter - you can appear to save a file in a certain location but if the flatpak does not have permission then it gets saved into the sandbox not where it appears to have been saved.  Not sure if there is a way to warn the user of this.

**Comment by Marukesu** [comment]
> if the flatpak does not have permission then it gets saved into the sandbox not where it appears to have been saved.

Just to make this clear, the portal only return the real path if the flatpak application has access to it (with `--filesystem`), otherwise the file/folder is exported to the document portal and that is the path returned.

applications should only need to add the `--filesystem` option if they need to access an folder without user interaction, like how epiphany has `--filesystem=xdg-download` for saving downloaded files and videos has `--filesystem=xdg-cache/thumbnails` for querying the thumbnails for the videos in library.

**Comment by jeremypw** [comment]
Even if limited filesystem access is granted, I don't think the "SaveAs" filechooser portal prevents a user navigating to a location where they do not have write access though does it? And does not give an error if a file is saved there (if the native user has write access).  As you say, it just actually saves it in somewhere like `/run/user/1000/doc/<id>/<filename>`  If you then try to reopen it with the filechooser portal, it does not show up where you thought it had been saved.

**Comment by Marukesu** [comment]
> Even if limited filesystem access is granted, I don't think the "SaveAs" filechooser portal prevents a user navigating to a location where they do not have write access though does it?

No, they don't it existence is to allow access to files outside of what is exposed to the sandbox.

> And does not give an error if a file is saved there (if the native user has write access). As you say, it just actually saves it in somewhere like `/run/user/1000/doc/<id>/<filename>` If you then try to reopen it with the filechooser portal, it does not show up where you thought it had been saved.

i did a check using code flatpak with filesystem access restricted to `--filesystem=~/projects` and it did saved the file in the home as requested and exported it back to the documents portal.

however, they thrown some warnings after the "SaveAs" dialog:
```
** (io.elementary.code:2): WARNING **: 12:20:15.859: Document.vala:898: query_info failed, but filename appears to be correct, allowing as new file

** (io.elementary.code:2): WARNING **: 12:20:15.860: Document.vala:843: Cannot create backup copy for file "new-test.txt": Erro ao obter informação para o arquivo “/run/user/1000/doc/d14091c5/new-test.txt”: No such file or directory
```

thoose don't happen when opening the file again.

**Comment by Marukesu** [comment]
one observation is, i'm using the xdg-desktop-portal and xdg-document-portal compiled from master. and `apt list xdg-desktop-portal -a` gives the `1.6.0` version (the more recent release is `1.10.1`).

**Comment by jeremypw** [comment]
OK, thanks. I am just using what comes with elementary.  I guess we can look forward to the Flatpak experience becoming smoother in the future.
