### ISSUE TITLE
 The trash icon does not change its state (empty/full) when deleting files.

### ISSUE THREAD

**Issue by marco4mp** [elementary/files#1924]
### What Happened?

With the latest Files update 6.1.0, the trash icon does not change its state (empty/full) when deleting files.
Btw, manual refresh makes the icon change.

### Steps to Reproduce

1. Delete a file
2. Look at the trash icon. It doesn't change.

https://user-images.githubusercontent.com/52709674/144259624-363de7a1-d431-44b7-832e-0b5370ffb84a.mp4

### Expected Behavior

The icon should change its state from empty to full.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Sounds like a regression - there was a similar issue fixed not long ago.
