### ISSUE TITLE
Speech bubbles for Git status in list view

### ISSUE THREAD

**Issue by lukors** [elementary/files#1925]
### What Happened?

This is essentially an issue for https://github.com/elementary/files/issues/1105#issuecomment-553859437.

- Files uses "chat availability" icons to indicate the Git status of files.
- The list view in Files use the smallest versions of the "chat availability" icons.
- The smallest versions of the "chat availability" icons are speech bubbles.

This means the list view uses speech bubbles to indicate the Git status of files. There is no tool tip when hovering the icon either, causing further confusion.

Here are some effort towards fixing this issue:
https://github.com/elementary/icons/issues/827
https://github.com/elementary/icons/pull/988

### Steps to Reproduce

1. Go to a folder with a Git repo
2. Create a file
3. Click "View as List" (Ctrl + 2) or "View in Columns" (Ctrl + 3)

### Expected Behavior

1. I expect a more fitting icon.
2. I expect Files to tell me what the icon means when I hover my mouse over it.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Thanks for the report. This is essentially two issues that can be fixed separately.  The issue about the appearance of the icon belongs in the icon theme repository.  The issue about tooltips can be fixed here.

**Comment by jeremypw** [comment]
Providing individual tooltips for the emblems is more awkward than it sounds as as they are not widgets but drawn by a cell renderer.

**Comment by danrabbit** [comment]
We added specific icon names for git emblems a while back, so this is probably a bitesize fix: https://github.com/elementary/icons/pull/1025
