### ISSUE TITLE
Trash icon not reflecting trash status

### ISSUE THREAD

**Issue by sixpounder** [elementary/files#1932]
### What Happened?

When an event that would change the trash status from empty to non-empty and viceversa - i.e. deleting a file while the trash is empty or emptying the trash - doesn't cause the trash icon on the sidebar to correctly reflect its status.

The correct status update is applied on subsequent app restarts.

### Steps to Reproduce

1. Start from and empty trash
2. Delete a file
3. The trash icon is still _user-trash_ (should be _user-trash-full_

Or:

1. Start from a trash with items in it
2. Empty the trash
3. The trash icon is still _user-trash-full_ (should be _user-trash_

### Expected Behavior

Trash status icon should update immediately after one of the two events described above takes place

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment]
This was just fixed in #1927 :)

**Comment by jeremypw** [comment]
Thanks for the report!  This has just been fixed by 872047db6c85efc6f3edb5472daa84c3ca80ea63 so you should get it in due course depending on whether you are

**Comment by sixpounder** [comment]
I was dumb enough to only look into open issues and not closed one.

Thank you Danielle!
