### ISSUE TITLE
Mounted external drives are appearing twice at the left pane of the Files application.

### ISSUE THREAD

**Issue by TryingHardNovice** [elementary/files#1942]
### What Happened?

Whenever I mount an external drive in the Files application (file manager/explorer). This drive appears twice at the left pane. When I close Files and reopen this, this disappears.

### Steps to Reproduce

1. Boot the OS.
2. Open the Files app.
3. Insert an external drive (a flash drive or a hard drive).
4. The mounted drive's icon appears twice at the left pane instead of only once.

### Expected Behavior

After opening the Files app and inserting any external drives, it should only show one copy of the drive at the left.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
This issue should have been resolved in the latest release (see commit e376918e1ff2c19b41935461ac857f93a29df10b).  I cannot confirm this issue on my system. Please could you post a screenshot showing the duplicate entries?  There should be one entry per volume/partition on the external drive, each of which will be followed by the name of the drive in brackets.

**Comment by jeremypw** [comment]
Closing as not confirmed to occur in latest release. Please re-open if you disagree.
