### ISSUE TITLE
Selecting files with shift + arrow keys has imprecise behavior

### ISSUE THREAD

**Issue by marco4mp** [elementary/files#1948]
### What Happened?

Selecting files with shift + arrow keys has imprecise behavior

### Steps to Reproduce

1. Select a file by clicking on it.
2. Press "shift" + "left or right" keys.
Result: Sometimes it does nothing. In others it selects more than one file at a time (sometimes it does it in reverse order).

### Expected Behavior

It should work fine.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Does this happen with a single uni-directional select or only when the direction changes?  What happens when the direction changes depends on where the cursor currently is.

**Comment by jeremypw** [comment]
I cannot confirm that it sometimes does nothing.  You can get "unexpected" effects by selecting a file then moving the cursor without altering the selection by holding down the `<Control>` key and doing a `<Shift>Arrow` select.

**Comment by marco4mp** [comment]
This is what happens when I do a single shift + arrow.

https://user-images.githubusercontent.com/52709674/146648132-bfd8e02b-586a-497b-86eb-a2ae5defa72e.mp4

**Comment by jeremypw** [comment]
OK, thanks - it looks like for you the cursor is not moving away from its current (unselected) location when you select a file with the helper.  So the a `<Shift>Arrow` select is then filling in the items between the previous cursor location and where you moved it to.  Its not happening for me but I am running an unreleased version of Files - I'll install the latest release and see whether I can confirm.

**Comment by marco4mp** [comment]
Okay, I just realized that this also happens just by clicking on a file and then pressing an arrow key (with the intention of changing the selection to the next file). Result: Another very distant file is selected, not the contiguous one.

**Comment by jeremypw** [comment]
OK, I've now identified that the problem is selecting **not with the helper** (e.g. by clicking on the icon of a non-folder or by rubberbanding) and without any previous selection.  Strangely if you select with the helper or by moving the cursor with the arrow keys then the issue does not happen so that is a temporary work around.

I'll fix it as soon as I can.

Thanks for the report!

**Comment by danrabbit** [comment]
Now that clicking labels activates, I'm not sure this can be reproduced in this manner. What I have noticed however is that rubberband selecting and then using arrow keys I can reproduce this issue.

So perhaps a more robust/general fix would be to make sure the focus position is set to the last item in the selection when a selection is created

**Comment by jeremypw** [comment]
@danrabbit  
> So perhaps a more robust/general fix would be to make sure the focus position is set to the last item in the selection when a selection is created

What do you mean by "last item"?  Do you mean the item that was most recently selected (which is what #1951 does) or the last item in the current sort order (which might lead to unexpected results).
