### ISSUE TITLE
Ctrl + A after hitting rename does not select the text

### ISSUE THREAD

**Issue by rakshit087** [elementary/files#1958]
### What Happened?

Ctrl + A after hitting rename does not select the text, but it selects all the folders and files in the directory. 

### Steps to Reproduce

1. Open File Manager.
2. Open any folder.
3. Try to rename a file. (Either by F2 or by Right Click > Rename)
4. Press Ctrl + A.

### Expected Behavior

All the text in the rename should get selected instead of all the folders.
 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Looks like a regression after changing "select all items" to an action so the associated accelerator gets intercepted before reaching the entry.  The text should already be selected (except for the extension which would not usually be changed) on starting renaming so not sure really need a select all action within the entry.  But the action should at least be disabled while renaming is on going and if possible passed on to the entry.

**Comment by rakshit087** [comment]
Yes, it is already selected, but I accidently clicked on so it got unselected so then I pressed ctrl+a. xD

**Comment by eliocamp** [comment]
> The text should already be selected (except for the extension which would not usually be changed) on starting renaming so not sure really need a select all action within the entry. 

There are several use-cases for select all in this case. 

1. You want to change the name and extension.
2. Using F2 -> Ctrl + A -> Ctrl + V to rename the file to a text in the clipboard (that includes extension)
3. Using F2 -> Ctrol + A -> Ctrl + C to copy the whole file name, including the extension.
