### ISSUE TITLE
Double click in ListView rename mode does not select word but cancels renaming

### ISSUE THREAD

**Issue by undergroundwires** [elementary/files#1959]
### What Happened?

Exits from rename mode

### Steps to Reproduce

1. F2, or right click to rename a file/folder
2. In the name double click a word

### Expected Behavior

Word to be highlighted/selected

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I cannot confirm this - I find double clicking on an unselected word in the edit box does select it.  I tried several different delimiters in UK English locale and keyboard.   Please indicate what locale/input method/delimiters this issue occurs with.

**Comment by undergroundwires** [comment]
It wouldn't be tricky to reproduce, pretty straightforward for me. It happens at any point of time e.g. at initial state after entering rename mode, or after adding characters inside rename mode. It completely exists from rename mode.

My settings are pretty much Swedish keyboard + OS defaults:
![image](https://user-images.githubusercontent.com/15555035/147503597-fa5ef373-15a1-40c7-8ee5-0f6b9880039d.png)

**Comment by jeremypw** [comment]
Hm, tried switching the layout to Swedish but still no luck. Could you please confirm that the issue does not occur in e.g. the "Type to test your layout" entry or in Code and that when you double click in FIles, the cursor is in edit (I-beam) form, not the arrow form.  You could try launching FIles from the terminal (`io.elementary.files`) and noting any message produced when the edit mode exits.  Also if you actually change the name and then double click does the name revert to the original when edit mode exits or is is changed?

**Comment by andreaswestrell** [comment]
The only thing I find different between the input two fields is that; "Type to test your keyboard" allows a single word and then the whole field to be selected when double clicked. (While rename in Files does not)

**Comment by jeremypw** [comment]
I have now found that the issue you describe occurs with list view but not with icon view (they use different widgets - the icon view uses a Gtk.TextView whereas the list view uses a Gtk.Entry).  Not immediately clear why they should behave differently but I'll look into it.   I also find that the second double click in icon view selects only the whole line of the TextView (which is the default behaviour of a TextView). That would have to be raised as a separate issue though if it is a problem.  You should be able to select the whole filename with `<Ctrl>A` (once PR #1962 has been merged).

**Comment by undergroundwires** [comment]
Thank you for the quick fix ❤️ Happy to be able to contribute to the OS and awesome to see how fast your reaction was. This is a privilege that I never experienced in any other OS I used.
