### ISSUE TITLE
Sort by size has no effect on folders.

### ISSUE THREAD

**Issue by marco4mp** [elementary/files#1971]
### What Happened?

When I sort by size this has no effect on folders.

### Steps to Reproduce

![Screenshot from 2022-01-03 12 27 46](https://user-images.githubusercontent.com/52709674/147949478-7aa22373-9fca-4fca-bcdd-97917ec00dfb.png)

### Expected Behavior

Files should be able to sort folders by size, just like other file managers.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
There is a note in the code to provide sorting on the the number of items in the folder in future, but at the moment, because the actual diskspace taken by the folder item itself is always 4K, they fallback to sorting by name.
