### ISSUE TITLE
Dragging to reorder bookmarks causes Files to crash and some bookmarks to be removed from the list.

### ISSUE THREAD

**Issue by marco4mp** [elementary/files#1975]
### What Happened?

Hi!

Dragging to reorder bookmarks causes Files to crash and some bookmarks to be removed from the list.

### Steps to Reproduce

https://user-images.githubusercontent.com/52709674/148648907-9da48dc0-5b11-4162-a4e9-5f628c98242f.mp4

### Expected Behavior

Files shouldn't crash and bookmarks shouldn't be removed when doing this.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I have experienced this once recently but as I was working on a development branch and couldn't reproduce it I did not report.  Ideally need to find a way of reproducing or run Files under gdb for a while to try and capture a backtrace.  Maybe a regression due to #1848?

**Comment by jeremypw** [comment]
OK, seems like to reproduce you need to drag/move the same bookmark twice in a row.  I have found the fix and will submit a PR.
