### ISSUE TITLE
FileChooser not following dark theme

### ISSUE THREAD

**Issue by joeljose350** [elementary/files#1984]
### What Happened?

The FileChooser always uses a light theme even if the system is set to use the dark theme.

![Screenshot from 2022-01-14 03 30 11](https://user-images.githubusercontent.com/53969297/149455711-0812316b-a62c-4c76-88be-2e10209de622.png)

### Steps to Reproduce

1. Set system to dark mode in Settings.
2. Open a file within an app to show the FileChooser.

### Expected Behavior

The FileChooser should follow the system theme.

### OS Version

6.1 (Jólnir)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment]
The file chooser in this screenshot is a widget inside VS Code, not the native system file chooser. So this is an issue with VS Code. There's nothing we can do in Files to resolve this, since it's not using the filechooser portal

**Comment by joeljose350** [comment]
I tested this problem in Pop!_OS 21.10 set to use the dark theme and VS Code did open the FileChooser in dark mode.

![Screenshot from 2022-01-16 03-13-19](https://user-images.githubusercontent.com/53969297/149638696-998be301-62a4-4d33-96fe-89d3ec8deb5c.png)

**Comment by danrabbit** [comment]
Pop uses an unsupported hack to force the dark stylesheet on all apps, so it's not really relevant here
