### ISSUE TITLE
FileChooser: highlight accept action

### ISSUE THREAD

**Issue by mcclurgm** [elementary/files#1990]
### Problem

Currently, there is no hierarchy to the buttons in the file chooser. I believe that the "accept" button (which can take the form of `Open`, `Save`, or others) should be highlighted. It is the primary action of the window, and according to the HIG, should be highlighted. 

Further advantages: This would also make the dialog easier to parse, since the expected action to be performed is visually prominent. Also, since we use the Enter key as a mnemonic for the accept button, it should be given a visual indication.

Current state:
![non-highlighted-save](https://user-images.githubusercontent.com/29022469/150658434-0bcbc57b-e01b-4739-9663-f907c752923f.png)

### Proposal

Add the `suggested-action` style class to the accept button.

![highlighted-save](https://user-images.githubusercontent.com/29022469/150658441-8f878b4b-f8cd-4426-a392-7fb20cd429e4.png)

If this is something you want, I will happily submit a quick PR. I just wanted to gauge whether this is desired by the design team beforehand.

**Comment by jeremypw** [comment]
I agree the action of the "Enter" key should be highlighted.
