### ISSUE TITLE
Visual reordering when opening large folders in list mode

### ISSUE THREAD

**Issue by peteruithoven** [elementary/files#1996]
### What Happened?

There might be some overlap with the following issue but my symptom seems a bit different. 
- https://github.com/elementary/files/issues/1939
- https://github.com/elementary/files/issues/1794

I see Files visually rearranging files in the list or column mode. It does not seem to matter whether I sort files on name or modified. 
In general it seems to take many times longer to open folders in Files than in the file chooser. 

## List
![Screen record from 2022-01-25 22 52 19 list mode](https://user-images.githubusercontent.com/523210/151066365-01c132b6-cd4c-43e0-a53f-364e013fc787.gif)

## Columns
![Screen record from 2022-01-25 22 55 10 columns](https://user-images.githubusercontent.com/523210/151066356-b3c4f748-82c2-4f6f-8a6c-43f80e6f9c88.gif)

## Grid
In grid mode it also takes long, but no visual re-ordering
![Screen record from 2022-01-25 22 54 01 grid](https://user-images.githubusercontent.com/523210/151066363-b027b462-d609-4a58-a7b2-039c0ce2e538.gif)

## Native file chooser
Also notice how opening the same folder in the native file chooser takes no time at all
![Screen record from 2022-01-25 22 59 21 file chooser](https://user-images.githubusercontent.com/523210/151066867-c4eae805-970d-43c5-a198-4c3387b395fc.gif)

### Steps to Reproduce

1. Open Files
2. Go to a folder with lot's of files

### Expected Behavior

It takes a bit longer, but not 6 seconds while seeing files being re-arranged. 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

OS: elementary OS 6.1 Jólnir x86_64 
Host: XPS 15 9550 
Kernel: 5.13.0-27-generic 
Uptime: 5 hours, 9 mins 
Packages: 2099 (dpkg), 90 (flatpak) 
Shell: bash 5.0.17 
Resolution: 3840x2160, 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Theme: io.elementary.stylesheet.blueberry [GTK3] 
Icons: elementary [GTK3] 
Terminal: io.elementary.t 
CPU: Intel i7-6700HQ (8) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 960M 
GPU: Intel HD Graphics 530 
Memory: 15949MiB / 31924MiB

**Comment by jeremypw** [comment]
I have done some work on improving load speed relating issues (see #1953) although that needs some more work in fixing failing unit tests (it should still be usable).  I'll try and get that in a reviewable state.

**Comment by jeremypw** [comment]
The above mentioned PR loads all the files *before* sorting so should fix this issue.

**Comment by peteruithoven** [comment]
Ow whow, that PR seems great! 
I'm happy to close this issue or you could add it to the Fixes list in the PR.

**Comment by jeremypw** [comment]
We might as well keep it open as it is slightly different from the others.

**Comment by peteruithoven** [comment]
This seems fixed :tada:
