### ISSUE TITLE
Files no longer shows nextcloud sync folders

### ISSUE THREAD

**Issue by dr-Styki** [elementary/files#2005]
### What Happened?

Files no longer shows nextcloud sync folders.

### Steps to Reproduce

1. elementary OS clean install.
2. update/upgrade
3. install nextcloud-desktop
4. setup folder sync
5. look at Files.

### Expected Behavior

Files should show all sync folders setup in the Nextcloud client.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Files still includes a `cloudproviders` plugin but you will need to install a compatible NextCloud client.  @marbetschar : The guide you produced for Hera seems to be no longer available (https://linux.marco.betschart.name/elementary-OS/Nextcloud-Client.html)  so the File wiki entry needs updating.  Is this something you could do when you have time? Do any changes need to be made to the plugin for the current version of NextCloud?

**Comment by marbetschar** [comment]
@jeremypw the URL did change - this works for me on Odin:
https://www.marco.betschart.name/resources/linux-desktop/install-nextcloud-client

**Comment by marbetschar** [comment]
@jeremypw however, I noticed as well: the Nextcloud shortcut in the sidebar of Files is gone for quite a while now

**Comment by jeremypw** [comment]
@marbetschar Maybe something to do with the re-written sidebar but it should still show plugin bookmarks.  At the moment only the cloudproviders plugin uses that function though.  I'll install NextCloud again and try it out.

**Comment by jeremypw** [comment]
Afaict, the ppa for the nextcloud client, mentioned in the wiki document,  is no longer relevant for elementary 6; it can be installed from AppCenter.  However, it seems that some versions of `libcloudproviders` and `nextcloud-client` are not compatible and I this is the case for those provided by elementary 6. You need a later version of `libcloudproviders` and a version of `nextcloud-client` with `libcloudproviders` support compiled in.  I tried installing Nautilus (Gnome Files) and its nextcloud plugin and that did not work on elementary 6 either.

If you are using a local NextCloud server (as I was for testing) then you can connect Files to it via DAV using a URL like dav://<accountname>@localhost/remote.php/webdav.

**Comment by dr-Styki** [comment]
It's a shame that versions of libcloudproviders and nextcloud-client are not compatible. 😥️
I just tried on Archlinux wich has libcloudproviders 0.3.1-2 like Ubuntu Jammy (22.04) and that work with Nautilus but not with Files.

**Comment by jeremypw** [comment]
Yes, I need to set up an elementary 7 install and at least make sure that it works on that if it cannot be made to work on elementary 6.

**Comment by jeremypw** [comment]
Embarrassingly, I have found that nextcloud/libcloudproviders are in fact working on elementary 6 and the bookmark non-appearance is down to a simple error made when rewriting the sidebar code :disappointed: 

A PR to fix this will be pushed shortly.
