### ISSUE TITLE
Trash (from bookmarks) shouldn't have a remove option.

### ISSUE THREAD

**Issue by marco4mp** [elementary/files#2013]
### What Happened?

Hi!

Trash (from bookmarks) shouldn't have a remove option. Btw, it reappears if you close and then open Files.

### Steps to Reproduce

1. Open Files
2. Right click on Trash icon
3. Select remove option

### Expected Behavior

The remove option should not be displayed.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Yes, that is an oversight during the sidebar rewrite.
