### ISSUE TITLE
Filechooser default typing action is search instead of rename

### ISSUE THREAD

**Issue by eliocamp** [elementary/files#2047]
### What Happened?

When saving a file, typing opens up the search action instead of changing the file name. I guess this makes sense on the open file dialogue, but when saving, most of the time one want to edit the name of the file, not search existing files/folders.

### Steps to Reproduce

1. Open the native "Save As" dialogue (for example, right click -> save as on this page)
2. Start typing to change the name of the file
3. The Filechooser starts searching

### Expected Behavior

The filename to save should change.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I think this the behaviour of the native Gtk.FileChooserWidget used (the file list gets focus) but could be changed in the elementary FileChooser if that is the majority opinion.

**Comment by mcclurgm** [comment]
My view on this: Assuming that the the most common intent of using a file chooser is to save a new file, not overwrite an existing file, then naming should be the default. If most people are going to save under a new name, then a big majority of the time they will be using the name field, every time they want to do this. They may only interact with the list part of the time: if they select an existing file, or need to change the directory. Either way, this will happen less frequently than using the name field.

There's a further (potentially related) bug, where after typing a character into the name field the list gets focused again. I haven't been able to replicate this, but maybe it's related to the code used to select the list by default.

**Comment by BugFixesAndPerformanceImprovements** [comment]
I agree that typing the file name should be the default behaviour. Typing whenever a save dialog appears should be about the saving of the file, not searching.

**Comment by kedicesur** [comment]
Sorry guys but this is the most disgusting issue i have ever met in the UI world. This should be fixed ASAP.

**Comment by jeremypw** [comment]
@kedicesur Hope to get the fix into the next release of Files.
