### ISSUE TITLE
Filechooser dialog & overwrite dialog close on key down

### ISSUE THREAD

**Issue by mcclurgm** [elementary/files#2051]
### What Happened?

Fallout from the implementation of #1989. When you press the esc key on either of these dialogs, the dialog dismisses immediately instead of waiting until key release. This is against the HIG.

This is a known issue with that PR, but deemed unimportant. Opening this issue to track, in case anyone wants to deal with a papercut at some point.

### Steps to Reproduce

1. Open a file chooser dialog somehow.
2. Press esc and hold it down
3. The dialog will already be dismissed, although it shouldn't be until you release the key

The same thing applies if you get a conflict dialog to launch. Then both dialogs will dismiss on key down if you press esc in succession.

### Expected Behavior

Following the HIG, they should both dismiss at key release.

### OS Version

6.x (Odin)

### Software Version

Compiled from git

**Comment by jeremypw** [comment]
Is this really against the HIG? Message dialogs are generally dismissed with key-down `Esc` and key-bound actions and signals also trigger on key-down. You can close a window with `Alt + F4` key-down for example.  
However mouse actions should trigger on button up.

**Comment by mcclurgm** [comment]
Huh, guess you're right. I have no idea where I got that mixed up.
