### ISSUE TITLE
Bookmarks to non-folders have incorrect icon after rebooting

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#2053]
### What Happened?

After creating a bookmark to e.g. a text file, the bookmark as an icon appropriate to the filetype.  However, after restarting Files, that bookmark incorrectly gets a "folder" icon.

### Steps to Reproduce

1. Bookmark a non-folder item
2. Close Files and reboot
3. Open Files
4. The newly created bookmark's icon has changed to that of a folder
5. Close and reopen FIles
6. The icons are now correct

### Expected Behavior

The bookmark to a non-folder always has the correct icon for the filetype.

### OS Version

7.x (Early Access)

### Software Version

Compiled from git

**Comment by 4jNsY6fCVqZv** [comment]
By the way, I use Files 6.1.3.
And have made several observations. It doesn't even need a system reboot. The error also occurs within a session.
And I have observed that it also happens that the icon changes back. However, I can't see the logic behind it. Sometimes I can open and close Files several times and the icon does not change.

**Comment by jeremypw** [comment]
Yes - must be some timing or caching effect - not sure. However, I am pushing a PR that should fix it by improving the fallback code for getting the icon.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for pushing the PR! Does it make sense to find out if timing or caching effects play a role here?

**Comment by jeremypw** [comment]
Ideally yes, but these things can be hard (time-consuming) to track down and fix. As the effect is essentially cosmetic I am not sure I want to devote the time at the moment.
