### ISSUE TITLE
Zoom doesn't work

### ISSUE THREAD

**Issue by eliocamp** [elementary/files#2057]
### What Happened?

Files is stuck in a high zoom level and cannot change it with Ctrl + mousewheel or Ctrl + two finger scroll

### Steps to Reproduce

1. Open files
2. Use Ctrl + Mouse Wheel to change zoom level
3. The Size and Type columns move randomly but zoom level doesn't change. 

https://user-images.githubusercontent.com/8617595/175564187-e7664ae4-fe6c-45d5-b9d5-5e437973855b.mp4

 

### Expected Behavior

Zoom should change. 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Hm, presumably something in the last release.  Sorry this wasn't picked up.  Fortunately. I find that I can still change the icon sizeby using the keyboard shortcuts but not <Ctrl> + Scroll.  Investigating.

**Comment by jeremypw** [comment]
This is the culprit: f736c8cb2870c5b7fd1582bbe7c0c31310e0bc3a. Part of preparing to migrate to Gtk4, but not done right :frowning_face:  Will push a fix soon.

**Comment by joshuamars** [comment]
I can zoom in with CTRL + mouse, but it gets stuck and won't zoom back out (or in further).

**Comment by jeremypw** [comment]
I have pushed a fix for this. Once it is merged I'll get a new release out.

**Comment by joshuamars** [comment]
Hey @eliocamp I was content to run `gsettings set io.elementary.files.icon-view zoom-level 'normal'` to reset the zoom for me until this is fixed. 

The options are:
'smallest'
'smaller'
'small'
'normal'
'large'
'larger'
'huge'
'huger'
'largest'
