### ISSUE TITLE
Open AppImage

### ISSUE THREAD

**Issue by peteruithoven** [elementary/files#206]
I'm not sure if this is the right repo but I'd like to be able to start AppImages from Files. Currently, even when an AppImage is made executable the Select Application window is shown. 

Also see: https://elementaryos.stackexchange.com/questions/13887/running-appimage-withoud-terminal

The specific AppImage I've tried is Ultimaker's Cura, from:
https://ultimaker.com/en/products/cura-software

This Blueprint might be relevant? https://blueprints.launchpad.net/elementaryos/+spec/appimage-integration

**Comment by peteruithoven** [comment]
Not sure what happened, but now I can simply run it...

(I was already executable earlier, since I was already able to run it using the Terminal.)

**Comment by jeremypw** [comment]
OK.  I did not have time to check the mime-type of an AppImage but if it is application/x-executable or application/x-shellscript.

Maybe Files did not pick up the permission change (it caches file objects) and needed restarting?

**Comment by peteruithoven** [comment]
I tried changing the permissions using `chmod` and it does seem to pick up the changes right away. (Showing or not showing the run option in the right click menu)

**Comment by jeremypw** [comment]
That's good - it would have a bug in Files otherwise...

**Comment by peteruithoven** [comment]
Adding the following Contractor file to `~/.local/share/contractor` makes it somewhat easier:
```
[Contractor Entry]
Name=Make executable
MimeType=application/x-executable;
Exec=pkexec chmod +x %U
```

**Comment by MaxValue** [comment]
Sorry to say this, but - not allowing `.AppImage` files to run on double-click is somewhat stupid. AppImage is the closest thing we got to OSX's applications. But this UX gets destroyed, because the user has to open a terminal every time they want to start an app.

(If this is not the current behaviour, let me know. It still doesn't allow to be started by double-click on my system.)

**Comment by jeremypw** [comment]
@MaxValue : On Juno, I downloaded a demo AppImage, made it executable and it ran fine when activated by clicking in Files (by default using a single-click, unless you have changed the Files settings).  The context menu shows "Run" as the first option.  This should work for any mimetype that is defined as a sub-type of application/x-executable in the system mime database.
