### ISSUE TITLE
Tabs not remembered after closing Files

### ISSUE THREAD

**Issue by jgomer2001** [elementary/files#2063]
### What Happened?

I happily used elementary OS 5.1 for a couple of years. I moved to 6.1 recently and noticed that after closing and reopening Files,  tabs previously open are not remembered. It just leaves you with a tab at your home location. Is there a way to restore the nice behavior of 5.1 where tabs are remembered?. Now I have to "remember" by my own where I left off before shutting down my computer.

A similar thing is happening with terminal, I added a comment [here](https://github.com/elementary/terminal/issues/616#issuecomment-1184927422). Any suggestion welcome

### Steps to Reproduce

1. Open files
2. Add a tab
3. Close files
4. Openf files (only 1 tab shown)

### Expected Behavior

I want my tabs restored

### OS Version

6.1

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Please check that you have History enabled in the Settings Security & Privacy plug. If this is disabled then Files now honors that setting and does not restore previously used locations.  Also check the result of `gsettings get io.elementary.files.preferences restore-tabs` in a terminal.

**Comment by jgomer2001** [comment]
Thanks! history was disabled. Files can remember tabs properly now.
