### ISSUE TITLE
Can't connect to secure webdav 

### ISSUE THREAD

**Issue by Mr-DeBonis** [elementary/files#2065]
### What Happened?

I'm trying to connect to a secure webdav server (webdav Https)  through the "Connect Server" functionality in the pantheon-files browser with no luck. Here's the screenshot of the windows I'm using:
![image](https://user-images.githubusercontent.com/33008431/184233653-d56271df-e701-4034-90fd-1ffb575c3267.png)

I've tried to connect through ssh to another server and it works.

I've tried to connect to the secure webdav using a third party software (available in windows only) and can connect succesfully. 

I hope you could help me.

### Steps to Reproduce

1. Open the pantheon-files
2. Click on Connect server
3. Pick Secure Webdav (HTTPS)
4. Enter credentials and Server url
5. Click on connect

### Expected Behavior

I expect to connect to the Webdav file browser.

### OS Version

5.x (Hera)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I'll need to set up a secure WebDav server in order to test this on the current version of elementary (6.1).  Do you get any error messages?

**Comment by Mr-DeBonis** [comment]
No, where could I check the logs @jeremypw ?

**Comment by jeremypw** [comment]
OK, so the UI just returned to the dialog after pressing "Connect"?  You could try running Files in the terminal with `G_MESSAGES_DEBUG=all io.elementary.files` and seeing if any new messages appear after pressing "Connect". Close all Files windows first. You will get a lot of irrelevant messages before that.

**Comment by Mr-DeBonis** [comment]
Thanks, now it is working on pantheon-files stand alone.

There were no errors in the logs except for:
```
** (io.elementary.files:12686): DEBUG: 13:54:28.745: gof-directory-async.vala:1136: found cached dir davs://soporte@soportedimacoficl.custhelp.com/dav/cp/customer/development
** (io.elementary.files:12686): DEBUG: 13:54:28.745: gof-directory-async.vala:205: Preparing directory for loading
** (io.elementary.files:12686): DEBUG: 13:54:28.745: gof-directory-async.vala:240: get_file_info
** (io.elementary.files:12686): DEBUG: 13:54:28.745: gof-directory-async.vala:386: check network
** (io.elementary.files:12686): DEBUG: 13:54:28.745: gof-directory-async.vala:417: File is already mounted - not reconnecting
** (io.elementary.files:12686): DEBUG: 13:54:28.745: gof-directory-async.vala:425: Attempt to connect to davs://soporte@soportedimacoficl.custhelp.com/dav/cp/customer/development/controllers succeeded
** (io.elementary.files:12686): DEBUG: 13:54:28.747: AbstractDirectoryView.vala:854: Guessed content type to be application/octet-stream from name - result_uncertain true
** (io.elementary.files:12686): DEBUG: 13:54:29.183: gof-directory-async.vala:271: try_query_info

(io.elementary.files:12686): GLib-GIO-CRITICAL **: 13:54:29.383: g_file_info_get_name: assertion 'G_IS_FILE_INFO (info)' failed

```

**Comment by Mr-DeBonis** [comment]
Although, It is a bit slow.

**Comment by jeremypw** [comment]
So, what changed to make it work?

Is the issue now about performance - in which case please update the description?  Thanks.

**Comment by Mr-DeBonis** [comment]
I took an alternative following [this tutorial](https://www.youtube.com/watch?v=Qz9Njd6iZiY). This solves the problem and mounts successfully a connection to a WebDav server.

Connection is slow also on third party devices, so I rule it out as a problem of the server. 

Thanks for your disposition.
