### ISSUE TITLE
copy and paste omits file extension if (possibly) unknown

### ISSUE THREAD

**Issue by cmburg** [elementary/files#2071]
### What Happened?

I have a jupyter notebook which I copy-pasted via `ctrt+c` and `ctrl+v` in pantheon files. Although the text `(copy)` has been added, the extension `.ipynb` was not. This issue does not appear on more common extensions as `.txt` or `.py`

### Steps to Reproduce

1. Create a file, e.g, `foo.ipynb` via the right mouse-button menu.
2. Select the file and press `ctrl+c`, `ctrl+v`

### Expected Behavior

The extension is kept

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
There is a note in the code: `        /* Strings longer than 4 or shorter than 1 are not regarded as extensions */`
I guess this limit could be increased to 5, however there may be some filenames containing `.` where the last 5 chars are not in fact an extension.  I do not think it is practical to try to maintain a list of "recognized extensions".
