### ISSUE TITLE
FileChooser Portal: Dim is not being removed after closing replace dialog

### ISSUE THREAD

**Issue by lenemter** [elementary/files#2076]
### What Happened?

When I download a file from a flatpaked browser and replace another file, browser window gets dimmed twice, once when FileChooser opens and once when replace dialog opens. After FileChooser dialog is closed, only one dim is removed, so you're stuck with a permanently dimmed window

### Steps to Reproduce

1. Use browser in flatpak (checked with Chrome and Firefox)
2. Overwrite a file while saving file
3. You're stuck with a dimmed window

### Expected Behavior

Normal window

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Also occurs with Flatpak'd Code.

**Comment by Marukesu** [comment]
The problem is that the overwrite dialog is a modal dialog over another modal dialog, the fix here's to make the overwrite dialog non-modal.

However, maybe the dim code in gala doesn't handle the case of multiple modals correctly and that needs to be fixed there instead.

**Comment by jeremypw** [comment]
Only occurs if you close the the conflict dialog with "Save" - if you choose "Cancel" then the issue does not occur.  Looking for a simple fix - but yes, may be a Gala issue.
