### ISSUE TITLE
Is not possible to use drag and drop with Alt+Tab

### ISSUE THREAD

**Issue by Maccer1** [elementary/files#208]
This issue affects all apps (I've checked that it happens on firefox, chrome, gimp, vlc...), not just files. However I don't know any better place to post this issue.

I've made [a video](https://gfycat.com/gifs/detail/WarmFlawedAyeaye) to explain the issue. Basically what I'm trying to do is selecting 3 files, dragging them with the mouse, then pressing Alt+Tab and dropping them in another window of files. As you see, it doesn't work. Somehow it gets stuck in the Alt+Tab animation and doesn't paste the files.

However, when I copy the files (right click> copy), press Alt+Tab and paste them; it works as I think it should.

**Comment by jeremypw** [comment]
I suggest posting this against the window manager (gala):

https://github.com/elementary/gala

**Comment by Maccer1** [comment]
Done :+1: 

https://github.com/elementary/gala/issues/122

**Comment by jeremypw** [comment]
Moved to Gala.
