### ISSUE TITLE
With new v6.2.0, new empty file closes the app

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/files#2098]
### What Happened?

Right-clicking inside the folder and selecting New -> Empty file immediately closes the app with this error in the terminal:

`** (io.elementary.files:8526): CRITICAL **: 08:21:39.090: marlin_file_operations_create_job_construct_file: assertion 'target_filename != NULL' failed` 

No issues with creating a new folder using the same technique.

Also, this has never happened before version 6.2.0.

### Steps to Reproduce

1. Open files
2. Open a folder inside User's home
3. Right-click inside that folder and select New -> Empty file

### Expected Behavior

Well, not to break

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
** (io.elementary.files:8526): CRITICAL **: 08:21:39.090: marlin_file_operations_create_job_construct_file: assertion 'target_filename != NULL' failed
```

### Hardware Info

Vanilla installation on Lenovo IdeaCentre AMD Ryzen 7, all apps coming from .deb files (manual and repo) or Flatpack. Nothing compiled, no meddling with the kernel.

**Comment by JoseExposito** [comment]
Hi! Thanks for reporting this crash. It is fixed in https://github.com/elementary/files/pull/2099

**Comment by WebShapedBiz** [comment]
Thank you @JoseExposito for your time and effort.
