### ISSUE TITLE
segfault when creating new empty file

### ISSUE THREAD

**Issue by GammaGames** [elementary/files#2102]
### What Happened?

Tried to create a new empty file with the right click menu:
![image](https://user-images.githubusercontent.com/7832163/201996124-c1bf9f80-ace8-4db8-b6b9-069c885f939d.png)

### Steps to Reproduce

1. Right click in a folder
2. Select "New" > "Empty File"
3. Crash

### Expected Behavior

Should've created a new file

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
** (io.elementary.files:737844): CRITICAL **: 11:20:29.340: marlin_file_operations_create_job_construct_file: assertion 'target_filename != NULL' failed
Segmentation fault
```

**Comment by danirabbit** [comment]
Thanks for your report! This was fixed in #2099. A new release is going out today :)
