### ISSUE TITLE
v6.2.1. at some point, while opened on the desktop, left column icons change

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/files#2105]
### What Happened?

I've noticed several times now that when Files are opened on the desktop, after a while, the icons in the left column change from styled:
![ksnip_20221119-092929](https://user-images.githubusercontent.com/6765137/202845662-0b412dd3-2834-4e06-a396-a37c01ff7fbd.png)

to generic:
![ksnip_20221119-110419](https://user-images.githubusercontent.com/6765137/202845669-02623f5d-1b9e-4160-a2ab-7b8ad719fc51.png)

Also, I've noticed that when opening Files, the icons in the left column are always all generic and then, entirely visible, get changed to the styled version. This change is so slow that you can actually see it happening every time, and that's something I've never experienced before.

After closing and opening Files again, the icons are always restored.

### Steps to Reproduce

1. Open Files and leave them on the Desktop
2. Do whatever you're doing for an unknown period of time
3. Check the Files window periodically for icon changes.

### Expected Behavior

Well, for the icons not to change

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

- 8× AMD Ryzen 7 4800u with Radeon graphics 
- Advanced Micro Devices, Inc. [AMD®/ATI] Renoir
- 16GB RAM
- 500GB NVMe M.2 SSD

**Comment by janxkoci** [comment]
Same thing, after every restart / cold boot. **You can get the icons back by refreshing the view with `F5`.**

I first noticed it a few weeks ago, running OS 6.1.

**Comment by jeremypw** [comment]
Probably due to this: https://github.com/elementary/files/pull/2054/files. I'll try to get a fix out soon.

**Comment by WebShapedBiz** [comment]
Thank you @jeremypw for your time and effort.
