### ISSUE TITLE
Files no longer shows size of folders in list view

### ISSUE THREAD

**Issue by mpanhans** [elementary/files#2108]
### What Happened?

In list view, Files used to show the size of folders as either "N items" or "Empty". Around the time of the update to Files mid-November, it seems to no longer display the size of folders in list mode. Instead it shows "----" for all of the folders.

### Steps to Reproduce

1. Apply all updates
2. Open Files and change to "View in list" mode
3. See what it says under the size column for any folder

### Expected Behavior

Files used to show the number of items in the folder, or "Empty".

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Probably due to commit b4679bc883d90c5e6aee40cc1f07fc875a9c0819
Fixing.

**Comment by mpanhans** [comment]
@jeremypw  Is there a way to ping for a review of this pull request https://github.com/elementary/files/pull/1978? It looks like a nice and simple fix to this issue that is a regression from earlier version of Files.

**Comment by jeremypw** [comment]
@mpanhans Thanks for the reminder.  I have put out a review request to the elementary desktop developer team for #1978 now.  I am concentrating on porting Files to Gtk4 now but this is worth getting into the Gtk3 version.

**Comment by mpanhans** [comment]
Hmm I just applied all updates to an elementary 7.0 install, Files gets updated to 6.3.1, and I am still seeing this issue. Every folder in List View says "----" for the size, regardless of whether it has items inside or not.

**Comment by jeremypw** [comment]
Ah - I was looking at a mounted hard disk partition.  That is showing item count. The installation partition is not. #1978 will also fix that issue.  Sorry for the confusion.
