### ISSUE TITLE
"This folder does not belong to you" should give option to demand acccess

### ISSUE THREAD

**Issue by SephReed** [elementary/files#2112]
### Problem

I have no idea why, but USB drives always seem to mount without read/write access.  It's already bad default behavior, but the fact that I have to search the entire internet for a way to get access to my own drives is much worse.

### Proposal

Put a button "Demand access", prompts for an admin password, gives the user permissions.

**Comment by meisenzahl** [comment]
@SephReed could you please specify the version of elementary OS you are using, or other operating system.

**Comment by jeremypw** [comment]
This is similar to the long outstanding issue #165

**Comment by SephReed** [comment]
@jeremypw, it is very similar.  I'm going to close this one and move over there.

@meisenzahl 6.1
