### ISSUE TITLE
"Paste into folder" doesn't work

### ISSUE THREAD

**Issue by marco4mp** [elementary/files#2115]
### What Happened?

The option "Paste into folder" doesn't work using the right click menu.

However it does work using the shortcut Shift+Ctrl+V.

### Steps to Reproduce

https://user-images.githubusercontent.com/52709674/211161778-09d4ac15-1684-4d85-9eb2-7e4eb5f1ea43.mp4

### Expected Behavior

The "Paste to folder" option should work with the context menu.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Confirmed on current master (Horus). Not sure when this regression occurred. Thanks for pointing it out.
