### ISSUE TITLE
Files should have a settings/cog wheel menu in the headerbar

### ISSUE THREAD

**Issue by Eldhrimer** [elementary/files#2123]
### Problem

1. Since there are now three settings options in the context menu, it is starting to feel too cramped.
2. Since the settings are global for the app, they have no place in the context menu for a given folder, it would be different if those settings where pertaining to the folder currently opened.
3. With a settings menu we could also expand on the available settings, like the missing icon size/viewport zoom setting, which is accessible through a keyboard/ keyboard + mouse wheel combination but is not teached, hinted or conveyed to the user in any way. Also, a theme setting to follow the system defined dark/light mode or have one independent.

### Proposal

A way to address all those issues would be to place a pop up settings/cog wheel menu in the headerbar.

### Prior Art (Optional)

There are already several default apps that follow this design pattern:
- Code
- Terminal
- Mail

**Comment by Eldhrimer** [comment]
I've read on previous issues that the design team didn't want to put an appmenu on the headerbar. Have they presented their reasons or their concerns? 

_(Also not a native speaker, hence my wording sometimes could be misinterpreted as rude or otherwise unpleasant. I truly just want to be helpful to the community, please excuse)_

**Comment by danirabbit** [comment]
@jeremypw Yeah I think there's enough stuff here that we should go ahead and do an app menu here now 👍

**Comment by jeremypw** [comment]
@danirabbit Great!  I'll make a start on it, probably next week.
