### ISSUE TITLE
No mount option in right click

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/files#2141]
### Problem

Previous versions of Files use to allow you to mount a drive via right click. I can not do this anymore. I have to open the drive in a new tab

### Proposal

Bring back the option to mount a drive without having to open it

**Comment by jeremypw** [comment]
I am still getting both an "Open" and "Open in New Tab" option when right-clicking on Volume entries under Storage (corresponding to separate partitions on the same drive).I also get these options for a USB hard drive, a USB stick and an SD card.  What kind of device are you experiencing this issue with.

**Comment by jeremypw** [comment]
Ah, re-reading the report I see you wish to mount the device *but not open it*.  I though the issue was you had to open it *in a new tab*, which is not the case.You are right, that option to mount without opening was not re-implemented when the sidebar was re-written. If there is a use case for this then it can be re-added.

**Comment by jeremypw** [comment]
I notice that using "Nautilus" the context menu has a "Mount" option, but choosing mounts *and opens* the device so I am not sure what it adds over an "Open" option (which Nautilus also has).

**Comment by Gabriel-p** [comment]
In my case I have an external drive I use to backup my system. So when I plug it in all I want to do is mount it so that it is visible to Back In Time, I don't want to open a new tab to have it mount. I understand this is a pretty small user case

**Comment by jeremypw** [comment]
I just had a play with Back in Time (QT version) and noticed that it does not seem to detect a drive that has just been plugged in.  However the equivalent Gtk progam GRsync *does* detect such a drive and allow it to be selected.  Such a drive also shows in the Gtk FileChooser and in Nautilus with an "unmount/eject" button against them.  Files should probably show the same to avoid confusion.

**Comment by Gabriel-p** [comment]
BIT does not detect a drive if it is not mounted, yes. GRsync is not available in the AppCenter or FlatHub so I won't try it. I'm not sure why BIT expects the drive to be mounted, but it does. The issue is that previous versions of Files allowed me to mount a drive via right click and now I can't. I'd love to have that feature back

**Comment by jeremypw** [comment]
I don't think BIT is in AppCenter either.  You can install GRSync with `sudo apt install grsync` in a terminal.  Both apps are front-ends to `rsync`.  I tend agree that removing debs from AppCenter is a bit premature.  There are some other backup apps in there though (I haven't tried them) but folks like to stick with what they know.

**Comment by jeremypw** [comment]
Looks like some work has been done on Flatpak grsync - see https://sourceforge.net/p/grsync/feature-requests/22/ so hopefully will become available soon.

**Comment by jeremypw** [comment]
Should be easy enough to replace. No guarantee it will get merged though.

**Comment by jeremypw** [comment]
@Gabriel-p I have pushed a PR that fixes this.
