### ISSUE TITLE
The tabs arent saved anymore after closing the files app.

### ISSUE THREAD

**Issue by Editorenbici** [elementary/files#2169]
### What Happened?

 I installed dropbox some days ago and seem to work nice until today.

Is the second time, the same happened one week ago with anothe installation. Maybe a bad update?

### Steps to Reproduce

1. Open the files app
2. go to some file other than your home
3. close
4. open again

### Expected Behavior

The tabs usually are restored after close the app

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

dell laptop. i5 7th gen 8 gb ram

**Comment by Editorenbici** [comment]
Thanks! The History seeting was the one.

**Comment by jeremypw** [comment]
Closing as resolved
