### ISSUE TITLE
Hangs when a folder with a large number of files needs to be shown

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/files#2172]
### What Happened?

I have a folder with ~10000 files. Files will hang for minutes while the `is not responding` dialogue appears non stop until it mananges to show the folder properly

### Steps to Reproduce

1. Open folder with ~10000 files

### Expected Behavior

Files should not hang

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Starting program: /usr/bin/io.elementary.files 
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Nuevo Thread 0x7ffff2dff640 (LWP 5150)]
[Nuevo Thread 0x7ffff25fe640 (LWP 5151)]
[Nuevo Thread 0x7ffff1dfd640 (LWP 5152)]
[Nuevo Thread 0x7ffff1516640 (LWP 5153)]
[Nuevo Thread 0x7fffe3fff640 (LWP 5156)]
[Thread 0x7fffe3fff640 (LWP 5156) terminado]
[Nuevo Thread 0x7fffe3fff640 (LWP 5157)]
[Nuevo Thread 0x7fffe33ff640 (LWP 5158)]
[Thread 0x7fffe3fff640 (LWP 5157) terminado]
[Thread 0x7fffe33ff640 (LWP 5158) terminado]
[Nuevo Thread 0x7fffe33ff640 (LWP 5159)]
[Nuevo Thread 0x7fffe3fff640 (LWP 5160)]
[Thread 0x7fffe3fff640 (LWP 5160) terminado]
[Nuevo Thread 0x7fffe3fff640 (LWP 5161)]
[Nuevo Thread 0x7fffe19ff640 (LWP 5162)]
[Thread 0x7fffe33ff640 (LWP 5159) terminado]
[Thread 0x7fffe19ff640 (LWP 5162) terminado]
[Thread 0x7fffe3fff640 (LWP 5161) terminado]
[Nuevo Thread 0x7fffe3fff640 (LWP 5163)]
[Nuevo Thread 0x7fffe19ff640 (LWP 5165)]
[Nuevo Thread 0x7fffe33ff640 (LWP 5167)]
[Nuevo Thread 0x7fffe0dfe640 (LWP 5168)]
[Thread 0x7fffe0dfe640 (LWP 5168) terminado]
[Thread 0x7fffe19ff640 (LWP 5165) terminado]
[Thread 0x7fffe33ff640 (LWP 5167) terminado]
[Thread 0x7ffff1516640 (LWP 5153) terminado]

(io.elementary.files:5147): Gtk-CRITICAL **: 10:09:49.824: gtk_widget_grab_focus: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.files:5147): Gtk-CRITICAL **: 10:10:09.940: gtk_widget_grab_focus: assertion 'GTK_IS_WIDGET (widget)' failed

** (io.elementary.files:5147): WARNING **: 10:10:33.673: Directory.vala:738: Error reported by next_files_async: Se canceló la operación
[Thread 0x7fffe3fff640 (LWP 5163) terminado]

(io.elementary.files:5147): GLib-GObject-WARNING **: 10:10:53.397: ../../../gobject/gsignal.c:2765: instance '0x555555d5d3c0' has no handler with id '836'
[Nuevo Thread 0x7fffe3fff640 (LWP 5195)]
[Thread 0x7ffff2dff640 (LWP 5150) terminado]
[Thread 0x7ffff25fe640 (LWP 5151) terminado]
[Thread 0x7ffff1dfd640 (LWP 5152) terminado]
[Thread 0x7ffff59cca80 (LWP 5147) terminado]
[Thread 0x7fffe3fff640 (LWP 5195) terminado]
[Nuevo process 5147]
[Inferior 1 (process 5147) exited normally]
```

### Hardware Info

AMD A8-3870 apu with radeon(tm) hd graphics 4 cores
NVIDIA® GeForce® 9500® GT
8 GB RAM

**Comment by jeremypw** [comment]
IconView in Gtk3 is known to be slow to show folders containing large numbers of items although your case seems far slower than expected.  Try showing the folder in ListView.  Is the folder on a local (fast ) disk or on a remote (possibly slow) disk? 

Have you noticed Files getting slow recently e.g. since the last release?

The Gtk4 version of Files should be faster as it uses new dynamic views.

**Comment by Gabriel-p** [comment]
The folder is on a local disk, with ListView it also takes a really long time to display. I have not noticed Files getting slower lately

**Comment by jeremypw** [comment]
@Gabriel-p Thanks for the further info.  If ListView is also taking a long time then it is not a layout issue.  Just confirmed this is a regression using a folder containing 20000 empty files.  The view lays out quickly but then the interface freezes for a long time.

**Comment by jeremypw** [comment]
The problem seems to lie in `File.vala` in particular in the `update ()` function.  

This code is visited repeatedly for each file and takes a significant time
```
            try {
                mount = location.find_enclosing_mount ();
                is_mounted = (mount != null);
            } catch (Error e) {
                is_mounted = false;
                debug (e.message);
            }
```

This code has not changed since 2019 but some other change may have caused it to be visited more often.

**Comment by jeremypw** [comment]
This issue seems to have been around as far back as I can compile with Horus so its surprising it hasn't been reported before.  I suspect the time is proportional to the square (or some other exponent) of the number of items.

**Comment by jeremypw** [comment]
As an aside, the current Gtk4 port also struggles with large folders but for different reasons so that will also need to be addressed.

**Comment by Gabriel-p** [comment]
Thank you very much for working on this @jeremypw!

**Comment by Gabriel-p** [comment]
@jeremypw @tintou I believe this issue should be reopened. I am experiencing it again with the latest elementary version

**Comment by jeremypw** [comment]
@Gabriel-p When you say you are experiencing it again, can you say which version was better and at what stage it deteriorated? Does it effect all views are only, say, Icon View?  If I can reproduce a regression then I'll investigate.  Are we still talking about 10,000 files to display?

**Comment by Gabriel-p** [comment]
Not sure when it started, I guess with eOS 8? I have a folder with ~17000 data files (.parquet) Attempting to access it hangs Files almost completely (I stop it after 1:30 min)

**Comment by jeremypw** [comment]
@Gabriel-p  With 17000 small files (not thumbnailed), Files should display the view within in ListView in under 10 seconds (as judged by my testing using many small files).  I would recommend avoiding Icon View with a large number of files as it is considerably slower.  Most file operations, especially undoable ones involving a large number of files are likely to be relatively slow.

Can you confirm that with less than thousand `.parquet` files the performance is OK? Does it get thumbnailed? I haven't used this file format and it is possible it it causes specific issues.

If the files are very large then memory problems may cause performance issues as well.

**Comment by Gabriel-p** [comment]
You are right, in ListView although it still struggles a bit with the icons at least the folder can be accessed .

I don't understand why though, these are parquet files and they need no thumbnail to be generated. Both ListView and IconView use the same blank icon, why does IconView completely hang Files? If anything I would think the opposite should happen because ListView displays info about the files whereas IconView only shows the names...

**Comment by jeremypw** [comment]
@Gabriel-p IconView takes a long time to calculate the layout of a large number of files in a grid (and to reconfigure the grid if the window size changes) since it does this for *every* item, visible or not - it is nothing to do with the amount of info displayed  (which is loaded anyway).  Its just the way it is coded by Gtk3. This problem will be solved when we succeed in porting Files to Gtk4 and are then able to use the *much* more efficient dynamic grid view available there. This widget only lays out items that are actually visible and recycles them.

I only mentioned thumbnails as I was not sure whether there was a thumbnailer backend for `parquet` files. I assume then it just gets a generic text icon.  You might still get a little bit of improvement by turning off "local thumbnailing".
