### ISSUE TITLE
Reduce default field when renaming a file

### ISSUE THREAD

**Issue by BenMorant** [elementary/files#2183]
### Problem

I wanted to rename a file on pantheon-files.
The "field" (?) for renaming was very big (sorry, I don't use the good terms), but as "A picture paints a thousand words" :

![Captures d'écran de 2023-05-02 09 15 36](https://user-images.githubusercontent.com/52816705/235679586-b4197c1e-2d90-4d7d-910b-9f190efaf528.png)

### Proposal

the "renaming field" should have by default one "row", maybe two ?

**Comment by jeremypw** [comment]
In IconView, the size of the rename field is governed by the size of the largest name in the view because the grid layout means all name fields must be the same size.  The oversize rename field does not cause significant problems when renaming does it?

**Comment by BenMorant** [comment]
Hello Jeremy !
Thanks for your clear reply.

> _The oversize rename field does not cause significant problems when renaming does it?_

Not at all. 
Your point actually is clear and logical.
Should I close the issue ?

**Comment by jeremypw** [comment]
I do not think any action will be taken for the Gtk3 version of Files unless there is a clear benefit.  For the Gtk4 version that is under development renaming is currently done in a dialog with a one line entry but I am not sure what the eventual solution will be.  I am going to close this as a design conflict - a new issue can always be opened after the Gtk4 release if that is not satisfactory.
