### ISSUE TITLE
Can't rename single file

### ISSUE THREAD

**Issue by peteruithoven** [elementary/files#2189]
### What Happened?

When trying to rename a single file, nothing seems to happen. While selecting multiple and then renaming opens the bulk rename dialog. 

### Steps to Reproduce

1. Install latest version from git
2. Right click a single file
3. Select Rename

When starting files through the terminal I see the following error:
> ** (io.elementary.files:46559): CRITICAL **: 16:58:06.952: AbstractDirectoryView.vala:3705: Failed to find rename file in model

### Expected Behavior

In place of the file name a textbox is shown in which the file name can be changed. 

### OS Version

7.x (Horus)

### Software Version

Compiled from git

### Log Output

```shell
** (io.elementary.files:46559): CRITICAL **: 16:58:06.952: AbstractDirectoryView.vala:3705: Failed to find rename file in model
```

**Comment by ryonakano** [comment]
Looks liken this happens if commit db6dfad35059bcd9a0a3ea1401a42c59f3d8942a is included.
