### ISSUE TITLE
Possibility to order items in grid view

### ISSUE THREAD

**Issue by BenMorant** [elementary/files#2193]
### Problem

When I'm navigating within pantheon-files in grid view (default view), I would like to be able to order items by creation date / modification date, ascending or descending order etc... 

### Proposal

Allow grid view to order items by creation date / modification date, ascending or descending order etc...

**Comment by lenemter** [comment]
This is already available in the right click menu.

**Comment by BenMorant** [comment]
Hi  Leo.
Arf...  Sorry for the disturbance. :/
I close the issue.
