### ISSUE TITLE
When viewing a folder externally created hidden files are shown

### ISSUE THREAD

**Issue by rasmus91** [elementary/files#2195]
### What Happened?

I opened files, then my terminal, and just wrote: `clear` in zsh. This caused a `.zsh_history.LOCK` file to appear in the files view.
![image](https://user-images.githubusercontent.com/2297739/236760902-12880213-2b48-45e0-9efe-e904ad857487.png)

If F5 is hit to refresh after, the fiels does as its supposed to

![image](https://user-images.githubusercontent.com/2297739/236761551-982b66f1-dbe7-41e4-a67e-310f9e36201f.png)

### Steps to Reproduce

1. Opened files, leave it on the home folder
2. Opened terminal (zsh) and type clear
3. the `.zsh_history.LOCK` file appeard in the files view where its set to not show hidden files.

### Expected Behavior

I would expect files to not show hidden files when set to not show hidden files

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I could not reproduce this (in latest master) by using the command `touch .zsh_history.LOCK` instead of `clear` as I use `bash`. Does it only happen for you with `zsh` or with all externally created hidden files?

**Comment by rasmus91** [comment]
No idea. I'll check when i get the opportunity.

**Comment by janxkoci** [comment]
I can reproduce it by just editing some text file in Code - it creates hidden tempfiles (dotfiles) in the same directory, but they are visible in Files. The files disappear when I flip the "show hidden" switch twice in the cog menu. I almost reported the wrong bug to Code repo, but then after flipping the switch I realized the problem might rather be here.

**Comment by rasmus91** [comment]
> I could not reproduce this (in latest master) by using the command `touch .zsh_history.LOCK` instead of `clear` as I use `bash`. Does it only happen for you with `zsh` or with all externally created hidden files?

> I can reproduce it by just editing some text file in Code - it creates hidden tempfiles (dotfiles) in the same directory, but they are visible in Files

I guess I don't need to check further?

**Comment by jeremypw** [comment]
OK, I can confirm the Code temp file issue when using the most recent stable ISO.  I'll check again using Files compiled from latest source.
