### ISSUE TITLE
When opened with specific file to select, the view is not showing that file

### ISSUE THREAD

**Issue by davidak** [elementary/files#2214]
### What Happened?

When i select "Open in File Browser..." in [Rapid Photo Downloader](https://damonlynch.net/rapid/), Files is opened and the file is selected, but it is not shown in the view. I have to scroll down to see it.

Demonstration Video: https://www.youtube.com/watch?v=QoJYM3_LbUE

Rapid Photo Downloader uses the Python Library [show-in-file-manager](https://github.com/damonlynch/showinfilemanager) to do it, which basically does:

`io.elementary.files FILE`

With that, the issue is easily reproducible.

### Steps to Reproduce

0. Open Terminal
1. Open Files
2. Copy this command in Terminal `io.elementary.files`, add a Whitespace
3. Scroll down in a folder with many files in Files and drag-and-drop a file from far down into the terminal, to get it's full path
4. Close Files
5. Run the command in Terminal, e.g. `io.elementary.files '/home/davidak/2023-06-10_14-28-09.mkv'`
6. Files is opened and you see the folder the selected file is in, you have to manually scroll down to see it

### Expected Behavior

The view is scrolled automatically to show the selected file.

### OS Version

Other Linux
NixOS 22.11.4479.d4a9ff82fc1

### Software Version

Older release (I have not run all updates)
elementary-files-6.2.1

**Comment by jeremypw** [comment]
Pushing to queue for fixes in the Gtk4 of Files.

**Comment by jeremypw** [comment]
Decided to fix now as some Gtk3 work is still happening and it touches parts of the code that will not change in Gtk4.

**Comment by jeremypw** [comment]
@davidak Are you able to test the linked PR? Unfortunately it has not attracted attention from reviewers yet.
