### ISSUE TITLE
Renaming a file creates a ghost file in the same directory

### ISSUE THREAD

**Issue by wout** [elementary/files#2216]
### What Happened?

Renaming a file creates a ghost file with the file's previous name and a grey text icon. After refreshing the folder, it's gone.

![image](https://github.com/elementary/files/assets/107324/0f98b128-a0cc-4c9d-b771-ffe929568ba2)

### Steps to Reproduce

1. Select a file
2. Hit F2 to rename
3. Enter a new name
4. Hit enter to confirm

### Expected Behavior

The ghost file should not be present.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

![image](https://github.com/elementary/files/assets/107324/7d6fcb69-7cef-4b0f-ae5c-0be4815eb726)

**Comment by jeremypw** [comment]
I havent been able to reproduce this when renaming an empty file in a subdirectory of Home. My hardware is fairly similar (12 × 12th Gen Intel® Core(TM) i5-1240P) but could be a timing issue.

**Comment by jeremypw** [comment]
Still cannot reproduce using version 6.3.1

**Comment by wout** [comment]
Yeah, it's weird. It's not always, but very often. The next time it happens, I'll pay better attention to previous actions and other contexts.

I just tried on another machine with Pantheon on NixOS, but couldn't reproduce it either.

**Comment by jeremypw** [comment]
May be related to #2179

**Comment by wout** [comment]
Ok, just had the same thing again by pasting files into the directory. On file, an empty favicon.ico, got replaced and left a ghost file:

![image](https://github.com/elementary/files/assets/107324/651be8e0-105d-4ac0-badd-bd83167dc112)

Then paste the files again, effectively replacing all of them, producing the same number of ghost files:

![image](https://github.com/elementary/files/assets/107324/6f0cc431-b190-440a-9f7d-5e8e9cf1e021)

**Comment by jeremypw** [comment]
Because `goutputstream` files appear and are removed extremely rapidly there is a race between the related signals.  Sometimes the "removed" signal gets processed *before* the "add" signal resulting in the file being added to the view *after* Files has (tried to) remove it.

**Comment by jeremypw** [comment]
A temporary workaround is to turn "Show hidden files" OFF.  I am working on a fix.
