### ISSUE TITLE
Opening from another apps remove the tabs history

### ISSUE THREAD

**Issue by hrstwn** [elementary/files#2235]
### What Happened?

Opening folders from another application like Firefox, e.g. when clicking on Show in Folder for downloaded files launches the elementary Files in a blank state, forgetting all the previous tabs opened in the last session.

### Steps to Reproduce

1. Open Firefox or other browsers, whatever
2. Download something safe from the internet 
3. Click Show in Folder

### Expected Behavior

elementary Files should restore all the tabs from the last session instead of opening just the Download folder.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Opening Files from another app uses the `-t` option which stops saved tabs being restored when Files opens- this is intended but leads to an inconsistency with how Files behaves if it is *already open* in which case the requested tab is added to the tab list.   It might be better just to always restore tabs (subject to privacy settings).

**Comment by hrstwn** [comment]
Is there a workaround to tweak this for myself?

**Comment by jeremypw** [comment]
Not that I can think of.  All I can suggest is:
 - Keeping Files running while running other apps where this is a problem - this should cause the existing tabs to remain
 - Creating bookmarks for key locations so they can be reopened quickly if they are lost. (`<Ctrl>Click` on a bookmark opens it in a new tab).

At some point I'll push a PR changing the behaviour to see if it is accepted.
