### ISSUE TITLE
copying folders/files

### ISSUE THREAD

**Issue by EverlastingOS** [elementary/files#2238]
### What Happened?

 when I copy a folder (with Pantheon files) to another location, I see all the files in the folder copied, eg a folder has 20 files, then I see all 20 files instead of the root folder, after a restart I can see that the folder is copied (as expected).

### Steps to Reproduce

1. Ctlr c on the folder
2. Ctlr V on destination three/ home folder
3.  Seeing all the files and not the folder, but it copies correctly, after a reboot I see that the folder is correctly. But requires a reboot, not that I close pantheon files and reboot.

### Expected Behavior

That I only see the folder and not all the X files.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I see the folder *and* all its children.  Must be a recent regression.  You should not need to reboot - just refresh the view with `F5`.

**Comment by jeremypw** [comment]
Looks like commit c0a70d796e7fb9f6523eef64205c3a1d7fade8ef is responsible.

**Comment by EverlastingOS** [comment]
> I see the folder _and_ all its children. Must be a recent regression. You should not need to reboot - just refresh the view with `F5`.

I see, but is there a fix on its way?

**Comment by jeremypw** [comment]
@EverlastingOS Yes, I have pushed a PR to fix it. Version 6.4 was going to be last Gtk3 release before porting to Gtk4 but as this is quite a serious regression I guess there will have to be another Gtk3 release.
