### ISSUE TITLE
Press and hold primary mouse button on a file or folder to select it

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/files#227]
Problem: A lot of users including me face problems with the single-click to open paradigm. Especially the pain of selecting files or folder without opening it. elementary OS provides two ways to do that by holding CTRL on keyboard and clicking to select files, but it requires an extra input device for a work that could have been done using only the mouse. Plus a lot of people might not be aware of it or find it uneasy to handle even if they discover the way. And the other way is clicking the tick on the corner of the file. But many people didn't expect that feature. Even I came to know if it recently. Plus it is not handy when it comes to clicking on the small tick icon with some touchpads as opposed to clicking the bigger file icon.

Solution: There had always been a way to select files and folder on touch input devices, running iOS (iPhone) or Android. One has to simply touch on the icon and hold it either to select it or open context menu. In elementary OS, we do have secondary-click to open context menu. So, we could just click and hold on a file or folder using the primary mouse button to select it. On selecting a file, a smaller cotext menu would appear showing common controls like "cut" "copy", etc.. A horizontal context menu with icons only should get in to way less. On clicking else where the context menu would disappear, but the file would remain selected. In this moment, clicking on other files would select or deselect them. The context menu would reappear after  a certain amount of delay when no more clicks are done. This would make it easy for people who are familiar with usual touch interfaces and would also make it easier for new people to get used to it. It would work the same way with mouse, touch-pads, track-balls or any other pointing device. This would also open up opportunities for touch screen devices like tablets or touch-enabled laptops

**Comment by SubhadeepJasu** [comment]
If elementary OS is supposed to run on touch-screen interface devices. It also opens up opportunities for touch-screen laptops and tablets. But would require some more work, like press-and-hold the icon to select it, but would also open the context menu somewhere outside or to the side of the window, so the user can easily tap and select more files to add to selection. Also an option to deselect all files or select all files must be added in that case, but only if it is a touch device.

**Comment by jeremypw** [comment]
The old PR has been closed as there have been too many related PRs merged ahead of it and there are more in the queue.  This will be revisited when the backlog is shorter and is not related to button handling.

**Comment by jeremypw** [comment]
Closing as there is now an option for single-click select for folders.
