### ISSUE TITLE
Don't depend on LibPlank

### ISSUE THREAD

**Issue by danirabbit** [elementary/files#2292]
### What Happened?

We currently depend on LibPlank for the PoofWindow, but (hopefully in OS 8) we'll be leaving Plank behind for a new Wayland-compatible dock

### Steps to Reproduce

Try to build without LibPlank I guess :sweat_smile: Relevant code is in BookmarkRow.vala

### Expected Behavior

We should either:
a. Move this PoofWindow stuff into Granite, if we intend to make this a pattern that all apps should use for removing draggable items
b. Move it into Files if this is a Files-specific thing
c. Just not have this at all

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I think the only other thing using it is Plank itself.  I think we might as well lose it from Files if it is not intended to make it a general pattern for removing sidebar items in all other apps.

**Comment by jeremypw** [comment]
I guess we can lose dragging items out of the sidebar altogether not just the animation.  Code and settings plugs do not implement that.
