### ISSUE TITLE
Refresh required before cut/paste will work if file is renamed

### ISSUE THREAD

**Issue by FunkySalamander** [elementary/files#2295]
### What Happened?

If I want to cut/paste a file that was recently renamed the filename cut to the clipboard reflects the old name not the renamed filename until the folder view is refreshed with the refresh button in the file manager. The cut/paste operation will fail until the refresh button is hit & the operation is retried.

### Steps to Reproduce

1) Copied a file from my phone to the desktop.
2) Renamed the file
3) Cut the file
4) Pasted the file to its permanent home
5) Upon receiving the error dialog I recall this bug
6) Go back & refresh the folder
7) Cut the file again
8) Paste the file to its permanent home sucessfully

### Expected Behavior

1) Copied a file from my phone to the desktop.
2) Renamed the file
3) Cut the file
4) Pasted the file to its permanent home

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

Edit:
Recreated the errant behavior with a generic new file to get the error message (In this case I renamed 'new file' to 'newfile.txt' & tried to cut/paste that):

Error while copying
There was an error getting information about "new file".
Details
`Error when getting information for file “/home/chrisbartels/Desktop/new file”: No such file or directory
`
Cancel  Skip All  Skip  Retry

**Comment by jeremypw** [comment]
Deselecting the file and reselecting also fixes the issue.

**Comment by FunkySalamander** [comment]
This also affects the destination, in the case where I create a directory but don't enter it before trying to paste into it.

**Comment by jeremypw** [comment]
The linked fix also deals with that issue.
