### ISSUE TITLE
Cannot use bulk rename selection

### ISSUE THREAD

**Issue by Efejn** [elementary/files#2298]
### What Happened?

Hello! First of all, I apology in advance for potential mistakes as it is the first time I write in Github and I am not very familiar with this community...

So, as the title says, I cannot use the bulk rename option with Files: it is greyed out in the option panel.

Thank you very much for your help!

### Steps to Reproduce

1. I select the files I want to rename
2. I click right to show the panel options
3. I search for 'rename'

### Expected Behavior

The 'rename' option is greyed out. I cannot click on it.

### OS Version

6.x (Odin/Jólnir)

### Software Version

Latest release (I have run all updates)

### Hardware Info

HP Elitebook 
Six hearts AMD Ryzen 5 pro 5650u with radeon graphics
Advanced Micro Devices, Inc. [AMD/ATI]
7,1 GiB RAM
64,7 GB storage (SSD NVMe)
Uses in French

**Comment by jeremypw** [comment]
Note: Files with limited access permissions usually have an emblem attached to the icon like a "lock" or "no entry" sign.

**Comment by jeremypw** [comment]
Correction: You do not need access to the files themselves it is write access to the parent folder only that you need.

**Comment by lenemter** [comment]
elementary OS 6 has Files 6.3.0 but bulk rename was added in 6.4.0.

**Comment by jeremypw** [comment]
That would be a simpler explanation!

**Comment by Efejn** [comment]
> I am using Elementary Horus (7.0) and I cannot reproduce this provided _all_ the selected files can be renamed (i.e. you have the appropriate access permissions). Where are the files you are trying to rename located? Locally or on a remote server? Can you rename them all individually?
> 
> Does bulk rename work if you try it on files you definitely own e.g. documents in the Documents folder?

Yes, I totally own the documents I want to rename and they are located on my laptop not on a server.

**Comment by danirabbit** [comment]
I'm not sure if Files will still build for 6.x. It looks like we do have new enough Handy for the tabbar. Might be worth trying to build it in a VM and then if that works we can try daily and then see if it's possible to release there

@jeremypw it looks like our build deps are really out of date in the packaging branch as well as in the meson and README. I've submitted a couple branches to update those where I could see. If you could check that and add anything that would be lovely :)
* https://github.com/elementary/files/pull/2299
* https://github.com/elementary/files/pull/2300

**Comment by jeremypw** [comment]
I am going to close this as looks like it was an issue with the age of the version used.
