### ISSUE TITLE
Help option does not work if there is a busy Files process

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#2305]
### What Happened?

Typed `io.elementary.files -h` and got output:
`GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
`
Prior to this I was using Files to display a location on a server that was inaccessible.

### Steps to Reproduce

1.  Connect a server and display a location on it
2. Close Files (with History/Restore Tabs ON)
3. Disconnect the server by e.g. turning off the network
4. Re-open Files - the tab enters a persistent working state
5. In a Terminal type `io.elementary.files -h`
6. Observe error message - Files may also crash

Also happens if the command is issued while a large folder is being loaded.

### Expected Behavior

Help output appears

### OS Version

8.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
See above
```

**Comment by jeremypw** [comment]
Closing this as this option has started working after a reboot.

**Comment by Marukesu** [comment]
i would reopen this and re-target to the fact that we currently do a DBus call for this when we have all the information needed to do in the new process itself.

**Comment by jeremypw** [comment]
Maybe better to open a wishlist report proposing the desired change in coding, unless steps to consistently reproduce the issue can be found.

**Comment by Marukesu** [comment]
i believe you can trigger this easily by blocking the global main context for long enough time. think about, loading a folder with a lot of files in it. and while it's loading, call `io.elementary.files -h`.

**Comment by jeremypw** [comment]
OK, thanks but, forgive my ignorance, I am not sure how to fix this - are you able to push a PR some time?

**Comment by Marukesu** [comment]
Sure, it's pretty straight-forward, i can send a PR later today.

**Comment by janxkoci** [comment]
Will it also fix a timeout I observed [here](https://github.com/elementary/files/issues/1858#issuecomment-1701191315)? My error didn't mention DBus, but otherwise the symptoms looked the same (Jeremy was trying to reproduce the same issue at the time).

**Comment by jeremypw** [comment]
@janxkoci The linked PR only addresses reacting to the CLI when already running so I do not think it will fix the underlying cause of the UI freezing in your situation.

**Comment by janxkoci** [comment]
I understand that, I just meant if the timeout in my error is the same as your DBus error, or if there may be another similar bug to be fixed. I know the freezing will be more complex.

**Comment by jeremypw** [comment]
Yes it should fix the timeout after the `--version` command.
