### ISSUE TITLE
Allow double clicking on the tab bar to duplicate the clicked tab

### ISSUE THREAD

**Issue by wout** [elementary/files#2308]
### Problem

Some applications (e.g. Code, Terminal) allow the creation of new tabs by double-clicking on the tab bar, while others don't. Files is one of them (and Web too). I find myself doing it often.

### Proposal

If a user double-clicks on the tab bar in files, create a new tab.

### Prior Art (Optional)

Code and Terminal do it.

**Comment by jeremypw** [comment]
This appears to be due to Files switching from Granite.DynamicNotebook to Hdy.TabView and Hdy.TabBar in preparation for the move to Gtk4. The Granite widget presumably implements the desired behaviour by default but we would have to implement ourselves with the Gtk4 widget I guess.

**Comment by jeremypw** [comment]
Note: The shortcut `<Ctrl><Alt>T` has the same effect and that still works.

**Comment by jeremypw** [comment]
Had a quick look into and it may not be easy to re-implement because of the sealed nature of the new widgets.  Would be easier to add new behaviour to the Add button to allow duplicating the current tab if double-clicked or a modifier pressed.

**Comment by danirabbit** [comment]
@wout can you open an issue report about this upstream against LibAdwaita? That would be the best way to fix it for everyone: https://gitlab.gnome.org/GNOME/libadwaita

**Comment by wout** [comment]
> @wout can you open an issue report about this upstream against LibAdwaita?

Sure, that's done!

**Comment by wout** [comment]
> Note: The shortcut `<Ctrl><Alt>T` has the same effect and that still works. Double clicking actually duplicates the clicked tab so it does not have the same effect as the "Add Tab" button, which creates a new (default) tab.

Never used that shortcut 😄️. I always use `ctrl+t`. Not sure if adding a new method to create tabs would be as intuitive though.

**Comment by jeremypw** [comment]
`Ctrl+t` has the same effect as clicking the Add button.  `Ctrl+Alt+t` has the same effect as as the "Duplicate Tab" option (or double-clicking the tab).

**Comment by jeremypw** [comment]
Going to close this as "Out of Scope" as  it can best be fixed upstream.
