### ISSUE TITLE
Segmentation fault when opening a folder with xdg-open or keyboard shortcut

### ISSUE THREAD

**Issue by IanHead** [elementary/files#2320]
### What Happened?

Files crashes with a segfault when I launch it with either the keyboard shortcut I set up in Settings, or any xdg-open command.

### Steps to Reproduce

1. Launch files
2. alt-f2, type `xdg-open ~/Downloads`

See the video for a demonstration:

https://github.com/elementary/files/assets/12196401/04fbd170-cd47-4bc1-a0ae-1e35ed1fdf8d

### Expected Behavior

Expected behaviour: Files opens my Downloads folder

Actual behaviour: Files dies ✝

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Looks like regression caused by 830694ee1f37ef749083a6cef8434ca8f629ab2a :disappointed:
