### ISSUE TITLE
Files crash

### ISSUE THREAD

**Issue by sebastien-tiphaine** [elementary/files#2324]
### What Happened?

The File app crash when clicking on the left arrow juste before the folder icon.

** (io.elementary.files:3847): CRITICAL **: 22:08:19.583: files_abstract_directory_view_update_thumbnail_info_and_plugins: assertion 'file != NULL' failed
Erreur de segmentation

### Steps to Reproduce

1. Open File
2. Click on the list style display
3. click on any black arrow placed juste before any folder icon.

### Expected Behavior

This should displays items inside the folder 

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
** (io.elementary.files:3847): CRITICAL **: 22:08:19.583: files_abstract_directory_view_update_thumbnail_info_and_plugins: assertion 'file != NULL' failed
Erreur de segmentation
```

**Comment by jeremypw** [comment]
This sounds like the issue that was fixed by ba8487e3dd1eab3180c27d9e72cbf2b32dbc250f and released in version 6.5.1.  Is the folder you are expanding empty? Does it happen when expanding any folder?  Can you check which version is running with `io,elementary.files --version`?

**Comment by sebastien-tiphaine** [comment]
Ok, since the update of yesterday, the problem seems to be effectively fixed. This was mainly happening on empty folders, but sometimes on other folders too.

My version of files is 6.5.2

Thanks a lot.

Cheers

Seb

**Comment by jeremypw** [comment]
OK, I'll close this issue then. Feel free to reopen if the issue recurs.
