### ISSUE TITLE
Rename triggers scroll to bottom?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/files#2325]
### What Happened?

When Files is sorted on Modified and then rename a file Files seems to scroll to the bottom. 
File name does not seem to matter. 
Viewing mode does not seem to matter. 
The sorting matters, this only seems to happen when sorted on Modified. 

![Rename triggers scroll to bottom](https://github.com/elementary/files/assets/523210/e4aac865-dd75-4e87-8107-af0a6b0089cd)
![Rename triggers scroll to bottom 2](https://github.com/elementary/files/assets/523210/4abb61c2-acf4-4b22-84a0-71a1dbf68b0a)

### Steps to Reproduce

1. Open a folder that has enough files so it's scrolls.
2. Sort on Modified.
3. Rename a file that's high in the list. 

### Expected Behavior

The scroll position doesn't change or follows the renamed file.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Seems to happen only when renaming folders. Investigating.

**Comment by jeremypw** [comment]
Found to be due to a timing issue due to the model sorting now being throttled delayed.
