### ISSUE TITLE
Selection changed on refresh?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/files#2328]
### What Happened?

When you have a file selected and then refresh Files (ctrl+r) the selection seems to change to a random other file.

![Refreshing with selection changes selection](https://github.com/elementary/files/assets/523210/4e9d156a-6f25-4275-84fa-f14863370e23)

Here I select a file, press the down arrow a couple of times, refresh and press the down arrow again a couple of times. 
![Refreshing with selection changes selection 3](https://github.com/elementary/files/assets/523210/0415af80-c6dd-480a-a83a-bafcad3d954e)

### Steps to Reproduce

1. Select a file
2. Refresh files (ctrl+r)
3. Press up or down keys

### Expected Behavior

When pressing up you expect the files above your original file to be selected, when pressing down the one below. 

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Confirmed that the selection is lost and the cursor position ends up at an unpredicatble location.

**Comment by jeremypw** [comment]
I am not sure whether the selection used to persist during a refresh.  If it doesn't then the cursor position should end up predictably at the top of the list.
