### ISSUE TITLE
FEAT New folder with selected items

### ISSUE THREAD

**Issue by svandragt** [elementary/files#2331]
### Problem

Often the user is interaccting with Files because they're going to action multiple files as a single unit (archiving, sharing, moving etc). It's handy then to create a folder with the currently selected files.

Currently the user must:

1. unselect the files, if any are selected)
2. second-click and navigate to new folder (or ctrl-shift-n)
3. reselect the files
4. drag / cut / copy them in the folder
5. (optionally delete the files if copied after actioning the new folder).

The "New" option is not available when multiple files are selected from the context menu

### Proposal

Add a "New folder with selected items..." option to the context menu that creates a new folder, moves all selected items into it, and then started editing the folder name with the existing name selected.

### Prior Art (Optional)

If my memory serves me right, this used to work? I could be wrong. macOS has a similar feature, and it aligns with the elementaryOS values of helping the user be more productive in an elegant way.

**Comment by svandragt** [comment]
Sorry dupe of https://github.com/elementary/files/issues/346

**Comment by jeremypw** [comment]
Thanks for the report.  Maybe I'll have another look at implementing this as it seemed to have some support from the design team but has fallen off the radar.

**Comment by jeremypw** [comment]
Thanks for the report.  Maybe I'll have another look at implementing this as it seemed to have some support from the design team but has fallen off the radar.
