### ISSUE TITLE
Integrate GNOME sushi

### ISSUE THREAD

**Issue by eddieimada** [elementary/files#234]
Not sure if this is the proper way to request a feature, but I would love to see GNOME sushi integrated with pantheon-files for quick preview of files. Ubuntu will ship it by default in 18.04.

http://www.omgubuntu.co.uk/2017/08/ubuntu-17-10-gnome-sushi-by-default
https://github.com/GNOME/sushi

Thanks.

**Comment by jeremypw** [comment]
The roadmap is to simplify Files code so there is no intention to code any preview support.  It may be possible to support Sushi using a .contract file, which requires no changes to Files.

**Comment by jeremypw** [comment]
Another problem is that gnome-sushi has a dependency on nautilus so installation on elementaryos would result in two filemanagers which is not desired.

**Comment by BAProductions** [comment]
> Another problem is that the gnome-sushi package has a dependency on nautilus so installation on elementaryos would result in two filemanagers which is not desired.

No really, Because you could maintain a of gnome-sushi for ElementaryOS thats does not dependency on nautilus at all

**Comment by stsdc** [comment]
@BAProductions another thing to maintain 😅️

**Comment by BAProductions** [comment]
> @BAProductions another thing to maintain 😅️

Yes I agree, But really your only forking gnome-sushi for and removing nautilus dependency & nothing more.
