### ISSUE TITLE
Unexpected selection after creating a new file

### ISSUE THREAD

**Issue by ldrahnik** [elementary/files#2357]
### What Happened?

Probably is missing a visual file selecting in the code when is created Empty file. I did not check that.

### Steps to Reproduce

A newly created file (no selected file in folder -> the right click outside of files -> select Empty file -> enter) is not selected visually but is opened when is pressed enter.

### Expected Behavior

Add selecting a newly created file visually or cancel opening the new file with the enter key when is not selected visually.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
$ io.elementary.files --version
$ io.elementary.files 6.5.2
```
```


### Hardware Info

_No response_

**Comment by jeremypw** [comment]
Just tried to reproduce this with v6.5.2 and find 

 - If the new file is created in an empty folder then it is selected after creation (without renaming) as expected
 -  If there are other files in the folder (whether or not selected) then after creation of a new file then the *first* file in the folder is selected *not* necessarily the new one.  This is a bug.
 - Subsequent pressing the Enter key opens the selected file, not the necessarily the new one.

Right-clicking on empty space deselects any existing selection before showing the menu.

**Comment by jeremypw** [comment]
Strangely this bug only occurs for files - new folders are selected and opened as expected.

**Comment by jeremypw** [comment]
This bug occurs in GridView but not in ListView.
