### ISSUE TITLE
Remove autoswitch to Icon mode

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#236]
Files is intended to switch the view mode automatically to IconView when navigating to a directory with the folder name "/icons/" or /.icons/" in the path, although this seems to be broken at the moment and no issue has been raised about it.

I propose to remove this feature since it has some flaws and it is uncertain how useful it is. This would simplify the code to some extent.  Fixing the flaws would significantly complicate the code.

Main flaws:
* Going back in history does not reverse the switch.
* The switch occurs whether or not the folder being viewed actually contains icons
* It is not possible for the user to switch this behaviour off.

**Comment by danrabbit** [comment]
Indeed, this behavior seems to take choice away from the user on how they want to view their files. If the user intended to use icon view, they could use the view switcher to do so. I'm +1 on removing this feature
