### ISSUE TITLE
Incorrect click coords in a scrolled view

### ISSUE THREAD

**Issue by danirabbit** [elementary/files#2411]
### What Happened?

Clicking in a view that has been scrolled results in a click at the wrong coordinates. This seems to have started after #2399

### Steps to Reproduce

1. Open a folder with a lot of items
2. Scroll down and click on of those items
3. Notice that the selection appears both on the item you selected and on some item above

### Expected Behavior

Clicking an item should select only that item and not a second click in another location :)

### OS Version

Early Access

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Happens in Iconview but not the List or Column Views.
