### ISSUE TITLE
Open in Warp does not check for active instances

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/files#2428]
### What Happened?

Not sure if this is a Files issue or a [Warp](https://github.com/warpdotdev/Warp) issue, but right clicking on a folder in Files and selecting 'Open in Warp' always opens a new Warp window instead of a new tab in the active Warp window (i.e.: same behaviour as with the default Terminal).

### Steps to Reproduce

1. Install Warp terminal
2. Open an instance of Warp
3. Go to a folder in Files
4. Right click and select 'Open in Warp'

### Expected Behavior

A new tab in the active Warp instance should be opened

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
This is almost certainly an issue in Warp. I'm not sure there's anything files can reasonably do about this. It just basically executes a command that asks Warp to open the address of the file, it isn't aware of open windows

**Comment by Gabriel-p** [comment]
Will open an issue there then. Thank  you!
