### ISSUE TITLE
pressing spacebar no longer opens selected file

### ISSUE THREAD

**Issue by janxkoci** [elementary/files#2451]
### What Happened?

I prefer to use spacebar to open files, as it's much closer to my laptop's touchpad. After the latest update and reboot (today) it no longer works. The cursor appears in an empty address bar (in place of breadcrumbs) but does nothing there (no search or path entry works). So I expect this to be bug, and would like to have the original behaviour back.

### Steps to Reproduce

1. Open Files and select some file (or even folder). The view doesn't seem to matter, happens in List or Columns view.
2. Press the `space` bar.
3. This is not what I wanted - cursor in useless place and no file / folder open.

### Expected Behavior

Space bar should open files / folders like it did yesterday. The current version reported:

```
$ io.elementary.files --version
io.elementary.files 7.0.0
```

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by myhousece** [comment]
It's happening to me too! I would really like to appeal back, it is very much needed.

**Comment by jeremypw** [comment]
Yes, looks like a regression - the spacebar is being captured by the searchbar now.  Will fix.
