### ISSUE TITLE
Files column view - width with long file names

### ISSUE THREAD

**Issue by hukipola** [elementary/files#247]
In the column view of Files I would really like that there's an maximum to the column width by default, that is more suitable for long file names. 
I had this issue due to one music album in my collection that had a really long name and it was really ugly to work with this folder from that on.

I had to change the io.elementary.files.column-view.preferred-column-width to 60 and now it's fine.

![screenshot from 2017-11-25 11 51 43](https://user-images.githubusercontent.com/19589577/33281657-3ae6a454-d3a6-11e7-9eb6-70e22e27b0f0.jpeg)

**Comment by jeremypw** [comment]
Removal of autosize columns to longest filename approved by UX team on Slack
