### ISSUE TITLE
Vala 0.39.2: items disappear on hover

### ISSUE THREAD

**Issue by donadigo** [elementary/files#269]
On valac 0.39.2, any directory or file that was hovered in the grid view, immediately disappears. This only happens with the grid view, any other view is fine.

**Comment by davidmhewitt** [comment]
Can confirm this. Compiling with 0.38 or earlier fixes the issue. Might be worth waiting for this bug to be fixed in case it's related: https://bugzilla.gnome.org/show_bug.cgi?id=791785

**Comment by davidmhewitt** [comment]
This was an issue in the GTK .vapi files provided by Vala 0.39.

As discussed in Slack, this has been resolved in the following commit: https://git.gnome.org/browse/vala/commit/?id=c39644a6dc1e2e3930d1f3ff660b62e7b60ea093

Files should hopefully start working again when compiled with the next Vala release.

**Comment by tintou** [comment]
The right valac version is now available in the repository, we now need to reflect the change in Files

**Comment by tintou** [comment]
It looks to work ootb here, closing the issue
