### ISSUE TITLE
Device properties in Files does not include full size

### ISSUE THREAD

**Issue by ghost** [elementary/files#271]
For my Linux installation (Elementary OS), I have split a 500 GB SSD as follows:

20 GB root
16 GB swap
464 GB /home
The problem is, that Pantheon Files is only showing a 20 GB root partition as a device and the rest of it is not shown (as you can see).

My question is: **Why is only a 20 GB partition shown as a device?**

![ncch3](https://user-images.githubusercontent.com/23245678/34257860-e95e4a7e-e65b-11e7-908a-b25112be59ec.png)

Another issue is, that I have two physical 4 TB drives. I use them under Windows 10. One of them is called "backup", the other one is not show under Elementary!

**Why is Elementary showing me only the "backup" drive??**

This is what the program disks is showing me. I expect the same or at least something similar from Pantheon-Files

![screenshot from 2017-12-21 14 17 03](https://user-images.githubusercontent.com/23245678/34257881-f76e2314-e65b-11e7-8f44-1e4de40faabd.png)

**Comment by jeremypw** [comment]
I would not expect a swap partition to show as a storage device.

If you are mounting a partition in fstab as part of the root filesystem (e.g. /home) rather than under /media or /mnt I do not think this should show as a separate device under gvfs (as listed by Gtk.VolumeManager) either.

If you hover over "Filesystem" what size does it indicate 20 or 484 GB?  What size does the device "Win10" show on hovering (or choosing properties from the context menu)? Is this the missing 4TB drive?

**Comment by saitam1** [comment]
It now shows the other 4TB disk. It was a dynamic drive instead of basic. I have now converted it to basic.


But if I hover over Filesystem it shows 10GB free of 20GB and the Win10 device shows 300GB free of 500GB. The drive devices are physically indentical.

**Comment by jeremypw** [comment]
OK, so is there still an issue?  Files is not intended to manage physical devices - you should use something like gparted for that.  Can you tell from what files are displayed when you click on the "Home" that the 464 GB is being incorporated into the root file system OK?  I suppose it could be considered a bug that the "File System" bookmark properties does not include this.

**Comment by saitam1** [comment]
Since the generic term is "Devices" I would say the whole size of a certain device should be indicated instead of just the root file system.

**Comment by jeremypw** [comment]
I agree.  Would you mind changing the issue description accordingly - or open a new issue?  Thanks.

**Comment by saitam1** [comment]
Also if I go to System Settings --> About it shows me the wrong information: 19.5 GB storage

![about](https://user-images.githubusercontent.com/23245678/34319124-0f1e5770-e7da-11e7-8c34-979741057b2a.png)

**Comment by jeremypw** [comment]
Closing as it contains several separate issues.  Please reopen new single issues.  If possible these will be addressed in the Gtk4 rewrite.
