### ISSUE TITLE
Files is not showing progress bar automatically

### ISSUE THREAD

**Issue by saitam1** [elementary/files#272]
When booting eOS and then starting `Files`, it shows no progress bars at all. Only after clicking a device the progress bar is getting loaded. See screenshots:

![1](https://user-images.githubusercontent.com/23245678/34296039-ddd3e186-e710-11e7-94da-50a088104175.png)

![2](https://user-images.githubusercontent.com/23245678/34296045-e0204664-e710-11e7-8ff2-ccd27c4cf929.png)

![3](https://user-images.githubusercontent.com/23245678/34296050-e2393708-e710-11e7-9e6b-735675a60c68.png)

![4](https://user-images.githubusercontent.com/23245678/34296053-e3e9f5c4-e710-11e7-9a1b-33fc3ab8e6c4.png)

**Comment by Ghostboy-287** [comment]
because they're not elementary os partitions so they are not mounted automatically for security reason.

**Comment by jeremypw** [comment]
Closing as this is to do with automounting partitions.  This can be arranged on boot using fstab.  There is already an issue filed about automounting new partitions.
