### ISSUE TITLE
Duplicate Applications after update or installing Tweak Tool from AppCenter

### ISSUE THREAD

**Issue by saitam1** [elementary/files#273]
I don't know what the reason for this was. Either an update or the installation of Tweak Tool from the AppCenter. But it caused, that several apps are available as duplicates. How is this possible and how can I remove them???

![screenshot from 2017-12-21 22 29 45](https://user-images.githubusercontent.com/23245678/34275681-aeeea364-e69e-11e7-9ba2-62e7999cc5b0.png)

**Comment by danrabbit** [comment]
This is an issue tracker for reporting problems with Files. For support questions, please use StackExchange: https://elementaryos.stackexchange.com/

You've likely installed applications that identify themselves using the same name and icon as our default apps, such as GNOME Calculator and GNOME Files
