### ISSUE TITLE
After moving directory executables are not recognized as such any longer

### ISSUE THREAD

**Issue by saitam1** [elementary/files#276]
If I download Sublime Text, I can run it from the Downloads directory, but if I move it via drag'n'drop inside `Files` to another directory, it does not recognize the executable `sublime_text` anymore. 

If I use the terminal and do `mv /Downloads/sublime* /new_destination/sublime`  it works

**Comment by jeremypw** [comment]
Could you check the properties of the sublime_text file after moving with Files?  (Use the context menu option "Properties" and choose the Permissions tab)  Have the permissions changed?

**Comment by jeremypw** [comment]
A quick test with an executable file (not sublime_text) has failed to reproduce this so far (Files v 3.5).  Does it happen both with drag and drop and using cut/paste?  Are you moving within the same filesystem?

**Comment by jeremypw** [comment]
Are there hidden files that are not being moved with Files?  (Press `Ctrl-H` to show hidden files if not already showing).

**Comment by mdh34** [comment]
@saitam1 sometimes files doesn't recognize an executable until i refresh with f5 - have you tried this?

**Comment by saitam1** [comment]
Right now it works. But moving a file or directory into the home directory didn't work right now. It just disappeared into nothing. I am not sure if F5 helped me or it suddenly worked again. strange behaviour anyway..

**Comment by jeremypw** [comment]
If you are compiling from source with valac 0.39.3 then there has been regression causing Icon View not to work properly - should be fixed soon.  Have you tried with List View?

**Comment by jeremypw** [comment]
Closing as it is unclear that this is a reproducible issue with Files.
