### ISSUE TITLE
Files context menu Issue

### ISSUE THREAD

**Issue by ChesterCloud** [elementary/files#277]
I have found a problem with Files app. When I try to  enter by right clicking on files-sub menu "About Files" happens nothing. I think you should fix this or just remove this action.

**Comment by jeremypw** [comment]
Which version of Files are you using?  As far as I can see this option does not appear in the latest version (0.3.5).  Where are you right-clicking exactly?

**Comment by ChesterCloud** [comment]
Version 0.3.5. On plank and launcher.

**Comment by peteruithoven** [comment]
When right clicking on Files in the Plank:
![screenshot from 2018-01-12 11 33 38](https://user-images.githubusercontent.com/523210/34871084-8e2d7a98-f78c-11e7-9fc1-81bec6ef6285.png)

**Comment by jeremypw** [comment]
Could you check whether you have an old org.pantheon.files.desktop file hanging around in /use/share/applications or elsewhere?  I think that might cause this.  You should only have io.elementary.files.desktop (and appdata) files but I am not sure whether the package update removed the old ones.

**Comment by peteruithoven** [comment]
I found `usr/share/applications/org.pantheon.files.desktop`, I can't find a `io.elementary.files.desktop` file.

It would be helpful to know which code is used for 0.3.5.

**Comment by jeremypw** [comment]
Sorry, it seems that 0.3.5 was released in June 17 and the change that removed the About entry was committed in August 17 so it is only in the unstable version - which is the one I use. Presumably something necessary to actually display the help has been removed from the stable version of elementary. I am not sure when of if there will be another stable release of FiIes before Juno, but in Juno, the About entry in Plank will be gone.

**Comment by jeremypw** [comment]
I can confirm that this issue exists as stated on Loki stable, but is fixed in master, so I will close this.
