### ISSUE TITLE
1st Files Window does the same thing as the 2nd one 

### ISSUE THREAD

**Issue by saitam1** [elementary/files#280]
Please do the following thing:

Open one window on a separate physical drive and one window on the eOS drive. Now do something on the eOS drive (go into a folder or go backwards) and the first windows will show the same activity

**Comment by jeremypw** [comment]
I have tried to reproduce this without success using an external USB hard drive. The only action that would be expected to sync across windows that I can think of is "Refresh" and then only if they are showing the same folder.

Can you provide any more information regarding which eos version you are on (release and whether stable or unstable repos). Also whether this always occurs or whether it depends on the type of view (icon, list or column) and whether the action is a mouse action or a keyboard action.  Are you opening the second window from Plank, the terminal or a keyboard shortcut etc?

**Comment by jeremypw** [comment]
Closing as no further info available and could not be reproduced.
