### ISSUE TITLE
Segfault when attempting to view contents of luks encrypted drive.

### ISSUE THREAD

**Issue by quequotion** [elementary/files#287]
The first time clicking on the drive in the sidebar Files asks for a key to open the drive and mounts it appropriately, then crashes. Subsequently any click on the drive to see its contents also crashes Files. Clicking on the eject button to close and dismount the drive works and does not crash Files.

gdb had this to say about it:

    Thread 1 "io.elementary.f" received signal SIGSEGV, Segmentation fault.
    0x00007ffff5a88d3f in g_type_check_instance_is_fundamentally_a () from /usr/lib/libgobject-2.0.so.0

**Comment by jeremypw** [comment]
With the current increase in use of encrypted drives,  it is becoming more important that Files handles them correctly.  There is a branch currently in progress (https://github.com/elementary/files/tree/fix-delayed-mount) related to mounting encrypted drives but it is uncertain that it is related to this issue.

**Comment by quequotion** [comment]
I never got around to trying that branch, but fortunately this is no longer happening.
