### ISSUE TITLE
Low contrast on permissions window

### ISSUE THREAD

**Issue by ramirocantu** [elementary/files#290]
![screenshot from 2018-01-07 22 21 50](https://user-images.githubusercontent.com/19764244/34898942-61a21720-f7bb-11e7-89c7-b6c272cef1b6.png)
## The problem
The low contrast is causing a problem in which budget displays are not reprudicing the contrast well and make hard to read the permission toggles.
## What we can do about it
I propose that we make an enabled button turn blue to make it absolutely clear that it is enabled.

**Comment by jeremypw** [comment]
This is really a stylesheet issue - it would be inappropriate to fix it just in Files.  It would be best to raise the issue at https://github.com/elementary/stylesheet/issues.

**Comment by jeremypw** [comment]
I'll mark this as "Won't Fix' only as far as Files is concerned.  I tend to agree that this could be improved.
