### ISSUE TITLE
Moving back doesn't work

### ISSUE THREAD

**Issue by Djaler** [elementary/files#291]
Reproduce:
1. Open some folder
2. Press Backspace

Expected: navigate back in histore
Actual: nothing

Files version - 0.3.5.1+r2763

**Comment by cassidyjames** [comment]
Backspace is not a good "navigate backwards" key; web browsers are dropping it in favor of other keys like alt+left/right to navigate history and we've done the same.

**Comment by Djaler** [comment]
I did not know about it. But still, this is a fairly common use case. In browsers it is droped, I think, because of interactive content, input fields and all that. There is no such thing In the file manager.

**Comment by jeremypw** [comment]
As far as I can see there was no positive decision or commit to remove this, so its absence appears to be a regression.  I have reinstated it as part of #297 pending any positive design decision regarding this.

**Comment by jeremypw** [comment]
UX team are in favour of removing (not fixing) "BackSpace" for navigation.  The alternatives are "<Alt>LeftArrow" and "XF86Back" (if you have it).

**Comment by Djaler** [comment]
Just a mind - Alt+LeftArrow - two keys. Backspace - one key. This is just easy to use with one hand (if we navigate just by arrow keys and enter, without a mouse).

**Comment by yellowcar1101** [comment]
Honestly, I dont know why no leave it as a setting for the user to decide. This feels like Apple deciding for the user. 

Now I need to waste more time looking for a Files replacement and looking how to uninstall it.

**Comment by sryze** [comment]
In web browsers it makes sense to remove support for the backspace key as navigating back, but in a file explorer I don't think it's a real issue to be honest. Windows File Explorer still supports it.
