### ISSUE TITLE
Single click doesn't work when other folder focused

### ISSUE THREAD

**Issue by donadigo** [elementary/files#292]
Steps to reproduce:
1. Open Files.
2. Enter some folder.
3. Go back.
4. Try to go to different folder.

The single-click doesn't enter the folder anymore. Happens currently in master.

**Comment by jeremypw** [comment]
Maybe related to #288 ?

**Comment by jeremypw** [comment]
The first click selects the new folder (when going back, the folder returned from is selected). A second click is required to activate it.  However, this is inconsistent with behaviour when no other folder is selected, in which case only one click is required to (select and) activate.

**Comment by jeremypw** [comment]
This is a race condition between selecting (on button press) and activating (on button release).  If you pause slightly before releasing then the behaviour is as expected.

**Comment by jeremypw** [comment]
This is due to the introduction of a selection-change signal throttling in order to increase performance for large selections. An alternative solution will be sought.
