### ISSUE TITLE
It it not possible to drag files and folders

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/files#300]
For some reason I wasn't able to drag files and folders in Files. I don't remember if it worked earlier. But this is an issue as of now.

**Comment by jeremypw** [comment]
I could not immediately reproduce this either on Loki stable or unstable.  Which are you on? 

Does this happen in all circumstances or only occasionally?  It is theoretically possible that there could be a set of operations that result in drag'n'drop being blocked  (it is temporarily blocked at some points but should always get unblocked) so if you can identify a particular sequence of operations causing this it would help.

**Comment by jeremypw** [comment]
Note that in ListView you have to drag the icon not the text.

**Comment by SubhadeepJasu** [comment]
Oh wait, its working now. I restarted files like about three times, for some reason its working now. I needed a confirmation that it wasn't a bug that got it. We can safely close this issue now, as it might have been a run time error. I was and am in the big icon view. Wierd! If this happens again we can reopen this issue. Thanks for your time.
