### ISSUE TITLE
GPG support (seahorse?)

### ISSUE THREAD

**Issue by phocean** [elementary/files#304]
It would be nice that Files has GPG support, at least integrating Seahorse actions properly like in Nautilus.

Even though some entries appear in the context menu, the support is broken now, with an error message displayed.

**Comment by jeremypw** [comment]
Which broken entries are you referring to?  Which actions would you like supported? Can they be implemented using commandline parameters for seahorse? In general, elementaryos is in favour of small focussed apps so if it is possible to meet your request using a contractor and an external app that would be preferred.  (See the repo for Contractor for info on how to write your own contracts)

**Comment by phocean** [comment]
I am refering about this one, when you install nautilus-seahorse:

![capture d ecran du 2018-01-25 18 49 41](https://user-images.githubusercontent.com/4280885/35403784-1e1a6890-0201-11e8-9bbb-0bd0107c05d5.png)

Which leads to such an error message:

![capture d ecran du 2018-01-25 18 54 45](https://user-images.githubusercontent.com/4280885/35403822-3c351028-0201-11e8-935b-feb314fcd4cc.png)

Instead, the integration with the seahorse plugin is nice:

![capture d ecran du 2018-01-25 18 51 33](https://user-images.githubusercontent.com/4280885/35403848-51dfff8c-0201-11e8-8723-513efb4dfd9e.png)

Encryption and decryption work flawlessly. Encrypting leads to a window to select recipients:

![capture d ecran du 2018-01-25 18 51 58](https://user-images.githubusercontent.com/4280885/35403878-69bacb78-0201-11e8-9f61-423bd89a660d.png)

I have to check what Contractor is all about, but the current Nautilus way looks compatible with your design goal, as it is simply calling an external app for everything including dialog boxes.

**Comment by jeremypw** [comment]
OK, thanks - I'll look into it further but it sounds as if it could be implemented by one or more .contract file rather than writing a plugin or something.

**Comment by jeremypw** [comment]
I'll also check why the existing "Open with" entry does not work - which decryption app are you using? It may be a problem with the .desktop file (Files just uses this to launch the app, passing the file URL as a parameter)

**Comment by phocean** [comment]
Thanks for your replies. The app is **seahorse**, it is actually a front-end, I believe, to gnome keyring.

I am trying to test as well.

**Comment by phocean** [comment]
Indeed, it is managed by this bunch of files:

```
% ls /usr/share/applications/seahors*.desktop              
/usr/share/applications/seahorse.desktop
/usr/share/applications/seahorse-pgp-encrypted.desktop
/usr/share/applications/seahorse-pgp-keys.desktop
/usr/share/applications/seahorse-pgp-signature.desktop
```

**Comment by jeremypw** [comment]
OK, I only have seahorse.desktop - I guess the others are installed by the nautilus-seahorse integration package??  If you look at the `Exec=` and `MimeType=` lines in these files it will tell you whether File can use them to open files.   `seahorse.desktop` is not suitable - there is no provision to pass a file path as a parameter to this executable.

**Comment by phocean** [comment]
Yes, exactly.

The decryption seems to be made with:

```
MimeType=application/pgp-encrypted;
Exec=seahorse-tool --decrypt
```
Key import:

```
MimeType=application/pgp-keys;
Exec=seahorse-tool --import
```

Signature:

```
MimeType=application/pgp-signature;
Exec=seahorse-tool --verify
```

But there are two problems:

- None of them seems to provisions a file (should be something like `%f`, right?)
- I don't see what allows to encrypt (there is an "encrypt" entry for all file types)

**Comment by jeremypw** [comment]
Reading the man page for seahorse-tool indicates that you should be able to pass a file name parameter - one can try editing the desktop file to be consistent with this.

**Comment by jeremypw** [comment]
Or, better - write  .contract files - one for decrypt and one for encrypt.

**Comment by phocean** [comment]
Yes, decryption works like that. I think I can hack something with Contractor, I will check that.

Wouldn't it be nice to have it packaged for elementary, as a substitute to this seahorse-nautilus package?

I will start with a github repo if I can make it, and update here... (I am not yet familiar on how things work with Elementary, just switched yesterday).

**Comment by jeremypw** [comment]
This worked for me (after installing the nautilus-seahorse package which is not ideal):

```
[Contractor Entry]
Name=GPG Decrypt
Description=Decrypt
MimeType=application/pgp-encrypted
Exec=seahorse-tool -d %f
```

**Comment by jeremypw** [comment]
Just put this in your .local/share/contractor directory.  Not sure where the seahorse-tool comes from though - if it is part of nautilus it is not ideal.  Ideally a stand alone app is needed.

**Comment by phocean** [comment]
Yes, for me too.

And I am reading the Contractor documentation, it seems very powerful and perfect for this stuff, indeed.

Thank you a lot for pointing me in the right direction! I did not expect that it would be so simple, actually.

**Comment by jeremypw** [comment]
The documentation of Contractor is being updated to include more examples of non-standard contracts like this.

**Comment by phocean** [comment]
I dropped my files in this repo, if it can be of any use:

https://github.com/phocean/contracts

**Comment by jeremypw** [comment]
Thanks phocean :-).  Any chance you can submit a PR to the Contractor repository updating the README.md file to reference these contracts under the **Examples** section?

**Comment by phocean** [comment]
Of course, done !

It is me that thank you for your great work, please keep it up, you are doing "Linux on the desktop" right! :-)

**Comment by jeremypw** [comment]
Closing as this will be dealt with by contract files linked with the Contractor repository examples.
