### ISSUE TITLE
"Volume is busy" dialog cuts the list of volumes

### ISSUE THREAD

**Issue by apcamargo** [elementary/files#318]
![screenshot from 2018-02-03 11 37 38](https://user-images.githubusercontent.com/22940964/35865672-449b3f6e-0b3c-11e8-8e88-8df82f7f3a53.png)

If I want to see the volumes that are busy, I need to resize the window.

**Comment by jeremypw** [comment]
This dialog is not produced by Files - I assume produced system volume manager.

**Comment by jeremypw** [comment]
Closing as does not see, to be a Files issue
