### ISSUE TITLE
Re-ordering a folder in one window does not update other open windows

### ISSUE THREAD

**Issue by jlnr** [elementary/files#326]
This is an edge case where the refresh button/shortcut has a visible effect:

1. Open first window showing the Home directory
2. Open second window showing the Home directory
3. Reverse the order of icons in one window via right-click->Sort By->Reverse
4. The other window retains its current order until the view is refreshed

Expected behavior: The refresh should happen automatically, just like "Show Hidden Files" automatically affects all windows.

**Comment by jlnr** [comment]
Quoting you/@jeremypw in #358:

> I am uncertain what the desired behaviour is though.  There may be a use case for viewing two different orders simultaneously.

Good point, that sounds like a plausible use case. I personally expected the sort order to apply to all windows immediately because it's conceptually a property of the directory, not of the window, and I trust Files to refresh directory information reliably. I also found it unintuitive that pressing refresh in one window also updates the sort order in other windows.

Not sure if this is really medium priority, I doubt many people will run into this :)

**Comment by jeremypw** [comment]
Reduced priority and flagged for UX input. I think conceptually the sort order is a property of the view (model) since the files are not re-ordered on disk.   However, Files placed some meta-data on disk which is immediately updated whenever a view showing that directory is re-ordered.  Perhaps this metadata should only be written when the last view of the directory is closed.

**Comment by jeremypw** [comment]
In the early Gtk4 version, the sort order of the same folder in different windows persists during a refresh (unlike current version).  I think I'll close this as it will not be fixed in the Gtk3 version.  A new issue can be raised if the Gtk4 version is problematic.
