### ISSUE TITLE
DLNA Explorer on io.elementar.files

### ISSUE THREAD

**Issue by torikulhabib** [elementary/files#329]
i hope support DLNA explorer 
because there is option for enabling just access on smartphone dlna explorer but can not access with pc elementary OS.
![screenshot from 2018-02-12 08 13 33](https://user-images.githubusercontent.com/26135527/36081067-a59ae6ae-0fcc-11e8-92b0-7bfa02071402.png)

**Comment by jeremypw** [comment]
Maybe a plugin can be written using this resource - https://01.org/dleyna?  A blueprint is needed first.
