### ISSUE TITLE
Juno - Open in Terminal appears twice - one does not work

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#334]
In the background context menu, the first item is now "Open in Terminal" but this entry does not have any effect.  The same entry under "Open with ..." works as usual.

**Comment by jeremypw** [comment]
This was due to the default file browser being set to "Terminal" in the applications Switchboard plug.  Not sure whether I did this or not but will close on the assumption I did.

**Comment by danrabbit** [comment]
I'm going to reopen this because I also have two "Open in Terminal" items on a relatively fresh Juno daily. I'm not sure if this is an issue in Files, but it's worth tracking

**Comment by mridulganga** [comment]
In Switchboard -> Applications 
Changing `File Browser` to `Terminal` Causes the extra `Open in -> Terminal` option to go but it adds an `Open in Terminal` Item to the Main Menu and this doesn't do anything.  

![open in](https://user-images.githubusercontent.com/3828236/39140747-3129ba3a-4743-11e8-8001-8321fa94ba7d.png)

**Comment by jeremypw** [comment]
This appears to be due to changes in Terminal - this now appears as a suitable app to receive folders as command line parameter so the "special" entry in the "Open in" sub menu is no longer required.  Or the special entry can be kept and the repeat entry in the suitable app list can be filtered out.
