### ISSUE TITLE
Juno - Optical drive does not mount

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#342]
Attempt to mount an optical drive using Juno fails with this terminal output:

[WARNING 19:29:10.743686] [GLib-GObject] invalid cast from 'GTask' to 'GSimpleAsyncResult'
[FATAL 19:29:10.743719] [GLib-GIO] g_simple_async_result_propagate_error: assertion 'G_IS_SIMPLE_ASYNC_RESULT (simple)' failed

The same source compiled on Loki successfully mounts the drive.

**Comment by mdh34** [comment]
This seems to be working in the latest builds
