### ISSUE TITLE
Directory up button

### ISSUE THREAD

**Issue by v01d** [elementary/files#352]
Sometimes, easy access for going up the directory hierarchy is really needed. Using the back button considers history, which doesn't necessarilly mean going up. Clicking on the path components is also cumbersome since they are different size and difficult to click if going many directories up.

**Comment by jeremypw** [comment]
At present the shortcut <Alt>Up provides this functionality.  It is very doubtful whether this is sufficiently important to warrant a dedicated button.

**Comment by danrabbit** [comment]
Yes, going to close as "Design Conflict` since this functionality is already provided by breadcrumbs and a shortcut
