### ISSUE TITLE
Opening a folder on two separate tabs prevents updates in the view

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/files#353]
Steps to reproduce:

- Open a folder with photos, or elements that have a thumbnail (ie: ~/Photos)
- Open the same folder on a second tab
- Close the app
- Re-open the app, one tab will have all the thumbnails as normal, the second one will not be updated. In fact, adding/removing a file on the tab with the thumbnails will not be reflected on the second tab

It can also be reproduced like so:

- Open the app, and go to a folder
- Open a second tab, and go to the same folder
- Try to create a file or a folder. You won't see it appear, but clicking Refresh updates the view

Note: No warnings or errors shown when running from the terminal after doing said actions

**Comment by Shnatsel** [comment]
Confirming this is a problem on Loki
