### ISSUE TITLE
File info badge padding

### ISSUE THREAD

**Issue by Djaler** [elementary/files#355]
As you can see in attached screenshots, badge that appears on file select have so big padding at right. I'm on Juno

![2018-03-10 10 51 19](https://user-images.githubusercontent.com/7964583/37239689-4053bc6e-2451-11e8-88e2-9a99f4a7a9d9.png)
![2018-03-10 10 51 22](https://user-images.githubusercontent.com/7964583/37239690-40730c2c-2451-11e8-82b8-f84b1a814329.png)

**Comment by jeremypw** [comment]
This seems to be specific to video file types.  I think it is due to space being reserved for a spinner that never appears (usually this space is reclaimed when the spinner closes.

**Comment by Djaler** [comment]
Not only videos. I reproduce it with zip archive too, for example. Also, it does not happen every time.

**Comment by jeremypw** [comment]
Closing as it no longer happens in the latest version (or Gtk4 version)
