### ISSUE TITLE
Use admin:/// for administrator operations

### ISSUE THREAD

**Issue by donadigo** [elementary/files#363]
It turns out that you can do admin operations on files or any other process if you use the `admin:///` URI scheme instead of the `file:///` one. In this case we should make all the context menu entries in root protected directories enabled and use this URI to allow the user to perform wanted operations.

**Comment by mdh34** [comment]
at the moment, putting `admin://` into the address bar of files and authenticating allows most standard procedures like renaming, deleting etc. A few things i noticed were that permissions aren't available, and copying files creates a file owned by the current user rather than root.

**Comment by danrabbit** [comment]
Closing as a duplicate of #165
