### ISSUE TITLE
Renaming Files in Downloads Folder

### ISSUE THREAD

**Issue by xayden** [elementary/files#366]
Renaming files in downloads folder seem to be impossible, it appears that I can rename the file but after 1 second, it cancels the renaming.

**Comment by Djaler** [comment]
Can you provide screencast?

**Comment by xayden** [comment]
It's working properly now, but I don't know why!

**Comment by jlnr** [comment]
This sounds like it could be caused by #87.

**Comment by xayden** [comment]
Yeah, that was the case with me, though I was doing the workaround suggested there I thought it's better to report the issue. Thanks for the response.
