### ISSUE TITLE
Open in Files

### ISSUE THREAD

**Issue by Djaler** [elementary/files#375]
First entry in context menu for folders - "Open in Files". Is it really needed?

**Comment by danrabbit** [comment]
Can you post a screenshot? I don't see an option for this. Do you perhaps have another file manager like Nautilus installed?

**Comment by Djaler** [comment]
This sounds strange, but when I change language to English, this entry is gone. You can see this at screenshots (the first entry on the second screenshot)
![screenshot from 2018-03-23 21 29 48](https://user-images.githubusercontent.com/7964583/37847363-aa7f8678-2ee1-11e8-830c-89cb096bfcde.png)
![2018-03-23 21 30 42](https://user-images.githubusercontent.com/7964583/37847364-aa9f6632-2ee1-11e8-9e8f-43200ee49b5c.png)

**Comment by Djaler** [comment]
So, can you try to change language?

**Comment by Djaler** [comment]
Look like this is the place https://github.com/elementary/files/blob/master/src/View/AbstractDirectoryView.vala#L2018

**Comment by Djaler** [comment]
Yeah, this is because of https://github.com/elementary/files/blob/master/src/View/AbstractDirectoryView.vala#L2017
`if (app_name != Marlin.APP_TITLE) {`
