### ISSUE TITLE
File picker doesn't navigate back on "Backspace" key

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#388]
![screenshot from 2018-03-24 15-53-55](https://user-images.githubusercontent.com/22585732/37862978-4a0964f8-2f7c-11e8-9f23-19a746031920.png)

**Comment by danrabbit** [comment]
This is a duplicate. We don’t use backspace as a navigation key. Major browsers have dropped this convention. Closing as “Design Conflict”

**Comment by uncertainquark** [comment]
Browsers have different use cases to drop this convention (losing a filled form for example). But there is no such thing to lose here by navigating back.

On the other hand, a user would expect the file picker to behave similar to the file manager where backspace key goes back.

So drawing parallels from the browser here doesn't really apply IMO.

**Comment by uncertainquark** [comment]
@danrabbit Its doing so for me ATM in 0.4 Loki. Do you mean it doesn't anymore in master branch?
