### ISSUE TITLE
Enable "Ctrl+Tab" navigation between Tabs in the File Manager

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#389]
Currently: 
1. Ctrl+T opens a new tab
2. Ctrl+W closes the existing tab

Since, both of the shortcuts are akin to a modern web browser, so should the tab navigation be possible with "Ctrl+Tab" for familiarity and discoverability. 

![screenshot from 2018-03-24 15-50-57](https://user-images.githubusercontent.com/22585732/37863188-333797e6-2f80-11e8-96eb-4c5353734b3c.png)

**Comment by jeremypw** [comment]
Ctrl + Tab does switch between tabs in master (added by commit https://github.com/elementary/files/commit/106054ed3966f3212f79797f7e16bfd676ea50ea)
