### ISSUE TITLE
Deleting a selected file using the keyboard forgets the navigation position

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#390]
Here is a file that I select using keyboard navigation:
![screenshot from 2018-03-24 16-30-16](https://user-images.githubusercontent.com/22585732/37863229-b423e0bc-2f80-11e8-9e30-090ebfaee182.png)

I then delete the file and I expect the next file should be selected by default. But the file manage completely forgets the navigation state and its destructive in consequence.
![screenshot from 2018-03-24 16-30-27](https://user-images.githubusercontent.com/22585732/37863230-b8000454-2f80-11e8-8592-f525b82ccbb7.png)

**Comment by jeremypw** [comment]
I am not entirely convinced - in some circumstances this could cause accidental deletion of the next file e.g. if it has a similar name and icon (so the user thinks the previous deletion did not happen) or the delete button is held down too long.  I suppose these possibilities could be mitigated by waiting for key release before selecting the next file.

**Comment by jlnr** [comment]
If Files waits for key release, it could look like the selection is flickering when deleting files quickly.

I think it's pretty satisfying to clean up junky directories by repeatedly pressing delete and maybe some arrow keys; like deleting spam in an email inbox.

**Comment by jeremypw** [comment]
For multiple deletions its probably better to select all the files first (which can be fast if they are contiguous (Use Shift-Click or rubberband) and then press Del.

**Comment by jeremypw** [comment]
The inked PR remember the cursor position after deletion although it does not select the file at that position because of concerns of accidental deletion.  Pressing an arrow key will select the item at the cursor position.  Note there is an outstanding issue concerning showing the position of the cursor independently from the selected status of items.
