### ISSUE TITLE
Set custom icon on folder

### ISSUE THREAD

**Issue by Djaler** [elementary/files#392]
For example, I have some cool icon in elementary style for dropbox folder. And I want to set it to dropbox folder. But I can't. Yeah, I can make Dropbox folder one on xdg directories and override icon, but it's a crutch.

**Comment by jeremypw** [comment]
It would be necessary to decide where to store the custom icons. see https://gitlab.gnome.org/GNOME/nautilus/issues/196.

**Comment by micahilbery** [comment]
Could we not store the custom icons in `~/.local/share/icons/`?

**Comment by jeremypw** [comment]
That is one possibility.

**Comment by Djaler** [comment]
Another question is where to store info about directory icon. Maybe in hidden file inside the directory? This way it works in dolphin (kde)

**Comment by jeremypw** [comment]
Another possibility is to use a custom file attribute (metadata) - this is the way Files stores the preferred sort column and order for the folder.

**Comment by Djaler** [comment]
Oh, I didn't know about this feature. Yeah, this would be better solution

**Comment by aljelly** [comment]
Isn't this a duplicate of #171?

**Comment by jeremypw** [comment]
Hmm, yes you're right.
