### ISSUE TITLE
Mounting encrypted drive in Juno errors

### ISSUE THREAD

**Issue by btkostner** [elementary/files#395]
Trying to mount an encrypted drive in Juno alpha fails.

```
Error unlocking /dev/nvme0n1: The function
'bd_crypto_luks_open_blob' called, but not implemented!
```

![screenshot from 2018-03-26 09 44 50](https://user-images.githubusercontent.com/3385679/37916928-58e94af6-30da-11e8-91f4-169ebf72884e.png)

```bash
btkostner@New-Caprica:~$ uname -a
Linux New-Caprica 4.15.0-12-generic #13-Ubuntu SMP Thu Mar 8 06:24:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

![screenshot from 2018-03-25 15 31 06](https://user-images.githubusercontent.com/3385679/37916955-68552f6e-30da-11e8-9707-22c6c3bdf258.png)

**Comment by mrdvdrm** [comment]
It seems it's a dependency problem of Ubuntu 18.04 with LUKS.

sudo apt install libblockdev-crypto2
systemctl restart udisks2.service

will solve the problem.

**Comment by jeremypw** [comment]
Closing as outdated.  Please reopen if occurs in Elementary OS 7 (Horus)
