### ISSUE TITLE
Home folder artifacts

### ISSUE THREAD

**Issue by Djaler** [elementary/files#40]
Sometimes I have a strange bug. In various folder I can see files from ~. You can view example in attached screencast
[screencast.zip](https://github.com/elementary/files/files/1096082/screencast.zip)

**Comment by jeremypw** [comment]
You video seems to start with Files already in a strange state.  Could you describe the steps leading up to this?

**Comment by Djaler** [comment]
I didn't find steps to reproduce it. Just saw once again and immidately record it

**Comment by jeremypw** [comment]
I can reproduce something similar when drag/dropping tabs between windows. Is that something you might have done?

**Comment by Djaler** [comment]
No, but I oftentimes navigate between tabs

**Comment by jeremypw** [comment]
OK.  Without some way of reproducing it, it is not really possible to proceed.  I'll wait to see if anyone else can confirm it.

**Comment by matzipan** [comment]
Should this issue be closed or marked as incomplete?
