### ISSUE TITLE
Implement org.freedesktop.portal.FileChooser [$65]

### ISSUE THREAD

**Issue by tintou** [elementary/files#403]
In the future, we will need to promote the use of [Gtk.FileChooserNative](https://valadoc.org/gtk+-3.0/Gtk.FileChooserNative.html) which can use the FileChooser portal to show the selector and thus allowing Files to provide this dialog instead of relying on a Gtk+ module.

**Comment by worldofpeace** [comment]
I'd like to also mention that GTK4 is removing module support.

**Comment by skewty** [comment]
This is related to #129 also

**Comment by autun12** [comment]
Hey I was wondering what is expected as a solution to the issue because I had seen to different issues referenced here.
