### ISSUE TITLE
Don't ask users to choose between two identical files.

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/files#404]
If files are identical in modified time and size, then when I copy or move a folder over another why prompt me to choose between each copy. They are most likely identical and it would allow me to actually make decisions rather than being forced to choose a replace or skip option. Certainly, with the current FileConflictDialog I am given no more information or reasonable alternative for a large group of files.

Related to #164

**Comment by artemanufrij** [comment]
@lewisgoddard it would help if one of the booth files is corrupt. I had it with an USB-Device.

**Comment by jeremypw** [comment]
The user is probably the best person to know whether files are really identical or not (unless we hash each file which I suspect would be costly).  If they are identical it doesn't really matter whether skip or replace is chosen.  I do not think Files should be making this call.

**Comment by lewisgoddard** [comment]
My point is that out of a couple of thousand files, there are only a couple that aren't identical. Why prompt me for everything else? It just reduces my ability to make individual judgements.

**Comment by jeremypw** [comment]
It sounds like you are using Files to do backups? Probably best to use a dedicated tool for this.

**Comment by jeremypw** [comment]
That being said, if a dev puts forward a PR acceptable to the UX team it would be accepted.

**Comment by lewisgoddard** [comment]
@jeremypw It's not backups per-se, it's when I take a directory of stuff I've been working on away on a USB to do work on a different machine, but I can't guarantee that I haven't made changes to both copies and want to merge them.

My problem would be totally fixed #405

**Comment by jeremypw** [comment]
OK.  #405 is easier to implement.

**Comment by jeremypw** [comment]
#405 Now in progress.

**Comment by jeremypw** [comment]
Closing as it has been acceptably fixed by fixing #405.
