### ISSUE TITLE
Add a "keep newest" option to FileConflictDialog

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/files#405]
Currently in FileConflictDialog you can either "Skip", "Replace", or "Rename", where "Rename" requires manual entry for each file. When copying near-identical folders over each other, I frequently find myself preferring a non-existent "keep newest" option that I can quickly apply to all future conflicts.

Related to #164

**Comment by jeremypw** [comment]
This sounds like a good idea.  I'll flag for UX input.

**Comment by jeremypw** [comment]
I presume "keep newest" means "most recently modified" rather than "most recently created".
