### ISSUE TITLE
Wrong context menu

### ISSUE THREAD

**Issue by Djaler** [elementary/files#41]
Sometimes I see context menu with directory actions instead of file actions. You can see this in attached screencast

[screencast.zip](https://github.com/elementary/files/files/1096116/screencast.zip)

**Comment by jeremypw** [comment]
You need to right click on a selected icon.  It seems this issue is because right-clicking is not pre-selecting.

**Comment by Djaler** [comment]
But most of time it works well with right-clicking on not selected icon

**Comment by jeremypw** [comment]
It seems to depend on whether there is already another item selected.
