### ISSUE TITLE
Bug reporting URL points to launchpad

### ISSUE THREAD

**Issue by krantideep95** [elementary/files#412]
Files version: 0.3.5
Ubuntu 16.04
When pantheon-files is run from terminal, the message printed about bug reporting points to launchpad, instead of github:
`[INFO 16:13:37.986641] Application.vala:82: Report any issues/bugs you might find to http://bugs.launchpad.net/pantheon-files`

**Comment by arshubham** [comment]
@krantideep95 It has been fixed in master. https://github.com/elementary/files/blob/fccfa34f0e83242269451962ba203fb75593d193/src/Application.vala#L66 . You will see the change whenever the new version is available.
