### ISSUE TITLE
Opening paths containing spaces via org.freedesktop.FileManager1 fails.

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/files#42]
A properly URI encoded path such as the following sent to the `ShowItems` method causes Files to try and open an incorrect path.
`file:///home/david/Downloads/Torrent%20Downloads/podcast.mp3`

For the example above Files tries and fails to open the following path:
`/home/david/Downloads/Torrent0Downloads/podcast.mp3/`

I have tested with Nautilus to check that the path I'm sending is well formed and it had no issue.

**Comment by vjr** [comment]
So looks like the path needs to be escaped and enclosed in quotes here: https://github.com/elementary/files/blob/master/pantheon-files-daemon/FileManager1.vala#L46 probably using this: https://github.com/elementary/files/blob/master/libcore/FileUtils.vala#L160

@davidmhewitt are you sure you're sending the path the right way? Does the escaping need to be done by you (the caller of `ShowItems`) or should it be done in the code like I'm thinking above?
