### ISSUE TITLE
Breadcrumb animates in from outside the pathbar

### ISSUE THREAD

**Issue by danrabbit** [elementary/files#420]
This might be a HiDPI-specific quirk. When moving from another path to the home folder, the icon and label animate in from what looks to be something like 12px to the left of the pathbar

**Comment by jeremypw** [comment]
On LoDPI, at least, this happens mainly when navigating from "File System" and "Network" and "Recent" to any local subfolder.

**Comment by jeremypw** [comment]
Regression since Loki stable release.
