### ISSUE TITLE
Google Drive Option in Files

### ISSUE THREAD

**Issue by mridulganga** [elementary/files#432]
Gnome's `Online Account` has an inbuilt Option to connect Google Drive to Nautilus. Even Linux Mint has implemented that feature in Nemo. It would be great if we had native support for Drive, Dropbox etc.

![Gdrive](https://www.howtogeek.com/wp-content/uploads/2017/01/ximg_588a63a298435.png.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.V4WbRVRa5m.png)

**Comment by jwinnie** [comment]
Duplicate of #172?
