### ISSUE TITLE
[feature-request] context menu icons

### ISSUE THREAD

**Issue by monkeydri** [elementary/files#439]
I don't know if pantheon-files relies on GTK in which case it might not be possible, however it will be very good if some icons were added to context menu (copy/paste/rename...), it makes it much faster to find the correct action.

If icons are consistent (same theme and color) to me it does not make pantheon-files less slick.

**Comment by jeremypw** [comment]
This is not really a Files issue - a change of policy on this would have to apply to all elementary apps in order to maintain consistency.  Not sure of the appropriate place to raise - maybe the stylesheet repo?

**Comment by monkeydri** [comment]
glad to hear that ! I happened to work on a vietnamese computer lately and I just thought I would have been 100x easier with icons here and there (it was a windows computer and I don't speak a work of vietnamese).

**Comment by danrabbit** [comment]
I think this is now closed by #788 ?
