### ISSUE TITLE
[feature-request] mix files and directories/folders - do not display directories/folders first

### ISSUE THREAD

**Issue by monkeydri** [elementary/files#441]
I would like the listing of a directory to list files and directories equally, not directories first. At least it could be available with some dconf option.

It is especially counter-intuitive when sorting by modification date, old directories appear on top of new files.

**Comment by jeremypw** [comment]
At present, the pantheon-file-choose module honours the gtk file-chooser setting in this respect, but Files itself does not (although the code to do so is mostly present so it would be easy to implement).  Elementary design philosophy is generally against the multiplication of options and settings, particularly in the UI.  However, I'll flag this for UX team input.

**Comment by aljelly** [comment]
Personally I'm used to folders first as I came from Windows, but I can understand others preferring folders and files equally sorted. One's preferences regarding this could depend on what OS you came from (Windows sorts folders first, macOS sorts equally).

If this is to be added, I imagine the best place to put it would probably be in the right click menu under the 'Sort by' submenu. Similar to the 'Reversed Order' tick box and positioned above or below it, there could be a 'Folders First' (or some other wording) tick box. It would be enabled by default to reflect the current way folders are sorted.

**Comment by jeremypw** [comment]
I guess this would be a reasonably unobtrusive way of doing it.

**Comment by jeremypw** [comment]
I have pushed a PR binding the Files behaviour to that of the Gtk FileChooser.  So at least there is consistency and you can choose the desired behaviour by changing the Gtk setting.  I have not included any UI in this PR and it may not be accepted.

**Comment by monkeydri** [comment]
Thanks a lot @jeremypw ! I just updated to release 4 (which includes this commit 1658742) and indeed it does respect the GTK FileChooser setting (`org.gtk.Settings.FileChooser sort-directories-first`). Awesome !

4.0+r3212+pkg71~daily~ubuntu5.0.1

**Comment by monkeydri** [comment]
Well it is now broken, I had not updated for a while and I just updated to latest (commit `45b3cd5e11`).
Now when sorting by date the files always appear on top of folders, regardless of modification date.

GTK FileChooser setting sort-directories-first is set to false
Pantheon file folder setting Sort By > "Folders before files" is unchecked (if I check it folders appears on top but newer files appear below, ie. not mixed).

**Comment by jeremypw** [comment]
@monkeydri Yes, sorting with folders first (or not) only works properly with sort-by-name at the moment :-(.  There is a PR #932 to fix this awaiting approval.  Note the modification date of a directory is only when it was created or renamed I think, not when a file inside it was modified.

**Comment by monkeydri** [comment]
Alright thank you very much again, will update when this PR is merged.

Regarding modification date yes I know a folder "modified date" is not updated when a file within it is modified however it works for some directories, ex. I have a dir with vscode projects (directories) and their "modified date" is updated on file change, probably by vscode itself.
