### ISSUE TITLE
Selection icon cut on small images

### ISSUE THREAD

**Issue by inad9300** [elementary/files#447]
When entering the folder (also when removing the screenshots):
![before-screenshot](https://user-images.githubusercontent.com/3440331/39407689-16e745b2-4bca-11e8-822b-2fd31ae0e1aa.png)
After taking a screenshot (also when pasting the small image so that only the two small images exist in the folder; and also when refreshing the view with Ctrl + R):
![after-screenshot](https://user-images.githubusercontent.com/3440331/39407691-190055c8-4bca-11e8-968b-6aad346287cd.png)
By the way, please notice how blurry the pictures icon looks on the address bar. It's pretty much like this for all icons...

**Comment by jeremypw** [comment]
This occurs when the height of the icon/thumbnail is less than that of the helper.  (The matter of blurry pathbar icons is a separate issue).
