### ISSUE TITLE
Position of "Downloads" folder in sidebar is inconsistent with the File Picker

### ISSUE THREAD

**Issue by moonmehta** [elementary/files#451]
The File manager sidebar shows the "Downloads" folder at the bottom, inconsistent with the alphabetical ordering of the rest of the folders. 
![screenshot from 2018-04-28 23-31-33](https://user-images.githubusercontent.com/22585732/39560102-cc66e942-4eb8-11e8-8c5a-f357b1b32881.png)

Alternately, if its a design choice (for some reason), it is inconsistent with the position of the "Downloads" folder in the file picker.
![screenshot from 2018-05-03 09-48-44](https://user-images.githubusercontent.com/22585732/39560105-e55b23fa-4eb8-11e8-9dfb-78031b85f483.png)

Fixing either would be okay, depending on the context of the design decision taken by the UX team previously.

**Comment by jeremypw** [comment]
This is not trivial to fix since Files uses its own custom sidebar and the FileChooser is a modification of the GtkFileChooser which still has the native Gtk+3 sidebar.  In principle it may be possible to replace the Gtk widget with a cutdown version of the Files sidebar.

**Comment by uncertainquark** [comment]
Does this get affected/solved by the [new native file chooser](https://medium.com/elementaryos/a-new-native-file-chooser-196acf9b06f0)?

**Comment by jeremypw** [comment]
Yes, apps which use the native file chooser interface will basically launch an instance of Files as I understand it.

**Comment by donadigo** [comment]
I began working on this here: https://github.com/elementary/xdg-desktop-portal-pantheon/pull/2

**Comment by 4jNsY6fCVqZv** [comment]
Sidebar in FileChooserDialog
![Screenshot](https://user-images.githubusercontent.com/46536067/144112095-ce7d6fee-6c11-4beb-ba12-c7d149711c20.png)

Sidebar in Files
![Screenshot](https://user-images.githubusercontent.com/46536067/144112800-48d3fee7-bcba-4f10-a6fa-59303a985609.png)

I use a stable elementary OS with the latest updates.

How come that even with the new FileChooser the positions are still not consistent?

**Comment by jeremypw** [comment]
This is a consequence of Files only partially modifying the default Gtk filechooser.  It does not currently currently replace the sidebar with a Files sidebar, it only replaces the pathbar and actions bar.  Hopefully, the remaining widgets will be replaced in the future.

**Comment by jeremypw** [comment]
Closing as it possible to reposition the bookmarks in Files.
