### ISSUE TITLE
Give option to automatically delete files trashed more than 'X' days ago.

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#452]
The days could be 7, 14, 30 and so on.

**Comment by jeremypw** [comment]
This could only (simply) be implemented to work while Files is open.  Do you envisage a confirmation dialog first ?

**Comment by uncertainquark** [comment]
The idea is that having the thrash to be automatically emptied after X days is a one-time setting, akin to the option GNOME has in their Settings app. After that point, it works automatically in the background so no user intervention is supposed to be needed. Sorry that I was not clear the first time.

**Comment by jeremypw** [comment]
Do you mean that the trash is completely emptied after X days?  Or that files that were trashed more than X days ago are permanently deleted?

**Comment by uncertainquark** [comment]
I mean the thrash is completely emptied after X days.

**Comment by uncertainquark** [comment]
Sorry, I for confused with the two options. What I meant is what you said in the latter part:
 >  files that were trashed more than X days ago are permanently deleted?

Basically how GNOME does it currently.

**Comment by jeremypw** [comment]
OK, undestood.  Needs input from design to whether to offer this and how to expose to user.
