### ISSUE TITLE
Send notification to open external devices when plugged in

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#453]
Right now, external devices that are plugged in take two clicks to open: Open the Files app and then find & open the device. A better solution is to send a notification on a new device plug in and allow it to be clicked to open the device contents. 

In the absence of the Plank dock supporting external devices appearing as dock icons (AFAIK, at least not by default), this would be a nice solution.

**Comment by jeremypw** [comment]
Are you assuming that Files is open when the device is plugged in?  If not then there needs to be something running in the background to make this happen.

**Comment by jeremypw** [comment]
On reflection I think this ought to be addressed at a system level e.g. with a wingpanel plug, which is guaranteed to be running at startup.

**Comment by uncertainquark** [comment]
Should I open a new bug in Wingpanel instead of this being labelled as "Out of Scope"? Because the feature is relevant to the OS, may only be out of scope for the Files app.

**Comment by jeremypw** [comment]
Yes, please do.  The "Out of Scope" label only refers to the Files project.

**Comment by uncertainquark** [comment]
File [here](https://github.com/elementary/wingpanel/issues/203).

**Comment by cassidyjames** [comment]
@jeremypw @uncertainquark for future reference, we can now use the "Transfer issue" feature of GitHub to move issues between repos, which keeps the discussion and context all in one place.
