### ISSUE TITLE
tests: failure without elementary-icon-theme

### ISSUE THREAD

**Issue by codygarver** [elementary/files#46]
`hicolor-icon-theme` does not suffice, but it should.

**Comment by jeremypw** [comment]
The test code in Files only mentions the following icon specifically: "file:///usr/share/icons/hicolor/16x16/apps/system-file-manager.svg"

Moreover, marlin-icon-info.c returns "hicolor" as the icon theme if the system default icon theme is unset.

It is not immediately clear therefore why the elementary theme is needed.

**Comment by danrabbit** [comment]
Is there a reason that we're testing for the existence of this icon? `system-file-manager` is covered in the freedesktop icon name spec, so it should theoretically always be provided

**Comment by jeremypw** [comment]
The test is not for the existence of the icon (it is assumed to be present).  It is used to test the functionality of marlin-icon-info.  We could alternatively use a built-in icon I suppose, but that would not reproduce normal use as well.

**Comment by danrabbit** [comment]
Oh I see. Yeah that icon wouldn't be provided in hicolor. Hicolor only stores third party icons. You would need either elementary or Adwaita or some other fdo icon set

**Comment by jeremypw** [comment]
Closing as should be fixed by linked merged PR
