### ISSUE TITLE
Some icons don't scale

### ISSUE THREAD

**Issue by mdh34** [elementary/files#460]
Some icons in the list view don't scale:

![screenshot from 2018-05-06 15 19 07](https://user-images.githubusercontent.com/12615975/39674257-019ddd70-5141-11e8-9547-5a2b445dbe0c.png)

**Comment by jeremypw** [comment]
This seems only to happen in HiDPI, with ListView and only for certain icons at certain zoom-levels.

**Comment by danrabbit** [comment]
This is because `icon_size` property in Gtk now seems to be only a suggestion. The `pixel_size` property needs to be set to actually restrain

**Comment by jeremypw** [comment]
I can confirm it does happen in Column View under the same conditions as List View on my system (it is mostly the same code). Using unstable Juno and using GTK_DEBUG=interactive to change the window scale.  @mdh34 - what version of Files/Elementary do you experience this in?

**Comment by mdh34** [comment]
@jeremypw this is on the latest juno builds

**Comment by jeremypw** [comment]
Hmm, I must admit since there is only one icon renderer so it is likely to affect all views.
