### ISSUE TITLE
Strange symlink arrows behavior in restored views

### ISSUE THREAD

**Issue by Djaler** [elementary/files#486]
You can see this by the link. https://youtu.be/UZ26E8gQfnQ

**Comment by jeremypw** [comment]
I shall have to get  HiDPI machine!

**Comment by Djaler** [comment]
This is just 1080p on 15.6" ;)

**Comment by jeremypw** [comment]
It may be that the emblems are being scaled to HiDPI when in LoDPI for some reason.
