### ISSUE TITLE
No rectangular selection in list and column views from below last row.

### ISSUE THREAD

**Issue by chbk** [elementary/files#487]
Using elementaryOS 0.4.1

In grid view, I can select multiple files by dragging the mouse over them while holding left-click. Why isn't that possible in list and column views?

**Comment by jeremypw** [comment]
It is possible, with the restriction that you must start on the blank part of the name column of an unselected row.  Icon View is different because there are empty spaces in between the file items that can be allocated to rubberband selection.

**Comment by chbk** [comment]
Alright, I tried it and you're right, I can select multiple files this way. However, this wasn't immediately apparent to me. I expect to be able to start a selection from the blank space below the files as well.

![s](https://user-images.githubusercontent.com/7478535/39969611-aa801262-56de-11e8-9037-074479ef3259.png)
