### ISSUE TITLE
Color tag is not removed when the file or folder is trashed or deleted completely

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#488]
## Actual behavior
When we create a new file or folder, add it a color label, delete it completely, and create a new one with the same name, the new one was shown with color label which we added the previous one, though we didn't add color label.

## Expected behavior
The color label should be removed when the file or folder is deleted.

## Steps to reproduce the behavior

![peek 2018-05-15 22-25](https://user-images.githubusercontent.com/26003928/40061258-7aa7d898-5893-11e8-9a4e-6c7754d649e8.gif)

 1. Create a file or folder and name any name
 2. Add color labels
 3. Delete the file or folder completely
 4. Then create a new file or folder **with the same name (in this gif example, "test" and "testt")**

Even if the previous one is file and the new one is folder, this issue happens. And vice versa.

**Comment by ryonakano** [comment]
It's difficult question... But IMHO, I think it is better to retain color tags' setting if the files or folders are only trashed. Because the files or folders just moved to trash, they are still on the disks and might be restored.

**Comment by jeremypw** [comment]
So if a file of same name were created while it was in the trash, the new file should not inherit the color and could be set to a different color.  If the old file were restored, overwriting the new file, it should regain its old color?  Quite tricky to achieve but no doubt possible.

**Comment by ryonakano** [comment]
Yes. However, this is just my personal thought, so it might be wrong or not be a good way.

**Comment by jeremypw** [comment]
Maybe better to raise a separate issue about restoring color tag when undeleting. 

It is clear that a new file should not inherit the color tag of a deleted file.
