### ISSUE TITLE
 Color tag does not restored when the file or folder is untrashed

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#491]
Involved #488.

**Comment by jeremypw** [comment]
* Trash a file with a color tag
* Create a new file with the same name and give it a different color tag
* Restore the old file from trash, overwriting the new file
* The original color tag is not restored.

**Comment by jeremypw** [comment]
Description edited because original is virtually the same as #488

**Comment by jeremypw** [comment]
This is unlikely to be implemented any time soon as this feature is not really worth the added complexity in my opinion.

**Comment by jeremypw** [comment]
This could probably only be fixed by changing the way color tags are stored - by moving them in to metadata of the file itself so restoring the file would automatically restore the color tag.  A drawback of this would be that only files on systems that support metadata file attributes could be color tagged.

**Comment by Marukesu** [comment]
looking at the [Gvfs wiki page](https://wiki.gnome.org/Projects/gvfs/doc#Metadata), maybe that wouldn't be a issue?

**Comment by jeremypw** [comment]
@Marukesu Thanks for the info.  Looks like the gvfs system works a bit like the Files own system which stores the color-tag data in a (SQL) database.  

> Metadata are tied to the particular file or directory. If it's moved or deleted (using GIO), changes are reflected to the metadata database the same way. It works very similar to xattrs.

Not sure if this means the metadata is restored on untrashing the file or not.

**Comment by jeremypw** [comment]
Worth investigating in the Gtk3 version as it has the potential to simplify or eliminate the color-tag plugin.
