### ISSUE TITLE
Strange arrow navigation

### ISSUE THREAD

**Issue by Djaler** [elementary/files#502]
Steps to reproduce:
1) Open any folder
2) Click right arrow key on keyboard.

Expected: First file selected
Actual: Second file selected. (Or no files selected if folder contains only one file).

It seems that it was broken recently, cause I always use such keyboard navigation.

**Comment by jeremypw** [comment]
Probably regression due to 44c8e49df73eaa2c4176a53a1b6e3c983e6cd5f5.

**Comment by jeremypw** [comment]
Only affects IconView.
