### ISSUE TITLE
Inconsistencies when dragging a file onto the sidebar

### ISSUE THREAD

**Issue by jlnr** [elementary/files#521]
- [x] When dragging a file and hovering over the section separators like "Devices", "Network" etc., the cursor shows a green plus, even though dropping a file here won't do anything.

- [ ] When dropping a file from e.g. ~/Downloads onto the sidebar entry for ~/Downloads, both the current file and the created link are selected. Expected behavior (for me at least): The original file should be deselected, just like when dragging from the file into the whitespace surrounding it (which also creates a link).

**Comment by jeremypw** [comment]
This should really be two separate reports.

**Comment by jlnr** [comment]
Sorry about that, I'll create more focused issues in the future.

**Comment by jeremypw** [comment]
In my opinion, the behaviour should match that of the context menu option "Bookmark" - that is the item stays selected and remains focused (the bookmark is not focused).
