### ISSUE TITLE
More useful empty folder state

### ISSUE THREAD

**Issue by harveycabaguio** [elementary/files#522]
Right now it just gives a "Folder is empty" message, it could be more useful if it used the welcome screen pattern with options for:

- Create a new folder
- Create new file (from templates)
- Paste file from clipboard (if available)

**Comment by jeremypw** [comment]
These are all available on the context menu so this would only save one click (tho' improve discoverability I suppose).

**Comment by SixFingeredAmish** [comment]
I’m not sure this is helpful to users. I think it’s a standard convention leave an empty folder as is. Adding options that the empty folder would just be overwhelming.

As for file creation, I would say most users’ conceptual model of creating files is not to create a file from the file explorer, rather, they open up an application (say, a word processor), and create a file there.

**Comment by jeremypw** [comment]
About the only time I use Files to create files/folders is when I need dummy files/folder for testing Files ; )

**Comment by jeremypw** [comment]
I do not think I am in favour of this:
* It would create a different mechanism for empty folders compared with non-empty folders when there is a mechanism that works the same way for both.
* The cost of code complexity is not worth the benefit
