### ISSUE TITLE
Search doesn't find same file with other query

### ISSUE THREAD

**Issue by peteruithoven** [elementary/files#528]
Something seems to go wrong with the search in Files. I tried the following from my home folder. 

I searched on "pasta", it shows a couple of options:
![files search pasta](https://user-images.githubusercontent.com/523210/41314609-9544eb7c-6e8d-11e8-92c4-3040d93c1c67.png)
When I search on "geitenkaas" or "gorgonzola", two words that are a part of the name of one of the files above, I get 0 results:
![files search geitenkaas](https://user-images.githubusercontent.com/523210/41314610-9568d244-6e8d-11e8-9824-fa8a3866f351.png)
![files search gorgonzola](https://user-images.githubusercontent.com/523210/41314611-95862fa6-6e8d-11e8-8a5a-911b5e2e9d4b.png)
When I go from the home folder into this "nextcloud old" folder it suddenly does find the files. 

Trying to search for the same words in catfish does give results:
![catfish search gorgonzola](https://user-images.githubusercontent.com/523210/41314613-95a9a440-6e8d-11e8-92fb-75453afcc1ff.png)
![catfish search geitenkaas](https://user-images.githubusercontent.com/523210/41314614-95d884ae-6e8d-11e8-9f45-db351b9bf31f.png)

What could be going on here?

I'm running elementary OS 0.4.1 Loki.
I didn't see useful logs when running pantheon-files from the terminal.

Please let me know if I can provide more information.

**Comment by jeremypw** [comment]
I have not been able to reproduce this on Juno so, hopefully whatever was causing it is fixed.

**Comment by peteruithoven** [comment]
Looks like it's indeed fixed in Juno. It's now also easier to see the searching status because of the indicator on the right. 
What is a bit of a pity is that a search can take 30 seconds to give results, while I have a SSD. The interface isn't really suitable for such delays.

**Comment by jeremypw** [comment]
@peteruithoven  Thanks.  Searches can take a long time if the scope includes a large number of files to check and there are few matches.  Searching continues until either the maximum number of matches is met or the scope is fully searched.  I believe there is an open issue about indicating that a search is ongoing.  It may be possible to give some preliminary results before the search is complete although we do not want the results tree jumping around too much.  There is a limit to how fast large scopes can be searched without pre-indexing however. There are a number of desirable improvements to search but it will be after Juno release that anything will be done.

**Comment by peteruithoven** [comment]
>  I believe there is an open issue about indicating that a search is ongoing

I've been seeing a searching indicator since I've upgraded to Juno. A great improvement. I think it was this pull request: https://github.com/elementary/files/pull/425

>  It may be possible to give some preliminary results before the search is complete although we do not want the results tree jumping around too much.

A I assumed this already happened, caused by experience in other applications. I'll check the issue queue for an existing issue and otherwise will open one.
