### ISSUE TITLE
Random files being created in Home directory

### ISSUE THREAD

**Issue by arshubham** [elementary/files#537]
I don't know if it is file's fault but these files are being created randomly. They are created and deleted on their on and can vary in numbers from 0-3. On opening them with code they seem to be empty. Didn't happen on my first install of juno, only appeared after reinstall and I didn't do anything radically different either times. Anyway opening this issue for visibility.

![screenshot from 2018-07-06 08 28 27](https://user-images.githubusercontent.com/14235191/42359531-00be5332-8100-11e8-8fec-2a8a9c1744ff.png)

**Comment by jeremypw** [comment]
There is no reason in Files code for these files to be produced as far as I can see - so I think this must be due to something else.  Marking as invalid and closing. Please feel free to re-open if you demonstrate a definite association with Files running.
