### ISSUE TITLE
Add sharing functionality in context menu.

### ISSUE THREAD

**Issue by arshubham** [elementary/files#538]
After reading a [phoronix article](https://www.phoronix.com/scan.php?page=news_item&px=KDE-Dolphin-Share-Menu), I really want to see this dolphin feature implemented in files with common sharing options. These two options can then be coupled under a single option too decreasing the height of context menu. 
![screenshot from 2018-07-08 17 28 06](https://user-images.githubusercontent.com/14235191/42419531-6de1598e-82d4-11e8-954f-ad3ccef8acf3.png)

Further integration with popular opensource services services like telegram (i need this very much), nextcloud would be great. This menu can also act as a place where 3rd party appcenter apps can register their contracts if they provide some sharing functionality.

**Comment by danrabbit** [comment]
This menu already uses contractor and these are extensions. Any app can add actions here.

Closing since this is already implemented

**Comment by arshubham** [comment]
@danrabbit oh, sorry I got excited a little when I saw this feature. Wouldn't it be a better idea if both the options are under one contract? also telegram being in a qt app may never implement a contract for elementary. Anyways thanks for the consideration.
