### ISSUE TITLE
Unable to launch pantheon-files using the terminal or a keyboard shortcut

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#539]
In Loki, I could open the Files app using the command "pantheon-files". And assign it to a shortcut key because it is apparently missing as an option in the Keyboard shortcuts pane.

In Juno-Beta 1 however, the command doesn't work. Using a menu editor app, I found that the command has been changed to "io.elementary.files %U", which is not in line with launching other apps like "pantheon-mail".

![screenshot from 2018-07-08 20-22-43](https://user-images.githubusercontent.com/22585732/42421055-c2d6f846-82ec-11e8-97c1-fc950e1e1bfa.png)

**Comment by BaptisteGelez** [comment]
Yes, all the elementary apps are now using RDNN to avoid conflicts with other commands and to keep consistency.

Aren't you able to launch Files with this command?

**Comment by uncertainquark** [comment]
> Yes, all the elementary apps are now using RDNN to avoid conflicts with other commands and to keep consistency.
For one, pantheon-mail isn't. So that's why I got confused. 

> Aren't you able to launch Files with this command?
I am able to launch Files with this command and I get why the devs went with RDNN (did read the blog post). But what I don't get is that this change also makes intuitive discoverability of the commands to launch apps from the terminal or set keyboard shortcuts.

**Comment by danrabbit** [comment]
This is intended. Mail will eventually use RDNN naming also
