### ISSUE TITLE
Change the behavior of Shift+Click

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#543]
It seems that both `ctrl+click` and `shift+click` do same behavior: both select only the clicked items. I think shift+click should select all items from start to end like this:

![screenshot from 2018-07-12 20-49-30](https://user-images.githubusercontent.com/26003928/42631460-458a0eb0-8615-11e8-927e-beed2a1b9aa4.png)

On Juno Beta1

**Comment by jeremypw** [comment]
Shift-Click does have the desired effect if you do not click on the helper (tick emblem), but click on the icon instead. The helpers were intended to aid selecting individual items, but I can see that this difference in behaviour could be confusing.  I'll flag for design team comment.
