### ISSUE TITLE
Unneeded periods

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#544]
![screenshot from 2018-07-12 19-36-58](https://user-images.githubusercontent.com/26003928/42631738-08deac9a-8616-11e8-9203-63c5dbe53ca8.png)

I suppose the periods in `Show the version of the program.` and `Quit Files.` in `io.elementary.files --help` are not necessary, because other help descriptions and help descriptions of other elementary components does not have periods.

**Comment by jeremypw** [comment]
I agree it should be consistent.
