### ISSUE TITLE
Restore and Empty the Trash always available

### ISSUE THREAD

**Issue by Djaler** [elementary/files#547]
This action is available even if there are no files in trash

**Comment by Djaler** [comment]
![image](https://user-images.githubusercontent.com/7964583/42731168-52922d7a-8810-11e8-81c4-d5e94d287447.png)

**Comment by jeremypw** [comment]
This is not happening for me with version 0.3.6+r2965+pkg69~ubuntu5.0.1 (Juno Beta).

**Comment by Djaler** [comment]
Hmm, I can't reproduce this now too

**Comment by jeremypw** [comment]
There are some obscure bugs in Files that happen only occasionally and depend on fine timing, order and positioning of clicks.  These are very difficult to fix.
