### ISSUE TITLE
Crash with activate directory after click on bookmark

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#549]
This does not always happen but this is how I reproduced the problem:

* Use List View
* Start away from Home
* Click Home bookmark
* Click on a subfolder (on a white part of the name field, after the name) _as soon as possible._

When carried out rapidly Files crashes maybe one in five times.

**Comment by cassidyjames** [comment]
I can't seem to reproduce this at all. @jeremypw are you on a slower HDD?

**Comment by jeremypw** [comment]
@cassidyjames: Thanks for having a look at this.   I am on an SSD with an i5 processor and it is sporadic even for me.  It is some kind of race condition in signal processing I think.  I'll check to see whether it is still a problem and whether I can pin down the conditions more closely.

**Comment by jeremypw** [comment]
@cassidyjames :  It is still occuring for me when I carry out the steps given in the bug description.  The most critical thing seems to the be how soon after pressing the `Home` bookmark you click on the folder name in the view.  The faster the more likely a crash.  If you have a very fast machine, maybe it is not easy to click fast enough. For me the delay should be under 0.5 sec.
