### ISSUE TITLE
Open in Terminal behavior when already one on a different workspace

### ISSUE THREAD

**Issue by alex285** [elementary/files#553]
elementary: 5.0
Files: 0.3.5
Gala: 0.3.1
Terminal: 0.5.0

### Reproduce 
1. Open a Terminal
2. Go to a new workspace
3. Open another Terminal
4. Go to a new workspace
3. Open Files
4. From Files context menu try to open a new Terminal
![open-terminal](https://user-images.githubusercontent.com/11244308/42882432-9f3c525c-8aa1-11e8-9232-27d25f31dc04.png)

### Outcome
A new tab opens in one of the two running terminals and Plank gets a red indicator that is btw hardly noticeable. Clicking it will move you to the workspace on this Terminal

### Expected Behavior
When a Terminal doesn't exist on the current workspace, then open a new Terminal. I believe this is the best design approach for workspaces use. You expect a (new) Terminal on the current working workspace

Note that if a Terminal already exists on the current workspace it will bring it into focus

Also see: https://github.com/elementary/files/issues/99

**Comment by jeremypw** [comment]
When the "Open in Terminal" option is clicked FIles just passes the URL to "open-pantheon-terminal-here.desktop", which runs io.elementary.terminal with the -w flag and the URL.  Files has no control over how Terminal and the window manager deal with it after that.  So, while I think your suggestion makes sense, I do not think this is a Files issue.  I suggest you raise it against Terminal.
