### ISSUE TITLE
Open in --> Other Application... has wrong headerbar

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#554]
## Actual behavior

![screenshot from 2018-07-21 18-59-54](https://user-images.githubusercontent.com/26003928/43034534-0c46c296-8d19-11e8-8543-763a35181d12.png)

## Expected behavior

![screenshot from 2018-07-21 18-59-54-2](https://user-images.githubusercontent.com/26003928/43034558-88b1f8c8-8d19-11e8-86be-4f9f4b424928.png)

## Steps to reproduce the behavior

1. Open Files
2. Right-click and select "Open in" --> "Other Application..."
3. The dialog has wrong headerbar

I'm not sure this issue is whether a bug or intentional feature.

**Comment by ryonakano** [comment]
Files 0.3.6
On Juno Beta1

**Comment by jeremypw** [comment]
I am closing this while it is intended to fix with the stylesheet.
