### ISSUE TITLE
[Feature Request] Append Slash When Autocompleting in Path Bar

### ISSUE THREAD

**Issue by amxmln** [elementary/files#556]
I’m not sure whether this is a bug or intended behaviour, but if I switch directories by using Ctrl+L to enter the path-bar and then type the names of folders, I always have to manually enter the slash after autocompleting with Tab. This gets very frustrating very quickly because it’s not consistent with the way autocomplete works in the Terminal for example—is there any reason behind it behaving like that?

**Comment by jeremypw** [comment]
I guess that if the foldername is unambiguously a completed folder then a slash should be entered automatically.  Care would need to be taken to deal names that may or may not be a folder or may not be complete.

**Comment by jeremypw** [comment]
This is addressed by PR #516

**Comment by amxmln** [comment]
Maybe take a look at how it’s implemented in GNOME Files—there it behaves like in the Terminal.

**Comment by jeremypw** [comment]
Its not quite the same situation as in Terminal.  In Terminal, you can only cd to a folder.  However, in FIles it is possible to navigate to a regular file - in this case Files automatically navigates to the parent folder and highlights the requested file.

**Comment by jeremypw** [comment]
Try creating e.g. a folder named "Documents" and a file named "documents". In Terminal, typing `cd doc` and pressing `Tab` completes to `cd Documents/`  In Files it completes to "..../documents" if you type "doc" + Tab and "Documents" if you type "Do".  However, this has revealed a bug in that under these circumstances (using the home directory), as it should not propose a completion at this point since there is also a folder "Downloads".  Moreover typing "Doc" causes the proposed completion to disappear (?!)

**Comment by jeremypw** [comment]
I'll create a new issue about this.

**Comment by cassidyjames** [comment]
I'm not sure that navigating to a specific file from the pathbar is a useful behavior, especially when the path bar is used primarily for navigating between folders. I think I'd like the tab appending behavior as well.

**Comment by jeremypw** [comment]
Its mainly for consistency of behaviour with bookmarks and commandline options I think. I have never used it.  I am about to submit a PR that fixes the issues mentioned here without losing that behaviour, but it would be simple enough just to ignore files that are not folders when completing.

**Comment by amxmln** [comment]
I agree with Cassidy, I had no idea selecting files through the pathbar was even a thing—it seems somewhat counter-intuitive to begin with.

Thanks for looking at this and solving it in any case! You're all doing a great job.

**Comment by jeremypw** [comment]
Because of the way Files already works it happens by default. But it is simple to exclude non-folders from completion (PR already submitted).
