### ISSUE TITLE
Two drag and drop actions in a row crashes the app

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/files#56]
To reproduce: 

1. Drag a file into another app, like a picture to GIMP
2. Drag another file, the app will crash as soon as the drag operation starts

```
Thread 1 "pantheon-files" received signal SIGSEGV, Segmentation fault.
0x00007ffff4dd2a67 in marlin_dnd_handler_set_selection_data_from_file_list () from /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.0
```

I couldn't get a better bt due to files keeping hold of my mouse and keyboard during the crash... but if this isn't enough i'll get a better one

**Comment by jeremypw** [comment]
I can confirm this although the number of drags/drops between apps needed before a crash occurs varies.  For me. the crash occurs in line 276 of DndHandler:

>bool in_recent = file_list.data.is_recent_uri_scheme ();

Presumably file_list is empty. A check for this condition is needed.

**Comment by jeremypw** [comment]
Further experimentation indicates this is much more likely to occur in IconView than ListView (where initial test was carried out).
