### ISSUE TITLE
Name labels are not aligned with icons

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#564]
![screenshot from 2018-07-26 13-54-43](https://user-images.githubusercontent.com/26003928/43242352-8c597364-90db-11e8-8f32-e9f5bd61bf18.png)

I found this issue today after I updated Files in AppCenter. I suppose the icons and name labels were centered before, but they're not now.

On Juno Beta1, with Files 0.3.6

**Comment by jeremypw** [comment]
There were a significant number of merges yesterday so this is probably due to one or more of them.  Will fix asap.

**Comment by jeremypw** [comment]
Caused by https://github.com/elementary/files/commit/307b2701e9d7ead750c3f9d0ba75796fc71ae998

**Comment by ryonakano** [comment]
@jeremypw Thank you!!
