### ISSUE TITLE
Set as Desktop Background for djvu

### ISSUE THREAD

**Issue by Djaler** [elementary/files#570]
There are an option to set .djvu file as desktop background in context menu. I don't think that this is good idea to set book as a background

**Comment by jeremypw** [comment]
This function is offered by a contractor so I guess there is something wrong with the valid mime-types specified in the .contract file.

**Comment by jeremypw** [comment]
Ah, OK - sorry for the confusion.  This contract is not installed by Files - I'll check where it is kept.

**Comment by jeremypw** [comment]
It is here: https://github.com/elementary/switchboard-plug-pantheon-shell/tree/master/set-wallpaper-contract

**Comment by Djaler** [comment]
So I should move issue to this repo?

**Comment by jeremypw** [comment]
Yes, I think so.
