### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by Djaler** [elementary/files#604]
There are some untranslated strings again.
"Recent", "Open in a New Window"

![image](https://user-images.githubusercontent.com/7964583/44302098-474dc380-a32b-11e8-8d95-9507a10cb249.png)
![image](https://user-images.githubusercontent.com/7964583/44302111-6187a180-a32b-11e8-8bf3-d6c4f3c04828.png)

**Comment by jeremypw** [comment]
I have identified the cause of the "Recent" problem and will fix.

The text "Open in a New Window" is not coming from Files - it is coming from the Granite DynamicNotebook so the issue should be raised there.

**Comment by Djaler** [comment]
I create it https://github.com/elementary/granite/issues/206
