### ISSUE TITLE
List and Column view doesn't normally show icons

### ISSUE THREAD

**Issue by ItsPossibleAlready** [elementary/files#609]
![2018-08-28 19-44-55](https://user-images.githubusercontent.com/26849971/44727067-fb550880-aafa-11e8-97a3-b4e19b0c44be.png)
    In list and column view it doesn't fully show folder with lock or minus.
![2018-08-28 19-47-44](https://user-images.githubusercontent.com/26849971/44727188-496a0c00-aafb-11e8-8bff-ebe529661ea2.png)

![2018-08-28 19-44-24](https://user-images.githubusercontent.com/26849971/44727062-f2643700-aafa-11e8-9718-5b8cff1040e6.png)

**Comment by jeremypw** [comment]
Probably due to one of several commits fiddling with the icon-renderer.
