### ISSUE TITLE
Right Click and Click is not working on files 

### ISSUE THREAD

**Issue by mahmodlte** [elementary/files#612]
Dear Elementary Developers Team, 

Right Click and Click is not working on files app when i want to open a file i just can not open it and it is not selecting the file and right click is the same problem it is not selecting the file to make action on it i hope to fix very soon it was working but after the latest updates it become not working 

Sincerely
Mahmood

**Comment by mahmodlte** [comment]
I found that this issue is just on Compressed Files when i trying to Click Or Right Click on them there is no action

**Comment by jeremypw** [comment]
Almost certainly due to https://github.com/elementary/files/commit/f93d3118954fb61269e0594db58835864255c29c

SImplified way of determining click position probably confusing tree coordinates and window coordinates so messing up when window is scrolled. Will fix asap.

**Comment by jeremypw** [comment]
A temporary workaround is to invoke the context menu with the keyboard using the Menu key or activate the selected file using the Space key.
