### ISSUE TITLE
Storage Utility to help users clear up disk space

### ISSUE THREAD

**Issue by steakscience** [elementary/files#615]
A feature to show remaining disk space and make drives that are nearly full more prominent is [being discussed](https://github.com/elementary/files/issues/350).

Adding on to that, I think the Files app should have a utility of some sort to accompany low disk space visuals. Instead of just telling the users the drive space is low, this utility helps users take action by presenting them with large files or old files. If they no longer need them, they can easily erase them.

**Comment by SixFingeredAmish** [comment]
> Disk space monitoring needs to be happening in the background whether or not Files is running

Good point! Isn't Files always running though?

**Comment by jeremypw** [comment]
It is not running on initial log in although once it has been opened, the pantheon-files daemon continues to run in the background. This could be fixed by adding the pf daemon to cerbere which makes sure certain services like wingpanel and plank are always running.

**Comment by SixFingeredAmish** [comment]
I feel like like the file explorer should always be running, just like search indexing is, etc

**Comment by jeremypw** [comment]
I tend to agree.  There was a proposed branch a couple of years back that required the files daemon to be started by cerbere on login to work properly (it was to do with unity quicklist availability) but it was not taken up at the time.  Probably a more detailed blueprint needs to be prepared and agreed by UX team before leaping into coding.
