### ISSUE TITLE
Files and File Picker should have similar interface

### ISSUE THREAD

**Issue by skewty** [elementary/files#616]
My understanding is that File picker is gtk code and the Files app is elementary code.

If you are looking for a user experience more consistent with say Windows 10 you should at least have the ability to switch to another view style in the File picker to make tasks like finding a picture not painful (no previews).

Ideally, the File picker and Files app should share a lot of their code.  Is this even doable?

**Comment by arshubham** [comment]
See https://github.com/elementary/files/issues/129 . This seems a possible dulplicate.

**Comment by skewty** [comment]
@arshubham totally is, my bad.
