### ISSUE TITLE
Missing desktop-folder-icon in colum view when folder is selected (juno beta2 live-iso)

### ISSUE THREAD

**Issue by J0Ar** [elementary/files#625]
Maybe this is a icon-theme issue...but on the other side, elementary OS doesn't use the desktop-folder...soo...¯\_(ツ)_/¯

I should notice...this is the beta2-live...its not installed. And i did not create this folder...is was just there.

![bildschirmfoto von 2018-09-21 10-47-07](https://user-images.githubusercontent.com/23266409/45877192-876def00-bd8c-11e8-81d1-284f2d20427b.png)

**Comment by J0Ar** [comment]
After installation the desktop folder is not visible...so only an issue on the live-medium.

**Comment by jeremypw** [comment]
Does this only occur in column view? All views use the same icon rendering code so I would expect a problem to affect all views (at least after matching the icon sizes by zooming).  I tried faking this on a Juno install by adding $HOME/Desktop to /etc/xdg/user-dirs.defaults and ~/.config/user-dirs.dirs.  I find it can occur in all views but only immediately after starting the application. Any operation causing the view to redraw results in the standard icon appearing.  So it looks like there is a small issue with it not always falling back to the standard folder.

**Comment by jeremypw** [comment]
You are right that elementary does not regard ~/Desktop as a special directory (it is not created or used by default) so do not expect the icon to be desktop-folder-icon.

**Comment by J0Ar** [comment]
I must withdraw my last comment. I don't know why but the desktop folder is now available !? 
I only installed Firefox and Thunderbird...hmm,strange...but to your question:  
In Colum-View you notice it because the path in the first column remains open.
But you are right, it is also in list-/folder-view. 
You can easily reproduce it by creating a new-empty-file in ~/ and then dragging it to the desktop folder. For a short moment you can see the desktop-folder is gone.
I think the specified icon, which shows the desktop folder open, is missing. 

I'd just like to mention this. I myself don't use the desktop folder and I'm more bothered that it is displayed and causes this visual problem. 
I'd appreciate it if it wasn't there at all. :)

**Comment by jeremypw** [comment]
Another easy way to trigger this (or a similar issue) is simply to rename one of the existing special folder icons in icons/elementary/places so that the expected one is not found at a certain zoom level.  Then zoom a view to that icon size - the icon disappears instead of falling back to the standard folder icon.

**Comment by danrabbit** [comment]
It's Firefox. Firefox creates this folder. I guess what's happening is that Files is looking for `user-desktop-drag-accept` and it isn't falling back to `user-desktop` when that isn't found

**Comment by J0Ar** [comment]
Closed because fix by https://github.com/elementary/icons/issues/746
