### ISSUE TITLE
Do not show Recent folder when History disabled

### ISSUE THREAD

**Issue by Pemicope** [elementary/files#627]
As you can see from the screenshot I've disabled History, but the "Recent" folder is still there on the file manager. This is a screenshot from Loki, but it has the same behaviour on June. Is there any way to remove it? Thanks, and keep up doing the excellent work you've been doing. I love elementary OS!

![screenshot from 2018-09-21 19-30-45](https://user-images.githubusercontent.com/43481036/45900787-a4301400-bdd8-11e8-8ad9-716d61b5de52.png)

**Comment by jeremypw** [comment]
There is no UX way of doing this but I guess Files should not show the Recent bookmark if History is disabled.

**Comment by Pemicope** [comment]
I understand.
Thank you so much for your reply, and I hope this will be fixed. :+1:

**Comment by danrabbit** [comment]
I’m wondering if maybe we should still keep the item and show a link to system settings to easily re-enable history? I’m not sure if it would be better in case users don’t understand the implications of disabling history
