### ISSUE TITLE
Clean up context menu

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#629]
The current context menu is in a seemingly random order with separators everywhere, effectively separating everything and making it look really cluttered.

![screenshot](https://i.imgur.com/d1mr1F1.png)

Instead, I think we should rethink the groupings of items into a few categories:

**Act on the currently-selected or being-clicked-on thing**
- Open in
- (Contractor items)
- Set a color
- Properties

**Act on the current folder**
- New
- Sort by
- Bookmark

**App-wide**
- Show hidden files

**Comment by danrabbit** [comment]
One other thing we've been doing in other apps is to put contractor items in a submenu called "Other Actions"

Following this convention, would the file context menu look something like this:

```
Open In ›
Other Actions ›
( colors )
Properties
---
Cut
Copy
Copy as Link
Rename
Move to Trash
---
Bookmark
```

**Comment by jeremypw** [comment]
The color tag and contract items are added by plugins which do no make any assumptions about the required position - they just append their item(s) to the end of the passed menu. Conversely, the view does not make any assumptions about what plugins are active and what menuitems they might append. 

So there may be complications in controlling the position of the plugin menuitems.
