### ISSUE TITLE
Don't open all selected files when single clicked

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#630]
I've heard one reason single click can be a pain for users is that when selecting files, a single misclick (due to difficulty hitting the small target and/or something like spontaneous tremors) when trying to hit a selection check opens every single selected file. This can range from mildly annoying to system-stalling depending on the number and type of files being worked with.

I didn't actually know this was a feature and am not sure it's a great one if it can easily cause that much strife. 

So I guess:

1. Is it obvious this is a useful feature?
2. Have we heard of people purposefully using this feature?
3. Is this feature worth the accessibility issues, and if so, how can we better address those issues?

**Comment by cassidyjames** [comment]
A possible solution that would be a pretty big change but I think for the better:

Have a concept of a selection mode when one or more items is selected. Ctrl/Shift clicking an item or hitting an item's selection check would go into this mode, as that's selecting an item.

In selection mode, all selectable items show their selection check, making it clear that they're selectable but currently unselected. Clicking an item in this mode toggles its selection. 

Since clicking in this mode selects or deselects, we could keep pressing Enter/Space to open the selected files in case that is a useful action, and unlikely to be accidental since it is unrelated to clicking to select.

Clicking outside of any items or tapping Esc could probably deselect all items and thus exit this mode.

**Comment by jeremypw** [comment]
I think dropping multiple item activation by single clicking is unlikely to be a problem for users (I never use it anyway) and as Cassidy says, they could still be activated by keyboard.

**Comment by cassidyjames** [comment]
It looks like this is almost exactly how Dropbox on the web behaves, actually. Single-clicking opens the file or folder by default, but checking the selection box switches to clicking to select files. Once all files are unselected, it goes back to the previous behavior.

**Comment by jeremypw** [comment]
I think a separate issue should be raised about the "selection mode" idea.  I can fix the specific issue about activating multiple file with single click easily but displaying helpers on non-selected/non-hovered items is a different matter.

**Comment by eljefuri** [comment]
Not sure if this is the right place to write this, but for what it's worth @cassidyjames I find the default single-click behavior quite disturbing and frustrating, irrespective of it being a multiple-file selection or not. Coming from macOS, the paradigm is click-to-select; I suppose the UX assumption made there is that primary use of a file navigator is _manipulating and working with files_. That may include opening them, but perhaps it more often has to due with manipulating them in different ways. It certainly does in my case.

Needless to say, the default click action with multiple files having been selected is _especially_ disturbing.

**Comment by jeremypw** [comment]
@eljfri: Files does support click to select but you have to change the setting using 

 `gsettings set io.elementary.files.preferences single-click false`
