### ISSUE TITLE
Selected folder(s) + compressed file > 'Open with' has a bug/clitch or empty submenu 

### ISSUE THREAD

**Issue by gre0j** [elementary/files#632]
Still at juno beta2...no update from beta1...fresh install after release.

When i select one or more folders in combination with a compressed file then in the 'Open with' context menu there is no entry…

![screenshot von 2018-09-26 10 15 07](https://user-images.githubusercontent.com/23266409/46066546-1dcb5780-c175-11e8-9cd3-ea6521bc15fb.png)

**Comment by ryonakano** [comment]
![screenshot 2018-09-26 18 02 44](https://user-images.githubusercontent.com/26003928/46069428-7e2eb900-c1b6-11e8-98fd-cda7718154df.png)

I can reproduce this (with `tar.gz`)

**Comment by jeremypw** [comment]
In this situation, the "Open in " menu item should not appear.  It works OK if you select e.g. a text file and a picture file.  But the same bug occurs if a compressed file and a normal text file are selected.
