### ISSUE TITLE
Clearer multi-select mode

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#634]
Split from #630.

**Comment by cassidyjames** [comment]
>A possible solution that would be a pretty big change but I think for the better:
>
>Have a concept of a selection mode when one or more items is selected. Ctrl/Shift clicking an item or hitting an item's selection check would go into this mode, as that's selecting an item.
>
>In selection mode, all selectable items show their selection check, making it clear that they're selectable but currently unselected. Clicking an item in this mode toggles its selection.
>
>Since clicking in this mode selects or deselects, we could keep pressing Enter/Space to open the selected files in case that is a useful action, and unlikely to be accidental since it is unrelated to clicking to select.
>
>Clicking outside of any items or tapping Esc could probably deselect all items and thus exit this mode.
>
>I think this would better respect user intent of selecting things while making it both clear and nondisruptive that the files are in a different state/mode with the selection checks being visible.

…

>It looks like this is almost exactly how Dropbox on the web behaves, actually. Single-clicking opens the file or folder by default, but checking the selection box switches to clicking to select files. Once all files are unselected, it goes back to the previous behavior.

**Comment by eljefuri** [comment]
@cassidyjames It feels intuitively like you are going to be fighting an uphill battle as long as the single-click rule is enforced in Files as uncompromisingly as it is across the rest of Elementary. Modes will add more complexity. For what it's worth, I believe that macOS Finder is and always has been modeless. Not that cloning Finder is goal...

Forgetting all that for a moment however:

There are a number of things you could do here, if you are willing to really go outside of expected UX paradigms. For example, something like your picture-in-picture mode could serve as a temporary "holding cell" for a selection of files, which could then be dragged wherever. Your "checkmark" selection idea could go well with that, to visually indicate what is there.

**Comment by jeremypw** [comment]
Closing as it is no longer relevant following the introduction of mixed-mode behaviour.  Multiple selections can no longer be activated by clicking, only by using the context menu.  Also it is not obvious what the separate issue is here.
