### ISSUE TITLE
Show Status in a status bar, the black pop-up looks tacky

### ISSUE THREAD

**Issue by mahajanudit** [elementary/files#640]
The black pop up kind of a status message that comes at the right bottom corner of files doesn't go with the flow of elementary. 
Another issue is, if I switch to another application or window and switch back, the status is not there while the file is still selected. This is highly inconsistent as now to see the status of the folder/file(s) selected either the user has to hover over the file or `Left`/`Right` arrow to re-select.
Windows does it beautifully but showing a status bar at the bottom. This also is a consistent design flow instead of a pop-up appearing the status bar continuously can show the information of the current folder and when the item(s) is selected it reflects to show their information. This way it won't seem out of place.
Here are two mock-ups i made

Folder (nothing selected): (https://drive.google.com/file/d/1pH2nLIRUmkJvjOvIe1YU-7RS9dtvGmMI/view)
Item Selected: (https://drive.google.com/open?id=1OMHYXBaNrS4FezrA5xKQFmh-pHdFfKOA)

Item Selected mock-up also has the current black popup which shouldn't be there. I have kept it just to show the contrast of the design flow mismatch.

The status bar could also be used for other information. For example, new folder button or something.

**Comment by danrabbit** [comment]
Closing as "Out of scope" since Files doesn't dictate the appearance of the overlay bar
