### ISSUE TITLE
Commit folder / file rename when clicking somewhere else

### ISSUE THREAD

**Issue by terndrup** [elementary/files#641]
This is just a small thing that has bothered me a few times.. basically, when you're in the process of renaming a file or folder, you have to press "Enter" to commit the renaming. If you click somewhere else, i.e. in the whitespace of the directory, your rename will not go through.

This may be by design, and I'm just not used to it, but to me it's just annoying. If you really want to cancel a rename pressing ESC is more intuitive than clicking somewhere else imo.

**Comment by cassidyjames** [comment]
I've also been mildly annoyed by this. I agree that saving on focus out makes sense, and ESC is a good indicator to cancel. It's not like it's a destructive action, as they can undo.

**Comment by terndrup** [comment]
Okay I'll see if I can figure it out and do a PR

**Comment by jeremypw** [comment]
It may have been something to do with allowing change of input method during rename (which produces a momentary focus out).  Anyway its something that a PR should be tested for.

**Comment by jeremypw** [comment]
This can be simply fixed by changing `true` to `false` in AbstractDirectoryView.vala line 3191, I think, so that it reads:
```
            if (renaming) {
                /* Cancel renaming */
                name_renderer.end_editing (false);
            }
```

**Comment by jeremypw** [comment]
Saving on focus out is likely to be problematic.
