### ISSUE TITLE
Holding down Ctrl+W will close Files

### ISSUE THREAD

**Issue by jlnr** [elementary/files#642]
When repeatedly mashing Ctrl+W, Files will keep the window open by opening a new home folder tab. (Whether that's a useful feature is another issue - #327.)

However, if I open a few tabs and *hold* Ctrl+W, I can reliably close Files.

Maybe it has to do with my key-repeat speed? I don't remember changing anything.

Expected behavior: Repeatedly pressing Ctrl+W should have the same behavior as holding Ctrl+W.

**Comment by jeremypw** [comment]
This actually causes a segmentation when the keys are released. Need to throttle Ctrl-W key presses.

**Comment by eljefuri** [comment]
I can confirm what @jlnr wrote. I attempted this by second-nature, coming from a few other macOS applications which have press-and-hold for key combinations which might be too easily pressed, disrupting workflow.
