### ISSUE TITLE
Read-only folder

### ISSUE THREAD

**Issue by ItsPossibleAlready** [elementary/files#643]
Maybe this issue not about "files" program. Yesterday my files was in read-write mode (in folder Downloads, Pictures e.t.c ). When I switch on my computer today, all my files switched to read-only mode.

**Comment by jeremypw** [comment]
This is unlikely to be down to Files.  I am marking it as 'Invalid' for now.  If you can reproduce this issue please re-open the bug.

**Comment by ItsPossibleAlready** [comment]
OK it was my problem. I have played with terminal. And i repaired my computer.
