### ISSUE TITLE
Minor visual glitch when right-clicking the home folder breadcrumb

### ISSUE THREAD

**Issue by jlnr** [elementary/files#645]
The two blue lines shouldn't extend this far to the left.

![cursor](https://user-images.githubusercontent.com/70772/46603053-4139bf00-caf2-11e8-9155-564d3791534d.png)

**Comment by pongloongyeat** [comment]
Just to add that this is present on eOS6 and instead of the blue line being shown, the _arrow (>)_ is shown on hold of the home folder.

![Screenshot from 2020-10-18 04 25 00](https://user-images.githubusercontent.com/31680656/96352961-66f2f900-10fa-11eb-88c4-f9eccc747ac1.png)
