### ISSUE TITLE
Compile phase errors

### ISSUE THREAD

**Issue by Dirli** [elementary/files#647]
os: gentoo
files version: current

/var/tmp/portage/pantheon-base/pantheon-files-9999/work/pantheon-files-9999/libcore/UserUtils.vala:39.28-39.42: error: The name `getgroups' does not exist in the context of `Linux'
        var group_number = Linux.getgroups (gid_list);
                           ^^^^^^^^^^^^^^^
/var/tmp/portage/pantheon-base/pantheon-files-9999/work/pantheon-files-9999/libcore/UserUtils.vala:39.13-39.53: error: var declaration not allowed with non-typed initializer
        var group_number = Linux.getgroups (gid_list);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/var/tmp/portage/pantheon-base/pantheon-files-9999/work/pantheon-files-9999/libcore/UserUtils.vala:40.29-40.40: error: The name `group_number' does not exist in the context of `PF.UserUtils.get_group_names_for_user'
        for (int i = 0; i < group_number; i++) {
                            ^^^^^^^^^^^^
/var/tmp/portage/pantheon-base/pantheon-files-9999/work/pantheon-files-9999/libcore/UserUtils.vala:68.28-68.42: error: The name `getgroups' does not exist in the context of `Linux'
        var group_number = Linux.getgroups (gid_list);
                           ^^^^^^^^^^^^^^^
/var/tmp/portage/pantheon-base/pantheon-files-9999/work/pantheon-files-9999/libcore/UserUtils.vala:68.13-68.53: error: var declaration not allowed with non-typed initializer
        var group_number = Linux.getgroups (gid_list);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/var/tmp/portage/pantheon-base/pantheon-files-9999/work/pantheon-files-9999/libcore/UserUtils.vala:69.29-69.40: error: The name `group_number' does not exist in the context of `PF.UserUtils.user_in_group'
        for (int i = 0; i < group_number; i++) {
                            ^^^^^^^^^^^^
Compilation failed: 6 error(s), 0 warning(s)

full log: https://paste.pound-python.org/show/b3Gcf8LcU0dW2m3QYQ1w/

**Comment by jeremypw** [comment]
I think you will need to raise this with whoever packaged/ported this for Gentoo, I am afraid.  Looks like a missing dependency or incorrect dependency version.

**Comment by jeremypw** [comment]
The Linux dev package (and .vapi file) needs to be available.  
See: https://valadoc.org/linux/Linux.getgroups.html

**Comment by Dirli** [comment]
Thanks, I'll look it up.

**Comment by Dirli** [comment]
compilation was successful, but had to boost Vala version (0.36 -> 0.40). There may be features Gentoo.
