### ISSUE TITLE
Pathbar disabled after switching tabs

### ISSUE THREAD

**Issue by markodp** [elementary/files#651]
Pathbar becomes disabled after this:
- open at least 2 tabs
- click on pathbar so that folder path becomes editable
- click on some other tab
- open back first tab

![screenshot from 2018-10-11 19 48 27](https://user-images.githubusercontent.com/805017/46823587-dbb62e80-cd8e-11e8-8c68-c20864ada016.png)

**Comment by naaando** [comment]
I can confirm this is happening and if you try a Ctrl+L after that and try to type it crashes
