### ISSUE TITLE
Backspace doesn't work as a keyboard shortcut for going back anymore

### ISSUE THREAD

**Issue by Heiko-M** [elementary/files#665]
In Loki you could hit backspace as a keyboard shortcut for going back. This doesn't work anymore under Juno. I hope this isn't intentional, I really liked having a keyboard shortcut for going back.

**Comment by peteruithoven** [comment]
An alternative you could use is alt+left. This also works in Browsers.

**Comment by danrabbit** [comment]
Closing as a duplicate of https://github.com/elementary/files/issues/291
