### ISSUE TITLE
F2 renaming shortcut only works after pressing it twice

### ISSUE THREAD

**Issue by aljelly** [elementary/files#666]
When I've just selected a file I have to press F2 twice in order to rename the file (it should only require one press).

### System Info
elementary OS 5.0 Juno (clean install of stable release, not the beta)

### Reproduction
Select a file in Files. Press F2. It won't work on the first press. Press it again, and it then allows renaming.

### Additional information
At one point the Files app somehow went into this state where any amount of presses of F2 didn't work, in other words F2 alone wasn't working at all. I had to move the mouse to certain positions on the app in order to get F2 to work (I don't know how I got it into this state).

**Comment by jeremypw** [comment]
I can confirm this happens if the item is selected using the helper or has been autoselected by Files.   If the item is selected using the keyboard it does not happen.

**Comment by jeremypw** [comment]
The other problem may be due to the sidebar capturing keyboard focus and the view not recapturing it when it should.  There is an outstanding bug about this and related PR (#603) awaiting review.

**Comment by jeremypw** [comment]
The F2 press twice bug seems to have been regressed recently at least in the case where a folder is autoselected after `<Alt>Up`
