### ISSUE TITLE
Click behavior is altered when sidebar has focus

### ISSUE THREAD

**Issue by peteruithoven** [elementary/files#674]
Reproduce:
1. Select View as List or View as Grid.
2. Click on empty area in sidebar (below network items for example). (It now has focus because you can use keys to navigate sidebar items)
3. In the files section (right bottom part) click on icons or file names. 

Expected behaviour: You open file / go into folder. 
Actual behaviour: The file is just selected. 

You can get it into normal working mode again by clicking in an empty area or in between file names.

I'm on Juno.

![peek 2018-10-19 21-16](https://user-images.githubusercontent.com/523210/47239061-81e3e300-d3e4-11e8-9fa2-9064ecaf43d9.gif)

**Comment by jeremypw** [comment]
This may be related to the fix #603, which is awaiting review and merging.  I'll check it out on that branch.
