### ISSUE TITLE
Files are not shown after pasting into folders newly created with the "does not exist" dialog.

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/files#681]
Steps to reproduce:
1) Navigate to a non-existent directory (i.e. ~/.notadirectory)
2) Files will state the directory doesn't exist and offer to create it, accept this
3) Try pasting some files into the new directory (they don't appear, which is bug number 1).
4) Upon attempting to paste again, you get the conflict dialog because the files were actually pasted in step 3
5) Upon cancelling the conflict dialog, files crashes.

Sorry that's two bugs in one report, but I wanted to get this written down as I can consistently reproduce this. This is Juno stable, I haven't tried master yet.

**Comment by jeremypw** [comment]
I suspect that solving the first problem will fix the second so its OK to leave as one report.

**Comment by jeremypw** [comment]
I have found a related bug affecting existing folders - will file a separate report.
