### ISSUE TITLE
Crash on secondary click after canceled paste

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#682]
To reproduce.

* Copy/paste a file into an existing folder
* Repeat the copy/paste - a dialog appears - choose Cancel
* Secondary-click on the folder background
* Files crashes.

**Comment by arshubham** [comment]
For me it also crashes on step 2

**Comment by jeremypw** [comment]
@arshubham  It does for me too now - maybe I was lucky the first time.  Anyway the linked PR should fix it.
