### ISSUE TITLE
Not open in ElementaryOS Juno, ERRO VALA:50

### ISSUE THREAD

**Issue by rodrigoaraujolima92** [elementary/files#683]
[PT-BR]
Apos fazer o processo de instalação do dropbox ele faz o sync porem nao aparece o icone nem mesmo da para saber se está sincronizando ou não.

**Comment by jeremypw** [comment]
To be honest, the dropbox plugin has not had any work recently as we are working of a new cloud provider interface which will supercede it.  I'll see if I can get the plugin working in Juno.

**Comment by geekpete** [comment]
I get the same:
```
$ io.elementary.files
** Message: 09:29:49.704: Application.vala:50: Report any issues/bugs you might find to https://github.com/elementary/files/issues

(io.elementary.files:3194): GLib-GObject-WARNING **: 09:29:49.716: specified class size for type 'PFDropbox' is smaller than the parent type's 'MarlinPluginsBase' class size

(io.elementary.files:3194): GLib-CRITICAL **: 09:29:49.716: g_once_init_leave: assertion 'result != 0' failed

(io.elementary.files:3194): GLib-GObject-ERROR **: 09:29:49.716: cannot create new instance of invalid (non-instantiatable) type '<invalid>'
Trace/breakpoint trap
```

remove `pantheon-files-plugin-dropbox` package and files starts working again as normal user:

```
$ sudo apt remove pantheon-files-plugin-dropbox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  pantheon-files-plugin-dropbox
0 to upgrade, 0 to newly install, 1 to remove and 0 not to upgrade.
After this operation, 59.4 kB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 317964 files and directories currently installed.)
Removing pantheon-files-plugin-dropbox (0.1-0~31+r2~ubuntu5.0.1) ...
```

**Comment by jeremypw** [comment]
I just tried compiling and installing the dropbox plugin from source and Files runs OK.  The dropbox emblems and context menu also work.

It looks like there is a binary incompatability between the version of libpantheon-files-core that was used to compile the deb and the one used for the current Files package,

**Comment by jeremypw** [comment]
I have pushed a PR with more detailed instructions for installing the plugin from source.

**Comment by codygarver** [comment]
This should be working now after update and reboot.
