### ISSUE TITLE
Ability to disable tabs / Do not default to tabbed view

### ISSUE THREAD

**Issue by eljefuri** [elementary/files#692]
I would like to be able to disable the tab bar entirely. I have never once used tabs in Files, or did I ever use it in the Finder on macOS. I can imagine them being _slightly_ more useful for my workflow with spring-loaded folders (#688) but as it presently stands, I cannot even imagine a use for tabs in Files and would simply like to have a cleaner interface.

Thank you for your consideration.

**Comment by jeremypw** [comment]
I do not think the slight increase in screen real estate by not showing the tabs is worth the extra code to be honest (as well as it being against elementaryos policy to multiply settings without very good reason. Sorry.

**Comment by eljefuri** [comment]
No problem. It is hardly a deal-breaker, and I figured this one had little chance. Thanks for looking at it anyway.

**Comment by LarryAlexander** [comment]
I don't see why not someone could do it. We should at least in these stages of creating the OS give the user control. Now agree not worth the extra code but people love choice, right?

**Comment by LarryAlexander** [comment]
Also can this please be closed soon.

**Comment by jeremypw** [comment]
@LarryAlexander :  You might look at https://elementary.io/docs/human-interface-guidelines#accessible-configuration for elementaryos' philosophy on this sort of thing.  It does not aim for maximum user choice - there are other distros that do that,

**Comment by jeremypw** [comment]
UX team have given this the thumbs down I am afraid.
