### ISSUE TITLE
Make shortcut keys discoverable in context menu

### ISSUE THREAD

**Issue by eljefuri** [elementary/files#697]
_[I know that this issue probably should be placed in some higher-level design repository since it is an Elementary-wide concern, but I want to underline how particularly painful it is to _not_ see shortcut keys listed next to their respective contextual menu items in Files.]_

There are things that I do on a daily basis in file management which are an absolute chore if a mouse or trackpad is needed to do them: Renaming files, trashing files, getting file properties. In order to discover a shortcut key of a given function, I am presently reduced to mashing out likely key combinations or rolling the dice with Google. This seems more than a bit silly, and the former is perhaps even a bit dangerous. Is there a help menu for things like this?

Perhaps it is needless to point out, but the [earliest MacOS revisions](https://youtu.be/hMENx28FueA?t=44) had figured out the utility of showing keyboard shortcuts in pull-down menus, and it is typically found in _context menus_ outside of Elementary. What is the justification for not including them here, when they could be so helpful?

I have already mentioned how [certain](https://github.com/elementary/files/issues/693) [aspects](https://github.com/elementary/files/issues/690) of [navigation](https://github.com/elementary/files/issues/691) would be greatly improved by more consideration given to [semi-professional file-slingers](https://github.com/elementary/files/issues/694), so consider this one in the sequence.

Thanks for your time and consideration.

**Comment by jeremypw** [comment]
This is something that has been on the backburner for a while.  We need to implement this - probably with a shortcut overlay window like the one that Gala uses to show window related shortcuts when the 'Super' key is pressed.

**Comment by jeremypw** [comment]
In the meanwhile a wiki page could be added to GitHub repository.

**Comment by peteruithoven** [comment]
I've opened the following issue shortcut overlay issue on including app shortcuts: https://github.com/elementary/shortcut-overlay/issues/53
(I still think it's a good idea to also include shortcuts in the context menu.)

**Comment by eljefuri** [comment]
> (I still think it's a good idea to also include shortcuts in the context menu.)

Me too, let's try to do that. Meanwhile thank you for opening those other issues.

**Comment by peteruithoven** [comment]
For the curious; here's the code that handles keyboard shortcuts: https://github.com/elementary/files/blob/master/src/View/AbstractDirectoryView.vala#L2730-L2946
(I discovered you can do shift+←/→ to navigate between sidebar and files)

**Comment by jeremypw** [comment]
The Window class also implements a large number of keyboard accelerators for actions and there are specific keyboard handlers in some other classes that take precedence over the base class handler.

**Comment by jeremypw** [comment]
`Shift`+`LeftArrow` ans `Shift`+`RightArrow` multi-selects in icon view but it does switch the keyboard focus in ListView, which is a bit inconsistent.  There is a pending PR that uses the Tab key to toggle focus in all views (#585)

**Comment by peteruithoven** [comment]
Relevant proposal for GTK: https://wiki.gnome.org/Projects/GTK/Menus.
