### ISSUE TITLE
column mode doesn't work when single click is not enabled

### ISSUE THREAD

**Issue by nsklaus** [elementary/files#701]
i disabled the single click option, i prefer good old double-click.
open io.elementary.files, switch view to columns, then double click on one folder, contents appear on the rightmost column, now try to double click on another folder, rightmost column never change, it's frozen.

my environment is, elementary juno, with kernel v4.19, using macbook air 2013, single boot.

**Comment by jeremypw** [comment]
Looks like fairly recent changes to click handling has broken something in double-click mode.

**Comment by jeremypw** [comment]
It looks like the click is not focusing the item and selecting it so it cannot be activated.
It is possible that PR #603 will fix this issue - I will check.
