### ISSUE TITLE
Xdg-open from root doesn't work with Files

### ISSUE THREAD

**Issue by Djaler** [elementary/files#703]
Steps to reproduce:
1. Set `io.elementary.files.desktop` as default app for `inode/directory`:
`sudo xdg-mime default io.elementary.files.desktop inode/directory`
2. Try to use `xdg-open` on any folder:
`sudo xdg-open /home/djaler`

Expected:
Files opened in specified directory

Actual:
```
** (io.elementary.files:21893): WARNING **: 23:16:10.223: Application.vala:54: Running Files as root using sudo is not possible. Please use the command: io.elementary.files-pkexec [folder]
```

**Comment by jeremypw** [comment]
The xdg-open man page states:

 "xdg-open is for use inside a desktop session only. It is not recommended to use xdg-open  as root."

Likewise opening Files with `sudo` is deliberately blocked for security reasons.

So I do not think this is a bug.

**Comment by Djaler** [comment]
Ok, thanks
