### ISSUE TITLE
Wrong number of selected elements reported

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/files#705]
12 files are selected, 11 are reported

![captura de pantalla de 2018-10-25 14-45-14](https://user-images.githubusercontent.com/6054951/47519834-dfed4c00-d864-11e8-9bcf-bd5ef9aaf2a4.png)

**Comment by jeremypw** [comment]
With the master version of Files, hovering a multi-selection like this is giving the properties of the hovered file in the overlay.  This might be a regression.

Does the properties window shown by the context menu option give the correct number of selected files?

**Comment by Gabriel-p** [comment]
I'm finding it very hard to get the multi-selection information to show actually. It is not working properly.

The properties window shows the correct number of files.

**Comment by jeremypw** [comment]
I have raised a new issue about the multi-selection properties overlay.

**Comment by jeremypw** [comment]
This should be fixed by an existing PR #669  Hopefully it will be approved and merged soon.
