### ISSUE TITLE
Broadcom Wifi missing after install

### ISSUE THREAD

**Issue by LarryAlexander** [elementary/files#707]
I am using an Aspire R7 laptop. 

I've had this issue in the past with my wifi card not being recognized by some Linux distros and it causes me to have to do it manually. I would love if someone could possibly implement these drivers and make it so that this issue is solved within Elementary OS at least. 

Also for anyone who has Broadcom cards and needs an offline fix to use the files below. Place them into your home folder or wherever and install them. Using these command in terminal. Hope I was able to help someone. 

Also, hope this will be taken into consideration.

Files:
http://mirrors.kernel.org/ubuntu/pool/main/b/b43-fwcutter/b43-fwcutter_015-9_amd64.deb http://www.lwfinger.com/b43-firmware/broadcom-wl-5.100.138.tar.bz2

Terminal Commands:
`sudo dpkg -i b43-fwcutter_015-9_amd64.deb
tar xfvj broadcom-wl-5.100.138.tar.bz2
sudo b43-fwcutter -w /lib/firmware broadcom-wl-5.100.138/linux/wl_apsta.o`

**Comment by jeremypw** [comment]
This is not really a Files issue.  You could try raising it under the 'wingpanel-indicator-network' but I suspect it may be an upstream problem. If it works in Ubuntu it should work in elementary.
