### ISSUE TITLE
Can't run a script other than .sh by context menu

### ISSUE THREAD

**Issue by fcostarodrigo** [elementary/files#711]
![output](https://user-images.githubusercontent.com/16693844/47600209-d31b4600-d993-11e8-99f3-566c7d67cd19.gif)

When I add the `execute` permission to a `.sh`, an option to run the file in the context menu appears. But when I do the same for a `.coffee` file, nothing happens. Is there a missing configuration?

Here there is a check to see if the file is executable, if so it adds the run item in the menu.
https://github.com/elementary/files/blob/383340845604a12c571dec876cdc15a948a19f92/src/View/AbstractDirectoryView.vala#L2064

This is where the `is_executable` function comes from.
https://github.com/elementary/files/blob/e79affb78b65a53dda79277adab4089750edccfa/libcore/pantheon-files-core-C.vapi#L194

Found this documentation, but it only says it returns true if the file is executable:
https://lazka.github.io/pgi-docs/GLib-2.0/flags.html#GLib.FileTest.IS_EXECUTABLE

Here is the source of `G_FILE_TEST_IS_EXECUTABLE`
https://github.com/GNOME/glib/blob/cbfa776fc149fcc3e351fbdf68c1a299519f4905/glib/gfileutils.h#L71

**Comment by jeremypw** [comment]
The `is_executable()` function referred to in the .vapi is a function of GOFFile not of GFile.  GOFFile is a wrapper for GFile, adding extra functionality.  The GOFFile function includes:
```
        if (G_LIKELY (content_type != NULL))
        {
            /* check if the content type is safe to execute, we don't use
             * g_content_type_can_be_executable() for unix because it also returns
             * true for "text/plain" and we don't want that */
            if (g_content_type_is_a (content_type, "application/x-executable")) {
                can_execute = TRUE;
            }
        }
```

so not all files with execute permission of executed by default.  This was put in place for security reasons.  We would have to expand the list of `safe` mimetypes for coffeescript to run.

**Comment by fcostarodrigo** [comment]
I managed to make coffee script files part of the `application/x-executable` type.

I created a file `~/.local/share/mime/packages/x-coffeescript.xml` with

```xml
<?xml version="1.0" encoding="utf-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
    <mime-type xmlns="http://www.freedesktop.org/standards/shared-mime-info" type="application/vnd.coffeescript">
      <comment>CoffeeScript document</comment>
      <comment xml:lang="ast">Documentu de CoffeScript</comment>
      <comment xml:lang="ca">document CoffeeScript</comment>
      <comment xml:lang="cs">dokument CoffeeScript</comment>
      <comment xml:lang="da">CoffeeScript-dokument</comment>
      <comment xml:lang="de">CoffeeScript-Dokument</comment>
      <comment xml:lang="el">Έγγραφο CoffeeScript</comment>
      <comment xml:lang="en_GB">CoffeeScript document</comment>
      <comment xml:lang="es">documento en CoffeeScript</comment>
      <comment xml:lang="eu">CoffeeScript dokumentua</comment>
      <comment xml:lang="fi">CoffeeScript-asiakirja</comment>
      <comment xml:lang="fr">document CoffeeScript</comment>
      <comment xml:lang="ga">cáipéis CoffeeScript</comment>
      <comment xml:lang="he">מסמך CoffeeScript</comment>
      <comment xml:lang="hr">CoffeeScript dokument</comment>
      <comment xml:lang="hu">CoffeeScript dokumentum</comment>
      <comment xml:lang="ia">Documento CoffeeScript</comment>
      <comment xml:lang="id">Dokumen CoffeeScript</comment>
      <comment xml:lang="it">Documento CoffeeScript</comment>
      <comment xml:lang="kk">CoffeeScript құжаты</comment>
      <comment xml:lang="ko">CoffeeScript 문서</comment>
      <comment xml:lang="oc">Document CoffeScript</comment>
      <comment xml:lang="pl">Dokument CoffeeScript</comment>
      <comment xml:lang="pt">documento CoffeeScript</comment>
      <comment xml:lang="pt_BR">Documento CoffeeScript</comment>
      <comment xml:lang="ru">Документ CoffeeScript</comment>
      <comment xml:lang="sk">Dokument CoffeeScript</comment>
      <comment xml:lang="sr">Кофи скрипт документ</comment>
      <comment xml:lang="sv">CoffeeScript-dokument</comment>
      <comment xml:lang="tr">CoffeeScript belgesi</comment>
      <comment xml:lang="uk">документ CoffeeScript</comment>
      <comment xml:lang="zh_CN">CoffeeScript 文档</comment>
      <comment xml:lang="zh_TW">CoffeeScript 文件</comment>
      <sub-class-of type="application/x-executable"/>
      <sub-class-of type="text/plain"/>
      <generic-icon name="text-x-script"/>
      <glob pattern="*.coffee"/>
    </mime-type>
</mime-info>
```
The content is based on `/usr/share/mime/application/vnd.coffeescript.xml`. I added the `mime-info` tag and the line `<sub-class-of type="application/x-executable"/>`.

Then I run `update-mime-database ~/.local/share/mime`.

Now the menu entry "Run" shows up for executable coffee script files.

Thanks.

**Comment by jeremypw** [comment]
@fcostarodrigo  Thanks for the tip !
