### ISSUE TITLE
Using the "Send by email" option does not respect configured applications

### ISSUE THREAD

**Issue by wout** [elementary/files#716]
I've got Thunderbird configured as my default email client, but Files still opens Mail when using the "Send by email" option from the contextual menu:

![image](https://user-images.githubusercontent.com/107324/47619110-5e532380-dadb-11e8-854a-1a541a17e39a.png)

**Comment by arshubham** [comment]
I think this is because the functionality is handled by mail itself. https://github.com/elementary/mail/blob/1.x/data/mail-attach.contract . However since mail is being rewritten you may want to open a issue there, to redirect the request or hide the contact if mail is not the default.

**Comment by wout** [comment]
Should I move the issue to Mail and close it here?

**Comment by arshubham** [comment]
Yes, you should move it there and close this one.

**Comment by wout** [comment]
https://github.com/elementary/mail/issues/311
