### ISSUE TITLE
Archive Manager hangs when pressing "Extract"

### ISSUE THREAD

**Issue by Coi-l** [elementary/files#718]
Steps to reproduce:
1) Browse to a zip file. I tried it with git from this link (https://github.com/git/git/archive/v2.19.1.zip) and a zip file manually zipped with the zip command line tool.

2) Browse to the zip file in Files

3) Open the zip file

4) Click Extract -> Window locked

System: Juno
Macbook Pro 5.1

Only way to close the now locked window is by reboot or finding and killing file-roller.

**Comment by jeremypw** [comment]
Please confirm whether it is the Files window that locks or the archive manager window.

**Comment by jeremypw** [comment]
I did not have any trouble extracting the given zip file from github using the native elementary Files/Archive Manager in an English locale.  You could try starting Files in a terminal with `io.elementary.files` (close existing Files windows first).  See if there are any useful messages given when the hang occurs.  When you press `Extract` you should get a native Gnome filechooser dialog asking where to extract.  Make sure this dialog window is not hidden underneath something as it will lock the archive manager window.

**Comment by Coi-l** [comment]
It is the Archive Manager window that hangs.

Starting Files from the terminal did not produce any output.

I'm guessing the problem is that the Archive Managers extract button is active but nothing is selected in the list of files. So when I then press the button it hangs.

**Comment by jeremypw** [comment]
So, what happens if you just start the Archive Manager alone from the commandline? 
e.g. `file-roller ./git-2.19.1.zip`

**Comment by Coi-l** [comment]
It hangs in the same way when pressing Extract

**Comment by jeremypw** [comment]
This looks like a bug in the Gnome Archive Manager.  Try filing a report here:
https://bugs.launchpad.net/ubuntu/+source/file-roller
