### ISSUE TITLE
files will happily destroy fat32 filesystems

### ISSUE THREAD

**Issue by Nine-H** [elementary/files#725]
without thinking I changed a directory name from `Notes` to `Notes.bak` on a fat32 filesystem, don't worry: the device is fine because I recovered it with dosfsck, it's just annoying that files didn't give me a heads up.

**Comment by jeremypw** [comment]
I tried to reproduce this using a USB stick with a FAT32 partition but could not.  It worked quite happily with a folder named "Notes.bak"

**Comment by jeremypw** [comment]
Closing as no followup from OP
