### ISSUE TITLE
Canceling copying a file into a folder that has a file with same name crashes the app

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#730]
* Create a new folder (hereinafter called FOLDER) and a new file (FILE A) in the same directory
* Create a new file (FILE A') inside FOLDER with the same name with FILE A
* Try to **copy** FILE A into the FOLDER. A confirmation dialog is shown because FILE A and FILE A' have same name
* Press `Esc` or click "Cancel". The app crashes

This issue does not happen when we **cut** and paste FILE A into FOLDER.

With Files 4.0 on Juno

**Comment by ryonakano** [comment]
And I got this error:

```
ERROR:/build/pantheon-files-qU8cns/pantheon-files-4.0+r3121+pkg70~ubuntu5.0.1/libcore/marlin-file-operations.c:4151:copy_move_file: code should not be reached
```

**Comment by jeremypw** [comment]
PR #684 (merged into master 11 days ago) fixed this, or a similar bug.  Are you using the stable or daily version of Juno?

**Comment by jeremypw** [comment]
The intention is to reduce the number of "assert_not_reached ()" lines in released code, replacing them with code to handle gracefully.

**Comment by jeremypw** [comment]
Yes, the last stable release (4.0) happened before the relevant fix.

**Comment by jeremypw** [comment]
This bug does not occur in the current master.

**Comment by ryonakano** [comment]
I see, thank you.
