### ISSUE TITLE
Focus issue when selecting mutiple files/folders randomly

### ISSUE THREAD

**Issue by mdalch** [elementary/files#733]
Focus is maintained while selecting multiple Files/Folders respectively afterwards, but it is not the case by selecting backwards or even in a random way!

OS: Juno 5.0 up to date

![peek 2018-11-03 13-20](https://user-images.githubusercontent.com/10380737/47952173-89ba9000-df6b-11e8-9e66-8330c55e88ac.gif)

**Comment by yeboahnanaosei** [comment]
Thank you for reporting this issue, I was struggling with how to write it. Anyway yes, this was not an issue on Loki.

**Comment by matej-marcisovsky** [comment]
I can confirm this bug. I was not sure how to reproduce it but based on the pattern described by @alchehabi I was able to experience this bug every time.

**Comment by peteruithoven** [comment]
@mdalch why was this closed? Has it been fixed? Could you include a reference to a PR if it's fixed?

**Comment by jeremypw** [comment]
I cannot reproduce this with the current master branch.  The selection persists regardless of the order of selecting *provided you click on the helper (tick)*.  Note that if you miss the helper then the selection will be lost (unless you also hold down the `<Ctrl>` key.  Version 4.1.7 has just been released.  Please confirm whether the problem can be reproduced with that version, thanks.

**Comment by mdalch** [comment]
@peteruithoven I closed it because it's fixed as I believe, I don't encounter this issue anymore since Files is up to date.

@jeremypw This issue was fixed actually in some version after 4.1.0. Honestly I forgot to close the issue in that time. I tried to remember in what exact version was this issue fixed but i couldn't. Sorry for that.
