### ISSUE TITLE
File System disk usage bar showing wrong value

### ISSUE THREAD

**Issue by cuibonobo** [elementary/files#734]
![screenshot from 2018-11-03 12-00-53](https://user-images.githubusercontent.com/391241/47954503-16138580-df61-11e8-8d95-66f861484c4d.png)

Hovering over the progress bar shows the following tooltip: `/ - ext3/ext4 (437.0 GB free of 501.2 GB`. The progress bar should be at about 8%, but it seems to be stuck in the beginning.

  * Files 4.0
  * elementary OS 5.0 Juno (64-bit)
  * Ubuntu 18.04 LTS
  * Linux 4.15.0-38-generic
  * GTK+ 3.22.30
  * ThinkPad T450
  * SAMSUNG MZ7LN512HCHP-000L1 (512 GB SSD)

**Comment by jeremypw** [comment]
If you right click on the drive and choose "Properties" does it show the same usage?
If you drag the edge of the sidebar towards the view to make the sidebar wider, does the blue part of the bar expand in proportion to the total width?  

Just tried to reproduce using a USB stick filled to about 5% of capacity but the bar showed approximately the right degree of fill.

**Comment by cuibonobo** [comment]
Right-clicking the drive in the sidebar doesn't show a "Properties" option. Am I looking in the wrong place? Expanding the sidebar does expand the blue part. I'm not sure if my eyes are playing tricks on me but it seems like when it's expanded the blue part is proportionally larger than when the sidebar is in its original place.

![screenshot from 2018-11-08 08-12-16](https://user-images.githubusercontent.com/391241/48200934-a588b200-e32e-11e8-9441-a473f5c3e8f8.png)

**Comment by jeremypw** [comment]
OK, thanks.  It looks like its a some kind padding/offset problem in that case.  You are right - the File System device does not show the "Properties" menu item for some reason.  I think that is another bug.  External devices and other partitions do show the option.  The File System device is also drawn shorter (there is already a report about this).
