### ISSUE TITLE
Folder icon for remote location changes when zoomed or when row expanded.

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#759]
Not sure if this should be raised here or in the icons project but ...

* Display a remote network location in ListView
* The smallest folder icon is a white cloud but zooming larger makes into a manilla folder with cloud imprint.
* Expanding a cloud icon also turns it into a small open manilla folder with a cloud imprint.

If there is a small sized icon for a manilla folder with a cloud imprint then there should be a similar one for a closed folder and it should be used in the view. (The sidebar will have to be considered separately - a cloud icon looks better there).

**Comment by peteruithoven** [comment]
Maybe this is an https://github.com/elementary/icons/ issue?
I think I can see what you mentioned in Lookbook:
 
![screenshot from 2018-11-15 15 15 52](https://user-images.githubusercontent.com/523210/48558340-5cfe6500-e8e9-11e8-82e8-07bfe3deef19.png)

**Comment by jeremypw** [comment]
Raised in icons project
