### ISSUE TITLE
Files App Doesn't Have Disable All and/or Some Specific File Thumbnails Option

### ISSUE THREAD

**Issue by umitseyhan75** [elementary/files#765]
For example, there is a .doc file in Files app and I can see what is in it. But I want to see just .doc template icon. I'm using Juno.

**Comment by jeremypw** [comment]
I think it would be over-complex to inhibit thumbnails of specific mimetypes, but it would be possible to add an option to control thumbnailing for local folders as well as remote folders.  This would have to be in the folder context menu as there is a prohibition on the use of an AppMenu in Files.
