### ISSUE TITLE
Folders before files

### ISSUE THREAD

**Issue by DDoubleU** [elementary/files#777]
Files doesn't have an option to configure the "Folders before files" option in dconf. You can only use the toggle/checkbox in the context menu. Would it be possible to implement this more like the "Show hidden files" option which is configurable through dconf.

**Comment by jeremypw** [comment]
There is a dconf setting - we use the existing `org.gtk.Settings.FileChooser.sort-directories-first`.  I do not think it would be appropriate to raise the option to the top level menu as I feel users are not going to change this very often once they have chosed their preference.

**Comment by jeremypw** [comment]
OK, thanks.  I'll close this now, then.
