### ISSUE TITLE
Connect to server not possible.

### ISSUE THREAD

**Issue by dkotrada** [elementary/files#79]
On Loki

When I click on the Item in the left panel in Files. "Connect to Server" "Mit Server verbinden"

I get an error. Please check your gvfs installation.

**Comment by jeremypw** [comment]
Please provide more information. Did it start happening after an update or on a clean install? What error do you get?

**Comment by dkotrada** [comment]
After an update.

**Comment by danrabbit** [comment]
Closing since OP never responded to the follow up question. Feel free to reopen if this can be reproduced
