### ISSUE TITLE
Permanently delete dialog - doesn't follow HIG

### ISSUE THREAD

**Issue by yelloball** [elementary/files#812]
The permanently delete dialog doesn't follow the design guidelines.

Within the dialog box, two 'normal' sized buttons with proper spacing between them are expected, rather than two large buttons stuck together.

Recreate by emptying contents from Trash folder.

![trash-delete-dialog-ui](https://user-images.githubusercontent.com/14001336/50044306-b48a1f00-00a7-11e9-9dcb-88f0200ea3d4.png)

**Comment by aleksandar-stefanovic** [comment]
In addition, it doesn't adhere to the "Rather than present the user with a warning, apps should let the user undo the action for an appropriate amount of time" guideline, which has explicitly noted

> **Deleting an item**. Instead of asking the user if they are sure, make the item "disappear" from the app, but provide an easy and intuitive way to undo the delete.

I guess this hasn't been implemented yet due to technical reasons.

**Comment by jeremypw** [comment]
This is probably related to #787.

@aleksandar-stefanovic : Undoable deletion actually moves files to Trash so it does not make much sense to have another undoable delete action from Trash. I guess it would technically be possible to move them to another hidden/temporary trash which emptied after a certain delay.  Please open a separate issue if you like.

You can in fact turn off this confirmation dialog by changing io.elementary.files.preferences.confirm-trash setting.

**Comment by danrabbit** [comment]
This has been fixed :)
