### ISSUE TITLE
Ctrl+C and Crtl+V do not work with dvorak keyboard

### ISSUE THREAD

**Issue by finetuned89** [elementary/files#815]
`ctrl+C` and `ctrl+V` do not work on selected items when using a US Dvorak keyboard. Using these key combos does nothing. Using the keys that are in place of C and V (J and K in this case) also do nothing. Switching to qwerty layout restores the functionality (on the J and K keys which are C and V in qwerty).

I am using a ISO-layout (dutch) Apple Bluetooth keyboard (model A1314) with the keycaps rearranged to dvorak:

![img_3534](https://user-images.githubusercontent.com/12174852/50107386-de238180-0232-11e9-9b85-09102811cc29.JPG)

Further details:

- Using ctrl+C and ctrl+V does work for copying and pasting text in the location bar and text fields when renaming files
- Using ctrl+C and ctrl+V does work in most other applications (including Code, LibreOffice, Firefox and Thunderbird)
- I am using the Dutch locale (formats and language)
- The keyboard selected is English (US) > Dvorak:

![keyboard-layout](https://user-images.githubusercontent.com/12174852/50111661-8b9b9280-023d-11e9-8c69-8c9aa659bd32.png)

This seems like the same problem as #257, but whatever fixed that did not fix it for my situation.

**Comment by jeremypw** [comment]
What keyboard layout have you selected in the Settings keyboard plug?  If you choose "Dutch" for the keyboard layout it does not give a "Dvorak" option.  Only "Macintosh", "Standard" and "with Sun dead keys"??

**Comment by finetuned89** [comment]
The keyboard selection is English (US) > Dvorak.

**Comment by jeremypw** [comment]
@finetuned89 :  I just tried changing my laptop keyboard layout to US (Dvorak) and copy/paste worked fine in English locale when I used the keys that are (or would be) labelled "C" and "V" (i.e. the keys in the positions of "I" and "." on a QWERTY keyboard)  together with the control key.

Please confirm your relabelled keyboard looks like:
![1200px-kb_united_states_dvorak svg](https://user-images.githubusercontent.com/10513844/50152166-d4456100-02ba-11e9-8802-48f9565fdfc6.png)

I'll try switching to Dutch locale.

**Comment by finetuned89** [comment]
I added a picture of my keyboard and the screenshot from the elementary to the original post. The layout is indeed the same as your picture, save for the fact that I'm using an ISO layout with the extra key next to the left shift.

**Comment by jeremypw** [comment]
@finetuned89 Are you able to install Files from the master source?  The fix for this may not have been release to the repository you are using yet.

**Comment by finetuned89** [comment]
Using the version from master source indeed solves this problem.

**Comment by jeremypw** [comment]
Fixed in master
