### ISSUE TITLE
'color tags' removed?

### ISSUE THREAD

**Issue by J0Ar** [elementary/files#829]
I noticed today the color tags are not shown anymore...were they removed lately at any point? 
![colortags](https://user-images.githubusercontent.com/23266409/50537379-f9f62400-0b5e-11e9-8391-6c6078a2e226.png)

UPDATE: I tried in qemu (purged and installed the last pantheon-files deb's ...) and i find out the last version (stable) with functional color tags was
https://code.launchpad.net/~elementary-os/+archive/ubuntu/stable/+build/15548537

**Comment by jeremypw** [comment]
Looks like c2b5adb873028abe947f742fa5d0371a668957be was intended to fix this :-(

**Comment by jeremypw** [comment]
This seems to be the problem: 0e523cc4501e910c648d979c9932239c5ee6d45e.
