### ISSUE TITLE
meson: shared libraries installed twice, with different versions (since 4.1.0)

### ISSUE THREAD

**Issue by decathorpe** [elementary/files#837]
Since commit https://github.com/elementary/files/commit/b2a92948a56e61276cfc43d7fcd1fb3c4874edc3 (the 4.1.0 Release commit, which also fixed the meson project version to match the actual version), there are now *two* shared libraries with different versions installed simultaneously:

- `/usr/lib64/libpantheon-files-core.so.0` and `/usr/lib64/libpantheon-files-widgets.so.0`, and
- `/usr/lib64/libpantheon-files-core.so.4.1.1` and `/usr/lib64/libpantheon-files-widgets.so.4.1.1`

It looks like those files are installed (or even compiled) twice somewhere in the meson definitions, with different versioning rules attached to them :interrobang:

**Comment by decathorpe** [comment]
Notifying @codygarver directly - this issue has been present in the last four stable releases you tagged (4.1.0, 4.1.1, 4.1.2, and 4.1.3), which I didn't push to fedora because of this issue.

**Comment by jeremypw** [comment]
After clearing out old all pantheon-files libraries from usr/lib/x86_64_linux-gnu and reinstalling from master source, only one set of libraries was installed, so maybe the package is not uninstalling the old libraries?

**Comment by decathorpe** [comment]
This is happening for RPM builds, so there's no "old version" present.

I'll check tomorrow if this issue persists.

**Comment by tintou** [comment]
We need to remove the `soversion` argument from
https://github.com/elementary/files/blob/master/libcore/meson.build#L73 and https://github.com/elementary/files/blob/master/libwidgets/meson.build#L33
