### ISSUE TITLE
Appcenter page bug link links to old launchpad bug tracking page.

### ISSUE THREAD

**Issue by aggalex** [elementary/files#84]
The "Report a Problem" button on the appcenter page for this app directs users to the old launchpad page of the app. Bug tracking is not accepted there. plz fix.

**Comment by btkostner** [comment]
This has already been fixed in [this commit](https://github.com/elementary/files/commit/7dd9a5af4e5985377199cd80b5411b68f76089c2) we are just waiting for a release to push it to users.
