### ISSUE TITLE
Location bar text doesn't have proper contrast in dark mode

### ISSUE THREAD

**Issue by GammaGames** [elementary/files#840]
Now that the location bar has been updated with a search icon, the text is black on dark grey when using the dark style.

![image](https://user-images.githubusercontent.com/7832163/50576676-1353d600-0dd4-11e9-9e8d-a18ca5452a6e.png)

**Comment by GammaGames** [comment]
This is only when you are in your home directory

**Comment by ryonakano** [comment]
![Screenshot from 2019-05-03 15-57-57](https://user-images.githubusercontent.com/26003928/57123343-68244f00-6dbc-11e9-8590-f95219cf51f9.png)

This should be fixed in the latest version of Files (4.1.8) which include a fix for this issue (#925).

**Comment by GammaGames** [comment]
Looks like I have 4.1.8 installed and it is indeed fixed. Thank you!
