### ISSUE TITLE
Less accurate search matching and UX

### ISSUE THREAD

**Issue by aberba** [elementary/files#842]
Currently, search in Files does not see some files in **sub directories** and even **current directory** sometimes when I search from the search bar. Seem the search is less accurate in that regard.

Also, the returned search results preview (shown in drop-down below search bar) does not allow me to see the remaining results using my mouse. The **three dots** appended at the end of returned results could be an active button which show all results found. 

![screenshot from 2019-01-02 21 15 52](https://user-images.githubusercontent.com/8314648/50613137-7e84d180-0ed4-11e9-9440-7b7db0399d45.png)

**Comment by jeremypw** [comment]
There are a couple of outstanding PRs that should help with this.  
#795 Fixes a bug that causes some search results not be displayed when the search window is first displayed (even though they have been found).
#804 Implements the idea of making the ellipsis activatable

**Comment by jeremypw** [comment]
Note: please raise separate issues rather than mention two different things in one issue (even if they are related).

**Comment by peteruithoven** [comment]
> Currently, search in Files does not see some files in sub directories and even current directory sometimes when I search from the search bar. Seem the search is less accurate in that regard.

This isn't really something we can verify / reproduce? Less accurate than what for example? 

I'm closing this issue, as @jeremypw mentioned you're also combining two issues in this issue.
