### ISSUE TITLE
File and folder names lost their border radius

### ISSUE THREAD

**Issue by Akryum** [elementary/files#843]
In Loki, the file and folder labels had a nice border radius when selected:

![screenshot from 2019-01-03 19-32-50](https://user-images.githubusercontent.com/2798204/50657424-bce2c500-0f96-11e9-974a-2e361022df1f.png)

Maybe it's just me, but it doesn't look good now:

![screenshot from 2019-01-03 19-56-28](https://user-images.githubusercontent.com/2798204/50657442-cf5cfe80-0f96-11e9-8fca-c7cd31cc378e.png)

![screenshot from 2019-01-03 19-56-35](https://user-images.githubusercontent.com/2798204/50657450-d3891c00-0f96-11e9-8229-ddf83baeb5aa.png)

**Comment by jeremypw** [comment]
This is down to 16a545eeebb2b758dda176481333fa5b5e271cc7

**Comment by Akryum** [comment]
Is it possible to use CSS to apply border radius on those?

**Comment by Akryum** [comment]
Maybe the background can be removed altogether since we have a background color now?

**Comment by jeremypw** [comment]
I think there is a problem using CSS in a CellRenderer - you are not rendering individual widgets, so changing the CSS for the view would change every item.

Yes, the background could be removed if @elementary/us approve.

**Comment by Akryum** [comment]
However this brings the question of the color tags. Maybe the background can safely be removed if there is no color tag. With color tag it would be better with border-radius, it looks unpolished without it.

MacOS has another solution, a color bullet in from of the label:

![macos](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/social/macos-mojave-macbook-finder-social-card.jpg)

**Comment by jeremypw** [comment]
The bullet could be emulated if desired.

**Comment by cassidyjames** [comment]
The color bullet looks nice and avoids contrast issues with text, so I'm in favor of that design change. Other @elementary/ux thoughts?

**Comment by jeremypw** [comment]
I'll look into implementing this.  May be tricky using CSS (suggestions?) but should be doable with Cairo

**Comment by jeremypw** [comment]
Or maybe can be rendered in the Pango layout?

**Comment by cassidyjames** [comment]
@jeremypw CSS would probably be best for flexibility down the road. We do a colored dot for calendars, maybe check that code?

**Comment by cassidyjames** [comment]
@jeremypw it looks like we add a grid with a width/height request and style class, then style it right in the code

https://github.com/elementary/calendar/blob/1da543ce2f5999183c50046fa693e4e2071e9ef6/src/Widgets/CalendarButton.vala#L218

https://github.com/elementary/calendar/blob/1da543ce2f5999183c50046fa693e4e2071e9ef6/src/Widgets/CalendarButton.vala#L20

**Comment by jeremypw** [comment]
@cassidyjames Thanks, I'll check that out, although here we are rendering a CellLayout not a Widget.
