### ISSUE TITLE
Background instead of lightening icon on hover

### ISSUE THREAD

**Issue by Akryum** [elementary/files#846]
Lightening the item icon or thumbnail isn't very accessible and can even be problematic for bright thumbnail (see #712). Maybe a better alternative would be to draw a background on hover without modifying the icon/thumbnail. It would also be less subtle and make it more clear if the user click will interact with the target item or the current folder.

**Comment by peteruithoven** [comment]
This issue might be relevant: https://github.com/elementary/files/issues/473

**Comment by danrabbit** [comment]
Yes, closing as a duplicate of #473
