### ISSUE TITLE
Closing unfocused tab shows wrong path in breadcrumb

### ISSUE THREAD

**Issue by janxkoci** [elementary/files#858]
When I have several tabs open in the Files and I close one of those not in focus, the breadcrumb switches to show a path of that (closed) tab instead of the one I have in front of me. Clicking into the tab or switching to different window and back will load the correct path in breadcrumb.
![snimek z 2019-01-11 15-15-05](https://user-images.githubusercontent.com/19331850/51038632-05f8d180-15b4-11e9-8ab1-f5b2eab83c2a.png)

**Comment by jeremypw** [comment]
An existing PR for a slightly different issue also fixes this one.

**Comment by janxkoci** [comment]
So when we will see this fixed?

**Comment by janxkoci** [comment]
I still see this btw, in the current stable..

**Comment by jeremypw** [comment]
Hmm, looks like that PR did not fix this issue as well after all :-(  I will have to fix separately.

**Comment by jeremypw** [comment]
Actually looking back the PR was withdrawn as nobody reviewed it!  So all the related issues are still outstanding.  Will try and find a simpler solution at some point.

**Comment by janxkoci** [comment]
I can confirm it's fixed.
