### ISSUE TITLE
Duplicate tab keyboard shortcut?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/files#867]
It's possible to duplicate a tab by right clicking the tab and selecting Duplicate. I'd love to be able to do this with a keyboard shortcut.
I've just learned that in browsers like Chrome and Firefox the only way to do this with the keyboard is by doing:
1. <kbd>Alt</kbd> + <kbd>D</kbd> or <kbd>Ctrl</kbd> + <kbd>L</kbd>: Focus url bar
2. <kbd>Alt</kbd> + <kbd>Enter</kbd>: Open in new tab

Would this be interesting for Files?

In my mind <kbd>Ctrl</kbd> + <kbd>Enter</kbd> makes more sense, but there is probably a reason. 

( <kbd>Shift</kbd> + <kbd>Enter</kbd>: Open in new window )

**Comment by joe247** [comment]
> It's possible to duplicate a tab by right clicking the tab and selecting Duplicate. I'd love to be able to do this with a keyboard shortcut.
> I've just learned that in browsers like Chrome and Firefox the only way to do this with the keyboard is by doing:
> 
>     1. Alt + D or Ctrl + L: Focus url bar
> 
>     2. Alt + Enter: Open in new tab
> 
> 
> Would this be interesting for Files?
> 
> In my mind Ctrl + Enter makes more sense, but there is probably a reason.
> 
> ( Shift + Enter: Open in new window )
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/69206512-duplicate-tab-keyboard-shortcut?utm_campaign=plugin&utm_content=tracker%2F65602118&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F65602118&utm_medium=issues&utm_source=github).

And <kbd>Ctrl</kbd>+<kbd>Tab</kbd> to scroll between tabs like this: 
![Screenshot from 2020-01-11 10 14 55](https://user-images.githubusercontent.com/38415384/72198978-41dea500-345b-11ea-9358-de1233ef8794.png)

**Comment by peteruithoven** [comment]
@joe247 that sounds like a separate feature? Could you open a new issue for it? (If it doesn't exist yet).

**Comment by joe247** [comment]
@peteruithoven sorry... I didn't check earlier... this feature already exists in Files!

In `io.elementary.terminal`  I can open new tabs using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> and move around using <kbd>Alt</kbd>+<kbd>N</kbd>... so both work well...

Sorry for unnecessarily taking your time...

**Comment by danirabbit** [comment]
Not sure when this was fixed, but there is a keyboard shortcut <kbd>Ctrl</kbd> <kbd>Alt</kbd> <kbd>T</kbd> for duplicating tabs already
