### ISSUE TITLE
polkit policy file installed to wrong location

### ISSUE THREAD

**Issue by decathorpe** [elementary/files#872]
When intltool was dropped (https://github.com/elementary/files/commit/81792176547bde56f54197c500729c8f8a03b9ad), the destination directory of the polkit file was changed to `/usr/share/applications/`, probably due to some copypasta gone wrong.

```diff
- install_dir : join_paths(get_option('datadir'), 'polkit-1', 'actions')
+ install_dir: join_paths(get_option('datadir'), 'applications'),
```

**Comment by codygarver** [comment]
Closed by #873
