### ISSUE TITLE
Permanently high CPU usage (4.1.4 regression)

### ISSUE THREAD

**Issue by Vortex-TH** [elementary/files#878]
Pantheon-files has an high CPU usage for me since 4.1.4, thus making it barely usable. There seems to be some operation in the background which causes icons to flicker when hovering over them and also causes (some) hidden folders to permanently swap position.

There are two ways to avoid this issue:
-Launch Files as privileged user
-Downgrade to 4.1.3

**Comment by jeremypw** [comment]
@Vortex-TH : I have installed 4.1.4 and do not get this problem.  Please could you give further information concerning your locale and any non-default settings? e.g. single-click/double-click mode, accessibility, drop-box plugin.  Does the high CPU usage start immediately after launch or after performing a certain operation?

**Comment by jeremypw** [comment]
OK, I have found that I had the new "Hide Local Thumbnails" option on.  If I turn this off then I do get the flickering as the pointer moves over an icon and a raised background CPU usage  (about 10% of one core).  Thanks for raising this issue.
