### ISSUE TITLE
Hidden files are sorted randomly

### ISSUE THREAD

**Issue by tuxiano** [elementary/files#880]
Hi,

I just noticed, that hidden files are sorted randomly even if I choose "sort by name" in the file manager version 4.1.4.

Kind regards,

tuxiano
![bildschirmfoto von 2019-02-03 14-59-49](https://user-images.githubusercontent.com/12428267/52177648-66022280-27c4-11e9-949d-a0668486ad00.png)

**Comment by jeremypw** [comment]
Not sure when that regression occurred... It only affects sorting by name.

**Comment by jeremypw** [comment]
Yes, there is a small error in the Vala port of the compare_by_displayname function.  Will push a PR soon.
