### ISSUE TITLE
Make better use of the address bar space

### ISSUE THREAD

**Issue by sprite-1** [elementary/files#885]
![image](https://user-images.githubusercontent.com/33685433/52705209-51403e80-2fbd-11e9-8020-4a24d1ccc726.png)

As can be seen on the above screenshot, the address bar is wasting quite a lot of white space while truncating the rest of the path. I think it should stretch all the way to the end or just leave a small gap at the end so the user can click that to edit the path just like before.

**Comment by jeremypw** [comment]
There does not seem to be any reason not to reduce the space at the right.

**Comment by jeremypw** [comment]
Fixed by #896
