### ISSUE TITLE
File and folders sorting is all over the place

### ISSUE THREAD

**Issue by sprite-1** [elementary/files#886]
I'm not sure what ordering they're following but it's not `by Name`

![image_2019-02-14_02-00-53](https://user-images.githubusercontent.com/33685433/52732968-7d2ee480-2ffc-11e9-8e8e-77dd25da3630.png)

**Comment by arshubham** [comment]
I think this regression has already been fixed in master. See https://github.com/elementary/files/issues/880

**Comment by sprite-1** [comment]
When do these changes normally get released after being fixed?

**Comment by jeremypw** [comment]
There is no fixed interval, I guess it depends on how serious the bug fixed is regarded.  I'll ask Cody Garver whether he can do another release fairly soon.

**Comment by peteruithoven** [comment]
I'm closing it as a duplicate

**Comment by sprite-1** [comment]
@jeremypw okay, thanks!
