### ISSUE TITLE
Color for file/folder not saved

### ISSUE THREAD

**Issue by cmburg** [elementary/files#892]
I am running the release version of "files" and set colors for folders are not saved. I had the same effect with the "flickering icon bug" but thought it comes from that bug itself.

To reproduce give a color to, e.g., a folder, click on free area to deselect the folder and see if color is set (unsure if it always does) and hit F5; the color is gone.

**Comment by jeremypw** [comment]
Regression due to 8efd7d62da64f9fc55b2e1a3088196c45a9251e2

**Comment by dennismayr** [comment]
This had been fixed and folder colors worked until the last batch of system updates, between yesterday and 2 days ago.

**Comment by jeremypw** [comment]
@dennismayr Presumably that was v 4.1.8 release committed 15 days ago?  Or are you tracking the master version?

**Comment by jeremypw** [comment]
The master version seems to be working OK.  Maybe mismatched version of the plug-in?
