### ISSUE TITLE
Files does not remember its size correctly

### ISSUE THREAD

**Issue by derkomai** [elementary/files#904]
Files now remembers its position when closed, but it seems there still are some issues with its size: if I pin Files to the right or left half of the screen (using the magnet feature), the next time Files is opened it will be wider that half of the screen. I can reproduce this behaviour in two different PCs.

**Comment by jeremypw** [comment]
Does not happen with other core apps so appears to be a Files problem.

**Comment by derkomai** [comment]
Yes, every other core app works ok.

**Comment by uncertainquark** [comment]
I'm having the same issue.

![Screenshot from 2020-03-21 16-03-55](https://user-images.githubusercontent.com/22585732/77224676-00225700-6b8e-11ea-8521-e1686d0f0d33.png)
![Screenshot from 2020-03-21 16-04-04](https://user-images.githubusercontent.com/22585732/77224679-0284b100-6b8e-11ea-8fc0-5590c4cf35af.png)
