### ISSUE TITLE
Can't do anything else while searching files

### ISSUE THREAD

**Issue by RicaBenhossi** [elementary/files#908]
When I'm performing a search (especially if I do this from / which takes more time), If Files app or even the address bar lose focus, search just stops.

Would be great if we have an option perform a search and do another thing while waiting it find what we want. 

![elementary File app Search](https://user-images.githubusercontent.com/15204313/54740670-d3aeb600-4b9a-11e9-98c6-0dd664c1cbea.gif)

**Comment by peteruithoven** [comment]
Relevant: https://github.com/elementary/files/pull/435

**Comment by jeremypw** [comment]
As indicated by the linked PR, achieving this would be difficult/unstable while maintaining the current paradigm of a `browser-like` search experience.  A separate search widget/window/process would make it easier but require significant refactoring as well as UX approval.

**Comment by RicaBenhossi** [comment]
I see... I saw that you guys were already trying to figure it out how to fix the problem.

Thank you all for the response.
