### ISSUE TITLE
Selecting files with SHIFT + ( Pos1 / END) broken

### ISSUE THREAD

**Issue by kr428** [elementary/files#917]
Massively using file manager for handling and moving around large batches of folders, I experienced odd behaviours when selecting multiple files using keyboard and SHIFT.

What does happen:

Step: Select an arbitrary file and press SHIFT+Pos1
Expectation: Select this file any everything "from there" to the first item in the current folder view.
Outcome: Select all items in the first column of the current window

Step: Select an arbitrary file and press SHIFT+END
Expectation: Select this file and everything "from there" to the last item in the current view.
Outcome: Jumps to the last item and unselects everything that has been selected before. 

That doesn't feel particularly concise or meaningful... ;)

**Comment by jeremypw** [comment]
I do not think these key combinations are explicitly handled by Files so I guess this is the native behaviour of the Gtk.IconView widget that forms the basis of the Icon view.  I note that the List view and Column view behave as you would expect.   I agree that the current behaviour of the Icon view is broken and should be consistent with the other views, so Files will have to override the native behaviour.

**Comment by jeremypw** [comment]
As there is already a PR (#802) awaiting review/approval/merging that touches upon the relevant code, it is probably better to base any fix on that PR.

**Comment by kr428** [comment]
Ok, cool, thanks for looking into this so quickly. :)

**Comment by jeremypw** [comment]
What you expect to happen if you press e.g. `<Shift><End>` followed by `<Shift><Home>` ?

Would you expect all the files to be selected or just the section between the initially selected file and the first item?
