### ISSUE TITLE
External triggers to open instances of already open apps should open a new tab, not a new window

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#928]
For example, if I click the folder icon on the Downloads panel on Firefox, and I already have the Files app open, gala should open a new tab of the download location, not a new window entirely.

**Comment by uncertainquark** [comment]
Hey, the issue was transferred but it appears "closed" because it was closed for the previous repo.

**Comment by cassidyjames** [comment]
@uncertainquark whoops, thanks for spotting that. Reopened.
