### ISSUE TITLE
Folders do not sort properly by date

### ISSUE THREAD

**Issue by bgcarlisle** [elementary/files#931]
To reproduce error:

* Make an empty folder, e.g. ~/test
* Navigate to ~/test
* Right-click, click New > Folder
* Right-click, click New > Empty file
* Right-click, click New > Folder
* Sort by Modified

The new empty file should be between the folders, but it is sorted as most recently modified (incorrect)

The modified column correctly lists the date and time they were all created, but they are not listed in this order

This behaviour is inconsistent with the Open / Save dialog

* Open Code
* Press control-O
* Navigate to ~/test
* Sort by Modified

The file is sorted between the folders correctly

**Comment by jeremypw** [comment]
This is so even if "directories before files" sorting is turned off.  It seems that when sorting by size, type or date, directories are always sorted before files, which is incorrect.
