### ISSUE TITLE
The password for connection with the server isn't remembered

### ISSUE THREAD

**Issue by PlatonB** [elementary/files#934]
1. Connect to server via SSH with "Remember password" option.
![SSH_Pantheon](https://user-images.githubusercontent.com/25541767/57060671-e00e4e80-6cc2-11e9-80c4-d74e9b0fec73.png)
2. Disconnect.
3. Connect.
All fields and the password should be filled again.

**Comment by jeremypw** [comment]
Have you tried bookmarking a location on the server? This works for me - I can disconnect and close Files then reopen and navigate to that location without re-entering any details using the bookmark.

If I use the "Connect Server" item in the sidebar, and enter just the protocol (SSH) and server then press connect, it connects without re-entering the passward (you have to have the keyring unlocked)

**Comment by jeremypw** [comment]
Have you tried it with other protocols?

**Comment by PlatonB** [comment]
> Have you tried bookmarking a location on the server?

I did not pay attention to this feature of Files. Later I will try to retest.

> Have you tried it with other protocols?

No

**Comment by jeremypw** [comment]
You may get a second "remember password" dialog - this does not come from Files but from the underlying system.  I am not sure why this is - there does seem to be some issue here.  Files does not actually remember the details - it asks the system to do so.

**Comment by jeremypw** [comment]
I seems to work with AFP and SMB for me, at least within a session.

**Comment by PlatonB** [comment]
I tested again. Bookmarking is the perfect solution. @jeremypw, thanks!
