### ISSUE TITLE
Color Labels in Files + Dark Mode = unreadable filenames

### ISSUE THREAD

**Issue by a-tokarev** [elementary/files#937]
elementary OS 5.0, Files, Dark Mode (via System Settings > Tweaks), no labels:

![no_labels](https://user-images.githubusercontent.com/32895328/57174307-7f5b4f00-6e45-11e9-976a-6b01b60b9275.png)

Dark Mode with labels:

![with_labels](https://user-images.githubusercontent.com/32895328/57174309-884c2080-6e45-11e9-8418-b329051b65d7.png)

Suggestion: to use dark font color for filenames on color labels in Dark Mode.

**Comment by jeremypw** [comment]
As the available color tags are all pale, a quick fix would be to always use black text for colored labels.

**Comment by cassidyjames** [comment]
@jeremypw I am working on https://github.com/elementary/granite/pull/284, but I agree since we know the tag colors, we could just always use a constant suitably-contrasting foreground color as well.

**Comment by cassidyjames** [comment]
@jeremypw the util is in Granite master, but awaiting a new release.
