### ISSUE TITLE
Remote thumbnail option not discoverable

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#941]
Despite being a long-time elementary user, I only recently figured out that the Files app indeed does have the ability to show previews/thumbnails of remote drives. 
![Screenshot from 2019-05-14 18 01 00](https://user-images.githubusercontent.com/22585732/57698218-bcf47f00-7672-11e9-965c-df18aefd65b2.png)

It didn't occur to me too look for the setting in the right-click context menu, because I was under the impression that the menu is for actions.
![photo_2019-05-14_18-02-37](https://user-images.githubusercontent.com/22585732/57698346-15c41780-7673-11e9-9bbd-46cfbddaf2eb.jpg)

I feel the option should be more discoverable.

**Comment by jeremypw** [comment]
Because a settings menu in Files is considered contrary to elementary's design principles, there are limited possibilities for exposing this option in the ui.  It seems to fit with the "Show hidden files" option though.
It is also context sensitive in that the option changes depending on whether you are in a local or remote folder (ie you can also hide local thumbnails) so its presence in a context menu is not unreasonable.

There has been a suggestion to reorganise the context menu to make things clearer #629 which could help.

**Comment by cassidyjames** [comment]
@jeremypw is there a strong reason to not enable that setting by default?

**Comment by jeremypw** [comment]
@cassidyjames It could mean transferring a lot of data over what might be a slow or expensive link if the thumbnails are not cached.  At least one other filemanager does not even offer the option.

**Comment by jeremypw** [comment]
Nautilus defaults to not showing remote thumbnails but they can be turned on using the settings menu.

**Comment by uncertainquark** [comment]
Is it a good idea to expose a "Show thumbnails" button on the File manager header bar?

**Comment by jeremypw** [comment]
I do not think the ux team would accept adding any more widgets to the header bar without an exceptionally good reason.

**Comment by jeremypw** [comment]
@cassidyjames I do not object to changing it to show remote thumbnails by default if you think that, these days, most remote connections are fast enough for this not to adversely affect the UI in most cases.

**Comment by cassidyjames** [comment]
@jeremypw I'd be interested in trying it out. Users expect thumbnailing on remote services like Dropbox and Google Drive on the web, which also spends a bit of bandwidth to preview the files. But it's worth it, especially in our case if users can still toggle it off. In the future on bandwidth-constrained networks (which network manager knows about), we could even turn it off but have an infobar telling the user why it's off and offering to turn it back on.

**Comment by uncertainquark** [comment]
If the location bar is brought below the header bar, It would give more breathing space to both the location bar as well as the action buttons that can be put in the header bar. What do you guys think?

**Comment by cassidyjames** [comment]
@uncertainquark I don't think there's much compelling reasoning to completely redesign Files for this one feature. Instead, we should be smarter about enabling it by default.

**Comment by jeremypw** [comment]
I've added this issue to the AppMenu project as showing remote thumbnails is a candidate for such a menu (it has global effect).

**Comment by uncertainquark** [comment]
Maybe we should enable thumbnails by default for external storage devices at least as they aren't to be fetched online or anything. It will make the experience of browsing pendrives and Android phones nicer.

**Comment by jeremypw** [comment]
@uncertainquark  Which protocols are the external devices using? USB memory and drives should already be regarded as local anyway as they are mounted at `/media/username/device` and therefore be thumbnailed.

MTP devices do not support thumbnailing (at least my old one does not).

**Comment by uncertainquark** [comment]
It's MTP. I'm using a Nokia 6.1 Plus on Android 10 and I don't see any other protocol option.

**Comment by uncertainquark** [comment]
However, I am able to show the thumbnails once I right-click and turn them on. So the support is certainly there.

**Comment by jeremypw** [comment]
Update - on Andoid devices MTP and PTP connections do support thumbnailing.  The linked PR #1265 implements the necessary changes to show thumbnails by default and to treat locally connected MTP and PTP devices as being "local", not "remote".
