### ISSUE TITLE
Missing items in Plank context menu on closed state

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#942]
Files app shows more items in the plank right-click context menu in open state than the closed one. 

![Screenshot from 2019-05-14 18 12 46](https://user-images.githubusercontent.com/22585732/57698925-65571300-7674-11e9-9605-f4b6d7c9cca6.png)
![Screenshot from 2019-05-14 18 14 19](https://user-images.githubusercontent.com/22585732/57698926-65efa980-7674-11e9-81e5-bd88eae0b423.png)

I think the extra items are great options to have even when the app is closes so that one can quickly open a certain location.

**Comment by jeremypw** [comment]
Thanks but this is essentially a duplicate of #127.
