### ISSUE TITLE
Add keyboard shortcut for opening file properties dialog

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#944]
I noticed that the Files app misses a keyboard shortcut to open the file properties dialog. AFAIK, GNOME has it set to `Ctrl+I` or something similar. It would be great for elementary Files app to have some shortcut as well.

![Screenshot from 2019-05-14 19 37 17](https://user-images.githubusercontent.com/22585732/57704764-3050bd80-7680-11e9-9baa-7f8f7c873637.png)

**Comment by jeremypw** [comment]
`<Ctrl>I` is used by at least one other filemanager to invert the current selection (although Files uses `<Ctrl><Shift>A` for that at the moment).

The shortcut for the Properties dialog is `<Alt><Enter>` which appears to have come from Windows but is used by at least one other filemanager.

**Comment by uncertainquark** [comment]
Hi, `Alt + Enter` works, thanks! We should look into ways to make it more discoverable though.
