### ISSUE TITLE
Files Explorer closes unexpectedly

### ISSUE THREAD

**Issue by aldovar** [elementary/files#950]
When I open "Download" Folder File explorer closes unexpectedly.

If I tried to open with Terminal: 

Message: 09:30:23.751: Application.vala:50: Report any issues/bugs you might find to https://github.com/elementary/files/issues

**Comment by jeremypw** [comment]
That message is normal.  Were there no other messages before the terminal prompt returned? Try running G_MESSAGE_DEBUG=all io.elementary.files in a terminal to get more verbose output.

**Comment by jeremypw** [comment]
Failing that yielding useful info, try getting a backtrace with:

`gdb io.elementary.files`
followed by
`run`
followed by
`bt`
when (if) Files has crashed.

**Comment by peteruithoven** [comment]
A first attempt at putting this gdb info on the website: https://github.com/elementary/website/blob/ca556251e405e9f41c4a1f6d3bfd8c8a6212eb55/docs/code/os-dev.md#inspecting-crashes-inspecting-crashes

**Comment by aldovar** [comment]
I tried: 

X:~$ G_MESSAGE_DEBUG=all io.elementary.files
** Message: 16:06:40.366: Application.vala:50: Report any issues/bugs you might find to https://github.com/elementary/files/issues
Violación de segmento

**Comment by aldovar** [comment]
Finally when I run io.elementary.files-pkexec as root I cloud delete all files in Download and Documents Folders and now Files works normally

**Comment by peteruithoven** [comment]
Could you try changing your system to english and trying this again? That would also help others with similar issues find this issue.

**Comment by peteruithoven** [comment]
> Finally when I run io.elementary.files-pkexec as root I cloud delete all files in Download and Documents Folders and now Files works normally

But that means you can't reproduce the issue anymore?

**Comment by aldovar** [comment]
Ok, I have downloaded a new file in folder Downloads and the bug come back...

** Message: 16:11:42.509: Application.vala:50: Report any issues/bugs you might find to https://github.com/elementary/files/issues
[Nuevo Thread 0x7fffe4a7f700 (LWP 15301)]
[Nuevo Thread 0x7fffd79d1700 (LWP 15303)]
[Nuevo Thread 0x7fffd5a19700 (LWP 15307)]
[Nuevo Thread 0x7fffd5218700 (LWP 15308)]
[Nuevo Thread 0x7fffd4a17700 (LWP 15309)]
[Nuevo Thread 0x7fffc7fff700 (LWP 15310)]
[Thread 0x7fffc7fff700 (LWP 15310) terminado]
[Thread 0x7fffd5a19700 (LWP 15307) terminado]
[Thread 0x7fffd5218700 (LWP 15308) terminado]
[Thread 0x7fffd4a17700 (LWP 15309) terminado]
[Nuevo Thread 0x7fffd4a17700 (LWP 15312)]

Thread 10 "io.elementary.f" received signal SIGSEGV, Segmentation fault.
[Cambiando a Thread 0x7fffd4a17700 (LWP 15312)]
0x00007ffff71417d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

**Comment by peteruithoven** [comment]
Please try using gdb: https://elementary.io/docs/code/os-dev#inspecting-crashes and sharing those logs. 
Please also try to use markdown to format your code, like I've corrected your post above.

Why were you using ` io.elementary.files-pkexec` btw?

**Comment by aldovar** [comment]
When I execute "run" it just get freezed (I can't write anymore) and never open... now I can't open Files app

I used files-pkexec just because I wanted to run as sudo

**Comment by jeremypw** [comment]
It looks like `GLib.Environment.get_user_special_dir (GLib.UserDirectory.TEMPLATES)` is returning `null` on your system, which is unexpected and Files is not coded to deal with this - although it copes if the template folder does not exist.  A fix is needed to prevent crashing under these circumstances.
