### ISSUE TITLE
Drag-and-drop does not work after double clicking a blank area 

### ISSUE THREAD

**Issue by statiolake** [elementary/files#951]
If once I double click a blank area, drag-and-drop does not work after that.  This issue occurs in any view mode (icon, list or column view).  If I change the layout, it starts working correctly again. (maybe because the view will be re-initialized?)

**Comment by statiolake** [comment]
![2019-05-24 05 39 37 の画面録画@2x](https://user-images.githubusercontent.com/20490597/58284804-6d3a5400-7de6-11e9-8e6f-162142548c52.gif)

The first two drag-and-drop s are OK.  After that, I double-clicked a blank area.  After that,  I cannot drag-and-drop anymore.

**Comment by jeremypw** [comment]
Curiously, dragging with the secondary button still works.
