### ISSUE TITLE
MKV is loading... loading...

### ISSUE THREAD

**Issue by AaronActu** [elementary/files#955]
Hi,

When I try to access .mkv files (or even by sharing them) I have the loading bar during a while and if it succeed - after more than 15mins of loading - to load the page, after downloading file is not always complete.

You can check it here : https://filemanager.cafecloud.fr/s/CH6J2IZ

Thanks !

**Comment by peteruithoven** [comment]
Could you include a gif? That url isn't loading for me.
I'd recommend using [Screenrecorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder), you can decrease the file size by for example decreasing the scale.

**Comment by jeremypw** [comment]
I downloaded a small .mkv file from `https://sample-videos.com/index.php#sample-mkv-video` (using Chrome) and it opened OK using Files to launch it in Videos.  Are you using Files to launch a .mkv on a remote filesystem?

**Comment by AaronActu** [comment]
Hi!

My apologies for this issue, I totally mistaken repo ... I must be really tired

Whatever, thanks y'all for your help !

Have a nice day
