### ISSUE TITLE
The name of the file and folder label is all white in Dark Variant

### ISSUE THREAD

**Issue by AdsonCicilioti** [elementary/files#976]
![image](https://user-images.githubusercontent.com/6278398/59955249-7d823500-945f-11e9-91a0-350607adf4b0.png)

**Comment by jeremypw** [comment]
Thanks for the report, it is a duplicate of #937.

**Comment by jeremypw** [comment]
Sorry, actually not a duplicate as this refers to untagged files.

It has been recently fixed in master by d471f331824649503c7039160ab508b2e64366ba

**Comment by AdsonCicilioti** [comment]
Dear @jeremypw,
This is not duplicate. Those white colors tando in the text as in the background are in everything, even I not applying a label color.

Could not understand?

**Comment by AdsonCicilioti** [comment]
But ok.. U've get the lastest connits and tag color is fixed. But when set any colors the name name stay illegible concern #937  issue.

![image](https://user-images.githubusercontent.com/6278398/59969265-f1841200-951f-11e9-9df3-6fc64457f852.png)
No contrast

And extra problem:
Context menu width cut color options.
![image](https://user-images.githubusercontent.com/6278398/59969282-40ca4280-9520-11e9-96d7-90f52becdb5c.png)

**Comment by jeremypw** [comment]
@AdsonCicilioti Thanks - I have now pushed a PR to fix #937 and the width issue.
