### ISSUE TITLE
Mark file after copying

### ISSUE THREAD

**Issue by koyuawsmbrtn** [elementary/files#987]
I would like to have a visual feedback after copying a small file which can be done like KDE does in Dolphin: marking a file after copying is complete.

![](https://user-images.githubusercontent.com/40538332/61123773-833ec980-a4a5-11e9-8cb1-30ee965052b5.png)

**Comment by peteruithoven** [comment]
@koyuawsmbrtn any change you could include an example of what that looks like in KDE with Dolphin?

**Comment by koyuawsmbrtn** [comment]
> @koyuawsmbrtn any change you could include an example of what that looks like in KDE with Dolphin?

![VirtualBox_Manjaro KDE_12_07_2019_16_47_43](https://user-images.githubusercontent.com/40538332/61136979-d8d69e80-a4c4-11e9-8834-c18cc59e2152.png)

**Comment by peteruithoven** [comment]
Come on, u can use words. It's selected? Or did anything else happen?

**Comment by koyuawsmbrtn** [comment]
> Come on, u can use words. It's selected? Or did anything else happen?

No, the problem is that it doesn't get selected after I copied it which I stated above.

**Comment by peteruithoven** [comment]
Thanks for clarifying. (You've never stated "selected", you've mentioned vague concepts like "visual feedback" and "mark".)

**Comment by jeremypw** [comment]
I think this makes sense - especially as the new file is selected if created by drag and drop.

**Comment by jeremypw** [comment]
Looking at the code, it was the intention to select the copied file, but there is a bug.  I will submit a PR to fix shortly.
