### ISSUE TITLE
Files not using global time format

### ISSUE THREAD

**Issue by D0J0P** [elementary/files#998]
I have my time format set to AM/PM, but Files uses 24hr in several places. 
![Screenshot from 2019-07-26 18 56 17](https://user-images.githubusercontent.com/19495660/61985483-680ca780-afd7-11e9-8489-e8f62ab3b1a6.png)
![Screenshot from 2019-07-26 19 00 18](https://user-images.githubusercontent.com/19495660/61985537-a7d38f00-afd7-11e9-8e42-0576d849f3e6.png)

Places that aren't using the globally set time format:

- File names (Like those found in screenshot files taken with the Screenshot app)
- "Modified" column of list view
- Properties of files

**Comment by jeremypw** [comment]
The screenshot file name ussue should be raised in the screenshot project.

The modified column and properties seem to follow time format inconsistently for me - some files are 12hr and some 24hr, which is a bit weird.  Maybe a timezone issue. The time format in properties matches that in the modified column so presumably the same bug. 

![Screenshot from 2019-07-27 10 57 34](https://user-images.githubusercontent.com/10513844/61993024-c2e8e200-b05d-11e9-88ca-e14b667e50a1.png)

**Comment by jeremypw** [comment]
I think this is due to mistranslation of the format strings in some locales.  I will push a fix to remove critical parts from the translatable strings which should help avoid this.
